-- gejast v49 klaverjas score app + leaderboard
-- Review in staging before applying to production.

create extension if not exists pgcrypto;

create table if not exists public.jas_games (
  id bigint generated by default as identity primary key,
  title text not null default 'Klaverjas potje',
  played_at date not null default current_date,
  variant text not null default '4_player',
  scoreboard_mode text not null default 'teams',
  created_by_player_id bigint null references public.players(id) on delete set null,
  created_by_name text null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.jas_game_entries (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.jas_games(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  display_name text not null,
  seat_no integer not null,
  team_no integer not null,
  total_points integer not null default 0,
  is_winner boolean not null default false,
  created_at timestamptz not null default now(),
  unique (game_id, player_id),
  unique (game_id, seat_no)
);

create index if not exists jas_games_played_idx on public.jas_games(played_at desc, created_at desc);
create index if not exists jas_game_entries_game_idx on public.jas_game_entries(game_id);
create index if not exists jas_game_entries_player_idx on public.jas_game_entries(player_id);
create index if not exists jas_game_entries_name_idx on public.jas_game_entries(lower(display_name));

create or replace function public._jas_session_player(session_token text)
returns public.players
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  state jsonb;
  player_row public.players%rowtype;
begin
  state := public.get_public_state(session_token);

  if coalesce(trim(state ->> 'my_name'), '') = '' then
    raise exception 'Log eerst in met een geldige spelersessie';
  end if;

  select *
    into player_row
    from public.players
   where lower(display_name) = lower(trim(state ->> 'my_name'))
   limit 1;

  if not found then
    raise exception 'Ingelogde speler niet gevonden';
  end if;

  return player_row;
end;
$$;

create or replace function public.get_jas_app_state(session_token text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  base_state jsonb;
  recent_games jsonb;
  registered_names jsonb;
begin
  base_state := public.get_public_state(session_token);

  select coalesce(jsonb_agg(p.display_name order by lower(p.display_name)), '[]'::jsonb)
    into registered_names
    from public.players p;

  select coalesce(jsonb_agg(game_row order by played_at desc, created_at desc), '[]'::jsonb)
    into recent_games
    from (
      select
        g.id,
        g.title,
        g.played_at,
        g.variant,
        g.scoreboard_mode,
        g.created_at,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id
        ), '[]'::jsonb) as players,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id and e.is_winner = true
        ), '[]'::jsonb) as winners
      from public.jas_games g
      order by g.played_at desc, g.created_at desc
      limit 12
    ) game_row;

  return jsonb_build_object(
    'all_names', registered_names,
    'my_name', base_state ->> 'my_name',
    'recent_games', recent_games
  );
end;
$$;

create or replace function public.create_jas_game(session_token text, game_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  session_player public.players%rowtype;
  game_id_out bigint;
  participant jsonb;
  resolved_player_id bigint;
  payload_participants jsonb;
  participant_count integer;
  distinct_player_count integer;
  seat_arr integer[];
  team_arr integer[];
  missing_name text;
begin
  session_player := public._jas_session_player(session_token);
  payload_participants := coalesce(game_payload -> 'participants', '[]'::jsonb);

  if coalesce(nullif(trim(game_payload ->> 'variant'), ''), '4_player') <> '4_player' then
    raise exception 'Alleen 4-speler klaverjas wordt ondersteund in deze versie';
  end if;

  if coalesce(nullif(trim(game_payload ->> 'scoreboard_mode'), ''), 'teams') <> 'teams' then
    raise exception 'Alleen teamscore wordt ondersteund in deze versie';
  end if;

  if jsonb_typeof(payload_participants) <> 'array' then
    raise exception 'Deelnemers ontbreken';
  end if;

  participant_count := jsonb_array_length(payload_participants);
  if participant_count <> 4 then
    raise exception 'Kies precies 4 geregistreerde spelers';
  end if;

  select count(distinct lower(trim(value ->> 'name')))
    into distinct_player_count
    from jsonb_array_elements(payload_participants) value;

  if distinct_player_count <> 4 then
    raise exception 'Elke speler mag maar één keer gekozen worden';
  end if;

  select array_agg((value ->> 'seat_no')::integer order by (value ->> 'seat_no')::integer),
         array_agg((value ->> 'team_no')::integer order by (value ->> 'seat_no')::integer)
    into seat_arr, team_arr
    from jsonb_array_elements(payload_participants) value;

  if seat_arr is distinct from array[1,2,3,4] then
    raise exception 'Stoelen moeten 1 t/m 4 zijn';
  end if;

  if team_arr is distinct from array[1,2,1,2] then
    raise exception 'Teams moeten stoel 1+3 en 2+4 gebruiken';
  end if;

  for participant in select * from jsonb_array_elements(payload_participants)
  loop
    resolved_player_id := null;

    select p.id
      into resolved_player_id
      from public.players p
     where lower(p.display_name) = lower(trim(participant ->> 'name'))
     limit 1;

    if resolved_player_id is null then
      missing_name := coalesce(participant ->> 'name', 'Onbekend');
      raise exception 'Speler niet gevonden of niet geregistreerd: %', missing_name;
    end if;
  end loop;

  insert into public.jas_games (
    title,
    played_at,
    variant,
    scoreboard_mode,
    created_by_player_id,
    created_by_name,
    payload
  )
  values (
    coalesce(nullif(trim(game_payload ->> 'title'), ''), 'Klaverjas potje'),
    coalesce(nullif(game_payload ->> 'played_at', '')::date, current_date),
    '4_player',
    'teams',
    session_player.id,
    session_player.display_name,
    coalesce(game_payload, '{}'::jsonb)
  )
  returning id into game_id_out;

  for participant in select * from jsonb_array_elements(payload_participants)
  loop
    select p.id
      into resolved_player_id
      from public.players p
     where lower(p.display_name) = lower(trim(participant ->> 'name'))
     limit 1;

    insert into public.jas_game_entries (
      game_id,
      player_id,
      display_name,
      seat_no,
      team_no,
      total_points,
      is_winner
    )
    values (
      game_id_out,
      resolved_player_id,
      coalesce(nullif(trim(participant ->> 'name'), ''), 'Onbekend'),
      (participant ->> 'seat_no')::integer,
      (participant ->> 'team_no')::integer,
      coalesce((participant ->> 'total_points')::integer, 0),
      coalesce((participant ->> 'is_winner')::boolean, false)
    );
  end loop;

  return jsonb_build_object('ok', true, 'game_id', game_id_out);
end;
$$;

create or replace function public.get_jas_leaderboard(limit_count integer default 100)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  leaderboard jsonb;
  recent_games jsonb;
begin
  select coalesce(jsonb_agg(row_data order by games_won desc, total_points desc, display_name asc), '[]'::jsonb)
    into leaderboard
    from (
      select
        p.id as player_id,
        p.display_name,
        coalesce(count(e.id), 0)::integer as games_played,
        coalesce(sum(case when e.is_winner then 1 else 0 end), 0)::integer as games_won,
        coalesce(sum(e.total_points), 0)::integer as total_points,
        round(coalesce(avg(e.total_points), 0)::numeric, 1) as avg_points,
        round(
          case when count(e.id) = 0 then 0
               else (sum(case when e.is_winner then 1 else 0 end)::numeric / count(e.id)::numeric) * 100
          end, 1
        ) as win_rate,
        max(g.played_at)::date as last_played_at
      from public.players p
      left join public.jas_game_entries e on e.player_id = p.id
      left join public.jas_games g on g.id = e.game_id
      group by p.id, p.display_name
      order by games_won desc, total_points desc, p.display_name asc
      limit greatest(coalesce(limit_count, 100), 1)
    ) row_data;

  select coalesce(jsonb_agg(game_row order by played_at desc, created_at desc), '[]'::jsonb)
    into recent_games
    from (
      select
        g.id,
        g.title,
        g.played_at,
        g.variant,
        g.scoreboard_mode,
        g.created_at,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id
        ), '[]'::jsonb) as players,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id and e.is_winner = true
        ), '[]'::jsonb) as winners
      from public.jas_games g
      order by g.played_at desc, g.created_at desc
      limit 20
    ) game_row;

  return jsonb_build_object(
    'leaderboard', leaderboard,
    'recent_games', recent_games
  );
end;
$$;

comment on function public.get_jas_app_state(text)
is 'Returns registered players, current logged in player name, and recent jas games for score.html.';

comment on function public.create_jas_game(text,jsonb)
is 'Stores a 4-player klaverjas game payload and creates normalized leaderboard entries for registered players only.';

comment on function public.get_jas_leaderboard(integer)
is 'Returns registered-player leaderboard stats plus recent games for leaderboard.html.';
