-- GEJAST v691 admin/account owner restore
-- Run after GEJAST_v690_full_site_compat.sql.
-- This intentionally does not fake privileged actions. It restores a real admin
-- session owner, claim/activation owner, and outbound mail-job queue.

begin;

create extension if not exists pgcrypto;

create table if not exists public.gejast_admin_users_v691 (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  otp_code_hash text null,
  role text not null default 'admin',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gejast_admin_sessions_v691 (
  token text primary key,
  admin_user_id bigint not null references public.gejast_admin_users_v691(id) on delete cascade,
  username text not null,
  role text not null default 'admin',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  user_agent text null,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists gejast_admin_sessions_v691_user_idx on public.gejast_admin_sessions_v691(admin_user_id, expires_at desc);
create index if not exists gejast_admin_sessions_v691_exp_idx on public.gejast_admin_sessions_v691(expires_at);

create table if not exists public.claim_requests (
  id bigint generated by default as identity primary key,
  requested_name text null,
  requester_email text null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.claim_requests
  add column if not exists requested_name text,
  add column if not exists desired_name text,
  add column if not exists display_name text,
  add column if not exists requester_email text,
  add column if not exists requester_note text,
  add column if not exists status text not null default 'pending',
  add column if not exists decision text,
  add column if not exists decision_reason text,
  add column if not exists decided_at timestamptz,
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists activated_at timestamptz,
  add column if not exists expires_at timestamptz,
  add column if not exists player_id bigint,
  add column if not exists allowed_username_id bigint,
  add column if not exists site_scope text not null default 'friends',
  add column if not exists request_meta jsonb not null default '{}'::jsonb,
  add column if not exists admin_meta jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists claim_requests_status_idx on public.claim_requests(status, created_at desc);
create index if not exists claim_requests_scope_status_idx on public.claim_requests(site_scope, status, created_at desc);
create index if not exists claim_requests_email_idx on public.claim_requests(lower(requester_email));

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players
  add column if not exists display_name text,
  add column if not exists pin_hash text,
  add column if not exists active boolean not null default false,
  add column if not exists approved boolean not null default false,
  add column if not exists approved_email text,
  add column if not exists site_scope text not null default 'friends',
  add column if not exists session_token text,
  add column if not exists last_login_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists players_display_name_lower_idx on public.players(lower(display_name));
create index if not exists players_active_scope_idx on public.players(site_scope, active, lower(display_name));

create table if not exists public.gejast_player_sessions_v691 (
  session_token text primary key,
  player_id bigint not null,
  display_name text not null,
  site_scope text not null default 'friends',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '45 days')
);

create index if not exists gejast_player_sessions_v691_player_idx on public.gejast_player_sessions_v691(player_id, expires_at desc);

create table if not exists public.player_activation_links (
  id bigint generated by default as identity primary key,
  claim_request_id bigint not null,
  activation_token text not null unique,
  activation_url text null,
  expires_at timestamptz not null default (now() + interval '14 days'),
  used_at timestamptz null,
  created_by_admin_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.player_activation_links
  add column if not exists claim_request_id bigint,
  add column if not exists activation_token text,
  add column if not exists activation_url text,
  add column if not exists expires_at timestamptz not null default (now() + interval '14 days'),
  add column if not exists used_at timestamptz,
  add column if not exists created_by_admin_id bigint,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists player_activation_links_token_idx on public.player_activation_links(activation_token);
create index if not exists player_activation_links_claim_idx on public.player_activation_links(claim_request_id, created_at desc);

create table if not exists public.outbound_email_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null default 'activation_email',
  job_status text not null default 'queued',
  recipient_email text not null,
  recipient_name text null,
  subject text not null default 'Activeer je account voor de Kale Nel',
  payload jsonb not null default '{}'::jsonb,
  requested_by_admin_id bigint null,
  related_claim_request_id bigint null,
  related_player_id bigint null,
  last_error text null,
  provider_message_id text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.outbound_email_jobs
  add column if not exists job_type text not null default 'activation_email',
  add column if not exists job_status text not null default 'queued',
  add column if not exists recipient_email text,
  add column if not exists recipient_name text,
  add column if not exists subject text not null default 'Activeer je account voor de Kale Nel',
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists requested_by_admin_id bigint,
  add column if not exists related_claim_request_id bigint,
  add column if not exists related_player_id bigint,
  add column if not exists last_error text,
  add column if not exists provider_message_id text,
  add column if not exists sent_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists outbound_email_jobs_status_idx on public.outbound_email_jobs(job_status, created_at desc);
create index if not exists outbound_email_jobs_claim_idx on public.outbound_email_jobs(related_claim_request_id);
create index if not exists outbound_email_jobs_email_idx on public.outbound_email_jobs(lower(recipient_email));

create table if not exists public.gejast_admin_audit_v691 (
  id bigint generated by default as identity primary key,
  admin_user_id bigint null,
  username text null,
  action text not null,
  target_type text null,
  target_id text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gejast_admin_audit_v691_created_idx on public.gejast_admin_audit_v691(created_at desc);

create or replace function public._gejast_random_hex_v691(byte_count integer default 32)
returns text
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_out text;
begin
  if to_regprocedure('extensions.gen_random_bytes(integer)') is not null then
    execute 'select encode(extensions.gen_random_bytes($1), ''hex'')' into v_out using byte_count;
    return v_out;
  elsif to_regprocedure('public.gen_random_bytes(integer)') is not null then
    execute 'select encode(public.gen_random_bytes($1), ''hex'')' into v_out using byte_count;
    return v_out;
  end if;

  return md5(random()::text || clock_timestamp()::text || txid_current()::text)
      || md5(clock_timestamp()::text || random()::text);
end
$fn$;

create or replace function public._gejast_hash_secret_v691(secret_input text)
returns text
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_hash text;
begin
  if nullif(secret_input, '') is null then
    raise exception 'secret_required';
  end if;

  if to_regprocedure('extensions.crypt(text,text)') is not null
     and to_regprocedure('extensions.gen_salt(text)') is not null then
    execute 'select extensions.crypt($1, extensions.gen_salt(''bf''))' into v_hash using secret_input;
    return v_hash;
  elsif to_regprocedure('public.crypt(text,text)') is not null
     and to_regprocedure('public.gen_salt(text)') is not null then
    execute 'select public.crypt($1, public.gen_salt(''bf''))' into v_hash using secret_input;
    return v_hash;
  end if;

  return 'md5:' || md5(secret_input || ':' || current_database());
end
$fn$;

create or replace function public._gejast_secret_matches_v691(secret_input text, stored_hash text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_check text;
begin
  if nullif(stored_hash, '') is null then
    return false;
  end if;

  if stored_hash like 'md5:%' then
    return stored_hash = ('md5:' || md5(coalesce(secret_input, '') || ':' || current_database()));
  end if;

  if to_regprocedure('extensions.crypt(text,text)') is not null then
    execute 'select extensions.crypt($1, $2)' into v_check using coalesce(secret_input, ''), stored_hash;
    return v_check = stored_hash;
  elsif to_regprocedure('public.crypt(text,text)') is not null then
    execute 'select public.crypt($1, $2)' into v_check using coalesce(secret_input, ''), stored_hash;
    return v_check = stored_hash;
  end if;

  return false;
end
$fn$;

create or replace function public.admin_bootstrap_user_v691(
  username_input text,
  password_input text,
  otp_code_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint;
  v_username text := lower(trim(coalesce(username_input, '')));
begin
  if exists (select 1 from public.gejast_admin_users_v691) then
    raise exception 'admin_bootstrap_already_done';
  end if;
  if v_username = '' then raise exception 'admin_username_required'; end if;
  if length(coalesce(password_input, '')) < 10 then raise exception 'admin_password_min_10_chars'; end if;
  if otp_code_input is not null and otp_code_input !~ '^[0-9]{6}$' then raise exception 'admin_otp_code_must_be_6_digits'; end if;

  insert into public.gejast_admin_users_v691(username, password_hash, otp_code_hash)
  values (v_username, public._gejast_hash_secret_v691(password_input), case when otp_code_input is null then null else public._gejast_hash_secret_v691(otp_code_input) end)
  returning id into v_id;

  return jsonb_build_object('ok', true, 'admin_user_id', v_id, 'username', v_username, 'message', 'Admin user created. Log in with this username, password, and the fixed 6-digit admin code if one was set.');
end
$fn$;

create or replace function public._gejast_admin_require_json_v691(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_row record;
begin
  select s.token, s.admin_user_id, s.username, s.role, s.expires_at, u.active
  into v_row
  from public.gejast_admin_sessions_v691 s
  join public.gejast_admin_users_v691 u on u.id = s.admin_user_id
  where s.token = nullif(trim(coalesce(admin_session_token, '')), '')
  limit 1;

  if not found then raise exception 'admin_session_invalid'; end if;
  if v_row.expires_at <= now() then raise exception 'admin_session_expired'; end if;
  if not coalesce(v_row.active, false) then raise exception 'admin_user_disabled'; end if;

  update public.gejast_admin_sessions_v691
  set last_seen_at = now()
  where token = v_row.token;

  return jsonb_build_object(
    'ok', true,
    'id', v_row.admin_user_id,
    'admin_user_id', v_row.admin_user_id,
    'username', v_row.username,
    'admin_username', v_row.username,
    'role', v_row.role,
    'admin_session_token', v_row.token,
    'expires_at', v_row.expires_at
  );
end
$fn$;

create or replace function public._gejast_admin_audit_v691(admin_session_token text, action_input text, target_type_input text default null, target_id_input text default null, metadata_input jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_admin jsonb;
begin
  v_admin := public._gejast_admin_require_json_v691(admin_session_token);
  insert into public.gejast_admin_audit_v691(admin_user_id, username, action, target_type, target_id, metadata)
  values ((v_admin->>'admin_user_id')::bigint, v_admin->>'admin_username', action_input, target_type_input, target_id_input, coalesce(metadata_input, '{}'::jsonb));
end
$fn$;

do $drop$
declare
  rec record;
  v_names text[] := array[
    'admin_login',
    'admin_dev_login',
    'admin_check_session',
    'admin_get_claim_requests',
    'admin_get_claim_history',
    'admin_get_expired_activation_queue',
    'admin_decide_claim_request',
    'admin_decide_claim_request_action',
    'create_player_activation_link',
    'create_player_activation_link_action',
    'admin_queue_activation_email',
    'admin_resend_pending_activation_action',
    'admin_resend_expired_activation_action',
    'admin_requeue_expired_activation_action',
    'admin_return_name_to_claimable_action',
    'admin_revoke_player_access',
    'admin_revoke_player_access_action',
    'admin_remove_player_action',
    'admin_set_activation_email_subject_action',
    'admin_validate_outbound_email_job',
    'admin_get_outbound_email_job_webhook_payload',
    'admin_get_latest_valid_outbound_email_job_webhook_payload',
    'admin_get_paardenrace_overview_v683',
    'admin_close_paardenrace_room_v683',
    'admin_get_beerpong_shared_stats_audit_v642',
    'admin_refresh_beerpong_shared_stats_v642',
    'admin_get_despimarkt_auto_market_audit_v646',
    'admin_get_mail_diagnostics',
    'get_activation_link_context',
    'account_get_activation_context_v687',
    'activate_player_from_email_link',
    'account_activate_v687',
    'login_player',
    'login_player_by_name_pin_v687',
    'account_public_state_v687',
    'account_request_claim_v687',
    'store_active_player_metadata',
    'admin_get_active_player_metadata_audit_v687',
    'admin_get_account_runtime_audit_v687',
    'admin_diagnose_login_player_v687',
    'admin_reset_login_player_pin_v687',
    'admin_add_requestable_name_v687',
    'admin_approve_account_claim_v687',
    'admin_reject_account_claim_v687'
  ];
begin
  for rec in
    select n.nspname, p.proname, pg_get_function_identity_arguments(p.oid) as args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = any(v_names)
  loop
    execute format('drop function if exists %I.%I(%s) cascade', rec.nspname, rec.proname, rec.args);
  end loop;
end
$drop$;

create or replace function public.admin_login(input_username text, input_password text, input_totp_code text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_user record;
  v_token text;
  v_expires timestamptz := now() + interval '12 hours';
begin
  select *
  into v_user
  from public.gejast_admin_users_v691
  where lower(username) = lower(trim(coalesce(input_username, '')))
    and active = true
  limit 1;

  if not found or not public._gejast_secret_matches_v691(coalesce(input_password, ''), v_user.password_hash) then
    raise exception 'admin_login_invalid';
  end if;

  if v_user.otp_code_hash is not null then
    if coalesce(input_totp_code, '') !~ '^[0-9]{6}$'
       or not public._gejast_secret_matches_v691(input_totp_code, v_user.otp_code_hash) then
      raise exception 'admin_otp_invalid';
    end if;
  elsif coalesce(input_totp_code, '') !~ '^[0-9]{6}$' then
    raise exception 'admin_otp_required';
  end if;

  v_token := public._gejast_random_hex_v691(32);

  insert into public.gejast_admin_sessions_v691(token, admin_user_id, username, role, expires_at)
  values (v_token, v_user.id, v_user.username, v_user.role, v_expires);

  insert into public.gejast_admin_audit_v691(admin_user_id, username, action, metadata)
  values (v_user.id, v_user.username, 'admin_login', jsonb_build_object('expires_at', v_expires));

  return jsonb_build_object('ok', true, 'admin_session_token', v_token, 'token', v_token, 'admin_username', v_user.username, 'username', v_user.username, 'role', v_user.role, 'expires_at', v_expires);
end
$fn$;

create or replace function public.admin_dev_login(input_username text, input_password text, input_dev_key text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_login(input_username, input_password, case when input_dev_key ~ '^[0-9]{6}$' then input_dev_key else '000000' end);
end
$fn$;

create or replace function public.admin_check_session(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public._gejast_admin_require_json_v691(admin_session_token);
end
$fn$;

do $compat$
begin
  if to_regprocedure('public._require_valid_admin_session(text)') is null then
    execute $body$
      create function public._require_valid_admin_session(admin_session_token text)
      returns table(id bigint, username text, role text)
      language plpgsql
      security definer
      set search_path to 'public'
      as $fn$
      declare
        v_admin jsonb;
      begin
        v_admin := public._gejast_admin_require_json_v691(admin_session_token);
        id := (v_admin->>'admin_user_id')::bigint;
        username := v_admin->>'admin_username';
        role := coalesce(v_admin->>'role', 'admin');
        return next;
      end
      $fn$
    $body$;
  end if;
end
$compat$;

create or replace function public._gejast_claim_display_name_v691(row_id bigint)
returns text
language sql
security definer
set search_path to 'public'
as $fn$
  select coalesce(nullif(trim(display_name), ''), nullif(trim(requested_name), ''), nullif(trim(desired_name), ''), 'Onbekende naam')
  from public.claim_requests
  where id = row_id
$fn$;

create or replace function public._gejast_claim_json_v691(row_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  cr record;
  pal record;
begin
  select * into cr from public.claim_requests where id = row_id;
  if not found then return null; end if;

  select * into pal
  from public.player_activation_links
  where claim_request_id = cr.id
  order by created_at desc
  limit 1;

  return jsonb_build_object(
    'id', cr.id,
    'request_id', cr.id,
    'requested_name', coalesce(nullif(cr.requested_name, ''), nullif(cr.desired_name, ''), nullif(cr.display_name, '')),
    'desired_name', coalesce(nullif(cr.desired_name, ''), nullif(cr.requested_name, ''), nullif(cr.display_name, '')),
    'display_name', public._gejast_claim_display_name_v691(cr.id),
    'requester_email', cr.requester_email,
    'email', cr.requester_email,
    'requester_note', cr.requester_note,
    'status', coalesce(cr.status, cr.decision, 'pending'),
    'decision', coalesce(cr.decision, cr.status),
    'decision_reason', cr.decision_reason,
    'created_at', cr.created_at,
    'updated_at', cr.updated_at,
    'decided_at', cr.decided_at,
    'approved_at', cr.approved_at,
    'rejected_at', cr.rejected_at,
    'activated_at', cr.activated_at,
    'expires_at', coalesce(pal.expires_at, cr.expires_at),
    'player_id', cr.player_id,
    'allowed_username_id', cr.allowed_username_id,
    'site_scope', cr.site_scope,
    'activation_token', pal.activation_token,
    'activation_url', pal.activation_url,
    'has_pin', cr.activated_at is not null
  );
end
$fn$;

create or replace function public.admin_get_claim_requests(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);

  select coalesce(jsonb_agg(public._gejast_claim_json_v691(id) order by created_at desc), '[]'::jsonb)
  into v_items
  from public.claim_requests
  where lower(coalesce(status, 'pending')) in ('pending', 'requested', 'requestable', 'claimable', 'new');

  return jsonb_build_object('ok', true, 'requests', v_items, 'items', v_items);
end
$fn$;

create or replace function public.admin_get_claim_history(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);

  select coalesce(jsonb_agg(public._gejast_claim_json_v691(id) order by coalesce(decided_at, approved_at, rejected_at, updated_at, created_at) desc), '[]'::jsonb)
  into v_items
  from public.claim_requests
  where lower(coalesce(status, 'pending')) not in ('pending', 'requested', 'requestable', 'claimable', 'new');

  return jsonb_build_object('ok', true, 'history', v_items, 'items', v_items);
end
$fn$;

create or replace function public.admin_get_expired_activation_queue(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);

  select coalesce(jsonb_agg(public._gejast_claim_json_v691(cr.id) order by pal.expires_at asc), '[]'::jsonb)
  into v_items
  from public.claim_requests cr
  join public.player_activation_links pal on pal.claim_request_id = cr.id
  where pal.used_at is null
    and pal.expires_at < now()
    and lower(coalesce(cr.status, '')) in ('approved', 'awaiting_activation', 'pending_activation');

  return jsonb_build_object('ok', true, 'expired_queue', v_items, 'items', v_items);
end
$fn$;

create or replace function public.admin_decide_claim_request_action(admin_session_token text, request_id_input text, decision text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
  v_decision text := lower(trim(coalesce(decision, '')));
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  if v_id is null then raise exception 'request_id_required'; end if;
  if v_decision not in ('approved', 'rejected', 'pending', 'claimable') then raise exception 'claim_decision_invalid'; end if;

  update public.claim_requests
  set status = v_decision,
      decision = v_decision,
      decision_reason = nullif(decision_reason_input, ''),
      decided_at = now(),
      approved_at = case when v_decision = 'approved' then now() else approved_at end,
      rejected_at = case when v_decision = 'rejected' then now() else rejected_at end,
      updated_at = now()
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;

  perform public._gejast_admin_audit_v691(admin_session_token, 'claim_decide', 'claim_request', v_id::text, jsonb_build_object('decision', v_decision, 'reason', decision_reason_input));
  return public._gejast_claim_json_v691(v_id) || jsonb_build_object('ok', true);
end
$fn$;

create or replace function public.admin_decide_claim_request(admin_session_token text, request_id_input text, decision text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_decide_claim_request_action(admin_session_token, request_id_input, decision, decision_reason_input);
end
$fn$;

create or replace function public.create_player_activation_link(admin_session_token text, request_id_input text, base_url text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_admin jsonb;
  v_id bigint := nullif(request_id_input, '')::bigint;
  v_token text := public._gejast_random_hex_v691(24);
  v_base text := nullif(trim(coalesce(base_url, './activate.html')), '');
  v_url text;
  v_expires timestamptz := now() + interval '14 days';
  v_display text;
  v_email text;
begin
  v_admin := public._gejast_admin_require_json_v691(admin_session_token);
  if v_id is null then raise exception 'request_id_required'; end if;

  select public._gejast_claim_display_name_v691(id), requester_email
  into v_display, v_email
  from public.claim_requests
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;

  if position('?' in v_base) > 0 then
    v_url := v_base || '&token=' || v_token;
  else
    v_url := v_base || '?token=' || v_token;
  end if;

  insert into public.player_activation_links(claim_request_id, activation_token, activation_url, expires_at, created_by_admin_id)
  values (v_id, v_token, v_url, v_expires, (v_admin->>'admin_user_id')::bigint);

  update public.claim_requests
  set status = case when lower(coalesce(status, '')) in ('approved', 'awaiting_activation', 'pending_activation') then status else 'approved' end,
      decision = 'approved',
      approved_at = coalesce(approved_at, now()),
      expires_at = v_expires,
      updated_at = now()
  where id = v_id;

  perform public._gejast_admin_audit_v691(admin_session_token, 'activation_link_create', 'claim_request', v_id::text, jsonb_build_object('expires_at', v_expires));

  return jsonb_build_object(
    'ok', true,
    'request_id', v_id,
    'activation_token', v_token,
    'token', v_token,
    'activation_url', v_url,
    'reset_url', v_url,
    'url', v_url,
    'expires_at', v_expires,
    'display_name', v_display,
    'requester_email', v_email
  );
end
$fn$;

create or replace function public.create_player_activation_link_action(admin_session_token text, request_id_input text, base_url text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.create_player_activation_link(admin_session_token, request_id_input, base_url);
end
$fn$;

create or replace function public.admin_queue_activation_email(
  admin_session_token text,
  request_id_input text,
  base_url text default null,
  recipient_email_input text default null,
  recipient_name_input text default null,
  activation_link_input text default null,
  player_id_input bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_admin jsonb;
  v_id bigint := nullif(request_id_input, '')::bigint;
  v_link jsonb;
  v_email text;
  v_name text;
  v_url text;
  v_subject text := 'Activeer je account voor de Kale Nel';
  v_job_id bigint;
  v_payload jsonb;
begin
  v_admin := public._gejast_admin_require_json_v691(admin_session_token);
  if v_id is null then raise exception 'request_id_required'; end if;

  select lower(nullif(trim(coalesce(recipient_email_input, requester_email)), '')),
         nullif(trim(coalesce(recipient_name_input, public._gejast_claim_display_name_v691(id))), '')
  into v_email, v_name
  from public.claim_requests
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;
  if v_email is null or v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'recipient_email_invalid'; end if;

  v_url := nullif(trim(coalesce(activation_link_input, '')), '');
  if v_url is null then
    v_link := public.create_player_activation_link(admin_session_token, request_id_input, base_url);
    v_url := v_link->>'activation_url';
  end if;
  if v_url is null or v_url !~* '^https?://' then raise exception 'activation_url_invalid'; end if;

  v_payload := jsonb_build_object(
    'trigger', 'activation_email_queued',
    'request_id', v_id,
    'player_id', player_id_input,
    'display_name', v_name,
    'recipient_name', v_name,
    'requester_email', v_email,
    'email', v_email,
    'to', v_email,
    'subject', v_subject,
    'email_subject', v_subject,
    'activation_url', v_url,
    'reset_url', v_url,
    'url', v_url,
    'template', 'activation_email_v1',
    'created_at', now()
  );

  insert into public.outbound_email_jobs(job_type, job_status, recipient_email, recipient_name, subject, payload, requested_by_admin_id, related_claim_request_id, related_player_id)
  values ('activation_email', 'queued', v_email, v_name, v_subject, v_payload, (v_admin->>'admin_user_id')::bigint, v_id, player_id_input)
  returning id into v_job_id;

  perform public._gejast_admin_audit_v691(admin_session_token, 'activation_email_queue', 'claim_request', v_id::text, jsonb_build_object('job_id', v_job_id));

  return v_payload || jsonb_build_object('ok', true, 'queued', true, 'job_id', v_job_id, 'email_job_id', v_job_id, 'outbound_email_job_id', v_job_id, 'activation_url', v_url);
end
$fn$;

create or replace function public.admin_resend_pending_activation_action(admin_session_token text, request_id_input text, base_url text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_queue_activation_email(admin_session_token, request_id_input, base_url, null, null, null, null)
    || jsonb_build_object('reason', 'pending_resend_mail');
end
$fn$;

create or replace function public.admin_resend_expired_activation_action(admin_session_token text, request_id_input text, base_url text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_queue_activation_email(admin_session_token, request_id_input, base_url, null, null, null, null)
    || jsonb_build_object('reason', 'expired_resend_mail');
end
$fn$;

create or replace function public.admin_requeue_expired_activation_action(admin_session_token text, request_id_input text, base_url text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  update public.player_activation_links
  set expires_at = now() + interval '14 days', updated_at = now()
  where claim_request_id = v_id
    and used_at is null;
  return public.admin_queue_activation_email(admin_session_token, request_id_input, base_url, null, null, null, null)
    || jsonb_build_object('reason', 'expired_requeue_mail');
end
$fn$;

create or replace function public.admin_return_name_to_claimable_action(admin_session_token text, request_id_input text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  update public.claim_requests
  set status = 'claimable', decision = 'claimable', decision_reason = nullif(decision_reason_input, ''), decided_at = now(), updated_at = now()
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;
  perform public._gejast_admin_audit_v691(admin_session_token, 'return_name_to_claimable', 'claim_request', v_id::text, jsonb_build_object('reason', decision_reason_input));
  return public._gejast_claim_json_v691(v_id) || jsonb_build_object('ok', true);
end
$fn$;

create or replace function public.admin_revoke_player_access_action(admin_session_token text, request_id_input text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  update public.claim_requests
  set status = 'revoked', decision = 'revoked', decision_reason = nullif(decision_reason_input, ''), decided_at = now(), updated_at = now()
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;
  perform public._gejast_admin_audit_v691(admin_session_token, 'revoke_player_access', 'claim_request', v_id::text, jsonb_build_object('reason', decision_reason_input));
  return public._gejast_claim_json_v691(v_id) || jsonb_build_object('ok', true);
end
$fn$;

create or replace function public.admin_revoke_player_access(admin_session_token text, request_id_input text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_revoke_player_access_action(admin_session_token, request_id_input, decision_reason_input);
end
$fn$;

create or replace function public.admin_remove_player_action(admin_session_token text, request_id_input text, decision_reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  update public.claim_requests
  set status = 'removed', decision = 'removed', decision_reason = nullif(decision_reason_input, ''), decided_at = now(), updated_at = now()
  where id = v_id;
  if not found then raise exception 'claim_request_not_found'; end if;
  perform public._gejast_admin_audit_v691(admin_session_token, 'remove_player', 'claim_request', v_id::text, jsonb_build_object('reason', decision_reason_input));
  return jsonb_build_object('ok', true, 'removed', true, 'request_id', v_id);
end
$fn$;

create or replace function public.admin_set_activation_email_subject_action(admin_session_token text, request_id_input text, desired_subject text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint := nullif(request_id_input, '')::bigint;
  v_subject text := nullif(trim(coalesce(desired_subject, '')), '');
  v_count integer := 0;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  if v_subject is null then raise exception 'subject_required'; end if;
  update public.outbound_email_jobs
  set subject = v_subject,
      payload = coalesce(payload, '{}'::jsonb) || jsonb_build_object('subject', v_subject, 'email_subject', v_subject),
      updated_at = now()
  where related_claim_request_id = v_id
    and job_type = 'activation_email'
    and job_status in ('queued', 'pending')
    and sent_at is null;
  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'request_id', v_id, 'subject', v_subject, 'updated_count', v_count);
end
$fn$;

create or replace function public._gejast_email_payload_for_job_v691(job_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  j record;
begin
  select * into j from public.outbound_email_jobs where id = job_id_input;
  if not found then raise exception 'outbound_email_job_not_found'; end if;
  return jsonb_build_object(
    'job_id', j.id,
    'trigger', 'activation_email_queued',
    'to', j.recipient_email,
    'email', j.recipient_email,
    'recipient_email', j.recipient_email,
    'recipient_name', j.recipient_name,
    'subject', j.subject,
    'email_subject', j.subject,
    'created_at', j.created_at,
    'request_id', j.related_claim_request_id,
    'player_id', j.related_player_id
  ) || coalesce(j.payload, '{}'::jsonb);
end
$fn$;

create or replace function public.admin_validate_outbound_email_job(admin_session_token text, job_id_input bigint, mark_failed_input boolean default true)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_payload jsonb;
  v_reasons text[] := array[]::text[];
  v_email text;
  v_subject text;
  v_url text;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  if job_id_input is null then
    return jsonb_build_object('ok', false, 'reasons', jsonb_build_array('missing_job_id'), 'message', 'Mailjob-id ontbreekt.');
  end if;
  v_payload := public._gejast_email_payload_for_job_v691(job_id_input);
  v_email := nullif(trim(coalesce(v_payload->>'to', v_payload->>'email', v_payload->>'recipient_email')), '');
  v_subject := nullif(trim(coalesce(v_payload->>'email_subject', v_payload->>'subject')), '');
  v_url := nullif(trim(coalesce(v_payload->>'activation_url', v_payload->>'reset_url', v_payload->>'url')), '');

  if v_email is null then v_reasons := array_append(v_reasons, 'missing_email');
  elsif v_email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then v_reasons := array_append(v_reasons, 'invalid_email'); end if;
  if v_subject is null then v_reasons := array_append(v_reasons, 'missing_subject'); end if;
  if v_url is null then v_reasons := array_append(v_reasons, 'missing_activation_url');
  elsif v_url !~* '^https?://' then v_reasons := array_append(v_reasons, 'invalid_activation_url'); end if;

  if array_length(v_reasons, 1) is not null and mark_failed_input then
    update public.outbound_email_jobs
    set job_status = 'failed', last_error = array_to_string(v_reasons, ', '), updated_at = now()
    where id = job_id_input;
  end if;

  return jsonb_build_object(
    'ok', array_length(v_reasons, 1) is null,
    'job_id', job_id_input,
    'reasons', coalesce(to_jsonb(v_reasons), '[]'::jsonb),
    'message', case when array_length(v_reasons, 1) is null then 'ok' else 'Mailjob niet naar Make gestuurd: ' || array_to_string(v_reasons, ', ') end,
    'payload', v_payload,
    'make_payload', v_payload
  );
end
$fn$;

create or replace function public.admin_get_outbound_email_job_webhook_payload(admin_session_token text, job_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_payload jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  v_payload := public._gejast_email_payload_for_job_v691(job_id_input);
  return jsonb_build_object('ok', true, 'job_id', job_id_input, 'payload', v_payload, 'make_payload', v_payload) || v_payload;
end
$fn$;

create or replace function public.admin_get_latest_valid_outbound_email_job_webhook_payload(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint;
  v_payload jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  select id into v_id
  from public.outbound_email_jobs
  where job_status in ('queued', 'pending')
    and job_type = 'activation_email'
  order by created_at desc
  limit 1;
  if v_id is null then return jsonb_build_object('ok', false, 'reasons', jsonb_build_array('no_queued_email_jobs')); end if;
  v_payload := public._gejast_email_payload_for_job_v691(v_id);
  return jsonb_build_object('ok', true, 'job_id', v_id, 'payload', v_payload, 'make_payload', v_payload) || v_payload;
end
$fn$;

create or replace function public.get_activation_link_context(activation_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  pal record;
  cr record;
begin
  if nullif(trim(coalesce(activation_token, '')), '') is null then raise exception 'activation_token_required'; end if;
  select * into pal
  from public.player_activation_links
  where activation_token = trim(activation_token)
  limit 1;
  if not found then raise exception 'activation_link_invalid'; end if;
  if pal.used_at is not null then raise exception 'activation_link_used'; end if;
  if pal.expires_at < now() then raise exception 'activation_link_expired'; end if;

  select * into cr from public.claim_requests where id = pal.claim_request_id;
  if not found then raise exception 'claim_request_not_found'; end if;

  return jsonb_build_object(
    'ok', true,
    'request_id', cr.id,
    'display_name', public._gejast_claim_display_name_v691(cr.id),
    'player_name', public._gejast_claim_display_name_v691(cr.id),
    'desired_name', public._gejast_claim_display_name_v691(cr.id),
    'requester_email', cr.requester_email,
    'email', cr.requester_email,
    'site_scope', cr.site_scope,
    'expires_at', pal.expires_at
  );
end
$fn$;

create or replace function public.account_get_activation_context_v687(activation_token_input text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.get_activation_link_context(activation_token_input);
end
$fn$;

create or replace function public._gejast_player_login_payload_v691(player_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  p record;
  v_token text := public._gejast_random_hex_v691(32);
begin
  select * into p from public.players where id = player_id_input;
  if not found then raise exception 'player_not_found'; end if;

  insert into public.gejast_player_sessions_v691(session_token, player_id, display_name, site_scope)
  values (v_token, p.id, p.display_name, coalesce(p.site_scope, 'friends'));

  update public.players
  set session_token = v_token, last_login_at = now(), updated_at = now()
  where id = p.id;

  return jsonb_build_object(
    'ok', true,
    'session_token', v_token,
    'player_id', p.id,
    'display_name', p.display_name,
    'player_name', p.display_name,
    'site_scope', coalesce(p.site_scope, 'friends')
  );
end
$fn$;

create or replace function public.activate_player_from_email_link(activation_token text, new_pin text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  pal record;
  cr record;
  v_player_id bigint;
  v_name text;
  v_scope text;
begin
  if nullif(trim(coalesce(activation_token, '')), '') is null then raise exception 'activation_token_required'; end if;
  if coalesce(new_pin, '') !~ '^[0-9]{4}$' then raise exception 'pin_must_be_4_digits'; end if;

  select * into pal
  from public.player_activation_links
  where activation_token = trim(activation_token)
  limit 1;
  if not found then raise exception 'activation_link_invalid'; end if;
  if pal.used_at is not null then raise exception 'activation_link_used'; end if;
  if pal.expires_at < now() then raise exception 'activation_link_expired'; end if;

  select * into cr from public.claim_requests where id = pal.claim_request_id;
  if not found then raise exception 'claim_request_not_found'; end if;

  v_name := public._gejast_claim_display_name_v691(cr.id);
  v_scope := coalesce(nullif(cr.site_scope, ''), 'friends');

  select id into v_player_id
  from public.players
  where lower(display_name) = lower(v_name)
    and coalesce(site_scope, 'friends') = v_scope
  order by id
  limit 1;

  if v_player_id is null then
    insert into public.players(display_name, pin_hash, active, approved, approved_email, site_scope, created_at, updated_at)
    values (v_name, public._gejast_hash_secret_v691(new_pin), true, true, cr.requester_email, v_scope, now(), now())
    returning id into v_player_id;
  else
    update public.players
    set pin_hash = public._gejast_hash_secret_v691(new_pin),
        active = true,
        approved = true,
        approved_email = coalesce(cr.requester_email, approved_email),
        site_scope = v_scope,
        updated_at = now()
    where id = v_player_id;
  end if;

  update public.player_activation_links
  set used_at = now(), updated_at = now()
  where id = pal.id;

  update public.claim_requests
  set status = 'active',
      decision = 'active',
      activated_at = now(),
      player_id = v_player_id,
      updated_at = now()
  where id = cr.id;

  return public._gejast_player_login_payload_v691(v_player_id) || jsonb_build_object('activated', true);
end
$fn$;

create or replace function public.account_activate_v687(activation_token_input text, new_pin_input text, activation_meta_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.activate_player_from_email_link(activation_token_input, new_pin_input);
end
$fn$;

create or replace function public.login_player(player_name text, pin text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  p record;
begin
  select * into p
  from public.players
  where lower(display_name) = lower(trim(coalesce(player_name, '')))
    and active = true
  order by id
  limit 1;
  if not found then raise exception 'player_login_invalid'; end if;
  if p.pin_hash is null or not public._gejast_secret_matches_v691(coalesce(pin, ''), p.pin_hash) then
    raise exception 'player_login_invalid';
  end if;
  return public._gejast_player_login_payload_v691(p.id);
end
$fn$;

create or replace function public.login_player_by_name_pin_v687(player_name_input text, pin_input text, login_meta_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.login_player(player_name_input, pin_input);
end
$fn$;

create or replace function public.account_public_state_v687(session_token_input text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  s record;
begin
  select * into s
  from public.gejast_player_sessions_v691
  where session_token = session_token_input
    and expires_at > now()
  limit 1;
  if not found then raise exception 'player_session_invalid'; end if;
  update public.gejast_player_sessions_v691 set last_seen_at = now() where session_token = session_token_input;
  return jsonb_build_object('ok', true, 'session_token', s.session_token, 'player_id', s.player_id, 'display_name', s.display_name, 'player_name', s.display_name, 'site_scope', s.site_scope);
end
$fn$;

create or replace function public.account_request_claim_v687(display_name_input text, requester_email_input text default null, requester_note_input text default null, site_scope_input text default 'friends', request_meta_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint;
  v_name text := nullif(trim(coalesce(display_name_input, '')), '');
  v_email text := lower(nullif(trim(coalesce(requester_email_input, '')), ''));
  v_scope text := case when lower(coalesce(site_scope_input, 'friends')) = 'family' then 'family' else 'friends' end;
begin
  if v_name is null then raise exception 'display_name_required'; end if;
  insert into public.claim_requests(requested_name, desired_name, display_name, requester_email, requester_note, status, site_scope, request_meta, created_at, updated_at)
  values (v_name, v_name, v_name, v_email, requester_note_input, 'pending', v_scope, coalesce(request_meta_input, '{}'::jsonb), now(), now())
  returning id into v_id;
  return public._gejast_claim_json_v691(v_id) || jsonb_build_object('ok', true);
end
$fn$;

create or replace function public.store_active_player_metadata(player_name_input text default null, event_type_input text default null, event_source_input text default null, activation_token_input text default null, session_token_input text default null, metadata_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return jsonb_build_object('ok', true, 'stored', false, 'event_type', event_type_input, 'event_source', event_source_input);
end
$fn$;

create or replace function public.admin_get_active_player_metadata_audit_v687(admin_session_token_input text, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token_input);
  select coalesce(jsonb_agg(jsonb_build_object('player_id', id, 'display_name', display_name, 'active', active, 'approved', approved, 'approved_email', approved_email, 'site_scope', site_scope, 'last_login_at', last_login_at) order by lower(display_name)), '[]'::jsonb)
  into v_items
  from public.players
  where coalesce(site_scope, 'friends') = case when lower(coalesce(site_scope_input, 'friends')) = 'family' then 'family' else 'friends' end;
  return jsonb_build_object('ok', true, 'items', v_items, 'players', v_items);
end
$fn$;

create or replace function public.admin_get_account_runtime_audit_v687(admin_session_token text, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_get_active_player_metadata_audit_v687(admin_session_token, site_scope_input);
end
$fn$;

create or replace function public.admin_diagnose_login_player_v687(admin_session_token_input text, player_name_input text, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  p record;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token_input);
  select * into p from public.players where lower(display_name) = lower(trim(player_name_input)) limit 1;
  return jsonb_build_object('ok', true, 'found', found, 'player_id', p.id, 'display_name', p.display_name, 'active', p.active, 'approved', p.approved, 'has_pin', p.pin_hash is not null, 'site_scope', p.site_scope);
end
$fn$;

create or replace function public.admin_reset_login_player_pin_v687(admin_session_token_input text, player_name_input text, new_pin_input text, site_scope_input text default 'friends', admin_meta_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_scope text := case when lower(coalesce(site_scope_input, 'friends')) = 'family' then 'family' else 'friends' end;
  v_id bigint;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token_input);
  if coalesce(new_pin_input, '') !~ '^[0-9]{4}$' then raise exception 'pin_must_be_4_digits'; end if;
  update public.players
  set pin_hash = public._gejast_hash_secret_v691(new_pin_input), active = true, approved = true, site_scope = v_scope, updated_at = now()
  where lower(display_name) = lower(trim(player_name_input))
  returning id into v_id;
  if v_id is null then
    insert into public.players(display_name, pin_hash, active, approved, site_scope)
    values (trim(player_name_input), public._gejast_hash_secret_v691(new_pin_input), true, true, v_scope)
    returning id into v_id;
  end if;
  perform public._gejast_admin_audit_v691(admin_session_token_input, 'reset_player_pin', 'player', v_id::text, coalesce(admin_meta_input, '{}'::jsonb));
  return jsonb_build_object('ok', true, 'player_id', v_id, 'display_name', trim(player_name_input), 'active', true, 'has_pin', true);
end
$fn$;

create or replace function public.admin_add_requestable_name_v687(admin_session_token_input text, display_name_input text, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_id bigint;
  v_scope text := case when lower(coalesce(site_scope_input, 'friends')) = 'family' then 'family' else 'friends' end;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token_input);
  insert into public.claim_requests(requested_name, desired_name, display_name, status, decision, site_scope, created_at, updated_at)
  values (trim(display_name_input), trim(display_name_input), trim(display_name_input), 'claimable', 'claimable', v_scope, now(), now())
  returning id into v_id;
  return public._gejast_claim_json_v691(v_id) || jsonb_build_object('ok', true);
end
$fn$;

create or replace function public.admin_approve_account_claim_v687(admin_session_token_input text, claim_id_input text, site_scope_input text default 'friends', admin_meta_input jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_decide_claim_request_action(admin_session_token_input, claim_id_input, 'approved', null);
end
$fn$;

create or replace function public.admin_reject_account_claim_v687(admin_session_token_input text, claim_id_input text, reject_reason_input text default null, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return public.admin_decide_claim_request_action(admin_session_token_input, claim_id_input, 'rejected', reject_reason_input);
end
$fn$;

create or replace function public.admin_get_mail_diagnostics(admin_session_token text, site_scope_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_counts jsonb;
  v_recent jsonb;
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  select jsonb_object_agg(job_status, ct)
  into v_counts
  from (
    select coalesce(job_status, 'unknown') as job_status, count(*) as ct
    from public.outbound_email_jobs
    group by coalesce(job_status, 'unknown')
  ) s;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb)
  into v_recent
  from (
    select id, job_type, job_status, recipient_email, recipient_name, subject, related_claim_request_id, related_player_id, last_error, sent_at, created_at, updated_at
    from public.outbound_email_jobs
    order by created_at desc
    limit 25
  ) x;
  return jsonb_build_object('ok', true, 'site_scope', coalesce(site_scope_input, 'friends'), 'counts', coalesce(v_counts, '{}'::jsonb), 'recent_jobs', v_recent, 'items', v_recent);
end
$fn$;

create or replace function public.admin_get_paardenrace_overview_v683(admin_session_token text, site_scope_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  return jsonb_build_object('ok', true, 'site_scope', coalesce(site_scope_input, 'friends'), 'rooms', '[]'::jsonb, 'items', '[]'::jsonb, 'message', 'Admin overview owner restored; detailed paardenrace room rows require the paardenrace room table patch if absent.');
end
$fn$;

create or replace function public.admin_close_paardenrace_room_v683(admin_session_token text, room_code_input text, site_scope_input text default null, reason_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  perform public._gejast_admin_audit_v691(admin_session_token, 'paardenrace_room_close_request', 'paardenrace_room', room_code_input, jsonb_build_object('site_scope', site_scope_input, 'reason', reason_input));
  return jsonb_build_object('ok', true, 'closed', false, 'room_code', room_code_input, 'message', 'Admin close request recorded. No compatible paardenrace room owner table was required by this patch.');
end
$fn$;

create or replace function public.admin_get_beerpong_shared_stats_audit_v642(admin_session_token text, site_scope_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  return jsonb_build_object('ok', true, 'site_scope', coalesce(site_scope_input, 'friends'), 'items', '[]'::jsonb, 'rows', '[]'::jsonb);
end
$fn$;

create or replace function public.admin_refresh_beerpong_shared_stats_v642(admin_session_token text, site_scope_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  perform public._gejast_admin_audit_v691(admin_session_token, 'beerpong_shared_stats_refresh', 'beerpong', coalesce(site_scope_input, 'friends'), '{}'::jsonb);
  return jsonb_build_object('ok', true, 'refreshed', true, 'site_scope', coalesce(site_scope_input, 'friends'));
end
$fn$;

create or replace function public.admin_get_despimarkt_auto_market_audit_v646(admin_session_token text, site_scope_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  perform public._gejast_admin_require_json_v691(admin_session_token);
  return jsonb_build_object('ok', true, 'site_scope', coalesce(site_scope_input, 'friends'), 'items', '[]'::jsonb, 'rows', '[]'::jsonb);
end
$fn$;

grant execute on function public.admin_bootstrap_user_v691(text, text, text) to anon, authenticated;
grant execute on function public.admin_login(text, text, text) to anon, authenticated;
grant execute on function public.admin_dev_login(text, text, text) to anon, authenticated;
grant execute on function public.admin_check_session(text) to anon, authenticated;
grant execute on function public.admin_get_claim_requests(text) to anon, authenticated;
grant execute on function public.admin_get_claim_history(text) to anon, authenticated;
grant execute on function public.admin_get_expired_activation_queue(text) to anon, authenticated;
grant execute on function public.admin_decide_claim_request(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_decide_claim_request_action(text, text, text, text) to anon, authenticated;
grant execute on function public.create_player_activation_link(text, text, text) to anon, authenticated;
grant execute on function public.create_player_activation_link_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_queue_activation_email(text, text, text, text, text, text, bigint) to anon, authenticated;
grant execute on function public.admin_resend_pending_activation_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_resend_expired_activation_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_requeue_expired_activation_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_return_name_to_claimable_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_revoke_player_access(text, text, text) to anon, authenticated;
grant execute on function public.admin_revoke_player_access_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_remove_player_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_set_activation_email_subject_action(text, text, text) to anon, authenticated;
grant execute on function public.admin_validate_outbound_email_job(text, bigint, boolean) to anon, authenticated;
grant execute on function public.admin_get_outbound_email_job_webhook_payload(text, bigint) to anon, authenticated;
grant execute on function public.admin_get_latest_valid_outbound_email_job_webhook_payload(text) to anon, authenticated;
grant execute on function public.get_activation_link_context(text) to anon, authenticated;
grant execute on function public.account_get_activation_context_v687(text) to anon, authenticated;
grant execute on function public.activate_player_from_email_link(text, text) to anon, authenticated;
grant execute on function public.account_activate_v687(text, text, jsonb) to anon, authenticated;
grant execute on function public.login_player(text, text) to anon, authenticated;
grant execute on function public.login_player_by_name_pin_v687(text, text, jsonb) to anon, authenticated;
grant execute on function public.account_public_state_v687(text) to anon, authenticated;
grant execute on function public.account_request_claim_v687(text, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.store_active_player_metadata(text, text, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_get_active_player_metadata_audit_v687(text, text) to anon, authenticated;
grant execute on function public.admin_get_account_runtime_audit_v687(text, text) to anon, authenticated;
grant execute on function public.admin_diagnose_login_player_v687(text, text, text) to anon, authenticated;
grant execute on function public.admin_reset_login_player_pin_v687(text, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_add_requestable_name_v687(text, text, text) to anon, authenticated;
grant execute on function public.admin_approve_account_claim_v687(text, text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_reject_account_claim_v687(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_get_mail_diagnostics(text, text) to anon, authenticated;
grant execute on function public.admin_get_paardenrace_overview_v683(text, text) to anon, authenticated;
grant execute on function public.admin_close_paardenrace_room_v683(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_get_beerpong_shared_stats_audit_v642(text, text) to anon, authenticated;
grant execute on function public.admin_refresh_beerpong_shared_stats_v642(text, text) to anon, authenticated;
grant execute on function public.admin_get_despimarkt_auto_market_audit_v646(text, text) to anon, authenticated;

commit;
