-- GEJAST / Wordt er gejast
-- v415 paardenrace SQL regeneration
-- Matches the reuploaded paardenrace frontend owner path:
-- - paardenrace.html
-- - paardenrace_live.html
-- - paardenrace_stats.html
-- - gejast-paardenrace.js
--
-- Core model:
-- - room/lobby state stays server-authoritative
-- - active match state lives in public.paardenrace_rooms.active_match jsonb
-- - completed match snapshots are copied into public.paardenrace_match_history
-- - obligations are stored in public.paardenrace_obligations

create extension if not exists pgcrypto;

create table if not exists public.paardenrace_rooms (
  id bigint generated by default as identity primary key,
  room_code text not null unique,
  host_player_id bigint,
  host_name text not null,
  stage text not null default 'lobby',
  countdown_ends_at timestamptz,
  active_match jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.paardenrace_room_players (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.paardenrace_rooms(id) on delete cascade,
  player_id bigint,
  player_name text not null,
  player_name_norm text generated always as (lower(player_name)) stored,
  selected_suit text,
  wager_bakken integer,
  is_ready boolean not null default false,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id, player_name_norm)
);

create table if not exists public.paardenrace_obligations (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.paardenrace_rooms(id) on delete cascade,
  match_ref uuid,
  player_id bigint,
  player_name text not null,
  amount_bakken integer not null,
  source_kind text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.paardenrace_match_history (
  id bigint generated by default as identity primary key,
  room_id bigint references public.paardenrace_rooms(id) on delete set null,
  room_code text,
  match_ref uuid not null,
  winner_suit text,
  summary_payload jsonb not null default '{}'::jsonb,
  finished_at timestamptz not null default now()
);

create or replace function public._paardenrace_safe_token(session_token text default null, session_token_input text default null)
returns text language sql immutable as $$
  select nullif(trim(coalesce(session_token, session_token_input, '')), '')
$$;

create or replace function public._paardenrace_require_name(session_token text default null, session_token_input text default null)
returns text language plpgsql security definer as $$
declare
  v_name text;
begin
  v_name := public._gejast_name_for_session(public._paardenrace_safe_token(session_token, session_token_input));
  if nullif(trim(coalesce(v_name,'')), '') is null then
    raise exception 'Log eerst in als speler.';
  end if;
  return v_name;
end;
$$;

create or replace function public._paardenrace_player_id(session_token text default null, session_token_input text default null)
returns bigint language plpgsql security definer as $$
declare
  v_token text := public._paardenrace_safe_token(session_token, session_token_input);
begin
  if v_token is null then
    return null;
  end if;
  begin
    return public._resolve_player_id_from_session_token(v_token);
  exception when others then
    return null;
  end;
end;
$$;

create or replace function public._paardenrace_random_room_code()
returns text language plpgsql security definer as $$
declare
  v_code text;
begin
  loop
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    exit when not exists(select 1 from public.paardenrace_rooms where room_code = v_code);
  end loop;
  return v_code;
end;
$$;

create or replace function public._paardenrace_suit_from_card(card_code text)
returns text language sql immutable as $$
  select case upper(right(coalesce(card_code,''), 1))
    when 'H' then 'hearts'
    when 'D' then 'diamonds'
    when 'C' then 'clubs'
    when 'S' then 'spades'
    else null
  end
$$;

create or replace function public._paardenrace_all_ready(room_id_input bigint)
returns boolean language sql stable as $$
  select exists(select 1 from public.paardenrace_room_players rp where rp.room_id = room_id_input)
     and not exists(
       select 1
       from public.paardenrace_room_players rp
       where rp.room_id = room_id_input
         and (
           coalesce(rp.is_ready,false) is false
           or rp.selected_suit is null
           or rp.wager_bakken is null
           or rp.wager_bakken < 1
         )
     )
$$;

create or replace function public._paardenrace_make_decks()
returns jsonb language sql volatile as $$
with deck as (
  select rank, suit, rank||suit as code
  from unnest(array['A','2','3','4','5','6','7','8','9','10','J','Q','K']) as rank
  cross join unnest(array['H','D','C','S']) as suit
),
non_aces as (
  select code
  from deck
  where code not in ('AH','AD','AC','AS')
  order by random()
),
numbered as (
  select code, row_number() over () as rn
  from non_aces
)
select jsonb_build_object(
  'gate_cards', coalesce((select jsonb_agg(code order by rn) from numbered where rn <= 10), '[]'::jsonb),
  'draw_deck', coalesce((select jsonb_agg(code order by rn) from numbered where rn > 10), '[]'::jsonb)
)
$$;

create or replace function public._paardenrace_upsert_player(room_id_input bigint, player_name_input text, player_id_input bigint)
returns void language plpgsql security definer as $$
begin
  insert into public.paardenrace_room_players(room_id, player_id, player_name)
  values (room_id_input, player_id_input, player_name_input)
  on conflict (room_id, player_name_norm) do update
    set player_id = coalesce(excluded.player_id, public.paardenrace_room_players.player_id),
        updated_at = now();
end;
$$;

create or replace function public._paardenrace_total_for_player(room_id_input bigint, player_name_input text)
returns integer language sql stable as $$
  select coalesce(sum(o.amount_bakken),0)::integer
  from public.paardenrace_obligations o
  where o.room_id = room_id_input
    and lower(o.player_name) = lower(player_name_input)
$$;

create or replace function public._paardenrace_result_summary(room_id_input bigint, active_match_input jsonb)
returns jsonb language plpgsql security definer as $$
declare
  v_rows jsonb := '[]'::jsonb;
begin
  select coalesce(jsonb_agg(jsonb_build_object(
    'player_name', rp.player_name,
    'selected_suit', rp.selected_suit,
    'wager_bakken', rp.wager_bakken,
    'is_winner', lower(coalesce(rp.selected_suit,'')) = lower(coalesce(active_match_input->>'winner_suit','')),
    'extra_bakken_received', coalesce((
      select sum((x->>'bakken')::integer)
      from jsonb_array_elements(coalesce(active_match_input->'nominations','[]'::jsonb)) x
      where lower(coalesce(x->>'target_player_name','')) = lower(rp.player_name)
    ),0),
    'total_bakken_owed', public._paardenrace_total_for_player(room_id_input, rp.player_name)
  ) order by rp.joined_at), '[]'::jsonb)
  into v_rows
  from public.paardenrace_room_players rp
  where rp.room_id = room_id_input;

  return jsonb_build_object('per_player', v_rows);
end;
$$;

create or replace function public._paardenrace_build_room_state(room_code_input text default null, session_token text default null, session_token_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_room public.paardenrace_rooms%rowtype;
  v_viewer_name text;
  v_players jsonb := '[]'::jsonb;
  v_viewer jsonb := '{}'::jsonb;
  v_active jsonb := '{}'::jsonb;
  v_result jsonb := null;
begin
  v_viewer_name := public._paardenrace_require_name(session_token, session_token_input);

  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;

  v_active := coalesce(v_room.active_match, '{}'::jsonb);

  select coalesce(jsonb_agg(jsonb_build_object(
    'player_name', rp.player_name,
    'selected_suit', rp.selected_suit,
    'wager_bakken', rp.wager_bakken,
    'is_ready', rp.is_ready,
    'is_host', lower(rp.player_name) = lower(v_room.host_name),
    'is_winner', lower(coalesce(rp.selected_suit,'')) = lower(coalesce(v_active->>'winner_suit','')),
    'total_bakken_owed', public._paardenrace_total_for_player(v_room.id, rp.player_name)
  ) order by rp.joined_at), '[]'::jsonb)
  into v_players
  from public.paardenrace_room_players rp
  where rp.room_id = v_room.id;

  select jsonb_build_object(
    'player_name', rp.player_name,
    'selected_suit', rp.selected_suit,
    'wager_bakken', rp.wager_bakken,
    'is_host', lower(rp.player_name) = lower(v_room.host_name),
    'can_nominate', v_room.stage = 'nominations'
      and lower(coalesce(rp.selected_suit,'')) = lower(coalesce(v_active->>'winner_suit',''))
      and not coalesce((v_active->'winner_submitted'->>lower(rp.player_name))::boolean, false),
    'nomination_budget_bakken', coalesce(rp.wager_bakken,0) * 2
  )
  into v_viewer
  from public.paardenrace_room_players rp
  where rp.room_id = v_room.id
    and lower(rp.player_name) = lower(v_viewer_name)
  limit 1;

  if v_active <> '{}'::jsonb then
    v_result := public._paardenrace_result_summary(v_room.id, v_active);
  end if;

  return jsonb_build_object(
    'room', jsonb_build_object(
      'room_code', v_room.room_code,
      'host_name', v_room.host_name,
      'stage', v_room.stage,
      'stage_label', case v_room.stage
        when 'lobby' then 'Lobby'
        when 'countdown' then 'Countdown'
        when 'race' then 'Race'
        when 'nominations' then 'Nominaties'
        when 'finished' then 'Finished'
        else v_room.stage end,
      'can_start', v_room.stage = 'lobby' and lower(v_room.host_name) = lower(v_viewer_name) and public._paardenrace_all_ready(v_room.id),
      'can_draw', v_room.stage = 'race' and lower(v_room.host_name) = lower(v_viewer_name),
      'countdown_remaining_seconds', case
        when v_room.stage = 'countdown' and v_room.countdown_ends_at is not null and v_room.countdown_ends_at > now()
          then greatest(0, ceil(extract(epoch from (v_room.countdown_ends_at - now())))::integer)
        else 0 end
    ),
    'viewer', coalesce(v_viewer, '{}'::jsonb),
    'players', v_players,
    'match', case when v_active = '{}'::jsonb then null else v_active end,
    'result_summary', v_result
  );
end;
$$;

create or replace function public.create_paardenrace_room_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_player_id bigint := public._paardenrace_player_id(session_token, session_token_input);
  v_code text := upper(trim(coalesce(room_code_input,'')));
  v_room_id bigint;
begin
  if v_code = '' then
    v_code := public._paardenrace_random_room_code();
  end if;

  insert into public.paardenrace_rooms(room_code, host_player_id, host_name)
  values (v_code, v_player_id, v_name)
  returning id into v_room_id;

  perform public._paardenrace_upsert_player(v_room_id, v_name, v_player_id);

  return public._paardenrace_build_room_state(v_code, session_token, session_token_input);
end;
$$;

create or replace function public.join_paardenrace_room_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_player_id bigint := public._paardenrace_player_id(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;

  perform public._paardenrace_upsert_player(v_room.id, v_name, v_player_id);

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.update_paardenrace_room_choice_safe(session_token text default null, session_token_input text default null, room_code_input text default null, selected_suit_input text default null, wager_bakken_input integer default null, ready_input boolean default false)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
  v_suit text := lower(trim(coalesce(selected_suit_input,'')));
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;

  if v_suit not in ('hearts','diamonds','clubs','spades') then
    v_suit := null;
  end if;

  update public.paardenrace_room_players
  set selected_suit = v_suit,
      wager_bakken = wager_bakken_input,
      is_ready = case
        when ready_input is true and v_suit is not null and wager_bakken_input is not null and wager_bakken_input > 0 then true
        else false end,
      updated_at = now()
  where room_id = v_room.id
    and lower(player_name) = lower(v_name);

  update public.paardenrace_rooms set updated_at = now() where id = v_room.id;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.start_paardenrace_countdown_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;
  if lower(v_room.host_name) <> lower(v_name) then
    raise exception 'Alleen de host mag starten.';
  end if;
  if not public._paardenrace_all_ready(v_room.id) then
    raise exception 'Nog niet iedereen is ready.';
  end if;

  update public.paardenrace_rooms
  set stage = 'countdown',
      countdown_ends_at = now() + interval '5 seconds',
      updated_at = now()
  where id = v_room.id;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.tick_paardenrace_room_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_room public.paardenrace_rooms%rowtype;
  v_decks jsonb;
  v_match_ref uuid;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;

  if v_room.stage = 'countdown' and v_room.countdown_ends_at is not null and v_room.countdown_ends_at <= now() then
    v_decks := public._paardenrace_make_decks();
    v_match_ref := gen_random_uuid();

    update public.paardenrace_rooms
    set stage = 'race',
        countdown_ends_at = null,
        active_match = jsonb_build_object(
          'match_ref', v_match_ref,
          'gate_cards', v_decks->'gate_cards',
          'draw_deck', v_decks->'draw_deck',
          'draw_index', 0,
          'revealed_draw_cards', '[]'::jsonb,
          'horse_positions', jsonb_build_object('hearts',0,'diamonds',0,'clubs',0,'spades',0),
          'revealed_gates', '[]'::jsonb,
          'gate_events', '[]'::jsonb,
          'winner_submitted', '{}'::jsonb,
          'nominations', '[]'::jsonb,
          'first_finish_suit', null,
          'first_claimed_finish_suit', null,
          'winner_suit', null,
          'last_draw_card', null
        ),
        updated_at = now(),
        finished_at = null
    where id = v_room.id;

    insert into public.paardenrace_obligations(room_id, match_ref, player_id, player_name, amount_bakken, source_kind, metadata)
    select v_room.id, v_match_ref, rp.player_id, rp.player_name, rp.wager_bakken, 'wager',
           jsonb_build_object('source_game','paardenrace','source_kind','wager','selected_suit',rp.selected_suit)
    from public.paardenrace_room_players rp
    where rp.room_id = v_room.id
      and coalesce(rp.wager_bakken,0) > 0;
  end if;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.draw_paardenrace_card_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
  m jsonb;
  draw_idx integer;
  draw_deck jsonb;
  gate_cards jsonb;
  positions jsonb;
  revealed jsonb;
  gate_events jsonb;
  card text;
  suit text;
  gate_no integer;
  gate_card text;
  gate_suit text;
  all_ready_gate boolean;
  winner_suit text;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;
  if lower(v_room.host_name) <> lower(v_name) then
    raise exception 'Alleen de host mag trekken.';
  end if;
  if v_room.stage <> 'race' then
    raise exception 'De race is niet actief.';
  end if;

  m := v_room.active_match;
  draw_idx := coalesce((m->>'draw_index')::integer, 0);
  draw_deck := coalesce(m->'draw_deck', '[]'::jsonb);
  gate_cards := coalesce(m->'gate_cards', '[]'::jsonb);
  positions := coalesce(m->'horse_positions', jsonb_build_object('hearts',0,'diamonds',0,'clubs',0,'spades',0));
  revealed := coalesce(m->'revealed_gates', '[]'::jsonb);
  gate_events := '[]'::jsonb;

  card := draw_deck->>draw_idx;
  if card is null then
    raise exception 'De trekstapel is leeg.';
  end if;

  suit := public._paardenrace_suit_from_card(card);
  positions := jsonb_set(positions, array[suit], to_jsonb(least(11, coalesce((positions->>suit)::integer,0) + 1)), true);

  if coalesce(m->>'first_finish_suit','') = '' and coalesce((positions->>suit)::integer,0) >= 11 then
    m := jsonb_set(m, '{first_finish_suit}', to_jsonb(suit), true);
  end if;

  for gate_no in 1..10 loop
    if exists(select 1 from jsonb_array_elements_text(revealed) v where v.value::integer = gate_no) then
      continue;
    end if;

    all_ready_gate := coalesce((positions->>'hearts')::integer,0) >= gate_no
      and coalesce((positions->>'diamonds')::integer,0) >= gate_no
      and coalesce((positions->>'clubs')::integer,0) >= gate_no
      and coalesce((positions->>'spades')::integer,0) >= gate_no;

    if all_ready_gate then
      gate_card := gate_cards->>(gate_no - 1);
      gate_suit := public._paardenrace_suit_from_card(gate_card);
      positions := jsonb_set(positions, array[gate_suit], to_jsonb(greatest(0, coalesce((positions->>gate_suit)::integer,0) - 1)), true);
      revealed := revealed || to_jsonb(gate_no);
      gate_events := gate_events || jsonb_build_array(jsonb_build_object('gate_no', gate_no, 'card_code', gate_card, 'suit', gate_suit));
    end if;
  end loop;

  if coalesce(m->>'winner_suit','') = '' then
    select min(suit_key) into winner_suit
    from (values ('hearts'),('diamonds'),('clubs'),('spades')) s(suit_key)
    where coalesce((positions->>suit_key)::integer,0) >= 11
      and exists(
        select 1
        from public.paardenrace_room_players rp
        where rp.room_id = v_room.id
          and lower(coalesce(rp.selected_suit,'')) = lower(suit_key)
      );

    if winner_suit is not null then
      m := jsonb_set(m, '{winner_suit}', to_jsonb(winner_suit), true);
      m := jsonb_set(m, '{first_claimed_finish_suit}', to_jsonb(winner_suit), true);
      update public.paardenrace_rooms set stage = 'nominations', updated_at = now() where id = v_room.id;
    end if;
  end if;

  m := jsonb_set(m, '{draw_index}', to_jsonb(draw_idx + 1), true);
  m := jsonb_set(m, '{last_draw_card}', to_jsonb(card), true);
  m := jsonb_set(m, '{revealed_draw_cards}', coalesce(m->'revealed_draw_cards','[]'::jsonb) || to_jsonb(card), true);
  m := jsonb_set(m, '{horse_positions}', positions, true);
  m := jsonb_set(m, '{revealed_gates}', revealed, true);
  m := jsonb_set(m, '{gate_events}', gate_events, true);

  update public.paardenrace_rooms
  set active_match = m,
      updated_at = now()
  where id = v_room.id;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.submit_paardenrace_nominations_safe(session_token text default null, session_token_input text default null, room_code_input text default null, allocations_input jsonb default '[]'::jsonb)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_player_id bigint := public._paardenrace_player_id(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
  m jsonb;
  v_budget integer;
  v_total integer := 0;
  row jsonb;
  tgt text;
  b integer;
  v_match_ref uuid;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;
  if v_room.stage <> 'nominations' then
    raise exception 'Nominatiefase is niet actief.';
  end if;

  m := coalesce(v_room.active_match, '{}'::jsonb);
  v_match_ref := nullif(coalesce(m->>'match_ref',''),'')::uuid;

  select rp.wager_bakken * 2 into v_budget
  from public.paardenrace_room_players rp
  where rp.room_id = v_room.id
    and lower(rp.player_name) = lower(v_name)
    and lower(coalesce(rp.selected_suit,'')) = lower(coalesce(m->>'winner_suit',''))
  limit 1;

  if v_budget is null then
    raise exception 'Alleen winnaars mogen nomineren.';
  end if;
  if coalesce((m->'winner_submitted'->>lower(v_name))::boolean, false) then
    raise exception 'Jouw nominaties zijn al opgeslagen.';
  end if;

  for row in select value from jsonb_array_elements(coalesce(allocations_input,'[]'::jsonb)) loop
    tgt := trim(coalesce(row->>'target_player_name',''));
    b := coalesce((row->>'bakken')::integer, 0);
    if b <= 0 then continue; end if;
    if lower(tgt) = lower(v_name) then
      raise exception 'Je mag jezelf niet nomineren.';
    end if;
    if not exists(select 1 from public.paardenrace_room_players rp where rp.room_id = v_room.id and lower(rp.player_name) = lower(tgt)) then
      raise exception 'Onbekende speler in nominaties: %', tgt;
    end if;
    v_total := v_total + b;
  end loop;

  if v_total <> v_budget then
    raise exception 'Je moet exact % Bakken verdelen.', v_budget;
  end if;

  for row in select value from jsonb_array_elements(coalesce(allocations_input,'[]'::jsonb)) loop
    tgt := trim(coalesce(row->>'target_player_name',''));
    b := coalesce((row->>'bakken')::integer, 0);
    if b <= 0 then continue; end if;

    insert into public.paardenrace_obligations(room_id, match_ref, player_id, player_name, amount_bakken, source_kind, metadata)
    values (
      v_room.id,
      v_match_ref,
      null,
      tgt,
      b,
      'winner_nomination',
      jsonb_build_object(
        'source_game','paardenrace',
        'source_kind','winner_nomination',
        'winner_player_id',v_player_id,
        'winner_player_name',v_name,
        'target_player_name',tgt
      )
    );
  end loop;

  m := jsonb_set(m, '{nominations}', coalesce(m->'nominations','[]'::jsonb) || allocations_input, true);
  m := jsonb_set(m, array['winner_submitted', lower(v_name)], 'true'::jsonb, true);

  update public.paardenrace_rooms
  set active_match = m,
      updated_at = now()
  where id = v_room.id;

  if not exists(
    select 1
    from public.paardenrace_room_players rp
    where rp.room_id = v_room.id
      and lower(coalesce(rp.selected_suit,'')) = lower(coalesce(m->>'winner_suit',''))
      and not coalesce((m->'winner_submitted'->>lower(rp.player_name))::boolean, false)
  ) then
    insert into public.paardenrace_match_history(room_id, room_code, match_ref, winner_suit, summary_payload, finished_at)
    values (
      v_room.id,
      v_room.room_code,
      v_match_ref,
      m->>'winner_suit',
      public._paardenrace_result_summary(v_room.id, m),
      now()
    );

    update public.paardenrace_rooms
    set stage = 'finished',
        active_match = m,
        finished_at = now(),
        updated_at = now()
    where id = v_room.id;
  end if;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.reset_paardenrace_room_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_name text := public._paardenrace_require_name(session_token, session_token_input);
  v_room public.paardenrace_rooms%rowtype;
begin
  select * into v_room
  from public.paardenrace_rooms
  where room_code = upper(trim(coalesce(room_code_input,'')));

  if v_room.id is null then
    raise exception 'Room niet gevonden.';
  end if;
  if lower(v_room.host_name) <> lower(v_name) then
    raise exception 'Alleen de host mag resetten.';
  end if;

  update public.paardenrace_room_players
  set selected_suit = null,
      wager_bakken = null,
      is_ready = false,
      updated_at = now()
  where room_id = v_room.id;

  update public.paardenrace_rooms
  set stage = 'lobby',
      countdown_ends_at = null,
      active_match = '{}'::jsonb,
      updated_at = now()
  where id = v_room.id;

  return public._paardenrace_build_room_state(v_room.room_code, session_token, session_token_input);
end;
$$;

create or replace function public.get_paardenrace_room_state_safe(session_token text default null, session_token_input text default null, room_code_input text default null)
returns jsonb language plpgsql security definer as $$
begin
  return public._paardenrace_build_room_state(room_code_input, session_token, session_token_input);
end;
$$;

create or replace function public.get_paardenrace_stats_public(session_token text default null, session_token_input text default null)
returns jsonb language plpgsql security definer as $$
declare
  v_overview jsonb;
  v_recent jsonb;
begin
  select jsonb_build_object(
    'matches_played', coalesce((select count(*) from public.paardenrace_match_history),0),
    'total_bakken', coalesce((select sum(amount_bakken) from public.paardenrace_obligations),0),
    'last_winner_suit', (select h.winner_suit from public.paardenrace_match_history h order by h.finished_at desc limit 1)
  ) into v_overview;

  select coalesce(jsonb_agg(jsonb_build_object(
    'room_code', h.room_code,
    'winner_suit', h.winner_suit,
    'player_names', coalesce(h.summary_payload->'per_player', '[]'::jsonb),
    'finished_at', h.finished_at
  ) order by h.finished_at desc), '[]'::jsonb)
  into v_recent
  from (
    select *
    from public.paardenrace_match_history
    order by finished_at desc
    limit 20
  ) h;

  return jsonb_build_object('overview', v_overview, 'recent_matches', v_recent);
end;
$$;

grant execute on function public.create_paardenrace_room_safe(text,text,text) to anon, authenticated;
grant execute on function public.join_paardenrace_room_safe(text,text,text) to anon, authenticated;
grant execute on function public.update_paardenrace_room_choice_safe(text,text,text,text,integer,boolean) to anon, authenticated;
grant execute on function public.start_paardenrace_countdown_safe(text,text,text) to anon, authenticated;
grant execute on function public.tick_paardenrace_room_safe(text,text,text) to anon, authenticated;
grant execute on function public.draw_paardenrace_card_safe(text,text,text) to anon, authenticated;
grant execute on function public.submit_paardenrace_nominations_safe(text,text,text,jsonb) to anon, authenticated;
grant execute on function public.reset_paardenrace_room_safe(text,text,text) to anon, authenticated;
grant execute on function public.get_paardenrace_room_state_safe(text,text,text) to anon, authenticated;
grant execute on function public.get_paardenrace_stats_public(text,text) to anon, authenticated;
