begin;

create extension if not exists pgcrypto with schema extensions;

create or replace function public._normalize_allowed_username(input_text text)
returns text
language sql
immutable
as $$
  select trim(both '-' from regexp_replace(lower(coalesce(input_text, '')), '[^a-z0-9]+', '-', 'g'));
$$;

create table if not exists public.allowed_usernames (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null,
  status text not null default 'available',
  reserved_for_email text null,
  reserved_for_person_note text null,
  player_id bigint null references public.players(id) on delete set null,
  current_claim_request_id bigint null references public.claim_requests(id) on delete set null,
  activation_link_id bigint null references public.player_activation_links(id) on delete set null,
  approved_by_admin_id bigint null,
  blocked_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint allowed_usernames_status_check check (
    lower(status) in (
      'available',
      'reserved',
      'pending_review',
      'approved_pending_activation',
      'active',
      'expired',
      'rejected',
      'blocked'
    )
  )
);

create unique index if not exists allowed_usernames_username_lower_uidx
  on public.allowed_usernames (lower(username));

create unique index if not exists allowed_usernames_display_name_lower_uidx
  on public.allowed_usernames (lower(display_name));

create table if not exists public.username_events (
  id bigint generated by default as identity primary key,
  allowed_username_id bigint not null references public.allowed_usernames(id) on delete cascade,
  event_type text not null,
  admin_id bigint null,
  claim_request_id bigint null references public.claim_requests(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.claim_requests
  add column if not exists allowed_username_id bigint null references public.allowed_usernames(id) on delete set null;

alter table public.claim_requests
  add column if not exists request_status text null;

alter table public.player_activation_links
  add column if not exists expired_processed_at timestamptz null;

create or replace function public._log_username_event(
  p_allowed_username_id bigint,
  p_event_type text,
  p_admin_id bigint default null,
  p_claim_request_id bigint default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if p_allowed_username_id is null then
    return;
  end if;

  insert into public.username_events (
    allowed_username_id,
    event_type,
    admin_id,
    claim_request_id,
    details
  )
  values (
    p_allowed_username_id,
    p_event_type,
    p_admin_id,
    p_claim_request_id,
    coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

insert into public.allowed_usernames (username, display_name, status, player_id)
select
  public._normalize_allowed_username(p.display_name) as username,
  p.display_name,
  case
    when coalesce(p.active, false) is true and p.pin_hash is not null then 'active'
    when p.pin_hash is not null then 'active'
    when coalesce(p.approved, false) is true then 'approved_pending_activation'
    else 'available'
  end as status,
  p.id
from public.players p
where coalesce(trim(p.display_name), '') <> ''
on conflict (username) do update
set
  display_name = excluded.display_name,
  player_id = coalesce(public.allowed_usernames.player_id, excluded.player_id),
  status = case
    when public.allowed_usernames.status in ('blocked', 'reserved') then public.allowed_usernames.status
    else excluded.status
  end,
  updated_at = now();

update public.claim_requests cr
set allowed_username_id = au.id,
    request_status = coalesce(cr.request_status, cr.status)
from public.allowed_usernames au
left join public.players p on p.id = cr.player_id
where cr.allowed_username_id is null
  and au.username = public._normalize_allowed_username(coalesce(cr.requester_meta ->> 'display_name', p.display_name));

create or replace function public._claim_request_allowed_username_before_write()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_display_name text;
  v_reserved_email text;
  v_allowed public.allowed_usernames%rowtype;
  v_existing_id bigint;
  v_new_status text;
begin
  v_display_name := nullif(trim(coalesce(NEW.requester_meta ->> 'display_name', '')), '');

  if v_display_name is null and NEW.player_id is not null then
    select display_name into v_display_name
    from public.players
    where id = NEW.player_id
    limit 1;
  end if;

  if v_display_name is null and NEW.allowed_username_id is not null then
    select display_name into v_display_name
    from public.allowed_usernames
    where id = NEW.allowed_username_id
    limit 1;
  end if;

  if v_display_name is null then
    raise exception 'Naam ontbreekt in deze aanvraag';
  end if;

  select *
    into v_allowed
    from public.allowed_usernames
   where username = public._normalize_allowed_username(v_display_name)
      or lower(display_name) = lower(v_display_name)
   order by case when lower(display_name) = lower(v_display_name) then 0 else 1 end
   limit 1;

  if not found then
    raise exception 'Deze naam is niet beschikbaar voor self-claim.';
  end if;

  if lower(coalesce(v_allowed.status, '')) in ('active', 'blocked') then
    raise exception 'Deze naam is niet beschikbaar voor self-claim.';
  end if;

  v_reserved_email := nullif(lower(trim(coalesce(v_allowed.reserved_for_email, ''))), '');
  if v_reserved_email is not null and lower(trim(coalesce(NEW.requester_email, ''))) <> v_reserved_email then
    raise exception 'Deze naam is gereserveerd voor een ander e-mailadres.';
  end if;

  NEW.allowed_username_id := v_allowed.id;
  NEW.request_status := coalesce(nullif(trim(coalesce(NEW.request_status, '')), ''), NEW.status);
  v_new_status := lower(coalesce(NEW.status, NEW.request_status, 'pending'));

  if v_new_status not in ('rejected', 'revoked', 'blocked', 'cancelled', 'expired') then
    select id
      into v_existing_id
      from public.claim_requests
     where allowed_username_id = v_allowed.id
       and id <> coalesce(NEW.id, -1)
       and lower(coalesce(status, request_status, 'pending')) in ('pending', 'approved', 'approved_pending_activation')
     order by id desc
     limit 1;

    if found then
      raise exception 'Er is al een open aanvraag voor deze naam.';
    end if;
  end if;

  return NEW;
end;
$$;

drop trigger if exists trg_claim_request_allowed_username_before_write on public.claim_requests;
create trigger trg_claim_request_allowed_username_before_write
before insert or update on public.claim_requests
for each row
execute function public._claim_request_allowed_username_before_write();

create or replace function public._sync_allowed_username_from_claim_request()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_status text;
  v_display_name text;
  v_has_live_link boolean;
  v_is_active boolean;
begin
  if NEW.allowed_username_id is null then
    return NEW;
  end if;

  v_display_name := nullif(trim(coalesce(NEW.requester_meta ->> 'display_name', '')), '');
  if v_display_name is null and NEW.player_id is not null then
    select display_name into v_display_name from public.players where id = NEW.player_id limit 1;
  end if;

  select exists(
    select 1
    from public.player_activation_links pal
    where pal.claim_request_id = NEW.id
      and pal.used_at is null
      and pal.expires_at >= now()
  ) into v_has_live_link;

  select exists(
    select 1
    from public.players p
    where p.id = NEW.player_id
      and p.pin_hash is not null
      and coalesce(p.active, true) is true
  ) into v_is_active;

  v_status := lower(coalesce(NEW.status, NEW.request_status, 'pending'));
  v_status := case
    when v_is_active then 'active'
    when v_status = 'approved' and v_has_live_link then 'approved_pending_activation'
    when v_status = 'approved' then 'reserved'
    when v_status = 'expired' then 'expired'
    when v_status in ('rejected', 'revoked') then 'rejected'
    when v_status = 'blocked' then 'blocked'
    else 'pending_review'
  end;

  update public.allowed_usernames
     set display_name = coalesce(v_display_name, display_name),
         player_id = coalesce(player_id, NEW.player_id),
         current_claim_request_id = NEW.id,
         status = v_status,
         updated_at = now()
   where id = NEW.allowed_username_id;

  perform public._log_username_event(
    NEW.allowed_username_id,
    case
      when v_status = 'pending_review' then 'claim_pending'
      when v_status = 'approved_pending_activation' then 'claim_approved_waiting_activation'
      when v_status = 'active' then 'claim_active'
      when v_status = 'expired' then 'claim_expired'
      when v_status = 'rejected' then 'claim_rejected'
      when v_status = 'blocked' then 'claim_blocked'
      else 'claim_updated'
    end,
    null,
    NEW.id,
    jsonb_build_object(
      'status', NEW.status,
      'request_status', NEW.request_status,
      'requester_email', NEW.requester_email
    )
  );

  return NEW;
end;
$$;

drop trigger if exists trg_claim_request_allowed_username_after_write on public.claim_requests;
create trigger trg_claim_request_allowed_username_after_write
after insert or update on public.claim_requests
for each row
execute function public._sync_allowed_username_from_claim_request();

create or replace function public._sync_allowed_username_from_player()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.allowed_usernames
     set display_name = NEW.display_name,
         player_id = NEW.id,
         status = case
           when coalesce(NEW.active, false) is true and NEW.pin_hash is not null then 'active'
           else status
         end,
         updated_at = now()
   where player_id = NEW.id
      or lower(display_name) = lower(NEW.display_name);

  return NEW;
end;
$$;

drop trigger if exists trg_sync_allowed_username_from_player on public.players;
create trigger trg_sync_allowed_username_from_player
after insert or update on public.players
for each row
execute function public._sync_allowed_username_from_player();

create or replace function public.process_expired_activation_links()
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_count integer := 0;
  rec record;
begin
  for rec in
    select pal.id,
           pal.claim_request_id,
           pal.player_id,
           pal.expires_at,
           cr.allowed_username_id
      from public.player_activation_links pal
      join public.claim_requests cr on cr.id = pal.claim_request_id
     where pal.used_at is null
       and pal.expires_at < now()
       and pal.expired_processed_at is null
  loop
    update public.player_activation_links
       set expired_processed_at = now()
     where id = rec.id;

    update public.claim_requests
       set status = 'expired',
           request_status = 'expired'
     where id = rec.claim_request_id;

    update public.allowed_usernames
       set status = 'expired',
           activation_link_id = rec.id,
           updated_at = now()
     where id = rec.allowed_username_id;

    perform public._log_username_event(
      rec.allowed_username_id,
      'activation_expired',
      null,
      rec.claim_request_id,
      jsonb_build_object('activation_link_id', rec.id, 'expires_at', rec.expires_at)
    );

    v_count := v_count + 1;
  end loop;

  return jsonb_build_object('processed_count', v_count);
end;
$$;

create or replace function public.get_requestable_names()
returns jsonb
language sql
security definer
set search_path to 'public'
as $$
  select jsonb_build_object(
    'names', coalesce(
      jsonb_agg(display_name order by lower(display_name)) filter (
        where lower(status) in ('available', 'reserved', 'expired', 'pending_review')
      ),
      '[]'::jsonb
    )
  )
  from public.allowed_usernames;
$$;

create or replace function public.admin_get_allowed_usernames(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  sess record;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token);
  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  return jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', au.id,
        'username', au.username,
        'display_name', au.display_name,
        'status', au.status,
        'reserved_for_email', au.reserved_for_email,
        'player_id', au.player_id,
        'current_claim_request_id', au.current_claim_request_id,
        'updated_at', au.updated_at
      ) order by lower(au.display_name))
      from public.allowed_usernames au
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_reserve_allowed_username(
  admin_session_token text,
  display_name_input text,
  reserved_for_email_input text default null,
  reserved_for_person_note_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  sess record;
  v_id bigint;
  v_username text;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token);
  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  if trim(coalesce(display_name_input, '')) = '' then
    raise exception 'Display name ontbreekt';
  end if;

  v_username := public._normalize_allowed_username(display_name_input);
  if v_username = '' then
    raise exception 'Kon geen geldige username-slug maken';
  end if;

  insert into public.allowed_usernames (
    username,
    display_name,
    status,
    reserved_for_email,
    reserved_for_person_note,
    approved_by_admin_id
  )
  values (
    v_username,
    trim(display_name_input),
    case when nullif(trim(coalesce(reserved_for_email_input, '')), '') is null then 'available' else 'reserved' end,
    nullif(lower(trim(coalesce(reserved_for_email_input, ''))), ''),
    nullif(trim(coalesce(reserved_for_person_note_input, '')), ''),
    sess.id
  )
  on conflict (username)
  do update set
    display_name = excluded.display_name,
    reserved_for_email = coalesce(excluded.reserved_for_email, public.allowed_usernames.reserved_for_email),
    reserved_for_person_note = coalesce(excluded.reserved_for_person_note, public.allowed_usernames.reserved_for_person_note),
    status = case
      when public.allowed_usernames.status in ('active', 'blocked') then public.allowed_usernames.status
      else excluded.status
    end,
    approved_by_admin_id = sess.id,
    updated_at = now()
  returning id into v_id;

  perform public._log_username_event(
    v_id,
    'username_reserved',
    sess.id,
    null,
    jsonb_build_object('reserved_for_email', nullif(lower(trim(coalesce(reserved_for_email_input, ''))), ''))
  );

  return jsonb_build_object('ok', true, 'allowed_username_id', v_id);
end;
$$;

create or replace function public.admin_get_expired_activation_queue(admin_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  sess record;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token);
  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  perform public.process_expired_activation_links();

  return jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'request_id', cr.id,
        'display_name', au.display_name,
        'requester_email', cr.requester_email,
        'status', coalesce(cr.request_status, cr.status),
        'expires_at', pal.expires_at,
        'activation_link_id', pal.id
      ) order by pal.expires_at desc)
      from public.claim_requests cr
      join public.allowed_usernames au on au.id = cr.allowed_username_id
      left join public.player_activation_links pal on pal.claim_request_id = cr.id
      where lower(coalesce(cr.request_status, cr.status, '')) = 'expired'
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_requeue_expired_activation(
  admin_session_token text,
  request_id_input bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  sess record;
  v_allowed_username_id bigint;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token);
  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  select allowed_username_id into v_allowed_username_id
  from public.claim_requests
  where id = request_id_input;

  if not found then
    raise exception 'Aanvraag niet gevonden';
  end if;

  update public.claim_requests
     set status = 'pending',
         request_status = 'pending_review'
   where id = request_id_input;

  update public.allowed_usernames
     set status = 'pending_review',
         updated_at = now()
   where id = v_allowed_username_id;

  perform public._log_username_event(
    v_allowed_username_id,
    'expired_requeued_for_review',
    sess.id,
    request_id_input,
    '{}'::jsonb
  );

  return jsonb_build_object('ok', true, 'request_id', request_id_input);
end;
$$;

create or replace function public.admin_resend_expired_activation(
  admin_session_token text,
  request_id_input bigint,
  base_url text default 'https://kalenel.nl/activate.html'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  sess record;
  v_allowed_username_id bigint;
  v_result jsonb;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token);
  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  select allowed_username_id into v_allowed_username_id
  from public.claim_requests
  where id = request_id_input;

  if not found then
    raise exception 'Aanvraag niet gevonden';
  end if;

  update public.claim_requests
     set status = 'approved',
         request_status = 'approved_pending_activation'
   where id = request_id_input;

  update public.allowed_usernames
     set status = 'approved_pending_activation',
         updated_at = now()
   where id = v_allowed_username_id;

  v_result := public.admin_queue_activation_email(
    admin_session_token,
    request_id_input,
    base_url,
    null,
    null,
    null,
    null
  );

  perform public._log_username_event(
    v_allowed_username_id,
    'expired_activation_resent',
    sess.id,
    request_id_input,
    coalesce(v_result, '{}'::jsonb)
  );

  return v_result;
end;
$$;

grant execute on function public.get_requestable_names() to anon, authenticated;
grant execute on function public.process_expired_activation_links() to anon, authenticated;
grant execute on function public.admin_get_allowed_usernames(text) to anon, authenticated;
grant execute on function public.admin_reserve_allowed_username(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_get_expired_activation_queue(text) to anon, authenticated;
grant execute on function public.admin_requeue_expired_activation(text, bigint) to anon, authenticated;
grant execute on function public.admin_resend_expired_activation(text, bigint, text) to anon, authenticated;

commit;
