begin;

create table if not exists public.badge_definitions (
  key text primary key,
  pack text not null,
  title text not null,
  nickname text not null default '',
  rarity_rank integer not null,
  rarity_label text not null,
  requirement_text text not null,
  image_full text not null,
  image_mini_48 text not null,
  image_mini_64 text not null,
  legacy_labels jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint badge_definitions_pack_chk check (pack in ('core', 'expansion', 'prestige')),
  constraint badge_definitions_rank_chk check (rarity_rank > 0)
);

create table if not exists public.badge_speed_thresholds (
  canonical_type_key text primary key,
  threshold_seconds numeric not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.ballroom_safe_king_history (
  id bigint generated by default as identity primary key,
  player_name text not null,
  claimed_at timestamptz not null default now(),
  released_at timestamptz,
  release_reason text,
  source_event text not null default 'state_change'
);

create table if not exists public.ballroom_safe_request_history (
  id bigint generated by default as identity primary key,
  request_id bigint,
  player_name text not null,
  requested_at timestamptz,
  resolved_status text not null,
  resolved_by_name text,
  resolved_at timestamptz not null default now()
);

alter table if exists public.ballroom_safe_requests
  add column if not exists resolved_by_name text;

create index if not exists idx_badge_definitions_rarity_rank on public.badge_definitions(rarity_rank);
create index if not exists idx_ballroom_safe_king_history_player on public.ballroom_safe_king_history(lower(player_name), claimed_at desc);
create index if not exists idx_ballroom_safe_request_history_player on public.ballroom_safe_request_history(lower(player_name), resolved_at desc);

insert into public.badge_speed_thresholds(canonical_type_key, threshold_seconds)
values
  ('bier', 20),
  ('2bakken', 75),
  ('liter_bier', 90),
  ('ice', 25),
  ('wijnfles', 240)
on conflict (canonical_type_key) do update
set threshold_seconds = excluded.threshold_seconds,
    updated_at = now();

insert into public.badge_definitions(key, pack, title, nickname, rarity_rank, rarity_label, requirement_text, image_full, image_mini_48, image_mini_64, legacy_labels)
values
  ('starter','core','Starter','',1,'Common','1 geverifieerde site-actie: een potje, drankje of speedpoging.','./assets/badges/core/badge-starter.png','./assets/badges/mini-48/badge-starter.png','./assets/badges/mini-64/badge-starter.png','["Starter"]'::jsonb),
  ('groeier','core','Groeier','',2,'Common','5 geverifieerde potjes of 10 geverifieerde drankacties.','./assets/badges/core/badge-groeier.png','./assets/badges/mini-48/badge-groeier.png','./assets/badges/mini-64/badge-groeier.png','["Groeier"]'::jsonb),
  ('actief','core','Actief','De Huisvriend',3,'Uncommon','15 potjes totaal of 25 geverifieerde drankacties.','./assets/badges/core/badge-actief.png','./assets/badges/mini-48/badge-actief.png','./assets/badges/mini-64/badge-actief.png','["Actief"]'::jsonb),
  ('gold','core','Gouden Hand','De Gouden',4,'Rare','Minstens 30 potjes totaal en minstens 55% winrate over je beste spel.','./assets/badges/core/badge-gold.png','./assets/badges/mini-48/badge-gold.png','./assets/badges/mini-64/badge-gold.png','["Gold","Gouden Hand"]'::jsonb),
  ('legend','core','Legende','De Legende',5,'Epic','Minstens 60 potjes totaal en minstens 60% winrate over je beste spel.','./assets/badges/core/badge-legend.png','./assets/badges/mini-48/badge-legend.png','./assets/badges/mini-64/badge-legend.png','["Legend","Legende"]'::jsonb),
  ('klaverkoning','core','Klaverkoning','De Kaartvorst',6,'Rare','20 klaverjaszeges.','./assets/badges/core/badge-klaverkoning.png','./assets/badges/mini-48/badge-klaverkoning.png','./assets/badges/mini-64/badge-klaverkoning.png','[]'::jsonb),
  ('bruggenbouwer','core','Bruggenbouwer','De Brugwachter',7,'Rare','20 boerenbridge-potjes of 10 boerenbridgezeges.','./assets/badges/core/badge-bruggenbouwer.png','./assets/badges/mini-48/badge-bruggenbouwer.png','./assets/badges/mini-64/badge-bruggenbouwer.png','[]'::jsonb),
  ('snelheidsduivel','core','Snelheidsduivel','De Bliksem',8,'Rare','3 geverifieerde snelheidsrecords onder de drempel van hun drankje.','./assets/badges/core/badge-snelheidsduivel.png','./assets/badges/mini-48/badge-snelheidsduivel.png','./assets/badges/mini-64/badge-snelheidsduivel.png','[]'::jsonb),
  ('ijskoud','core','IJskoud','De Vriezer',9,'Rare','Een geverifieerde Ice-tijd onder 25 seconden.','./assets/badges/core/badge-ijskoud.png','./assets/badges/mini-48/badge-ijskoud.png','./assets/badges/mini-64/badge-ijskoud.png','[]'::jsonb),
  ('kurkentrekker','core','Kurkentrekker','De Flessentrekker',10,'Rare','5 geverifieerde fles-wijn of wijnfles-events.','./assets/badges/core/badge-kurkentrekker.png','./assets/badges/mini-48/badge-kurkentrekker.png','./assets/badges/mini-64/badge-kurkentrekker.png','[]'::jsonb),
  ('verifieermeester','core','Verifieermeester','De Getuige',11,'Epic','50 geaccepteerde verificatiestemmen op andermans requests.','./assets/badges/core/badge-verifieermeester.png','./assets/badges/mini-48/badge-verifieermeester.png','./assets/badges/mini-64/badge-verifieermeester.png','[]'::jsonb),
  ('pussycup_prins','core','Pussycup-prins','Fluwelen Pols',12,'Epic','Minstens 12 beerpongpotjes en pussycup-percentage van minstens 75%.','./assets/badges/core/badge-pussycup_prins.png','./assets/badges/mini-48/badge-pussycup_prins.png','./assets/badges/mini-64/badge-pussycup_prins.png','[]'::jsonb),
  ('onbreekbaar','core','Onbreekbaar','De Onbreekbare',13,'Epic','10 geverifieerde overwinningen op rij over alle spellen samen.','./assets/badges/core/badge-onbreekbaar.png','./assets/badges/mini-48/badge-onbreekbaar.png','./assets/badges/mini-64/badge-onbreekbaar.png','[]'::jsonb),
  ('spinozageest','core','Spinoza-geest','De Spinozist',14,'Legendary','Breed actief: 25 potjes, 20 geverifieerde drankacties, 10 geaccepteerde verificaties en activiteit in minstens 2 spelcategorieen.','./assets/badges/core/badge-spinozageest.png','./assets/badges/mini-48/badge-spinozageest.png','./assets/badges/mini-64/badge-spinozageest.png','[]'::jsonb),
  ('alleskunner','expansion','Alleskunner','De Veelvraat',15,'Epic','Minstens 10 geregistreerde potjes in klaverjas, boerenbridge en beerpong.','./assets/badges/expansion/badge-alleskunner.png','./assets/badges/mini-48/badge-alleskunner.png','./assets/badges/mini-64/badge-alleskunner.png','[]'::jsonb),
  ('nachtburgemeester','expansion','Nachtburgemeester','De Nachtwacht',16,'Epic','12 geverifieerde drank- of snelheidsacties tussen 01:00 en 05:00.','./assets/badges/expansion/badge-nachtburgemeester.png','./assets/badges/mini-48/badge-nachtburgemeester.png','./assets/badges/mini-64/badge-nachtburgemeester.png','[]'::jsonb),
  ('dorstmachine','expansion','Dorstmachine','De Dorstmotor',17,'Rare','40 geverifieerde drinkunits totaal.','./assets/badges/expansion/badge-dorstmachine.png','./assets/badges/mini-48/badge-dorstmachine.png','./assets/badges/mini-64/badge-dorstmachine.png','[]'::jsonb),
  ('literlegende','expansion','Literlegende','De Tapkraan',18,'Legendary','3 geverifieerde liter bier-pogingen onder 90 seconden.','./assets/badges/expansion/badge-literlegende.png','./assets/badges/mini-48/badge-literlegende.png','./assets/badges/mini-64/badge-literlegende.png','[]'::jsonb),
  ('bekerbeul','expansion','Bekerbeul','De Pingbeul',19,'Rare','20 beerpongzeges.','./assets/badges/expansion/badge-bekerbeul.png','./assets/badges/mini-48/badge-bekerbeul.png','./assets/badges/mini-64/badge-bekerbeul.png','[]'::jsonb),
  ('trouwewachter','expansion','Trouwe Wachter','De Portier',20,'Rare','20 geaccepteerde verificatiestemmen op requests van anderen.','./assets/badges/expansion/badge-trouwewachter.png','./assets/badges/mini-48/badge-trouwewachter.png','./assets/badges/mini-64/badge-trouwewachter.png','[]'::jsonb),
  ('salonleeuw','expansion','Salonleeuw','De Fluwelen Gast',21,'Rare','10 goedgekeurde ballroom-entrees of 5 keer als koning in de ballroom.','./assets/badges/expansion/badge-salonleeuw.png','./assets/badges/mini-48/badge-salonleeuw.png','./assets/badges/mini-64/badge-salonleeuw.png','[]'::jsonb),
  ('ijzerenmaag','expansion','IJzeren Maag','De Betonmaag',22,'Epic','5 geverifieerde avonden met minstens 10 drinkunits.','./assets/badges/expansion/badge-ijzerenmaag.png','./assets/badges/mini-48/badge-ijzerenmaag.png','./assets/badges/mini-64/badge-ijzerenmaag.png','[]'::jsonb),
  ('laatsteronde','expansion','Laatste Ronde','De Nachtdienst',23,'Legendary','5 geverifieerde acties na 04:00 in de nacht.','./assets/badges/expansion/badge-laatsteronde.png','./assets/badges/mini-48/badge-laatsteronde.png','./assets/badges/mini-64/badge-laatsteronde.png','[]'::jsonb),
  ('fluwelenvorst','prestige','Fluwelen Vorst','De Rode Baron',24,'Legendary','10 keer ballroom-koning of 25 goedgekeurde ballroom-entrees.','./assets/badges/prestige/badge-fluwelenvorst.png','./assets/badges/mini-48/badge-fluwelenvorst.png','./assets/badges/mini-64/badge-fluwelenvorst.png','[]'::jsonb),
  ('rozenkoning','prestige','Rozenkoning','De Charmeur',25,'Legendary','15 verschillende avond- of weekendzeges in matches met minstens 3 deelnemers.','./assets/badges/prestige/badge-rozenkoning.png','./assets/badges/mini-48/badge-rozenkoning.png','./assets/badges/mini-64/badge-rozenkoning.png','[]'::jsonb),
  ('vuurproef','prestige','Vuurproef','De Vlam',26,'Epic','7 geverifieerde drank- of snelheidsdagen op rij.','./assets/badges/prestige/badge-vuurproef.png','./assets/badges/mini-48/badge-vuurproef.png','./assets/badges/mini-64/badge-vuurproef.png','[]'::jsonb),
  ('sleuteldrager','prestige','Sleuteldrager','De Binnenste Kring',27,'Epic','Minstens 100 potjes totaal en activiteit in minstens 4 grote siteonderdelen.','./assets/badges/prestige/badge-sleuteldrager.png','./assets/badges/mini-48/badge-sleuteldrager.png','./assets/badges/mini-64/badge-sleuteldrager.png','[]'::jsonb),
  ('dobbelofniets','prestige','Dobbel of Niets','De Waaghals',28,'Rare','12 backend-geverifieerde comebackzeges na echte achterstand.','./assets/badges/prestige/badge-dobbelofniets.png','./assets/badges/mini-48/badge-dobbelofniets.png','./assets/badges/mini-64/badge-dobbelofniets.png','[]'::jsonb),
  ('kaartopera','prestige','Kaartopera','De Dirigent',29,'Epic','20 klaverjaszeges, 20 boerenbridgezeges en 5 echte live spectator-deelnames.','./assets/badges/prestige/badge-kaartopera.png','./assets/badges/mini-48/badge-kaartopera.png','./assets/badges/mini-64/badge-kaartopera.png','[]'::jsonb),
  ('avondster','prestige','Avondster','De Laatste Gloed',30,'Mythic','50 potjes, 50 geverifieerde drankacties, 25 geaccepteerde verificaties, minstens 2 speed-threshold hits en activiteit in ballroom en live spectator-games.','./assets/badges/prestige/badge-avondster.png','./assets/badges/mini-48/badge-avondster.png','./assets/badges/mini-64/badge-avondster.png','[]'::jsonb)
on conflict (key) do update
set pack = excluded.pack,
    title = excluded.title,
    nickname = excluded.nickname,
    rarity_rank = excluded.rarity_rank,
    rarity_label = excluded.rarity_label,
    requirement_text = excluded.requirement_text,
    image_full = excluded.image_full,
    image_mini_48 = excluded.image_mini_48,
    image_mini_64 = excluded.image_mini_64,
    legacy_labels = excluded.legacy_labels,
    updated_at = now();

create or replace function public._badge_norm_name(v text)
returns text
language sql
immutable
as $$
  select lower(trim(coalesce(v, '')))
$$;

create or replace function public._badge_normalize_drink_type(v text)
returns text
language sql
immutable
as $$
  select case
    when lower(regexp_replace(coalesce(v, ''), '[^a-z0-9]+', '', 'g')) in ('2bakken','tweebakken') then '2bakken'
    when lower(regexp_replace(coalesce(v, ''), '[^a-z0-9]+', '', 'g')) in ('literbier','liter_bier') then 'liter_bier'
    when lower(regexp_replace(coalesce(v, ''), '[^a-z0-9]+', '', 'g')) in ('wijnfles','fleswijn','wijn') then 'wijnfles'
    when lower(regexp_replace(coalesce(v, ''), '[^a-z0-9]+', '', 'g')) in ('ice','smirnoffice') then 'ice'
    when lower(regexp_replace(coalesce(v, ''), '[^a-z0-9]+', '', 'g')) in ('shot','shots') then 'shot'
    else 'bier'
  end
$$;

create or replace function public._badge_public_player_row_scoped(
  player_name_input text,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $$
declare
  v_scope text := case when lower(trim(coalesce(site_scope_input, ''))) = 'family' then 'family' else 'friends' end;
  v_raw jsonb;
  v_players jsonb := '[]'::jsonb;
  v_row jsonb := null;
begin
  begin
    v_raw := public.get_all_site_players_public_scoped(site_scope_input => v_scope);
    if jsonb_typeof(v_raw) = 'object' and v_raw ? 'players' then
      v_players := coalesce(v_raw->'players', '[]'::jsonb);
    elsif jsonb_typeof(v_raw) = 'array' then
      v_players := v_raw;
    end if;
  exception when others then
    v_players := '[]'::jsonb;
  end;

  select value
    into v_row
    from jsonb_array_elements(v_players)
   where public._badge_norm_name(coalesce(
           value->>'player_name',
           value->>'display_name',
           value->>'chosen_username',
           value->>'public_display_name',
           value->>'nickname'
         )) = public._badge_norm_name(player_name_input)
      or public._badge_norm_name(coalesce(value->>'display_name', '')) = public._badge_norm_name(player_name_input)
      or public._badge_norm_name(coalesce(value->>'chosen_username', '')) = public._badge_norm_name(player_name_input)
      or public._badge_norm_name(coalesce(value->>'public_display_name', '')) = public._badge_norm_name(player_name_input)
      or public._badge_norm_name(coalesce(value->>'nickname', '')) = public._badge_norm_name(player_name_input)
   limit 1;

  return v_row;
end;
$$;

create or replace function public._badge_verified_drink_rows(player_name_input text)
returns table(
  canonical_type_key text,
  occurred_at timestamptz,
  total_units numeric,
  local_day date,
  local_hour integer
)
language sql
stable
as $$
  select
    public._badge_normalize_drink_type(coalesce(to_jsonb(de)->>'event_type_key', to_jsonb(de)->>'event_type_label', 'bier')) as canonical_type_key,
    coalesce(nullif(to_jsonb(de)->>'verified_at', '')::timestamptz, de.created_at) as occurred_at,
    coalesce(nullif(to_jsonb(de)->>'total_units', '')::numeric, coalesce(nullif(to_jsonb(de)->>'quantity', '')::numeric, 1)) as total_units,
    (coalesce(nullif(to_jsonb(de)->>'verified_at', '')::timestamptz, de.created_at) at time zone 'Europe/Amsterdam')::date as local_day,
    extract(hour from coalesce(nullif(to_jsonb(de)->>'verified_at', '')::timestamptz, de.created_at) at time zone 'Europe/Amsterdam')::int as local_hour
  from public.drink_events de
  left join public.players p on p.id = de.player_id
  where lower(coalesce(to_jsonb(de)->>'status', 'pending')) = 'verified'
    and public._badge_norm_name(coalesce(
      nullif(trim(coalesce(to_jsonb(de)->>'player_name', '')), ''),
      nullif(trim(coalesce(p.display_name, '')), ''),
      nullif(trim(coalesce(p.username, '')), '')
    )) = public._badge_norm_name(player_name_input)
$$;

create or replace function public._badge_verified_speed_rows(player_name_input text)
returns table(
  canonical_type_key text,
  occurred_at timestamptz,
  duration_seconds numeric,
  local_day date,
  local_hour integer
)
language sql
stable
as $$
  select
    public._badge_normalize_drink_type(coalesce(to_jsonb(dsa)->>'speed_type_key', to_jsonb(dsa)->>'event_type_key', 'bier')) as canonical_type_key,
    coalesce(nullif(to_jsonb(dsa)->>'verified_at', '')::timestamptz, dsa.created_at) as occurred_at,
    coalesce(nullif(to_jsonb(dsa)->>'duration_seconds', '')::numeric, 0) as duration_seconds,
    (coalesce(nullif(to_jsonb(dsa)->>'verified_at', '')::timestamptz, dsa.created_at) at time zone 'Europe/Amsterdam')::date as local_day,
    extract(hour from coalesce(nullif(to_jsonb(dsa)->>'verified_at', '')::timestamptz, dsa.created_at) at time zone 'Europe/Amsterdam')::int as local_hour
  from public.drink_speed_attempts dsa
  left join public.players p on p.id = dsa.player_id
  where lower(coalesce(to_jsonb(dsa)->>'status', 'pending')) = 'verified'
    and public._badge_norm_name(coalesce(
      nullif(trim(coalesce(to_jsonb(dsa)->>'player_name', '')), ''),
      nullif(trim(coalesce(p.display_name, '')), ''),
      nullif(trim(coalesce(p.username, '')), '')
    )) = public._badge_norm_name(player_name_input)
$$;

create or replace function public._badge_all_match_rows_scoped(
  player_name_input text,
  site_scope_input text default 'friends'
)
returns table(
  game_key text,
  match_ref text,
  finished_at timestamptz,
  is_win boolean,
  participants_count integer
)
language sql
stable
as $$
  with summary_rows as (
    select
      r.game_key,
      r.match_ref,
      r.finished_at,
      exists(select 1 from unnest(coalesce(r.winner_names, '{}'::text[])) w where public._badge_norm_name(w) = public._badge_norm_name(player_name_input)) as is_win,
      coalesce(array_length(r.participants, 1), 0) as participants_count,
      r.participants
    from public._gejast_summary_rows_scoped(false, site_scope_input) r
  ),
  summary_player as (
    select s.game_key, s.match_ref, s.finished_at, s.is_win, s.participants_count
    from summary_rows s
    where exists (select 1 from unnest(coalesce(s.participants, '{}'::text[])) p where public._badge_norm_name(p) = public._badge_norm_name(player_name_input))
  ),
  beerpong_player as (
    select
      'beerpong'::text as game_key,
      coalesce(nullif(trim(coalesce(m.client_match_id, '')), ''), m.id::text) as match_ref,
      coalesce(m.finished_at, m.created_at) as finished_at,
      case
        when lower(coalesce(m.winner_team, '')) = 'a' and exists (select 1 from public.players p where p.id = any(coalesce(m.team_a_player_ids, '{}'::bigint[])) and public._badge_norm_name(p.display_name) = public._badge_norm_name(player_name_input)) then true
        when lower(coalesce(m.winner_team, '')) = 'b' and exists (select 1 from public.players p where p.id = any(coalesce(m.team_b_player_ids, '{}'::bigint[])) and public._badge_norm_name(p.display_name) = public._badge_norm_name(player_name_input)) then true
        else false
      end as is_win,
      coalesce(array_length(coalesce(m.team_a_player_ids, '{}'::bigint[]), 1), 0) + coalesce(array_length(coalesce(m.team_b_player_ids, '{}'::bigint[]), 1), 0) as participants_count
    from public.beerpong_matches m
    where coalesce(m.deleted_at is null, true)
      and coalesce(lower(m.match_status), 'finished') = 'finished'
      and site_scope_input <> 'family'
      and (
        exists (select 1 from public.players p where p.id = any(coalesce(m.team_a_player_ids, '{}'::bigint[])) and public._badge_norm_name(p.display_name) = public._badge_norm_name(player_name_input))
        or
        exists (select 1 from public.players p where p.id = any(coalesce(m.team_b_player_ids, '{}'::bigint[])) and public._badge_norm_name(p.display_name) = public._badge_norm_name(player_name_input))
      )
  )
  select * from summary_player
  union all
  select * from beerpong_player
$$;

create or replace function public._ballroom_track_king_history_v352()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if nullif(trim(coalesce(new.king_name, '')), '') is not null then
      if not exists (
        select 1 from public.ballroom_safe_king_history h
        where public._badge_norm_name(h.player_name) = public._badge_norm_name(new.king_name)
          and h.released_at is null
      ) then
        insert into public.ballroom_safe_king_history(player_name, claimed_at, source_event)
        values (new.king_name, coalesce(new.claimed_at, new.updated_at, now()), 'state_insert');
      end if;
    end if;
    return new;
  end if;

  if public._badge_norm_name(old.king_name) is distinct from public._badge_norm_name(new.king_name) then
    if nullif(trim(coalesce(old.king_name, '')), '') is not null then
      update public.ballroom_safe_king_history
         set released_at = coalesce(new.updated_at, now()),
             release_reason = case when nullif(trim(coalesce(new.king_name, '')), '') is null then 'abdicated' else 'replaced' end
       where public._badge_norm_name(player_name) = public._badge_norm_name(old.king_name)
         and released_at is null;
    end if;
    if nullif(trim(coalesce(new.king_name, '')), '') is not null then
      insert into public.ballroom_safe_king_history(player_name, claimed_at, source_event)
      values (new.king_name, coalesce(new.claimed_at, new.updated_at, now()), 'state_update');
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_ballroom_track_king_history_v352 on public.ballroom_safe_state;
create trigger trg_ballroom_track_king_history_v352
after insert or update on public.ballroom_safe_state
for each row execute function public._ballroom_track_king_history_v352();

create or replace function public._ballroom_track_request_history_v352()
returns trigger
language plpgsql
as $$
begin
  if coalesce(old.status, 'pending') = 'pending'
     and coalesce(new.status, 'pending') in ('approved', 'rejected') then
    insert into public.ballroom_safe_request_history(
      request_id,
      player_name,
      requested_at,
      resolved_status,
      resolved_by_name,
      resolved_at
    )
    values (
      new.id,
      new.player_name,
      new.requested_at,
      new.status,
      new.resolved_by_name,
      coalesce(new.resolved_at, now())
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_ballroom_track_request_history_v352 on public.ballroom_safe_requests;
create trigger trg_ballroom_track_request_history_v352
after update on public.ballroom_safe_requests
for each row execute function public._ballroom_track_request_history_v352();

create or replace function public.ballroom_resolve_request_safe(
  session_token text default null,
  session_token_input text default null,
  request_id_input bigint default null,
  approve_input boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  viewer_name text := public._ballroom_safe_require_name(session_token, session_token_input);
  king_name text;
  req_name text;
begin
  select s.king_name into king_name from public.ballroom_safe_state s where s.id = 1;
  if lower(coalesce(king_name, '')) <> lower(coalesce(viewer_name, '')) then
    raise exception 'Alleen de koning mag verzoeken beoordelen.';
  end if;
  if request_id_input is null then
    raise exception 'Er ontbreekt een verzoek-id.';
  end if;
  select r.player_name into req_name
  from public.ballroom_safe_requests r
  where r.id = request_id_input
    and r.status = 'pending';
  if req_name is null then
    raise exception 'Dit entreeverzoek is niet meer actief.';
  end if;

  update public.ballroom_safe_requests
     set status = case when approve_input then 'approved' else 'rejected' end,
         resolved_at = now(),
         resolved_by_name = viewer_name
   where id = request_id_input
     and status = 'pending';

  if approve_input then
    insert into public.ballroom_safe_members(player_name, approved_at, updated_at)
    values (req_name, now(), now())
    on conflict (player_name) do update set updated_at = now();
  end if;

  return public.get_ballroom_public_state_safe(session_token, session_token_input);
end;
$$;

insert into public.ballroom_safe_king_history(player_name, claimed_at, source_event)
select s.king_name, coalesce(s.claimed_at, s.updated_at, now()), 'backfill'
from public.ballroom_safe_state s
where s.id = 1
  and nullif(trim(coalesce(s.king_name, '')), '') is not null
  and not exists (
    select 1
    from public.ballroom_safe_king_history h
    where public._badge_norm_name(h.player_name) = public._badge_norm_name(s.king_name)
      and h.released_at is null
  );

insert into public.ballroom_safe_request_history(request_id, player_name, requested_at, resolved_status, resolved_by_name, resolved_at)
select r.id, r.player_name, r.requested_at, r.status, r.resolved_by_name, coalesce(r.resolved_at, now())
from public.ballroom_safe_requests r
where r.status in ('approved', 'rejected')
  and not exists (
    select 1 from public.ballroom_safe_request_history h where h.request_id = r.id
  );

create or replace function public.get_player_badge_bundle_scoped(
  player_name text,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_scope text := case when lower(trim(coalesce(site_scope_input, ''))) = 'family' then 'family' else 'friends' end;
  v_public_row jsonb := public._badge_public_player_row_scoped(player_name, v_scope);
  v_display_name text := coalesce(
    nullif(trim(coalesce(v_public_row->>'chosen_username', '')), ''),
    nullif(trim(coalesce(v_public_row->>'public_display_name', '')), ''),
    nullif(trim(coalesce(v_public_row->>'nickname', '')), ''),
    nullif(trim(coalesce(v_public_row->>'display_name', '')), ''),
    nullif(trim(coalesce(v_public_row->>'player_name', '')), ''),
    trim(coalesce(player_name, ''))
  );
  v_original_name text := coalesce(nullif(trim(coalesce(v_public_row->>'player_name', '')), ''), v_display_name);
  v_total_matches integer := 0;
  v_total_wins integer := 0;
  v_total_site_actions integer := 0;
  v_klaverjas_matches integer := 0;
  v_boerenbridge_matches integer := 0;
  v_beerpong_matches integer := 0;
  v_klaverjas_wins integer := 0;
  v_boerenbridge_wins integer := 0;
  v_beerpong_wins integer := 0;
  v_best_game_win_pct numeric := 0;
  v_verified_drink_actions integer := 0;
  v_total_drink_units numeric := 0;
  v_verified_speed_attempts integer := 0;
  v_speed_threshold_hits integer := 0;
  v_ice_under_25 integer := 0;
  v_liter_under_90 integer := 0;
  v_wine_events integer := 0;
  v_accepted_verifications integer := 0;
  v_pussycup_pct numeric := 0;
  v_max_win_streak integer := 0;
  v_match_game_activity_count integer := 0;
  v_site_areas_active_count integer := 0;
  v_live_participations integer := 0;
  v_total_comeback_wins integer := 0;
  v_ballroom_approved_entries integer := 0;
  v_ballroom_king_claims integer := 0;
  v_night_actions integer := 0;
  v_after_four_actions integer := 0;
  v_heavy_nights integer := 0;
  v_evening_weekend_win_dates integer := 0;
  v_max_consecutive_active_days integer := 0;
  v_attained text[] := '{}'::text[];
  v_attained_badges jsonb := '[]'::jsonb;
  v_all_badges jsonb := '[]'::jsonb;
  v_primary_badge jsonb := null;
  v_primary_nickname text := '';
begin
  with match_rows as (
    select * from public._badge_all_match_rows_scoped(v_original_name, v_scope)
  ),
  by_game as (
    select game_key, count(*)::int as matches, count(*) filter (where is_win)::int as wins
    from match_rows
    group by game_key
  )
  select
    coalesce((select sum(matches) from by_game), 0),
    coalesce((select sum(wins) from by_game), 0),
    coalesce((select matches from by_game where game_key = 'klaverjas'), 0),
    coalesce((select matches from by_game where game_key = 'boerenbridge'), 0),
    coalesce((select matches from by_game where game_key = 'beerpong'), 0),
    coalesce((select wins from by_game where game_key = 'klaverjas'), 0),
    coalesce((select wins from by_game where game_key = 'boerenbridge'), 0),
    coalesce((select wins from by_game where game_key = 'beerpong'), 0),
    coalesce((select max(case when matches > 0 then round((100.0 * wins::numeric) / matches::numeric, 1) else 0 end) from by_game), 0),
    coalesce((select count(*) from by_game), 0),
    coalesce((
      with ordered as (
        select finished_at, match_ref, is_win,
               sum(case when not is_win then 1 else 0 end) over(order by finished_at, match_ref) as grp
        from match_rows
      )
      select max(streak)::int
      from (
        select grp, count(*) filter (where is_win) as streak
        from ordered
        group by grp
      ) s
    ), 0),
    coalesce((
      select count(distinct (finished_at at time zone 'Europe/Amsterdam')::date)
      from match_rows
      where is_win
        and participants_count >= 3
        and (
          extract(hour from finished_at at time zone 'Europe/Amsterdam') >= 18
          or extract(dow from finished_at at time zone 'Europe/Amsterdam') in (0, 5, 6)
        )
    ), 0)
  into
    v_total_matches,
    v_total_wins,
    v_klaverjas_matches,
    v_boerenbridge_matches,
    v_beerpong_matches,
    v_klaverjas_wins,
    v_boerenbridge_wins,
    v_beerpong_wins,
    v_best_game_win_pct,
    v_match_game_activity_count,
    v_max_win_streak,
    v_evening_weekend_win_dates;

  with drinks as (
    select * from public._badge_verified_drink_rows(v_original_name)
  )
  select
    count(*)::int,
    coalesce(sum(total_units), 0),
    count(*) filter (where canonical_type_key = 'wijnfles')::int,
    count(*) filter (where local_hour >= 1 and local_hour < 5)::int,
    count(*) filter (where local_hour >= 4)::int,
    coalesce((
      select count(*)
      from (
        select local_day
        from drinks
        group by local_day
        having sum(total_units) >= 10
      ) nights
    ), 0)
  into
    v_verified_drink_actions,
    v_total_drink_units,
    v_wine_events,
    v_night_actions,
    v_after_four_actions,
    v_heavy_nights;

  with speed as (
    select * from public._badge_verified_speed_rows(v_original_name)
  )
  select
    count(*)::int,
    count(*) filter (where canonical_type_key = 'ice' and duration_seconds > 0 and duration_seconds < 25)::int,
    count(*) filter (where canonical_type_key = 'liter_bier' and duration_seconds > 0 and duration_seconds < 90)::int,
    coalesce((
      select count(*)
      from speed s
      join public.badge_speed_thresholds t on t.canonical_type_key = s.canonical_type_key
      where s.duration_seconds > 0
        and s.duration_seconds <= t.threshold_seconds
    ), 0)
  into
    v_verified_speed_attempts,
    v_ice_under_25,
    v_liter_under_90,
    v_speed_threshold_hits;

  v_night_actions := coalesce(v_night_actions, 0) + coalesce((select count(*) from public._badge_verified_speed_rows(v_original_name) s where s.local_hour >= 1 and s.local_hour < 5), 0);
  v_after_four_actions := coalesce(v_after_four_actions, 0) + coalesce((select count(*) from public._badge_verified_speed_rows(v_original_name) s where s.local_hour >= 4), 0);

  with active_days as (
    select distinct local_day
    from (
      select local_day from public._badge_verified_drink_rows(v_original_name)
      union
      select local_day from public._badge_verified_speed_rows(v_original_name)
    ) x
  ),
  grouped as (
    select local_day, local_day - (row_number() over(order by local_day))::int as grp
    from active_days
  )
  select coalesce(max(streak), 0)
    into v_max_consecutive_active_days
    from (
      select grp, count(*)::int as streak
      from grouped
      group by grp
    ) s;

  select
    coalesce((select count(*)::int from public._gejast_live_participation_rows_scoped(v_scope) l where public._badge_norm_name(l.player_name) = public._badge_norm_name(v_original_name)), 0),
    coalesce((select count(*)::int from public._gejast_klaverjas_comeback_rows_scoped(v_scope) k where public._badge_norm_name(k.player_name) = public._badge_norm_name(v_original_name)), 0)
    +
    coalesce((select count(*)::int from public._gejast_boerenbridge_comeback_rows_scoped(v_scope) b where public._badge_norm_name(b.player_name) = public._badge_norm_name(v_original_name)), 0)
  into
    v_live_participations,
    v_total_comeback_wins;

  select
    coalesce((select count(*)::int from public.ballroom_safe_request_history h where public._badge_norm_name(h.player_name) = public._badge_norm_name(v_original_name) and lower(coalesce(h.resolved_status, '')) = 'approved'), 0),
    coalesce((select count(*)::int from public.ballroom_safe_king_history h where public._badge_norm_name(h.player_name) = public._badge_norm_name(v_original_name)), 0)
  into
    v_ballroom_approved_entries,
    v_ballroom_king_claims;

  select coalesce(((public.get_beerpong_player_pussycup_public(v_original_name)->'summary'->>'pussycup_pct')::numeric), 0)
    into v_pussycup_pct;

  select
    coalesce((
      select count(*)::int
      from public.drink_event_verifications dev
      join public.drink_events de on de.id = dev.drink_event_id
      left join public.players vp on vp.id = dev.verifier_player_id
      where coalesce((to_jsonb(dev)->>'approved')::boolean, false) is true
        and public._badge_norm_name(coalesce(nullif(trim(coalesce(to_jsonb(dev)->>'verifier_player_name', '')), ''), nullif(trim(coalesce(vp.display_name, '')), ''))) = public._badge_norm_name(v_original_name)
        and public._badge_norm_name(coalesce(nullif(trim(coalesce(to_jsonb(de)->>'player_name', '')), ''), nullif(trim(coalesce((select p.display_name from public.players p where p.id = de.player_id limit 1), '')), ''))) <> public._badge_norm_name(v_original_name)
    ), 0)
    +
    coalesce((
      select count(*)::int
      from public.drink_speed_verifications dsv
      join public.drink_speed_attempts dsa on dsa.id = dsv.attempt_id
      left join public.players vp on vp.id = dsv.verifier_player_id
      where coalesce((to_jsonb(dsv)->>'approved')::boolean, false) is true
        and public._badge_norm_name(coalesce(nullif(trim(coalesce(to_jsonb(dsv)->>'verifier_player_name', '')), ''), nullif(trim(coalesce(vp.display_name, '')), ''))) = public._badge_norm_name(v_original_name)
        and public._badge_norm_name(coalesce(nullif(trim(coalesce(to_jsonb(dsa)->>'player_name', '')), ''), nullif(trim(coalesce((select p.display_name from public.players p where p.id = dsa.player_id limit 1), '')), ''))) <> public._badge_norm_name(v_original_name)
    ), 0)
  into v_accepted_verifications;

  v_total_site_actions := coalesce(v_total_matches, 0) + coalesce(v_verified_drink_actions, 0) + coalesce(v_verified_speed_attempts, 0);
  v_site_areas_active_count :=
    (case when v_total_matches > 0 then 1 else 0 end) +
    (case when v_verified_drink_actions > 0 then 1 else 0 end) +
    (case when v_verified_speed_attempts > 0 then 1 else 0 end) +
    (case when v_accepted_verifications > 0 then 1 else 0 end) +
    (case when v_live_participations > 0 then 1 else 0 end) +
    (case when (v_ballroom_approved_entries > 0 or v_ballroom_king_claims > 0) then 1 else 0 end);

  if v_total_site_actions >= 1 then v_attained := array_append(v_attained, 'starter'); end if;
  if v_total_matches >= 5 or v_verified_drink_actions >= 10 then v_attained := array_append(v_attained, 'groeier'); end if;
  if v_total_matches >= 15 or v_verified_drink_actions >= 25 then v_attained := array_append(v_attained, 'actief'); end if;
  if v_total_matches >= 30 and v_best_game_win_pct >= 55 then v_attained := array_append(v_attained, 'gold'); end if;
  if v_total_matches >= 60 and v_best_game_win_pct >= 60 then v_attained := array_append(v_attained, 'legend'); end if;
  if v_klaverjas_wins >= 20 then v_attained := array_append(v_attained, 'klaverkoning'); end if;
  if v_boerenbridge_matches >= 20 or v_boerenbridge_wins >= 10 then v_attained := array_append(v_attained, 'bruggenbouwer'); end if;
  if v_speed_threshold_hits >= 3 then v_attained := array_append(v_attained, 'snelheidsduivel'); end if;
  if v_ice_under_25 >= 1 then v_attained := array_append(v_attained, 'ijskoud'); end if;
  if v_wine_events >= 5 then v_attained := array_append(v_attained, 'kurkentrekker'); end if;
  if v_accepted_verifications >= 50 then v_attained := array_append(v_attained, 'verifieermeester'); end if;
  if v_beerpong_matches >= 12 and v_pussycup_pct >= 75 then v_attained := array_append(v_attained, 'pussycup_prins'); end if;
  if v_max_win_streak >= 10 then v_attained := array_append(v_attained, 'onbreekbaar'); end if;
  if v_total_matches >= 25 and v_verified_drink_actions >= 20 and v_accepted_verifications >= 10 and v_match_game_activity_count >= 2 then v_attained := array_append(v_attained, 'spinozageest'); end if;
  if v_klaverjas_matches >= 10 and v_boerenbridge_matches >= 10 and v_beerpong_matches >= 10 then v_attained := array_append(v_attained, 'alleskunner'); end if;
  if v_night_actions >= 12 then v_attained := array_append(v_attained, 'nachtburgemeester'); end if;
  if v_total_drink_units >= 40 then v_attained := array_append(v_attained, 'dorstmachine'); end if;
  if v_liter_under_90 >= 3 then v_attained := array_append(v_attained, 'literlegende'); end if;
  if v_beerpong_wins >= 20 then v_attained := array_append(v_attained, 'bekerbeul'); end if;
  if v_accepted_verifications >= 20 then v_attained := array_append(v_attained, 'trouwewachter'); end if;
  if v_ballroom_approved_entries >= 10 or v_ballroom_king_claims >= 5 then v_attained := array_append(v_attained, 'salonleeuw'); end if;
  if v_heavy_nights >= 5 then v_attained := array_append(v_attained, 'ijzerenmaag'); end if;
  if v_after_four_actions >= 5 then v_attained := array_append(v_attained, 'laatsteronde'); end if;
  if v_ballroom_king_claims >= 10 or v_ballroom_approved_entries >= 25 then v_attained := array_append(v_attained, 'fluwelenvorst'); end if;
  if v_evening_weekend_win_dates >= 15 then v_attained := array_append(v_attained, 'rozenkoning'); end if;
  if v_max_consecutive_active_days >= 7 then v_attained := array_append(v_attained, 'vuurproef'); end if;
  if v_total_matches >= 100 and v_site_areas_active_count >= 4 then v_attained := array_append(v_attained, 'sleuteldrager'); end if;
  if v_total_comeback_wins >= 12 then v_attained := array_append(v_attained, 'dobbelofniets'); end if;
  if v_klaverjas_wins >= 20 and v_boerenbridge_wins >= 20 and v_live_participations >= 5 then v_attained := array_append(v_attained, 'kaartopera'); end if;
  if v_total_matches >= 50 and v_verified_drink_actions >= 50 and v_accepted_verifications >= 25 and v_speed_threshold_hits >= 2 and (v_ballroom_approved_entries > 0 or v_ballroom_king_claims > 0) and v_live_participations > 0 then v_attained := array_append(v_attained, 'avondster'); end if;

  select coalesce(array_agg(distinct x order by x), '{}'::text[]) into v_attained from unnest(v_attained) as t(x);

  select coalesce(jsonb_agg(to_jsonb(bd) order by bd.rarity_rank desc, bd.key), '[]'::jsonb)
    into v_attained_badges
    from public.badge_definitions bd
   where bd.key = any(v_attained);

  select coalesce(jsonb_agg(
    to_jsonb(bd) || jsonb_build_object('earned', bd.key = any(v_attained))
    order by bd.rarity_rank asc, bd.key asc
  ), '[]'::jsonb)
    into v_all_badges
    from public.badge_definitions bd;

  select to_jsonb(bd)
    into v_primary_badge
    from public.badge_definitions bd
   where bd.key = any(v_attained)
     and nullif(trim(coalesce(bd.nickname, '')), '') is not null
   order by bd.rarity_rank desc, bd.key asc
   limit 1;

  v_primary_nickname := coalesce(v_primary_badge->>'nickname', '');

  return jsonb_build_object(
    'player_name', v_original_name,
    'display_name', v_display_name,
    'original_name', v_original_name,
    'site_scope', v_scope,
    'badge_count', coalesce(array_length(v_attained, 1), 0),
    'primary_badge', v_primary_badge,
    'primary_nickname', v_primary_nickname,
    'attained_badges', coalesce(v_attained_badges, '[]'::jsonb),
    'all_badges', coalesce(v_all_badges, '[]'::jsonb),
    'mini_badges_48', coalesce(v_attained_badges, '[]'::jsonb),
    'mini_badges_64', coalesce(v_attained_badges, '[]'::jsonb),
    'facts', jsonb_build_object(
      'total_matches', v_total_matches,
      'total_wins', v_total_wins,
      'klaverjas_matches', v_klaverjas_matches,
      'boerenbridge_matches', v_boerenbridge_matches,
      'beerpong_matches', v_beerpong_matches,
      'klaverjas_wins', v_klaverjas_wins,
      'boerenbridge_wins', v_boerenbridge_wins,
      'beerpong_wins', v_beerpong_wins,
      'best_game_win_pct', v_best_game_win_pct,
      'verified_drink_actions', v_verified_drink_actions,
      'verified_speed_attempts', v_verified_speed_attempts,
      'total_drink_units', v_total_drink_units,
      'speed_threshold_hits', v_speed_threshold_hits,
      'ice_under_25', v_ice_under_25,
      'liter_under_90', v_liter_under_90,
      'wine_events', v_wine_events,
      'accepted_verifications', v_accepted_verifications,
      'pussycup_pct', v_pussycup_pct,
      'max_win_streak', v_max_win_streak,
      'live_participations', v_live_participations,
      'total_comeback_wins', v_total_comeback_wins,
      'ballroom_approved_entries', v_ballroom_approved_entries,
      'ballroom_king_claims', v_ballroom_king_claims,
      'night_actions', v_night_actions,
      'after_four_actions', v_after_four_actions,
      'heavy_nights', v_heavy_nights,
      'evening_weekend_win_dates', v_evening_weekend_win_dates,
      'max_consecutive_active_days', v_max_consecutive_active_days,
      'site_areas_active_count', v_site_areas_active_count
    )
  );
end;
$$;

create or replace function public.get_site_player_badge_cards_scoped(
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_scope text := case when lower(trim(coalesce(site_scope_input, ''))) = 'family' then 'family' else 'friends' end;
  v_raw jsonb;
  v_players jsonb := '[]'::jsonb;
  v_card jsonb;
  v_bundle jsonb;
  v_cards jsonb := '[]'::jsonb;
begin
  v_raw := public.get_all_site_players_public_scoped(site_scope_input => v_scope);
  if jsonb_typeof(v_raw) = 'object' and v_raw ? 'players' then
    v_players := coalesce(v_raw->'players', '[]'::jsonb);
  elsif jsonb_typeof(v_raw) = 'array' then
    v_players := v_raw;
  end if;

  for v_card in select value from jsonb_array_elements(v_players)
  loop
    v_bundle := public.get_player_badge_bundle_scoped(
      coalesce(
        nullif(trim(coalesce(v_card->>'player_name', '')), ''),
        nullif(trim(coalesce(v_card->>'display_name', '')), ''),
        nullif(trim(coalesce(v_card->>'chosen_username', '')), '')
      ),
      v_scope
    );

    v_cards := v_cards || jsonb_build_array(
      jsonb_build_object(
        'player_name', coalesce(v_card->>'player_name', v_bundle->>'player_name'),
        'display_name', coalesce(v_bundle->>'display_name', v_card->>'display_name', v_card->>'player_name'),
        'original_name', coalesce(v_bundle->>'original_name', v_card->>'player_name'),
        'favorite_game', v_card->>'favorite_game',
        'total_matches', coalesce(nullif(v_card->>'total_matches', '')::int, 0),
        'total_wins', coalesce(nullif(v_card->>'total_wins', '')::int, 0),
        'best_rating', coalesce(nullif(v_card->>'best_rating', '')::numeric, 1000),
        'primary_nickname', coalesce(v_bundle->>'primary_nickname', ''),
        'primary_badge', v_bundle->'primary_badge',
        'mini_badges', coalesce(v_bundle->'mini_badges_48', '[]'::jsonb),
        'badge_count', coalesce((v_bundle->>'badge_count')::int, 0)
      )
    );
  end loop;

  return jsonb_build_object('cards', v_cards);
end;
$$;

grant execute on function public._badge_norm_name(text) to anon, authenticated;
grant execute on function public._badge_normalize_drink_type(text) to anon, authenticated;
grant execute on function public._badge_public_player_row_scoped(text, text) to anon, authenticated;
grant execute on function public._badge_verified_drink_rows(text) to anon, authenticated;
grant execute on function public._badge_verified_speed_rows(text) to anon, authenticated;
grant execute on function public._badge_all_match_rows_scoped(text, text) to anon, authenticated;
grant execute on function public.get_player_badge_bundle_scoped(text, text) to anon, authenticated;
grant execute on function public.get_site_player_badge_cards_scoped(text) to anon, authenticated;

commit;
