begin;

create table if not exists public.beerpong_matches (
  id bigint generated by default as identity primary key,
  client_match_id text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  created_by_player_id bigint references public.players(id) on delete set null,
  match_status text not null default 'finished',
  match_format text not null default '2v2',
  team_a_player_ids bigint[] not null default '{}',
  team_b_player_ids bigint[] not null default '{}',
  winner_team text,
  cups_left_team_a integer,
  cups_left_team_b integer,
  notes text,
  payload jsonb not null default '{}'::jsonb,
  stats_applied_at timestamptz
);

create table if not exists public.beerpong_player_ratings (
  player_id bigint primary key references public.players(id) on delete cascade,
  rating numeric(10,2) not null default 1000,
  matches_played integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  last_result text,
  updated_at timestamptz not null default now()
);

create index if not exists beerpong_matches_finished_at_idx on public.beerpong_matches (finished_at desc);
create index if not exists beerpong_matches_status_idx on public.beerpong_matches (match_status);
create index if not exists beerpong_matches_created_by_idx on public.beerpong_matches (created_by_player_id);
create index if not exists beerpong_ratings_rating_idx on public.beerpong_player_ratings (rating desc);

create or replace function public.save_beerpong_match(
  session_token text,
  client_match_id text,
  payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_player public.players%rowtype;
  v_match_id bigint;
  v_existing public.beerpong_matches%rowtype;
  v_format text := lower(trim(coalesce(payload->>'format', '2v2')));
  v_status text := lower(trim(coalesce(payload->>'status', 'finished')));
  v_winner_team text := lower(trim(coalesce(payload->>'winner_team', '')));
  v_team_a_ids bigint[] := coalesce((select array_agg(value::bigint) from jsonb_array_elements_text(coalesce(payload->'team_a_player_ids','[]'::jsonb))), '{}'::bigint[]);
  v_team_b_ids bigint[] := coalesce((select array_agg(value::bigint) from jsonb_array_elements_text(coalesce(payload->'team_b_player_ids','[]'::jsonb))), '{}'::bigint[]);
  v_team_a_count integer;
  v_team_b_count integer;
  v_team_a_avg numeric(10,4);
  v_team_b_avg numeric(10,4);
  v_expected_a numeric(10,6);
  v_expected_b numeric(10,6);
  v_actual_a numeric(10,2);
  v_actual_b numeric(10,2);
  v_delta integer;
  v_now timestamptz := now();
  v_finished_at timestamptz := coalesce(nullif(payload->>'finished_at','')::timestamptz, now());
  v_notes text := nullif(trim(coalesce(payload->>'notes','')), '');
  v_cups_a integer := nullif(payload->>'cups_left_team_a','')::integer;
  v_cups_b integer := nullif(payload->>'cups_left_team_b','')::integer;
  v_stats_applied boolean := false;
begin
  if nullif(trim(coalesce(client_match_id, '')), '') is null then
    raise exception 'client_match_id ontbreekt';
  end if;

  if v_format not in ('1v1','2v2') then
    raise exception 'Ongeldig formaat';
  end if;

  v_team_a_count := coalesce(array_length(v_team_a_ids, 1), 0);
  v_team_b_count := coalesce(array_length(v_team_b_ids, 1), 0);

  if v_format = '1v1' then
    if v_team_a_count <> 1 or v_team_b_count <> 1 then
      raise exception 'Bij 1v1 moet elk team precies 1 speler hebben';
    end if;
  else
    if v_team_a_count <> 2 or v_team_b_count <> 2 then
      raise exception 'Bij 2v2 moet elk team precies 2 spelers hebben';
    end if;
  end if;

  if exists (
    select 1
    from unnest(v_team_a_ids) a
    join unnest(v_team_b_ids) b on a = b
  ) then
    raise exception 'Een speler mag maar in één team staan';
  end if;

  if v_winner_team not in ('team_a','team_b') then
    raise exception 'winner_team ontbreekt of is ongeldig';
  end if;

  begin
    if nullif(trim(coalesce(session_token,'')), '') is not null then
      select * into v_player from public._gejast_player_from_session(session_token);
    end if;
  exception when others then
    null;
  end;

  insert into public.beerpong_matches (
    client_match_id,
    created_at,
    updated_at,
    finished_at,
    created_by_player_id,
    match_status,
    match_format,
    team_a_player_ids,
    team_b_player_ids,
    winner_team,
    cups_left_team_a,
    cups_left_team_b,
    notes,
    payload
  ) values (
    client_match_id,
    v_now,
    v_now,
    case when v_status = 'finished' then v_finished_at else null end,
    v_player.id,
    case when v_status = 'finished' then 'finished' else 'draft' end,
    v_format,
    v_team_a_ids,
    v_team_b_ids,
    v_winner_team,
    v_cups_a,
    v_cups_b,
    v_notes,
    coalesce(payload, '{}'::jsonb)
  )
  on conflict (client_match_id)
  do update set
    updated_at = v_now,
    finished_at = case when excluded.match_status = 'finished' then coalesce(public.beerpong_matches.finished_at, excluded.finished_at) else public.beerpong_matches.finished_at end,
    match_status = excluded.match_status,
    match_format = excluded.match_format,
    team_a_player_ids = excluded.team_a_player_ids,
    team_b_player_ids = excluded.team_b_player_ids,
    winner_team = excluded.winner_team,
    cups_left_team_a = excluded.cups_left_team_a,
    cups_left_team_b = excluded.cups_left_team_b,
    notes = excluded.notes,
    payload = excluded.payload
  returning * into v_existing;

  v_match_id := v_existing.id;

  if v_existing.stats_applied_at is null and v_existing.match_status = 'finished' then
    insert into public.beerpong_player_ratings (player_id)
    select p.player_id
    from (
      select unnest(v_team_a_ids) as player_id
      union
      select unnest(v_team_b_ids) as player_id
    ) p
    on conflict (player_id) do nothing;

    select avg(r.rating) into v_team_a_avg from public.beerpong_player_ratings r where r.player_id = any(v_team_a_ids);
    select avg(r.rating) into v_team_b_avg from public.beerpong_player_ratings r where r.player_id = any(v_team_b_ids);

    v_expected_a := 1 / (1 + power(10::numeric, (coalesce(v_team_b_avg,1000) - coalesce(v_team_a_avg,1000)) / 400.0));
    v_expected_b := 1 - v_expected_a;
    v_actual_a := case when v_winner_team = 'team_a' then 1 else 0 end;
    v_actual_b := case when v_winner_team = 'team_b' then 1 else 0 end;
    v_delta := round(32 * (v_actual_a - v_expected_a));
    if v_delta = 0 then
      v_delta := case when v_winner_team = 'team_a' then 1 else -1 end;
    end if;

    update public.beerpong_player_ratings r
       set rating = r.rating + v_delta,
           matches_played = r.matches_played + 1,
           wins = r.wins + 1,
           current_streak = greatest(r.current_streak, 0) + 1,
           best_streak = greatest(r.best_streak, greatest(r.current_streak, 0) + 1),
           last_result = 'win',
           updated_at = v_now
     where r.player_id = any(v_team_a_ids)
       and v_winner_team = 'team_a';

    update public.beerpong_player_ratings r
       set rating = r.rating - v_delta,
           matches_played = r.matches_played + 1,
           losses = r.losses + 1,
           current_streak = least(r.current_streak, 0) - 1,
           last_result = 'loss',
           updated_at = v_now
     where r.player_id = any(v_team_b_ids)
       and v_winner_team = 'team_a';

    update public.beerpong_player_ratings r
       set rating = r.rating + abs(v_delta),
           matches_played = r.matches_played + 1,
           wins = r.wins + 1,
           current_streak = greatest(r.current_streak, 0) + 1,
           best_streak = greatest(r.best_streak, greatest(r.current_streak, 0) + 1),
           last_result = 'win',
           updated_at = v_now
     where r.player_id = any(v_team_b_ids)
       and v_winner_team = 'team_b';

    update public.beerpong_player_ratings r
       set rating = r.rating - abs(v_delta),
           matches_played = r.matches_played + 1,
           losses = r.losses + 1,
           current_streak = least(r.current_streak, 0) - 1,
           last_result = 'loss',
           updated_at = v_now
     where r.player_id = any(v_team_a_ids)
       and v_winner_team = 'team_b';

    update public.beerpong_matches
       set stats_applied_at = v_now,
           updated_at = v_now
     where id = v_match_id;

    v_stats_applied := true;
  end if;

  return jsonb_build_object(
    'ok', true,
    'match_id', v_match_id,
    'client_match_id', client_match_id,
    'match_status', v_existing.match_status,
    'stats_applied', v_stats_applied
  );
end;
$fn$;

create or replace function public.get_beerpong_leaderboard_public()
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  return jsonb_build_object(
    'leaderboard', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'player_id', p.id,
          'display_name', coalesce(nullif(pp.nickname,''), p.display_name),
          'nickname', pp.nickname,
          'profile_picture_url', pp.profile_picture_url,
          'rating', r.rating,
          'matches_played', r.matches_played,
          'wins', r.wins,
          'losses', r.losses,
          'winrate', case when r.matches_played > 0 then round((100.0 * r.wins / r.matches_played)::numeric, 1) else 0 end,
          'current_streak', r.current_streak,
          'best_streak', r.best_streak
        ) order by r.rating desc, r.wins desc, lower(p.display_name)
      )
      from public.beerpong_player_ratings r
      join public.players p on p.id = r.player_id
      left join public.player_profiles pp on pp.player_id = p.id
      where coalesce(p.active,false) is true
    ), '[]'::jsonb),
    'matches_count', coalesce((select count(*)::int from public.beerpong_matches where match_status = 'finished'), 0),
    'recent_matches', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'client_match_id', m.client_match_id,
          'finished_at', m.finished_at,
          'finished_at_local', to_char(m.finished_at at time zone 'Europe/Amsterdam', 'DD-MM-YYYY HH24:MI'),
          'winner_names', case when m.winner_team = 'team_a' then (
            select array_agg(p.display_name order by lower(p.display_name)) from public.players p where p.id = any(m.team_a_player_ids)
          ) else (
            select array_agg(p.display_name order by lower(p.display_name)) from public.players p where p.id = any(m.team_b_player_ids)
          ) end,
          'loser_names', case when m.winner_team = 'team_a' then (
            select array_agg(p.display_name order by lower(p.display_name)) from public.players p where p.id = any(m.team_b_player_ids)
          ) else (
            select array_agg(p.display_name order by lower(p.display_name)) from public.players p where p.id = any(m.team_a_player_ids)
          ) end,
          'match_format', m.match_format,
          'cups_left_team_a', m.cups_left_team_a,
          'cups_left_team_b', m.cups_left_team_b
        ) order by m.finished_at desc nulls last
      )
      from (
        select * from public.beerpong_matches where match_status = 'finished' order by finished_at desc nulls last limit 12
      ) m
    ), '[]'::jsonb)
  );
end;
$fn$;

grant execute on function public.save_beerpong_match(text, text, jsonb) to anon, authenticated;
grant execute on function public.get_beerpong_leaderboard_public() to anon, authenticated;

commit;
