begin;

create table if not exists public.active_web_push_presence (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  p256dh_key text not null,
  auth_key text not null,
  session_token text not null,
  player_name text not null,
  page_path text,
  user_agent text,
  permission text,
  standalone boolean,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists active_web_push_presence_endpoint_uidx on public.active_web_push_presence(endpoint);
create index if not exists active_web_push_presence_last_seen_idx on public.active_web_push_presence(last_seen_at desc);
create index if not exists active_web_push_presence_player_idx on public.active_web_push_presence(lower(player_name), last_seen_at desc);

create table if not exists public.admin_web_push_jobs (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  p256dh_key text not null,
  auth_key text not null,
  title text not null,
  body text not null,
  target_url text,
  job_status text not null default 'queued',
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  last_error text
);

create index if not exists admin_web_push_jobs_queue_idx on public.admin_web_push_jobs(job_status, created_at asc);

create or replace function public.touch_active_web_push_presence(
  session_token text,
  endpoint_input text,
  p256dh_input text,
  auth_input text,
  page_path_input text default null,
  permission_input text default null,
  standalone_input boolean default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_state jsonb;
  v_name text;
begin
  if nullif(trim(coalesce(session_token, '')), '') is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_session_token');
  end if;
  if nullif(trim(coalesce(endpoint_input, '')), '') is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_endpoint');
  end if;
  begin
    v_state := public.get_public_state(session_token);
  exception when others then
    return jsonb_build_object('ok', false, 'reason', 'invalid_session');
  end;
  v_name := nullif(trim(coalesce(v_state->>'my_name', v_state->>'display_name', v_state->>'player_name', '')), '');
  if v_name is null then
    return jsonb_build_object('ok', false, 'reason', 'inactive_session');
  end if;

  insert into public.active_web_push_presence (
    endpoint, p256dh_key, auth_key, session_token, player_name, page_path, user_agent, permission, standalone, first_seen_at, last_seen_at, updated_at
  ) values (
    trim(endpoint_input), trim(coalesce(p256dh_input,'')), trim(coalesce(auth_input,'')), trim(session_token), v_name,
    nullif(trim(coalesce(page_path_input,'')), ''), nullif(trim(coalesce(current_setting('request.headers', true)::json->>'user-agent','')), ''),
    nullif(trim(coalesce(permission_input,'')), ''), standalone_input, now(), now(), now()
  )
  on conflict (endpoint) do update set
    p256dh_key = excluded.p256dh_key,
    auth_key = excluded.auth_key,
    session_token = excluded.session_token,
    player_name = excluded.player_name,
    page_path = excluded.page_path,
    user_agent = excluded.user_agent,
    permission = excluded.permission,
    standalone = excluded.standalone,
    last_seen_at = now(),
    updated_at = now();

  delete from public.active_web_push_presence where last_seen_at < now() - interval '24 hours';

  return jsonb_build_object('ok', true, 'player_name', v_name);
end;
$fn$;

create or replace function public.admin_get_active_web_push_presence(
  admin_session_token text,
  active_minutes integer default 5
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_session jsonb;
  v_minutes integer := greatest(1, least(coalesce(active_minutes, 5), 60));
  v_since timestamptz := now() - make_interval(mins => v_minutes);
begin
  v_session := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_session->>'ok')::boolean, false) is not true then
    raise exception 'Log opnieuw in als admin.';
  end if;

  return jsonb_build_object(
    'ok', true,
    'active_endpoints', (select count(*)::int from public.active_web_push_presence where last_seen_at >= v_since and permission = 'granted'),
    'unique_players', (select count(distinct lower(player_name))::int from public.active_web_push_presence where last_seen_at >= v_since and permission = 'granted'),
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'player_name', x.player_name,
        'page_path', x.page_path,
        'last_seen_at', x.last_seen_at,
        'user_agent', x.user_agent,
        'user_agent_label', case
          when coalesce(x.user_agent,'') ilike '%iphone%' or coalesce(x.user_agent,'') ilike '%ipad%' then 'iPhone/iPad'
          when coalesce(x.user_agent,'') ilike '%android%' then 'Android'
          when coalesce(x.user_agent,'') ilike '%windows%' then 'Windows'
          when coalesce(x.user_agent,'') ilike '%mac os%' then 'macOS'
          else 'Browser'
        end
      ) order by x.last_seen_at desc, lower(x.player_name))
      from public.active_web_push_presence x
      where x.last_seen_at >= v_since and x.permission = 'granted'
    ), '[]'::jsonb)
  );
end;
$fn$;

create or replace function public.admin_queue_active_web_push(
  admin_session_token text,
  title_input text,
  body_input text,
  target_url_input text default null,
  active_minutes integer default 5
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_session jsonb;
  v_minutes integer := greatest(1, least(coalesce(active_minutes, 5), 60));
  v_since timestamptz := now() - make_interval(mins => v_minutes);
  v_title text := left(trim(coalesce(title_input,'')), 80);
  v_body text := left(trim(coalesce(body_input,'')), 240);
  v_target text := nullif(trim(coalesce(target_url_input,'')), '');
  v_count integer := 0;
begin
  v_session := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_session->>'ok')::boolean, false) is not true then
    raise exception 'Log opnieuw in als admin.';
  end if;
  if v_title = '' then raise exception 'Titel ontbreekt.'; end if;
  if v_body = '' then raise exception 'Bericht ontbreekt.'; end if;

  insert into public.admin_web_push_jobs(endpoint, p256dh_key, auth_key, title, body, target_url)
  select distinct on (endpoint)
    endpoint,
    p256dh_key,
    auth_key,
    v_title,
    v_body,
    coalesce(v_target, './index.html')
  from public.active_web_push_presence
  where last_seen_at >= v_since
    and permission = 'granted'
    and nullif(trim(coalesce(endpoint,'')), '') is not null
    and nullif(trim(coalesce(p256dh_key,'')), '') is not null
    and nullif(trim(coalesce(auth_key,'')), '') is not null
  order by endpoint, last_seen_at desc;

  get diagnostics v_count = row_count;

  return jsonb_build_object(
    'ok', true,
    'queued_count', v_count,
    'target_url', coalesce(v_target, './index.html'),
    'active_minutes', v_minutes
  );
end;
$fn$;

create or replace function public.claim_admin_web_push_jobs(max_jobs integer default 25)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_limit integer := greatest(1, least(coalesce(max_jobs, 25), 100));
  v_items jsonb := '[]'::jsonb;
begin
  with picked as (
    select id
    from public.admin_web_push_jobs
    where job_status = 'queued'
    order by created_at asc
    limit v_limit
    for update skip locked
  ), updated as (
    update public.admin_web_push_jobs j
    set job_status = 'sending', claimed_at = now()
    from picked
    where j.id = picked.id
    returning j.*
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'job_id', id,
    'endpoint', endpoint,
    'p256dh_key', p256dh_key,
    'auth_key', auth_key,
    'title', title,
    'body', body,
    'target_url', target_url
  ) order by created_at asc), '[]'::jsonb)
  into v_items
  from updated;

  return jsonb_build_object('ok', true, 'items', v_items);
end;
$fn$;

create or replace function public.mark_admin_web_push_job_sent(job_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  update public.admin_web_push_jobs
  set job_status = 'sent', sent_at = now(), last_error = null
  where id = job_id_input;
  return jsonb_build_object('ok', true);
end;
$fn$;

create or replace function public.mark_admin_web_push_job_failed(job_id_input bigint, error_input text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  update public.admin_web_push_jobs
  set job_status = 'failed', failed_at = now(), last_error = left(coalesce(error_input,''), 1000)
  where id = job_id_input;
  return jsonb_build_object('ok', true);
end;
$fn$;

grant execute on function public.touch_active_web_push_presence(text, text, text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.admin_get_active_web_push_presence(text, integer) to anon, authenticated;
grant execute on function public.admin_queue_active_web_push(text, text, text, text, integer) to anon, authenticated;
grant execute on function public.claim_admin_web_push_jobs(integer) to anon, authenticated;
grant execute on function public.mark_admin_web_push_job_sent(bigint) to anon, authenticated;
grant execute on function public.mark_admin_web_push_job_failed(bigint, text) to anon, authenticated;

commit;
