-- GEJAST v841 — deep shop analytics schema
-- Production schema source for the protected shop analytics dashboard.

begin;

create table if not exists public.shop_finance_ledger_v841 (
  id bigint generated by default as identity primary key,
  occurred_on date not null default current_date,
  direction text not null check (direction in ('cost','income')),
  category text not null check (category in ('marketing','packaging','payment_fee','refund','chargeback','tax','software','shipping_adjustment','discount','other')),
  amount_cents integer not null check (amount_cents > 0 and amount_cents <= 100000000),
  currency text not null default 'eur' check (currency = 'eur'),
  order_id uuid references public.shop_orders(id) on delete set null,
  product_name text,
  note text,
  created_by_admin_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists shop_finance_ledger_v841_occurred_idx on public.shop_finance_ledger_v841 (occurred_on desc, id desc);
create index if not exists shop_finance_ledger_v841_order_idx on public.shop_finance_ledger_v841 (order_id) where order_id is not null;
alter table public.shop_finance_ledger_v841 enable row level security;
revoke all on table public.shop_finance_ledger_v841 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_finance_ledger_v841 to service_role;
grant usage, select on sequence public.shop_finance_ledger_v841_id_seq to service_role;

create table if not exists public.shop_product_cost_cache_v841 (
  id smallint primary key default 1 check (id = 1),
  payload jsonb not null default '{"products":[]}'::jsonb,
  generated_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);
insert into public.shop_product_cost_cache_v841 (id) values (1) on conflict (id) do nothing;
alter table public.shop_product_cost_cache_v841 enable row level security;
revoke all on table public.shop_product_cost_cache_v841 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_product_cost_cache_v841 to service_role;

CREATE OR REPLACE FUNCTION public.shop_admin_analytics_snapshot_v841(p_from timestamp with time zone, p_to timestamp with time zone)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
with
bounds as (
  select greatest(coalesce(p_from, now() - interval '30 days'), timestamptz '2020-01-01 00:00:00+00') as from_ts,
         least(coalesce(p_to, now()), now() + interval '1 day') as to_ts
),
events as (
  select e.*
  from public.site_visitor_events e, bounds b
  where e.created_at >= b.from_ts and e.created_at < b.to_ts
    and (e.page_path = '/shop/' or e.page_path like '/shop/%' or e.page_path = '/shop')
),
orders as (
  select o.*
  from public.shop_orders o, bounds b
  where o.created_at >= b.from_ts and o.created_at < b.to_ts
),
order_items as (
  select
    o.id as order_id,
    o.status,
    o.payment_verified_at,
    o.submitted_to_printify_at,
    o.created_at,
    coalesce(nullif(li->>'catalog_printify_product_id',''), nullif(li->>'printify_product_id',''), nullif(li->>'product_id','')) as product_id,
    nullif(li->>'name','') as product_name,
    nullif(li->>'collection','') as collection,
    nullif(li->>'size','') as size,
    greatest(1, coalesce(nullif(li->>'qty','')::integer,1)) as qty,
    coalesce(nullif(li->>'unit_price_cents','')::integer,0) as unit_price_cents,
    case when nullif(li->>'fulfillment_cost_cents','') is not null then (li->>'fulfillment_cost_cents')::integer end as unit_cost_cents,
    coalesce(nullif(li->>'fulfillment_estimated_import_cents_per_unit','')::integer,0) as import_cents_per_unit,
    nullif(li#>>'{fulfillment_route,print_provider_id}','') as provider_id
  from orders o
  cross join lateral jsonb_array_elements(o.line_items) li
),
order_econ as (
  select
    o.id,o.status,o.created_at,o.payment_verified_at,o.submitted_to_printify_at,o.shipped_at,o.currency,
    o.subtotal_cents,o.shipping_cents,o.total_cents,o.paid_amount_cents,o.fulfillment_estimated_import_cents,
    o.shipping_source_currency,o.shipping_source_cents,o.fx_snapshot,
    coalesce(ic.known_product_cost_cents,0)::bigint as known_product_cost_cents,
    coalesce(ic.missing_cost_units,0)::bigint as missing_cost_units,
    coalesce(ic.units,0)::bigint as units,
    case
      when o.shipping_cents = 0 then 0
      when lower(coalesce(o.shipping_source_currency,'')) = 'eur' and o.shipping_source_cents is not null then o.shipping_source_cents
      when lower(coalesce(o.shipping_source_currency,'')) = 'usd'
        and o.shipping_source_cents is not null
        and nullif(o.fx_snapshot->>'rate','') is not null
      then round(o.shipping_source_cents * (o.fx_snapshot->>'rate')::numeric)::integer
      else null
    end as supplier_shipping_cost_cents
  from orders o
  left join lateral (
    select
      sum(case when oi.unit_cost_cents is not null then oi.unit_cost_cents * oi.qty else 0 end)::bigint as known_product_cost_cents,
      sum(case when oi.unit_cost_cents is null then oi.qty else 0 end)::bigint as missing_cost_units,
      sum(oi.qty)::bigint as units
    from order_items oi where oi.order_id=o.id
  ) ic on true
),
day_events as (
  select ((e.created_at at time zone 'Europe/Amsterdam') - interval '6 hours')::date as day,
         count(*) filter (where e.event_name='page_view')::bigint as page_views,
         count(distinct e.visitor_id)::bigint as visitors,
         count(distinct e.session_id)::bigint as sessions,
         count(*) filter (where e.event_name='product_view')::bigint as product_views,
         count(*) filter (where e.event_name='add_to_cart')::bigint as add_to_cart,
         count(*) filter (where e.event_name='checkout_start')::bigint as checkout_starts
  from events e group by 1
),
day_orders as (
  select ((o.created_at at time zone 'Europe/Amsterdam') - interval '6 hours')::date as day,
         count(*)::bigint as orders_created,
         count(*) filter (where o.payment_verified_at is not null)::bigint as paid_orders,
         coalesce(sum(o.total_cents) filter (where o.payment_verified_at is not null),0)::bigint as paid_sales_cents,
         coalesce(sum(o.paid_amount_cents) filter (where o.payment_verified_at is not null),0)::bigint as cash_received_cents
  from order_econ o group by 1
),
event_product as (
  select
    nullif(e.extra->>'product_id','') as product_id,
    max(nullif(e.extra->>'product_name','')) as product_name,
    max(nullif(e.extra->>'collection','')) as collection,
    count(*) filter (where e.event_name='product_view')::bigint as views,
    count(distinct e.session_id) filter (where e.event_name='product_view')::bigint as viewing_sessions,
    count(*) filter (where e.event_name='add_to_cart')::bigint as adds,
    coalesce(sum(case when e.event_name='add_to_cart' then greatest(1,coalesce(nullif(e.extra->>'qty','')::integer,1)) else 0 end),0)::bigint as added_units,
    count(*) filter (where e.event_name='remove_from_cart')::bigint as removes
  from events e
  where nullif(e.extra->>'product_id','') is not null
  group by 1
),
sold_product as (
  select
    oi.product_id,
    max(oi.product_name) as product_name,
    max(oi.collection) as collection,
    coalesce(sum(oi.qty),0)::bigint as ordered_units,
    coalesce(sum(oi.qty) filter (where oi.payment_verified_at is not null),0)::bigint as paid_units,
    coalesce(sum(oi.unit_price_cents*oi.qty),0)::bigint as ordered_revenue_cents,
    coalesce(sum(oi.unit_price_cents*oi.qty) filter (where oi.payment_verified_at is not null),0)::bigint as paid_revenue_cents,
    coalesce(sum(oi.unit_cost_cents*oi.qty) filter (where oi.payment_verified_at is not null and oi.unit_cost_cents is not null),0)::bigint as paid_known_cost_cents,
    coalesce(sum(oi.qty) filter (where oi.payment_verified_at is not null and oi.unit_cost_cents is null),0)::bigint as paid_missing_cost_units
  from order_items oi
  group by oi.product_id
),
product_keys as (
  select product_id from event_product where product_id is not null
  union
  select product_id from sold_product where product_id is not null
),
product_stats as (
  select
    k.product_id,
    coalesce(ep.product_name, sp.product_name, k.product_id) as product_name,
    coalesce(ep.collection, sp.collection, 'unknown') as collection,
    coalesce(ep.views,0) as views,coalesce(ep.viewing_sessions,0) as viewing_sessions,
    coalesce(ep.adds,0) as adds,coalesce(ep.added_units,0) as added_units,coalesce(ep.removes,0) as removes,
    coalesce(sp.ordered_units,0) as ordered_units,coalesce(sp.paid_units,0) as paid_units,
    coalesce(sp.ordered_revenue_cents,0) as ordered_revenue_cents,coalesce(sp.paid_revenue_cents,0) as paid_revenue_cents,
    coalesce(sp.paid_known_cost_cents,0) as paid_known_cost_cents,coalesce(sp.paid_missing_cost_units,0) as paid_missing_cost_units
  from product_keys k
  left join event_product ep using(product_id)
  left join sold_product sp using(product_id)
),
ledger as (
  select l.* from public.shop_finance_ledger_v841 l, bounds b
  where l.occurred_on >= ((b.from_ts at time zone 'Europe/Amsterdam') - interval '6 hours')::date
    and l.occurred_on <= (((b.to_ts - interval '1 microsecond') at time zone 'Europe/Amsterdam') - interval '6 hours')::date
),
event_totals as (
  select
    count(distinct visitor_id)::bigint as visitors,count(distinct session_id)::bigint as sessions,
    count(*) filter (where event_name='page_view')::bigint as page_views,
    count(*) filter (where event_name='collection_view')::bigint as collection_views,
    count(*) filter (where event_name='product_view')::bigint as product_views,
    count(*) filter (where event_name='product_image_interaction')::bigint as image_interactions,
    count(*) filter (where event_name='add_to_cart')::bigint as add_to_cart,
    count(*) filter (where event_name='remove_from_cart')::bigint as remove_from_cart,
    count(*) filter (where event_name='cart_open')::bigint as cart_opens,
    count(*) filter (where event_name='checkout_start')::bigint as checkout_starts,
    count(*) filter (where event_name='checkout_submit')::bigint as checkout_submits,
    count(*) filter (where event_name='order_created')::bigint as tracked_order_created,
    count(*) filter (where event_name='payment_link_click')::bigint as payment_link_clicks,
    count(*) filter (where event_name='order_status_check')::bigint as status_checks
  from events
),
order_totals as (
  select
    count(*)::bigint as orders_created,
    count(*) filter (where payment_verified_at is not null)::bigint as paid_orders,
    count(*) filter (where payment_verified_at is null)::bigint as unpaid_orders,
    count(*) filter (where submitted_to_printify_at is not null)::bigint as production_orders,
    count(*) filter (where shipped_at is not null)::bigint as shipped_orders,
    coalesce(sum(total_cents),0)::bigint as pipeline_sales_cents,
    coalesce(sum(total_cents) filter (where payment_verified_at is not null),0)::bigint as recognized_sales_cents,
    coalesce(sum(paid_amount_cents) filter (where payment_verified_at is not null),0)::bigint as cash_received_cents,
    coalesce(sum(total_cents) filter (where payment_verified_at is null),0)::bigint as pending_sales_cents,
    coalesce(sum(known_product_cost_cents) filter (where payment_verified_at is not null),0)::bigint as paid_known_product_cost_cents,
    coalesce(sum(fulfillment_estimated_import_cents) filter (where payment_verified_at is not null),0)::bigint as paid_import_allowance_cents,
    coalesce(sum(supplier_shipping_cost_cents) filter (where payment_verified_at is not null and supplier_shipping_cost_cents is not null),0)::bigint as paid_known_shipping_cost_cents,
    coalesce(sum(shipping_cents) filter (where payment_verified_at is not null),0)::bigint as paid_shipping_revenue_cents,
    coalesce(sum(missing_cost_units) filter (where payment_verified_at is not null),0)::bigint as paid_missing_cost_units,
    count(*) filter (where payment_verified_at is not null and supplier_shipping_cost_cents is null and shipping_cents > 0)::bigint as paid_missing_shipping_cost_orders,
    coalesce(sum(known_product_cost_cents) filter (where submitted_to_printify_at is not null),0)::bigint as committed_known_product_cost_cents,
    coalesce(sum(supplier_shipping_cost_cents) filter (where submitted_to_printify_at is not null and supplier_shipping_cost_cents is not null),0)::bigint as committed_known_shipping_cost_cents,
    coalesce(sum(units),0)::bigint as units_created,
    coalesce(sum(units) filter (where payment_verified_at is not null),0)::bigint as units_paid
  from order_econ
),
ledger_totals as (
  select coalesce(sum(amount_cents) filter (where direction='cost'),0)::bigint as costs_cents,
         coalesce(sum(amount_cents) filter (where direction='income'),0)::bigint as income_cents
  from ledger
)
select jsonb_build_object(
  'range', (select jsonb_build_object('from',from_ts,'to',to_ts,'business_day','Europe/Amsterdam 06:00-06:00') from bounds),
  'events', (select to_jsonb(event_totals) from event_totals),
  'orders', (select to_jsonb(order_totals) from order_totals),
  'ledger', (select jsonb_build_object(
      'costs_cents',lt.costs_cents,'income_cents',lt.income_cents,
      'entries',coalesce((select jsonb_agg(to_jsonb(x) order by x.occurred_on desc,x.id desc) from (select * from ledger order by occurred_on desc,id desc limit 300) x),'[]'::jsonb),
      'by_category',coalesce((select jsonb_agg(jsonb_build_object('category',category,'direction',direction,'amount_cents',amount_cents) order by amount_cents desc)
        from (select category,direction,sum(amount_cents)::bigint amount_cents from ledger group by category,direction) z),'[]'::jsonb)
    ) from ledger_totals lt),
  'daily',coalesce((
    select jsonb_agg(jsonb_build_object(
      'day',d.day,'visitors',coalesce(de.visitors,0),'sessions',coalesce(de.sessions,0),'page_views',coalesce(de.page_views,0),
      'product_views',coalesce(de.product_views,0),'add_to_cart',coalesce(de.add_to_cart,0),'checkout_starts',coalesce(de.checkout_starts,0),
      'orders_created',coalesce(dor.orders_created,0),'paid_orders',coalesce(dor.paid_orders,0),
      'paid_sales_cents',coalesce(dor.paid_sales_cents,0),'cash_received_cents',coalesce(dor.cash_received_cents,0)
    ) order by d.day)
    from (select day from day_events union select day from day_orders) d
    left join day_events de using(day) left join day_orders dor using(day)
  ),'[]'::jsonb),
  'products',coalesce((select jsonb_agg(to_jsonb(p) order by p.paid_revenue_cents desc,p.views desc,p.product_name) from product_stats p),'[]'::jsonb),
  'collections',coalesce((
    select jsonb_agg(to_jsonb(c) order by c.paid_revenue_cents desc,c.collection)
    from (
      select coalesce(collection,'unknown') collection,sum(qty)::bigint ordered_units,
             coalesce(sum(qty) filter(where payment_verified_at is not null),0)::bigint paid_units,
             sum(unit_price_cents*qty)::bigint ordered_revenue_cents,
             coalesce(sum(unit_price_cents*qty) filter(where payment_verified_at is not null),0)::bigint paid_revenue_cents
      from order_items group by coalesce(collection,'unknown')
    ) c
  ),'[]'::jsonb),
  'sizes',coalesce((
    select jsonb_agg(to_jsonb(s) order by s.paid_units desc,s.size)
    from (
      select coalesce(size,'unknown') size,sum(qty)::bigint ordered_units,
             coalesce(sum(qty) filter(where payment_verified_at is not null),0)::bigint paid_units
      from order_items group by coalesce(size,'unknown')
    ) s
  ),'[]'::jsonb),
  'countries',coalesce((
    select jsonb_agg(to_jsonb(c) order by c.orders desc,c.country)
    from (
      select upper(coalesce(nullif(shipping_address->>'country',''),'unknown')) country,count(*)::bigint orders,
             count(*) filter(where payment_verified_at is not null)::bigint paid_orders,
             coalesce(sum(total_cents) filter(where payment_verified_at is not null),0)::bigint paid_sales_cents
      from orders group by upper(coalesce(nullif(shipping_address->>'country',''),'unknown'))
    ) c
  ),'[]'::jsonb),
  'devices',coalesce((
    select jsonb_agg(to_jsonb(d) order by d.sessions desc,d.device)
    from (
      select coalesce(nullif(device_type,''),'unknown') device,count(distinct session_id)::bigint sessions,count(distinct visitor_id)::bigint visitors
      from events group by coalesce(nullif(device_type,''),'unknown')
    ) d
  ),'[]'::jsonb),
  'browsers',coalesce((
    select jsonb_agg(to_jsonb(d) order by d.sessions desc,d.browser)
    from (
      select coalesce(nullif(browser_name,''),'unknown') browser,count(distinct session_id)::bigint sessions
      from events group by coalesce(nullif(browser_name,''),'unknown')
    ) d
  ),'[]'::jsonb),
  'referrers',coalesce((
    select jsonb_agg(to_jsonb(r) order by r.sessions desc,r.referrer)
    from (
      select case when coalesce(referrer_url,'')='' then '(direct)' else split_part(regexp_replace(referrer_url,'^https?://','','i'),'/',1) end referrer,
             count(distinct session_id)::bigint sessions,count(distinct visitor_id)::bigint visitors
      from events group by 1 order by 2 desc limit 30
    ) r
  ),'[]'::jsonb),
  'campaigns',coalesce((
    select jsonb_agg(to_jsonb(u) order by u.sessions desc,u.utm_source,u.utm_campaign)
    from (
      select coalesce(nullif(extra->>'utm_source',''),'(none)') utm_source,
             coalesce(nullif(extra->>'utm_medium',''),'(none)') utm_medium,
             coalesce(nullif(extra->>'utm_campaign',''),'(none)') utm_campaign,
             count(distinct session_id)::bigint sessions,count(distinct visitor_id)::bigint visitors
      from events
      where nullif(extra->>'utm_source','') is not null or nullif(extra->>'utm_campaign','') is not null
      group by 1,2,3 order by 4 desc limit 50
    ) u
  ),'[]'::jsonb),
  'recent_events',coalesce((
    select jsonb_agg(to_jsonb(x) order by x.created_at desc)
    from (
      select id,created_at,event_name,event_label,visitor_id,session_id,device_type,browser_name,
             extra->>'product_id' product_id,extra->>'product_name' product_name,extra->>'collection' collection,
             extra->>'qty' qty,extra->>'cart_value_cents' cart_value_cents,extra->>'order_id' order_id,
             extra->>'utm_source' utm_source,extra->>'utm_campaign' utm_campaign,referrer_url
      from events order by created_at desc limit 250
    ) x
  ),'[]'::jsonb),
  'order_economics',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',oe.id,'status',oe.status,'created_at',oe.created_at,'payment_verified_at',oe.payment_verified_at,
      'submitted_to_fulfillment_at',oe.submitted_to_printify_at,'shipped_at',oe.shipped_at,'subtotal_cents',oe.subtotal_cents,
      'shipping_revenue_cents',oe.shipping_cents,'total_cents',oe.total_cents,'cash_received_cents',oe.paid_amount_cents,
      'units',oe.units,'known_product_cost_cents',oe.known_product_cost_cents,'missing_cost_units',oe.missing_cost_units,
      'import_allowance_cents',oe.fulfillment_estimated_import_cents,'supplier_shipping_cost_cents',oe.supplier_shipping_cost_cents,
      'known_expected_contribution_cents',
        case when oe.missing_cost_units=0 and (oe.shipping_cents=0 or oe.supplier_shipping_cost_cents is not null)
             then oe.total_cents-oe.known_product_cost_cents-oe.fulfillment_estimated_import_cents-coalesce(oe.supplier_shipping_cost_cents,0)
             else null end
    ) order by oe.created_at desc)
    from order_econ oe
  ),'[]'::jsonb)
);
$function$


revoke all on function public.shop_admin_analytics_snapshot_v841(timestamptz,timestamptz) from public, anon, authenticated;
grant execute on function public.shop_admin_analytics_snapshot_v841(timestamptz,timestamptz) to service_role;
comment on table public.shop_finance_ledger_v841 is 'Private Bruis shop non-order finance ledger for analytics v841. Browser roles have no direct access.';
comment on table public.shop_product_cost_cache_v841 is 'Private admin-only current catalog production-cost snapshot for shop analytics v841.';
comment on function public.shop_admin_analytics_snapshot_v841(timestamptz,timestamptz) is 'Service-role-only aggregated shop analytics snapshot for protected v841 admin API.';
commit;
