
begin;

create table if not exists public.player_profiles (
  player_id bigint primary key references public.players(id) on delete cascade,
  nickname text,
  profile_picture_url text,
  favorite_game text,
  bio text,
  updated_at timestamptz not null default now()
);

create table if not exists public.invite_links (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  note text,
  created_by_admin_username text,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  opened_count integer not null default 0,
  last_opened_at timestamptz,
  revoked_at timestamptz
);

create table if not exists public.game_match_summaries (
  id bigint generated by default as identity primary key,
  game_type text not null,
  client_match_id text not null,
  created_at timestamptz not null default now(),
  finished_at timestamptz,
  created_by_player_id bigint references public.players(id) on delete set null,
  winner_names text[] not null default '{}',
  participant_names text[] not null default '{}',
  recap_text text,
  summary_payload jsonb not null default '{}'::jsonb,
  unique (game_type, client_match_id)
);

create index if not exists game_match_summaries_game_type_idx on public.game_match_summaries(game_type);
create index if not exists game_match_summaries_finished_at_idx on public.game_match_summaries(finished_at desc);

create or replace function public._hash_invite_token(raw_token text)
returns text language sql immutable as $$
  select encode(extensions.digest(coalesce(raw_token,''), 'sha256'),'hex')
$$;

create or replace function public.admin_create_invite_link_action(
  admin_session_token text,
  note_input text default null,
  expires_hours integer default 168,
  base_url text default null
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_session jsonb;
  v_username text;
  v_token text;
  v_hash text;
  v_url text;
  v_expires_at timestamptz := now() + make_interval(hours => greatest(1, least(coalesce(expires_hours,168), 24*90)));
begin
  v_session := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_session->>'ok')::boolean, false) is not true then
    raise exception 'Log opnieuw in als admin.';
  end if;
  v_username := coalesce(nullif(trim(v_session->>'admin_username'),''), nullif(trim(v_session->>'username'),''), 'admin');
  v_token := encode(extensions.gen_random_bytes(18), 'hex');
  v_hash := public._hash_invite_token(v_token);
  insert into public.invite_links(token_hash, note, created_by_admin_username, expires_at)
  values (v_hash, nullif(trim(coalesce(note_input,'')),''), v_username, v_expires_at);
  v_url := coalesce(nullif(trim(coalesce(base_url,'')),''), 'https://kalenel.nl/invite.html') || '?token=' || v_token;
  return jsonb_build_object('ok', true, 'invite_token', v_token, 'invite_url', v_url, 'expires_at', v_expires_at);
end;
$fn$;

create or replace function public.public_get_invite_link_info(token_input text)
returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_row public.invite_links%rowtype;
  v_hash text := public._hash_invite_token(token_input);
begin
  select * into v_row from public.invite_links i where i.token_hash = v_hash and i.revoked_at is null limit 1;
  if not found then raise exception 'Uitnodigingslink niet gevonden.'; end if;
  if v_row.expires_at is not null and v_row.expires_at < now() then raise exception 'Uitnodigingslink is verlopen.'; end if;
  update public.invite_links set opened_count = opened_count + 1, last_opened_at = now() where id = v_row.id;
  return jsonb_build_object('ok', true, 'note', v_row.note, 'expires_at', v_row.expires_at, 'expires_at_label', to_char(v_row.expires_at at time zone 'Europe/Amsterdam', 'DD-MM-YYYY HH24:MI'));
end;
$fn$;

create or replace function public.save_game_match_summary(
  session_token text default null,
  game_type text default null,
  client_match_id text default null,
  summary_payload jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_player public.players%rowtype;
  v_game_type text := lower(trim(coalesce(game_type,'')));
  v_client_match_id text := nullif(trim(coalesce(client_match_id,'')), '');
  v_winner_names text[] := coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(summary_payload->'winner_names','[]'::jsonb))), '{}'::text[]);
  v_participants text[] := coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(summary_payload->'participants','[]'::jsonb))), '{}'::text[]);
  v_finished_at timestamptz := nullif(summary_payload->>'finished_at','')::timestamptz;
begin
  if v_game_type not in ('klaverjas','boerenbridge') then raise exception 'game_type ongeldig'; end if;
  if v_client_match_id is null then raise exception 'client_match_id ontbreekt'; end if;
  begin
    if nullif(trim(coalesce(session_token,'')), '') is not null then
      select * into v_player from public._gejast_player_from_session(session_token);
    end if;
  exception when others then
    null;
  end;
  insert into public.game_match_summaries(game_type, client_match_id, finished_at, created_by_player_id, winner_names, participant_names, recap_text, summary_payload)
  values (v_game_type, v_client_match_id, v_finished_at, v_player.id, v_winner_names, v_participants, nullif(trim(coalesce(summary_payload->>'recap_text','')), ''), coalesce(summary_payload, '{}'::jsonb))
  on conflict (game_type, client_match_id)
  do update set finished_at = excluded.finished_at, created_by_player_id = coalesce(excluded.created_by_player_id, public.game_match_summaries.created_by_player_id), winner_names = excluded.winner_names, participant_names = excluded.participant_names, recap_text = excluded.recap_text, summary_payload = excluded.summary_payload;
  return jsonb_build_object('ok', true);
end;
$fn$;

create or replace function public.get_player_profiles_public()
returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
begin
  return jsonb_build_object('profiles', coalesce((
    with vote_stats as (
      select p.id as player_id,
             count(*) filter (where gv.desired_status='ja')::int as vote_yes_count,
             count(*) filter (where gv.desired_status='nee')::int as vote_no_count,
             count(*)::int as vote_total,
             coalesce(round((100.0 * count(*) filter (where gv.desired_status='ja')) / nullif(count(*),0),1),0) as reliability_score
      from public.players p
      left join public.gejast_weekly_votes gv on gv.player_id = p.id
      group by p.id
    ), yes_runs as (
      select t.player_id, max(t.streak)::int as max_yes_streak
      from (
        select gv.player_id,
               count(*) filter (where gv.desired_status='ja') over (partition by gv.player_id, grp) as streak
        from (
          select gv.*, row_number() over(partition by gv.player_id order by gv.cycle_key) - row_number() over(partition by gv.player_id, (gv.desired_status='ja') order by gv.cycle_key) as grp
          from public.gejast_weekly_votes gv
        ) gv
        where gv.desired_status='ja'
      ) t group by t.player_id
    ), current_yes as (
      select s.player_id, count(*)::int as current_yes_streak
      from (
        select gv.player_id, gv.desired_status, gv.cycle_key,
               row_number() over(partition by gv.player_id order by gv.cycle_key desc) as rn
        from public.gejast_weekly_votes gv
      ) s
      where s.desired_status='ja' and not exists (
        select 1 from public.gejast_weekly_votes later
        where later.player_id=s.player_id and later.cycle_key>s.cycle_key and later.desired_status<>'ja'
      )
      group by s.player_id
    ), match_stats as (
      select p.id as player_id,
             count(distinct g.id)::int as total_matches,
             count(distinct g.id) filter (where lower(p.display_name)=any(select lower(x) from unnest(g.winner_names) x))::int as wins
      from public.players p
      left join public.game_match_summaries g on exists (select 1 from unnest(g.participant_names) n where lower(n)=lower(p.display_name))
      group by p.id
    )
    select jsonb_agg(jsonb_build_object(
      'player_id', p.id,
      'display_name', p.display_name,
      'nickname', pp.nickname,
      'profile_picture_url', pp.profile_picture_url,
      'favorite_game', pp.favorite_game,
      'bio', pp.bio,
      'vote_yes_count', coalesce(vs.vote_yes_count,0),
      'vote_no_count', coalesce(vs.vote_no_count,0),
      'reliability_score', coalesce(vs.reliability_score,0),
      'current_yes_streak', coalesce(cy.current_yes_streak,0),
      'max_yes_streak', coalesce(yr.max_yes_streak,0),
      'total_matches', coalesce(ms.total_matches,0),
      'wins', coalesce(ms.wins,0),
      'achievements_count', ((case when coalesce(vs.reliability_score,0)>=90 then 1 else 0 end) + (case when coalesce(cy.current_yes_streak,0)>=3 then 1 else 0 end) + (case when coalesce(ms.total_matches,0)>=10 then 1 else 0 end) + (case when coalesce(ms.wins,0)>=5 then 1 else 0 end))
    ) order by lower(p.display_name)), '[]'::jsonb)
    from public.players p
    left join public.player_profiles pp on pp.player_id = p.id
    left join vote_stats vs on vs.player_id = p.id
    left join yes_runs yr on yr.player_id = p.id
    left join current_yes cy on cy.player_id = p.id
    left join match_stats ms on ms.player_id = p.id
    where coalesce(p.active, false) is true
  ), '[]'::jsonb));
end;
$fn$;

grant execute on function public.admin_create_invite_link_action(text, text, integer, text) to anon, authenticated;
grant execute on function public.public_get_invite_link_info(text) to anon, authenticated;
grant execute on function public.save_game_match_summary(text, text, text, jsonb) to anon, authenticated;
grant execute on function public.get_player_profiles_public() to anon, authenticated;

commit;
