-- v847 operational hardening for Bruis shop/admin.
-- No refund/chargeback workflow is introduced.

create table if not exists public.shop_ops_settings_v847 (
  id smallint primary key default 1 check (id = 1),
  owner_email text null,
  email_alerts_enabled boolean not null default false,
  daily_brief_enabled boolean not null default true,
  weekly_brief_enabled boolean not null default true,
  paid_not_submitted_hours integer not null default 2 check (paid_not_submitted_hours between 1 and 168),
  production_stuck_days integer not null default 7 check (production_stuck_days between 1 and 60),
  telemetry_stale_hours integer not null default 12 check (telemetry_stale_hours between 1 and 168),
  cost_change_alert_cents integer not null default 100 check (cost_change_alert_cents between 1 and 100000),
  low_margin_bps integer not null default 2000 check (low_margin_bps between 0 and 10000),
  backup_retention_days integer not null default 90 check (backup_retention_days between 7 and 730),
  updated_at timestamptz not null default now()
);
insert into public.shop_ops_settings_v847(id) values (1) on conflict (id) do nothing;
alter table public.shop_ops_settings_v847 enable row level security;
revoke all on table public.shop_ops_settings_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_ops_settings_v847 to service_role;

create table if not exists public.shop_ops_state_v847 (
  id smallint primary key default 1 check (id = 1),
  catalog_baseline jsonb null,
  catalog_hash text null,
  last_cost_refresh_at timestamptz null,
  last_catalog_check_at timestamptz null,
  last_order_check_at timestamptz null,
  last_backup_at timestamptz null,
  last_daily_brief_date date null,
  last_weekly_brief_key text null,
  last_run_at timestamptz null,
  last_error text null,
  updated_at timestamptz not null default now()
);
insert into public.shop_ops_state_v847(id) values (1) on conflict (id) do nothing;
alter table public.shop_ops_state_v847 enable row level security;
revoke all on table public.shop_ops_state_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_ops_state_v847 to service_role;

create table if not exists public.shop_alerts_v847 (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  kind text not null,
  severity text not null check (severity in ('info','medium','high')),
  title text not null check (char_length(title) between 1 and 200),
  message text not null check (char_length(message) between 1 and 4000),
  entity_type text null,
  entity_id text null,
  dedupe_key text not null,
  metadata jsonb not null default '{}'::jsonb,
  acknowledged_at timestamptz null,
  resolved_at timestamptz null,
  notified_at timestamptz null
);
create unique index if not exists shop_alerts_v847_open_dedupe_idx on public.shop_alerts_v847(dedupe_key) where resolved_at is null;
create index if not exists shop_alerts_v847_created_idx on public.shop_alerts_v847(created_at desc);
alter table public.shop_alerts_v847 enable row level security;
revoke all on table public.shop_alerts_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_alerts_v847 to service_role;
grant usage,select on sequence public.shop_alerts_v847_id_seq to service_role;

create table if not exists public.shop_catalog_drift_v847 (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  kind text not null,
  severity text not null check (severity in ('info','medium','high')),
  product_id text null,
  variant_id text null,
  product_name text null,
  previous_value jsonb null,
  current_value jsonb null,
  dedupe_key text not null,
  resolved_at timestamptz null
);
create index if not exists shop_catalog_drift_v847_observed_idx on public.shop_catalog_drift_v847(observed_at desc);
alter table public.shop_catalog_drift_v847 enable row level security;
revoke all on table public.shop_catalog_drift_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_catalog_drift_v847 to service_role;
grant usage,select on sequence public.shop_catalog_drift_v847_id_seq to service_role;

create table if not exists public.shop_backup_snapshots_v847 (
  id uuid primary key default extensions.gen_random_uuid(),
  created_at timestamptz not null default now(),
  reason text not null default 'scheduled',
  schema_version integer not null default 847,
  counts jsonb not null default '{}'::jsonb,
  payload jsonb not null,
  payload_sha256 text not null
);
create index if not exists shop_backup_snapshots_v847_created_idx on public.shop_backup_snapshots_v847(created_at desc);
alter table public.shop_backup_snapshots_v847 enable row level security;
revoke all on table public.shop_backup_snapshots_v847 from public, anon, authenticated;
grant select,insert,delete on table public.shop_backup_snapshots_v847 to service_role;

create table if not exists public.shop_owner_briefs_v847 (
  id bigint generated by default as identity primary key,
  period_type text not null check (period_type in ('daily','weekly')),
  period_key text not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  generated_at timestamptz not null default now(),
  summary jsonb not null,
  email_sent_at timestamptz null,
  email_error text null,
  unique(period_type,period_key)
);
alter table public.shop_owner_briefs_v847 enable row level security;
revoke all on table public.shop_owner_briefs_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_owner_briefs_v847 to service_role;
grant usage,select on sequence public.shop_owner_briefs_v847_id_seq to service_role;

create table if not exists public.shop_payment_fee_rules_v847 (
  id bigint generated by default as identity primary key,
  provider text not null unique,
  enabled boolean not null default false,
  rate_bps integer not null default 0 check (rate_bps between 0 and 10000),
  fixed_fee_cents integer not null default 0 check (fixed_fee_cents between 0 and 100000),
  note text null,
  updated_at timestamptz not null default now()
);
insert into public.shop_payment_fee_rules_v847(provider,enabled,rate_bps,fixed_fee_cents,note)
values
  ('bunq_me',false,0,0,'Configure only from an authoritative provider fee schedule.'),
  ('tikkie',false,0,0,'Configure only from an authoritative provider fee schedule.'),
  ('manual_transfer',false,0,0,'Normally zero, but remains disabled until explicitly confirmed.')
on conflict(provider) do nothing;
alter table public.shop_payment_fee_rules_v847 enable row level security;
revoke all on table public.shop_payment_fee_rules_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_payment_fee_rules_v847 to service_role;
grant usage,select on sequence public.shop_payment_fee_rules_v847_id_seq to service_role;

create table if not exists public.shop_tax_invoice_settings_v847 (
  id smallint primary key default 1 check (id = 1),
  invoicing_enabled boolean not null default true,
  tax_calculation_enabled boolean not null default false,
  invoice_prefix text not null default 'BRUIS',
  default_vat_rate_bps integer null check (default_vat_rate_bps is null or default_vat_rate_bps between 0 and 10000),
  seller_name text not null default 'Bruis',
  seller_address text null,
  seller_postal_city text null,
  seller_country text null default 'NL',
  vat_number text null,
  kvk_number text null,
  invoice_note text null,
  updated_at timestamptz not null default now()
);
insert into public.shop_tax_invoice_settings_v847(id) values(1) on conflict(id) do nothing;
alter table public.shop_tax_invoice_settings_v847 enable row level security;
revoke all on table public.shop_tax_invoice_settings_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_tax_invoice_settings_v847 to service_role;

create sequence if not exists public.shop_invoice_number_v847_seq;

create table if not exists public.shop_invoices_v847 (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  order_id uuid not null unique references public.shop_orders(id) on delete restrict,
  issued_at timestamptz not null default now(),
  currency text not null default 'eur',
  gross_total_cents integer not null check (gross_total_cents >= 0),
  net_total_cents integer null check (net_total_cents is null or net_total_cents >= 0),
  vat_total_cents integer null check (vat_total_cents is null or vat_total_cents >= 0),
  vat_rate_bps integer null,
  tax_status text not null default 'unconfigured' check (tax_status in ('unconfigured','configured','exempt','reverse_charge','out_of_scope')),
  customer jsonb not null,
  line_items jsonb not null,
  seller jsonb not null,
  note text null,
  created_at timestamptz not null default now()
);
create index if not exists shop_invoices_v847_issued_idx on public.shop_invoices_v847(issued_at desc);
alter table public.shop_invoices_v847 enable row level security;
revoke all on table public.shop_invoices_v847 from public, anon, authenticated;
grant select,insert,update,delete on table public.shop_invoices_v847 to service_role;
grant usage,select on sequence public.shop_invoices_v847_id_seq to service_role;
grant usage,select on sequence public.shop_invoice_number_v847_seq to service_role;

alter table public.shop_orders
  add column if not exists payment_fee_cents integer null check (payment_fee_cents is null or payment_fee_cents >= 0),
  add column if not exists payment_fee_source text null,
  add column if not exists payment_fee_rule_id bigint null references public.shop_payment_fee_rules_v847(id) on delete set null,
  add column if not exists invoice_number text null;

create or replace function public.shop_apply_payment_fee_v847(order_id_input uuid, admin_id_input bigint default null)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare o public.shop_orders%rowtype; r public.shop_payment_fee_rules_v847%rowtype; base_cents integer; fee_cents integer; ledger_id bigint;
begin
  select * into o from public.shop_orders where id=order_id_input;
  if not found then return jsonb_build_object('ok',false,'error','order_not_found'); end if;
  select * into r from public.shop_payment_fee_rules_v847 where provider=coalesce(o.payment_provider,'manual_transfer') and enabled=true limit 1;
  if not found then return jsonb_build_object('ok',true,'configured',false,'payment_fee_cents',o.payment_fee_cents); end if;
  base_cents:=coalesce(o.paid_amount_cents,o.total_cents,0);
  fee_cents:=greatest(0,round(base_cents*r.rate_bps::numeric/10000)::integer+r.fixed_fee_cents);
  update public.shop_orders set payment_fee_cents=fee_cents,payment_fee_source='configured_rule',payment_fee_rule_id=r.id,updated_at=now() where id=o.id;
  select id into ledger_id from public.shop_finance_ledger_v841 where order_id=o.id and direction='cost' and category='payment_fee' order by id desc limit 1;
  if ledger_id is null and fee_cents>0 then
    insert into public.shop_finance_ledger_v841(occurred_on,direction,category,amount_cents,currency,order_id,note,created_by_admin_id,updated_at)
    values((coalesce(o.payment_verified_at,o.paid_at,now()) at time zone 'Europe/Amsterdam')::date,'cost','payment_fee',fee_cents,'eur',o.id,'Automatically calculated from configured payment-provider fee rule.',admin_id_input,now())
    returning id into ledger_id;
  end if;
  return jsonb_build_object('ok',true,'configured',true,'provider',r.provider,'payment_fee_cents',fee_cents,'ledger_id',ledger_id,'rule_id',r.id);
end;$function$;

create or replace function public.shop_issue_invoice_v847(order_id_input uuid)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare o public.shop_orders%rowtype; s public.shop_tax_invoice_settings_v847%rowtype; existing public.shop_invoices_v847%rowtype; seq_no bigint; invoice_no text; vat_cents integer; net_cents integer; status text:='unconfigured'; new_id bigint;
begin
  select * into existing from public.shop_invoices_v847 where order_id=order_id_input;
  if found then return jsonb_build_object('ok',true,'existing',true,'invoice_number',existing.invoice_number,'invoice_id',existing.id,'tax_status',existing.tax_status); end if;
  select * into o from public.shop_orders where id=order_id_input;
  if not found then return jsonb_build_object('ok',false,'error','order_not_found'); end if;
  if o.payment_verified_at is null then return jsonb_build_object('ok',false,'error','payment_not_verified'); end if;
  select * into s from public.shop_tax_invoice_settings_v847 where id=1;
  if not found or s.invoicing_enabled is not true then return jsonb_build_object('ok',true,'skipped',true,'reason','invoicing_disabled'); end if;
  if s.tax_calculation_enabled and s.default_vat_rate_bps is not null then
    vat_cents:=round(coalesce(o.total_cents,0)*s.default_vat_rate_bps::numeric/(10000+s.default_vat_rate_bps))::integer;
    net_cents:=coalesce(o.total_cents,0)-vat_cents; status:='configured';
  else vat_cents:=null; net_cents:=null; status:='unconfigured'; end if;
  seq_no:=nextval('public.shop_invoice_number_v847_seq');
  invoice_no:=regexp_replace(coalesce(s.invoice_prefix,'BRUIS'),'[^A-Za-z0-9_-]','','g')||'-'||to_char(now() at time zone 'Europe/Amsterdam','YYYY')||'-'||lpad(seq_no::text,6,'0');
  insert into public.shop_invoices_v847(invoice_number,order_id,issued_at,currency,gross_total_cents,net_total_cents,vat_total_cents,vat_rate_bps,tax_status,customer,line_items,seller,note)
  values(invoice_no,o.id,now(),coalesce(o.currency,'eur'),coalesce(o.total_cents,0),net_cents,vat_cents,case when status='configured' then s.default_vat_rate_bps else null end,status,
    jsonb_build_object('name',o.customer_name,'email',o.customer_email,'phone',o.customer_phone,'shipping_address',o.shipping_address),
    coalesce(o.line_items,'[]'::jsonb),
    jsonb_build_object('name',s.seller_name,'address',s.seller_address,'postal_city',s.seller_postal_city,'country',s.seller_country,'vat_number',s.vat_number,'kvk_number',s.kvk_number),
    s.invoice_note) returning id into new_id;
  update public.shop_orders set invoice_number=invoice_no,updated_at=now() where id=o.id;
  return jsonb_build_object('ok',true,'existing',false,'invoice_number',invoice_no,'invoice_id',new_id,'tax_status',status);
end;$function$;

revoke all on function public.shop_apply_payment_fee_v847(uuid,bigint) from public,anon,authenticated;
grant execute on function public.shop_apply_payment_fee_v847(uuid,bigint) to service_role;
revoke all on function public.shop_issue_invoice_v847(uuid) from public,anon,authenticated;
grant execute on function public.shop_issue_invoice_v847(uuid) to service_role;

create or replace function public.admin_list_security_v847(admin_session_token_input text)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare sess record; current_hash text; current_id bigint; sessions_json jsonb; devices_json jsonb;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token_input);
  if coalesce(sess.ok,false) is not true then return jsonb_build_object('ok',false,'error','invalid_admin_session'); end if;
  current_hash:=public._hash_session_token(admin_session_token_input);
  select id into current_id from public.admin_sessions where token_hash=current_hash and expires_at>now() limit 1;
  select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'created_at',s.created_at,'last_used_at',s.last_used_at,'expires_at',s.expires_at,'is_current',(s.id=current_id)) order by s.last_used_at desc nulls last),'[]'::jsonb)
  into sessions_json from public.admin_sessions s where s.admin_id=sess.admin_id and s.expires_at>now();
  select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'device_label',d.device_label,'trusted_at',d.trusted_at,'last_seen_at',d.last_seen_at,'expires_at',d.expires_at,'revoked_at',d.revoked_at,'active',(d.revoked_at is null and d.expires_at>now())) order by d.last_seen_at desc nulls last),'[]'::jsonb)
  into devices_json from public.admin_trusted_devices d where lower(d.admin_username)=lower(sess.username);
  return jsonb_build_object('ok',true,'admin_username',sess.username,'current_session_id',current_id,'sessions',sessions_json,'devices',devices_json);
end;$function$;

create or replace function public.admin_revoke_trusted_device_v847(admin_session_token_input text,device_id_input bigint)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare sess record;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token_input);
  if coalesce(sess.ok,false) is not true then return jsonb_build_object('ok',false,'error','invalid_admin_session'); end if;
  update public.admin_trusted_devices set revoked_at=coalesce(revoked_at,now()),last_seen_at=now() where id=device_id_input and lower(admin_username)=lower(sess.username);
  return jsonb_build_object('ok',true);
end;$function$;

create or replace function public.admin_revoke_session_v847(admin_session_token_input text,session_id_input bigint)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare sess record; current_hash text; current_id bigint;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token_input);
  if coalesce(sess.ok,false) is not true then return jsonb_build_object('ok',false,'error','invalid_admin_session'); end if;
  current_hash:=public._hash_session_token(admin_session_token_input);
  select id into current_id from public.admin_sessions where token_hash=current_hash and expires_at>now() limit 1;
  if session_id_input=current_id then return jsonb_build_object('ok',false,'error','cannot_revoke_current_session_here'); end if;
  delete from public.admin_sessions where id=session_id_input and admin_id=sess.admin_id;
  return jsonb_build_object('ok',true);
end;$function$;

create or replace function public.admin_revoke_other_sessions_v847(admin_session_token_input text)
returns jsonb language plpgsql security definer set search_path='public'
as $function$
declare sess record; current_hash text; deleted_count integer;
begin
  select * into sess from public._require_valid_admin_session(admin_session_token_input);
  if coalesce(sess.ok,false) is not true then return jsonb_build_object('ok',false,'error','invalid_admin_session'); end if;
  current_hash:=public._hash_session_token(admin_session_token_input);
  delete from public.admin_sessions where admin_id=sess.admin_id and token_hash<>current_hash;
  get diagnostics deleted_count=row_count;
  return jsonb_build_object('ok',true,'revoked_sessions',deleted_count);
end;$function$;

revoke all on function public.admin_list_security_v847(text) from public;
revoke all on function public.admin_revoke_trusted_device_v847(text,bigint) from public;
revoke all on function public.admin_revoke_session_v847(text,bigint) from public;
revoke all on function public.admin_revoke_other_sessions_v847(text) from public;
grant execute on function public.admin_list_security_v847(text) to anon,authenticated;
grant execute on function public.admin_revoke_trusted_device_v847(text,bigint) to anon,authenticated;
grant execute on function public.admin_revoke_session_v847(text,bigint) to anon,authenticated;
grant execute on function public.admin_revoke_other_sessions_v847(text) to anon,authenticated;
