-- v842 shop-admin security and intelligence hardening.
-- Production-applied 2026-09-20.

alter table public.site_visitors enable row level security;
alter table public.site_visit_sessions enable row level security;
alter table public.site_visitor_events enable row level security;

revoke all on table public.site_visitors from anon, authenticated;
revoke all on table public.site_visit_sessions from anon, authenticated;
revoke all on table public.site_visitor_events from anon, authenticated;

create table if not exists public.shop_admin_audit_v842 (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  admin_id bigint null references public.admin_accounts(id) on delete set null,
  admin_username text null,
  surface text not null,
  action text not null,
  object_type text null,
  object_id text null,
  success boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  constraint shop_admin_audit_v842_surface_len check (char_length(surface) between 1 and 80),
  constraint shop_admin_audit_v842_action_len check (char_length(action) between 1 and 120),
  constraint shop_admin_audit_v842_object_type_len check (object_type is null or char_length(object_type) <= 80),
  constraint shop_admin_audit_v842_object_id_len check (object_id is null or char_length(object_id) <= 200),
  constraint shop_admin_audit_v842_username_len check (admin_username is null or char_length(admin_username) <= 160)
);

alter table public.shop_admin_audit_v842 enable row level security;
revoke all on table public.shop_admin_audit_v842 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_admin_audit_v842 to service_role;
grant usage, select on sequence public.shop_admin_audit_v842_id_seq to service_role;

create index if not exists shop_admin_audit_v842_occurred_idx
  on public.shop_admin_audit_v842 (occurred_at desc);
create index if not exists shop_admin_audit_v842_admin_idx
  on public.shop_admin_audit_v842 (admin_id, occurred_at desc);
create index if not exists shop_admin_audit_v842_action_idx
  on public.shop_admin_audit_v842 (surface, action, occurred_at desc);
