begin;

create extension if not exists pgcrypto;

alter table if exists public.jas_games add column if not exists updated_at timestamptz not null default now();
alter table if exists public.jas_games add column if not exists deleted_at timestamptz;
alter table if exists public.beerpong_matches add column if not exists deleted_at timestamptz;
alter table if exists public.boerenbridge_matches add column if not exists deleted_at timestamptz;

create table if not exists public.match_change_log (
  id bigint generated by default as identity primary key,
  game_type text not null,
  match_ref text not null,
  change_type text not null,
  changed_by_role text not null,
  changed_by_name text,
  changed_at timestamptz not null default now(),
  reason text,
  before_payload jsonb,
  after_payload jsonb
);

create table if not exists public.game_rating_rebuild_queue (
  id bigint generated by default as identity primary key,
  game_type text not null,
  reason text,
  match_ref text,
  requested_by_role text,
  requested_by_name text,
  requested_at timestamptz not null default now(),
  status text not null default 'pending',
  processed_at timestamptz,
  last_error text
);
create index if not exists game_rating_rebuild_queue_status_idx on public.game_rating_rebuild_queue(status, requested_at);

create table if not exists public.klaverjas_player_ratings (
  player_name text primary key,
  elo_rating numeric not null default 1000,
  games_played integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  draws integer not null default 0,
  last_match_at timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists public.klaverjas_player_rating_history (
  id bigint generated by default as identity primary key,
  game_id bigint references public.jas_games(id) on delete cascade,
  player_name text not null,
  rating_before numeric not null default 1000,
  rating_after numeric not null default 1000,
  created_at timestamptz not null default now()
);
create index if not exists klaverjas_player_rating_history_player_idx on public.klaverjas_player_rating_history(lower(player_name), created_at desc);

create table if not exists public.boerenbridge_player_ratings (
  player_name text primary key,
  elo_rating numeric not null default 1000,
  games_played integer not null default 0,
  wins integer not null default 0,
  podium_finishes integer not null default 0,
  top_half_finishes integer not null default 0,
  total_points integer not null default 0,
  total_exact_bids integer not null default 0,
  total_slagen integer not null default 0,
  last_match_at timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists public.boerenbridge_player_rating_history (
  id bigint generated by default as identity primary key,
  match_id bigint references public.boerenbridge_matches(id) on delete cascade,
  player_name text not null,
  rating_before numeric not null default 1000,
  rating_after numeric not null default 1000,
  created_at timestamptz not null default now()
);
create index if not exists boerenbridge_player_rating_history_player_idx on public.boerenbridge_player_rating_history(lower(player_name), created_at desc);

create or replace function public._elo_expected(rating_a numeric, rating_b numeric)
returns numeric language sql immutable as $$
  select 1.0 / (1.0 + power(10.0, (coalesce(rating_b,1000) - coalesce(rating_a,1000)) / 400.0));
$$;

create or replace function public._enqueue_rating_rebuild(
  p_game_type text,
  p_reason text default null,
  p_match_ref text default null,
  p_requested_by_role text default null,
  p_requested_by_name text default null
) returns void
language plpgsql security definer set search_path to 'public' as $fn$
begin
  insert into public.game_rating_rebuild_queue(game_type, reason, match_ref, requested_by_role, requested_by_name)
  values (lower(trim(coalesce(p_game_type,''))), p_reason, p_match_ref, p_requested_by_role, p_requested_by_name);
end;
$fn$;

create or replace function public.rebuild_beerpong_ratings()
returns void language plpgsql security definer set search_path to 'public' as $fn$
declare
  m record;
  a_players text[];
  b_players text[];
  team_a_avg numeric;
  team_b_avg numeric;
  expected_a numeric;
  actual_a numeric;
  k_factor numeric := 28.0;
  margin_factor numeric;
  delta_total numeric;
  p text;
  before_rating numeric;
  after_rating numeric;
  ts timestamptz;
  winner_a boolean;
begin
  truncate table public.beerpong_player_rating_history restart identity;
  delete from public.beerpong_player_ratings;

  for m in
    select *
    from public.beerpong_matches
    where coalesce(deleted_at is null, true)
    order by coalesce(finished_at, created_at), id
  loop
    a_players := coalesce(m.team_a_player_names, '{}'::text[]);
    b_players := coalesce(m.team_b_player_names, '{}'::text[]);
    if coalesce(array_length(a_players,1),0) = 0 or coalesce(array_length(b_players,1),0) = 0 then
      continue;
    end if;
    ts := coalesce(m.finished_at, m.created_at, now());
    winner_a := lower(coalesce(m.winner_team,'')) in ('a','team_a');

    foreach p in array a_players loop
      insert into public.beerpong_player_ratings(player_name) values (p) on conflict (player_name) do nothing;
    end loop;
    foreach p in array b_players loop
      insert into public.beerpong_player_ratings(player_name) values (p) on conflict (player_name) do nothing;
    end loop;

    select avg(elo_rating) into team_a_avg from public.beerpong_player_ratings where player_name = any(a_players);
    select avg(elo_rating) into team_b_avg from public.beerpong_player_ratings where player_name = any(b_players);
    expected_a := public._elo_expected(team_a_avg, team_b_avg);
    actual_a := case when winner_a then 1 else 0 end;
    margin_factor := least(1.25, greatest(1.0, 1.0 + abs(coalesce(m.team_a_cups_left,0) - coalesce(m.team_b_cups_left,0))::numeric / 20.0));
    delta_total := k_factor * margin_factor * (actual_a - expected_a);

    foreach p in array a_players loop
      select elo_rating into before_rating from public.beerpong_player_ratings where player_name = p;
      update public.beerpong_player_ratings
         set elo_rating = elo_rating + (delta_total / greatest(coalesce(array_length(a_players,1),1),1)),
             games_played = games_played + 1,
             wins = wins + case when winner_a then 1 else 0 end,
             losses = losses + case when not winner_a then 1 else 0 end,
             last_match_at = ts,
             updated_at = now()
       where player_name = p;
      select elo_rating into after_rating from public.beerpong_player_ratings where player_name = p;
      insert into public.beerpong_player_rating_history(match_id, player_name, rating_before, rating_after, created_at)
      values (m.id, p, coalesce(before_rating,1000), coalesce(after_rating,1000), ts);
    end loop;

    foreach p in array b_players loop
      select elo_rating into before_rating from public.beerpong_player_ratings where player_name = p;
      update public.beerpong_player_ratings
         set elo_rating = elo_rating - (delta_total / greatest(coalesce(array_length(b_players,1),1),1)),
             games_played = games_played + 1,
             wins = wins + case when not winner_a then 1 else 0 end,
             losses = losses + case when winner_a then 1 else 0 end,
             last_match_at = ts,
             updated_at = now()
       where player_name = p;
      select elo_rating into after_rating from public.beerpong_player_ratings where player_name = p;
      insert into public.beerpong_player_rating_history(match_id, player_name, rating_before, rating_after, created_at)
      values (m.id, p, coalesce(before_rating,1000), coalesce(after_rating,1000), ts);
    end loop;
  end loop;
end;
$fn$;

create or replace function public.rebuild_klaverjas_ratings()
returns void language plpgsql security definer set search_path to 'public' as $fn$
declare
  g record;
  team1_players text[];
  team2_players text[];
  team1_points integer;
  team2_points integer;
  team1_avg numeric;
  team2_avg numeric;
  expected_1 numeric;
  actual_1 numeric;
  k_factor numeric := 30.0;
  margin_factor numeric;
  delta_total numeric;
  p text;
  before_rating numeric;
  after_rating numeric;
  ts timestamptz;
begin
  truncate table public.klaverjas_player_rating_history restart identity;
  delete from public.klaverjas_player_ratings;

  for g in
    with per_game as (
      select
        j.id,
        j.played_at,
        j.created_at,
        array_agg(e.display_name order by e.seat_no) filter (where e.team_no = 1) as team1_players,
        array_agg(e.display_name order by e.seat_no) filter (where e.team_no = 2) as team2_players,
        max(e.total_points) filter (where e.team_no = 1) as team1_points,
        max(e.total_points) filter (where e.team_no = 2) as team2_points
      from public.jas_games j
      join public.jas_game_entries e on e.game_id = j.id
      where j.deleted_at is null
      group by j.id, j.played_at, j.created_at
    )
    select * from per_game order by played_at, created_at, id
  loop
    team1_players := coalesce(g.team1_players, '{}'::text[]);
    team2_players := coalesce(g.team2_players, '{}'::text[]);
    if coalesce(array_length(team1_players,1),0)=0 or coalesce(array_length(team2_players,1),0)=0 then
      continue;
    end if;
    ts := coalesce(g.created_at, now());
    foreach p in array team1_players loop insert into public.klaverjas_player_ratings(player_name) values (p) on conflict (player_name) do nothing; end loop;
    foreach p in array team2_players loop insert into public.klaverjas_player_ratings(player_name) values (p) on conflict (player_name) do nothing; end loop;
    select avg(elo_rating) into team1_avg from public.klaverjas_player_ratings where player_name = any(team1_players);
    select avg(elo_rating) into team2_avg from public.klaverjas_player_ratings where player_name = any(team2_players);
    expected_1 := public._elo_expected(team1_avg, team2_avg);
    actual_1 := case when coalesce(g.team1_points,0) > coalesce(g.team2_points,0) then 1 when coalesce(g.team1_points,0) < coalesce(g.team2_points,0) then 0 else 0.5 end;
    margin_factor := least(1.5, greatest(1.0, 1.0 + abs(coalesce(g.team1_points,0) - coalesce(g.team2_points,0))::numeric / 600.0));
    delta_total := k_factor * margin_factor * (actual_1 - expected_1);

    foreach p in array team1_players loop
      select elo_rating into before_rating from public.klaverjas_player_ratings where player_name = p;
      update public.klaverjas_player_ratings
         set elo_rating = elo_rating + (delta_total / greatest(coalesce(array_length(team1_players,1),1),1)),
             games_played = games_played + 1,
             wins = wins + case when actual_1 = 1 then 1 else 0 end,
             losses = losses + case when actual_1 = 0 then 1 else 0 end,
             draws = draws + case when actual_1 = 0.5 then 1 else 0 end,
             last_match_at = ts,
             updated_at = now()
       where player_name = p;
      select elo_rating into after_rating from public.klaverjas_player_ratings where player_name = p;
      insert into public.klaverjas_player_rating_history(game_id, player_name, rating_before, rating_after, created_at)
      values (g.id, p, coalesce(before_rating,1000), coalesce(after_rating,1000), ts);
    end loop;

    foreach p in array team2_players loop
      select elo_rating into before_rating from public.klaverjas_player_ratings where player_name = p;
      update public.klaverjas_player_ratings
         set elo_rating = elo_rating - (delta_total / greatest(coalesce(array_length(team2_players,1),1),1)),
             games_played = games_played + 1,
             wins = wins + case when actual_1 = 0 then 1 else 0 end,
             losses = losses + case when actual_1 = 1 then 1 else 0 end,
             draws = draws + case when actual_1 = 0.5 then 1 else 0 end,
             last_match_at = ts,
             updated_at = now()
       where player_name = p;
      select elo_rating into after_rating from public.klaverjas_player_ratings where player_name = p;
      insert into public.klaverjas_player_rating_history(game_id, player_name, rating_before, rating_after, created_at)
      values (g.id, p, coalesce(before_rating,1000), coalesce(after_rating,1000), ts);
    end loop;
  end loop;
end;
$fn$;

create or replace function public.rebuild_boerenbridge_ratings()
returns void language plpgsql security definer set search_path to 'public' as $fn$
declare
  m record;
  rec record;
  names text[];
  p text;
  before_rating numeric;
  after_rating numeric;
  n integer;
  i integer;
  j integer;
  ratings numeric[];
  points integer[];
  exacts integer[];
  slagen integer[];
  deltas numeric[];
  podium_cut integer;
  top_half_cut integer;
  k_factor numeric := 24.0;
  expected_i numeric;
  actual_i numeric;
  ts timestamptz;
begin
  truncate table public.boerenbridge_player_rating_history restart identity;
  delete from public.boerenbridge_player_ratings;
  if to_regclass('public.boerenbridge_player_stats') is not null then
    delete from public.boerenbridge_player_stats;
  end if;

  for m in
    select id, payload, finished_at, started_at, created_at
    from public.boerenbridge_matches
    where deleted_at is null
      and coalesce(match_status, case when nullif(payload->>'finished_at','') is not null then 'finished' else 'draft' end) = 'finished'
    order by coalesce(finished_at, started_at, created_at), id
  loop
    names := '{}'::text[]; ratings := '{}'::numeric[]; points := '{}'::integer[]; exacts := '{}'::integer[]; slagen := '{}'::integer[]; deltas := '{}'::numeric[];
    for rec in
      select
        coalesce(x->>'name','') as player_name,
        coalesce((x->>'final_total_points')::integer,0) as final_total_points,
        coalesce((x->>'exact_bid_count')::integer,0) as exact_bid_count,
        coalesce((x->>'total_slagen')::integer,0) as total_slagen
      from jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x
      where nullif(trim(coalesce(x->>'name','')), '') is not null
      order by coalesce((x->>'final_total_points')::integer,0) desc, coalesce(x->>'name','') asc
    loop
      names := array_append(names, rec.player_name);
      points := array_append(points, rec.final_total_points);
      exacts := array_append(exacts, rec.exact_bid_count);
      slagen := array_append(slagen, rec.total_slagen);
      insert into public.boerenbridge_player_ratings(player_name) values (rec.player_name) on conflict (player_name) do nothing;
      select elo_rating into before_rating from public.boerenbridge_player_ratings where player_name = rec.player_name;
      ratings := array_append(ratings, coalesce(before_rating,1000));
      deltas := array_append(deltas, 0);
    end loop;

    n := coalesce(array_length(names,1),0);
    if n < 2 then continue; end if;
    ts := coalesce(m.finished_at, m.started_at, m.created_at, now());
    podium_cut := least(3, n);
    top_half_cut := ceil(n::numeric / 2.0)::integer;

    for i in 1..n loop
      for j in 1..n loop
        if i = j then continue; end if;
        expected_i := public._elo_expected(ratings[i], ratings[j]);
        actual_i := case when points[i] > points[j] then 1 when points[i] < points[j] then 0 else 0.5 end;
        deltas[i] := coalesce(deltas[i],0) + (k_factor / greatest(n - 1, 1)) * (actual_i - expected_i);
      end loop;
    end loop;

    for i in 1..n loop
      p := names[i];
      before_rating := ratings[i];
      update public.boerenbridge_player_ratings
         set elo_rating = elo_rating + deltas[i],
             games_played = games_played + 1,
             wins = wins + case when points[i] = (select max(v) from unnest(points) as v) then 1 else 0 end,
             podium_finishes = podium_finishes + case when i <= podium_cut then 1 else 0 end,
             top_half_finishes = top_half_finishes + case when i <= top_half_cut then 1 else 0 end,
             total_points = total_points + points[i],
             total_exact_bids = total_exact_bids + exacts[i],
             total_slagen = total_slagen + slagen[i],
             last_match_at = ts,
             updated_at = now()
       where player_name = p;
      select elo_rating into after_rating from public.boerenbridge_player_ratings where player_name = p;
      insert into public.boerenbridge_player_rating_history(match_id, player_name, rating_before, rating_after, created_at)
      values (m.id, p, coalesce(before_rating,1000), coalesce(after_rating,1000), ts);
      if to_regclass('public.boerenbridge_player_stats') is not null then
        insert into public.boerenbridge_player_stats(player_name, games_played, wins, total_points, updated_at)
        values (p, 1, case when points[i] = (select max(v) from unnest(points) as v) then 1 else 0 end, points[i], now())
        on conflict (player_name)
        do update set
          games_played = public.boerenbridge_player_stats.games_played + 1,
          wins = public.boerenbridge_player_stats.wins + excluded.wins,
          total_points = public.boerenbridge_player_stats.total_points + excluded.total_points,
          updated_at = now();
      end if;
    end loop;
  end loop;
end;
$fn$;

create or replace function public.process_game_rating_rebuild_queue(p_limit integer default 10)
returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  q record;
  processed integer := 0;
begin
  for q in
    select id, game_type
    from public.game_rating_rebuild_queue
    where status = 'pending'
    order by requested_at, id
    limit greatest(coalesce(p_limit,10),1)
    for update skip locked
  loop
    update public.game_rating_rebuild_queue set status='processing' where id = q.id;
    begin
      if q.game_type = 'beerpong' then
        perform public.rebuild_beerpong_ratings();
      elsif q.game_type = 'klaverjas' then
        perform public.rebuild_klaverjas_ratings();
      elsif q.game_type = 'boerenbridge' then
        perform public.rebuild_boerenbridge_ratings();
      else
        raise exception 'Onbekend speltype: %', q.game_type;
      end if;
      update public.game_rating_rebuild_queue set status='done', processed_at=now(), last_error=null where id = q.id;
      processed := processed + 1;
    exception when others then
      update public.game_rating_rebuild_queue set status='error', processed_at=now(), last_error=sqlerrm where id = q.id;
      raise;
    end;
  end loop;
  return jsonb_build_object('ok', true, 'processed', processed);
end;
$fn$;

create or replace function public.create_jas_game(session_token text, game_payload jsonb)
returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  session_player public.players%rowtype;
  game_id_out bigint;
  participant jsonb;
  resolved_player_id bigint;
  payload_participants jsonb;
  participant_count integer;
  distinct_player_count integer;
  seat_arr integer[];
  team_arr integer[];
  missing_name text;
begin
  session_player := public._jas_session_player(session_token);
  payload_participants := coalesce(game_payload -> 'participants', '[]'::jsonb);

  if coalesce(nullif(trim(game_payload ->> 'variant'), ''), '4_player') <> '4_player' then
    raise exception 'Alleen 4-speler klaverjas wordt ondersteund in deze versie';
  end if;
  if coalesce(nullif(trim(game_payload ->> 'scoreboard_mode'), ''), 'teams') <> 'teams' then
    raise exception 'Alleen teamscore wordt ondersteund in deze versie';
  end if;
  if jsonb_typeof(payload_participants) <> 'array' then
    raise exception 'Deelnemers ontbreken';
  end if;
  participant_count := jsonb_array_length(payload_participants);
  if participant_count <> 4 then
    raise exception 'Kies precies 4 geregistreerde spelers';
  end if;
  select count(distinct lower(trim(value ->> 'name'))) into distinct_player_count from jsonb_array_elements(payload_participants) value;
  if distinct_player_count <> 4 then
    raise exception 'Elke speler mag maar één keer gekozen worden';
  end if;
  select array_agg((value ->> 'seat_no')::integer order by (value ->> 'seat_no')::integer),
         array_agg((value ->> 'team_no')::integer order by (value ->> 'seat_no')::integer)
    into seat_arr, team_arr
  from jsonb_array_elements(payload_participants) value;
  if seat_arr is distinct from array[1,2,3,4] then raise exception 'Stoelen moeten 1 t/m 4 zijn'; end if;
  if team_arr is distinct from array[1,2,1,2] then raise exception 'Teams moeten stoel 1+3 en 2+4 gebruiken'; end if;

  for participant in select * from jsonb_array_elements(payload_participants) loop
    select p.id into resolved_player_id from public.players p where lower(p.display_name) = lower(trim(participant ->> 'name')) limit 1;
    if resolved_player_id is null then
      missing_name := coalesce(participant ->> 'name', 'Onbekend');
      raise exception 'Speler niet gevonden of niet geregistreerd: %', missing_name;
    end if;
  end loop;

  insert into public.jas_games(title, played_at, variant, scoreboard_mode, created_by_player_id, created_by_name, payload, updated_at)
  values (
    coalesce(nullif(trim(game_payload ->> 'title'), ''), 'Klaverjas potje'),
    coalesce(nullif(game_payload ->> 'played_at', '')::date, current_date),
    '4_player',
    'teams',
    session_player.id,
    session_player.display_name,
    coalesce(game_payload, '{}'::jsonb),
    now()
  ) returning id into game_id_out;

  for participant in select * from jsonb_array_elements(payload_participants) loop
    select p.id into resolved_player_id from public.players p where lower(p.display_name) = lower(trim(participant ->> 'name')) limit 1;
    insert into public.jas_game_entries(game_id, player_id, display_name, seat_no, team_no, total_points, is_winner)
    values (
      game_id_out,
      resolved_player_id,
      coalesce(nullif(trim(participant ->> 'name'), ''), 'Onbekend'),
      (participant ->> 'seat_no')::integer,
      (participant ->> 'team_no')::integer,
      coalesce((participant ->> 'total_points')::integer, 0),
      coalesce((participant ->> 'is_winner')::boolean, false)
    );
  end loop;

  perform public._enqueue_rating_rebuild('klaverjas', 'new_match', game_id_out::text, 'player', session_player.display_name);
  perform public.process_game_rating_rebuild_queue(10);
  return jsonb_build_object('ok', true, 'game_id', game_id_out);
end;
$fn$;

create or replace function public._beerpong_rebuild_trigger()
returns trigger language plpgsql security definer set search_path to 'public' as $fn$
begin
  perform public._enqueue_rating_rebuild('beerpong', TG_OP, coalesce(new.client_match_id, old.client_match_id), 'system', 'trigger');
  perform public.process_game_rating_rebuild_queue(10);
  return coalesce(new, old);
end;
$fn$;

drop trigger if exists beerpong_rebuild_after_change on public.beerpong_matches;
create trigger beerpong_rebuild_after_change after insert or update or delete on public.beerpong_matches
for each row execute function public._beerpong_rebuild_trigger();

create or replace function public._boerenbridge_rebuild_trigger()
returns trigger language plpgsql security definer set search_path to 'public' as $fn$
begin
  perform public._enqueue_rating_rebuild('boerenbridge', TG_OP, coalesce(new.client_match_id, old.client_match_id), 'system', 'trigger');
  perform public.process_game_rating_rebuild_queue(10);
  return coalesce(new, old);
end;
$fn$;

drop trigger if exists boerenbridge_rebuild_after_change on public.boerenbridge_matches;
create trigger boerenbridge_rebuild_after_change after insert or update or delete on public.boerenbridge_matches
for each row execute function public._boerenbridge_rebuild_trigger();

create or replace function public.get_match_control_list_action(
  game_type_input text,
  session_token text default null,
  admin_session_token text default null,
  limit_count integer default 30
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_game text := lower(trim(coalesce(game_type_input,'')));
  v_limit integer := greatest(coalesce(limit_count,30),1);
  v_player public.players%rowtype;
  v_admin jsonb;
  result jsonb;
begin
  begin
    if nullif(trim(coalesce(session_token,'')), '') is not null then
      select * into v_player from public._gejast_player_from_session(session_token);
    end if;
  exception when others then null; end;

  begin
    if nullif(trim(coalesce(admin_session_token,'')), '') is not null then
      v_admin := to_jsonb(public.admin_check_session(admin_session_token));
    end if;
  exception when others then v_admin := null; end;

  if v_game = 'beerpong' then
    select coalesce(jsonb_agg(row_json order by created_at desc), '[]'::jsonb) into result
    from (
      select m.created_at,
        jsonb_build_object(
          'match_ref', m.client_match_id,
          'title', coalesce(array_to_string(m.team_a_player_names, ' + ') || ' vs ' || array_to_string(m.team_b_player_names, ' + '), 'Beerpong'),
          'created_at', m.created_at,
          'updated_at', m.updated_at,
          'finished_at', m.finished_at,
          'editable_until', m.created_at + interval '5 minutes',
          'can_edit', (v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id and now() <= m.created_at + interval '5 minutes'),
          'deleted_at', m.deleted_at,
          'summary', jsonb_build_object('winner_team', m.winner_team, 'team_a', m.team_a_player_names, 'team_b', m.team_b_player_names)
        ) as row_json
      from public.beerpong_matches m
      where ((v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id))
      order by m.created_at desc
      limit v_limit
    ) s;
  elsif v_game = 'boerenbridge' then
    select coalesce(jsonb_agg(row_json order by created_at desc), '[]'::jsonb) into result
    from (
      select m.created_at,
        jsonb_build_object(
          'match_ref', m.client_match_id,
          'title', coalesce(m.match_name, 'Boerenbridge'),
          'created_at', m.created_at,
          'updated_at', m.updated_at,
          'finished_at', m.finished_at,
          'editable_until', m.created_at + interval '5 minutes',
          'can_edit', (v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id and now() <= m.created_at + interval '5 minutes'),
          'deleted_at', m.deleted_at,
          'summary', jsonb_build_object('participants', coalesce(m.payload->'participants', m.payload->'players', '[]'::jsonb), 'winners', coalesce(m.payload#>'{match_summary,winner_names}', '[]'::jsonb))
        ) as row_json
      from public.boerenbridge_matches m
      where ((v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id))
      order by m.created_at desc
      limit v_limit
    ) s;
  elsif v_game = 'klaverjas' then
    select coalesce(jsonb_agg(row_json order by created_at desc), '[]'::jsonb) into result
    from (
      select j.created_at,
        jsonb_build_object(
          'match_ref', j.id::text,
          'title', j.title,
          'created_at', j.created_at,
          'updated_at', j.updated_at,
          'finished_at', j.created_at,
          'editable_until', j.created_at + interval '5 minutes',
          'can_edit', (v_admin is not null) or (v_player.id is not null and j.created_by_player_id = v_player.id and now() <= j.created_at + interval '5 minutes'),
          'deleted_at', j.deleted_at,
          'summary', jsonb_build_object('players', coalesce((select jsonb_agg(e.display_name order by e.seat_no) from public.jas_game_entries e where e.game_id = j.id), '[]'::jsonb))
        ) as row_json
      from public.jas_games j
      where ((v_admin is not null) or (v_player.id is not null and j.created_by_player_id = v_player.id))
      order by j.created_at desc
      limit v_limit
    ) s;
  else
    raise exception 'Onbekend speltype';
  end if;

  return jsonb_build_object('ok', true, 'matches', result, 'is_admin', v_admin is not null, 'player_name', v_player.display_name);
end;
$fn$;

create or replace function public.get_match_control_detail_action(
  game_type_input text,
  match_ref text,
  session_token text default null,
  admin_session_token text default null
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_game text := lower(trim(coalesce(game_type_input,'')));
  v_player public.players%rowtype;
  v_admin jsonb;
  out_payload jsonb;
  v_can_edit boolean := false;
begin
  begin if nullif(trim(coalesce(session_token,'')), '') is not null then select * into v_player from public._gejast_player_from_session(session_token); end if; exception when others then null; end;
  begin if nullif(trim(coalesce(admin_session_token,'')), '') is not null then v_admin := to_jsonb(public.admin_check_session(admin_session_token)); end if; exception when others then v_admin := null; end;

  if v_game = 'beerpong' then
    select jsonb_build_object('client_match_id', m.client_match_id, 'payload', m.payload, 'created_at', m.created_at, 'updated_at', m.updated_at, 'deleted_at', m.deleted_at)
      into out_payload
    from public.beerpong_matches m
    where m.client_match_id = match_ref
      and ((v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id));
    select (v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id and now() <= m.created_at + interval '5 minutes') into v_can_edit from public.beerpong_matches m where m.client_match_id = match_ref;
  elsif v_game = 'boerenbridge' then
    select jsonb_build_object('client_match_id', m.client_match_id, 'payload', m.payload, 'created_at', m.created_at, 'updated_at', m.updated_at, 'deleted_at', m.deleted_at)
      into out_payload
    from public.boerenbridge_matches m
    where m.client_match_id = match_ref
      and ((v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id));
    select (v_admin is not null) or (v_player.id is not null and m.created_by_player_id = v_player.id and now() <= m.created_at + interval '5 minutes') into v_can_edit from public.boerenbridge_matches m where m.client_match_id = match_ref;
  elsif v_game = 'klaverjas' then
    select jsonb_build_object('match_ref', j.id::text, 'payload', j.payload, 'created_at', j.created_at, 'updated_at', j.updated_at, 'deleted_at', j.deleted_at)
      into out_payload
    from public.jas_games j
    where j.id = match_ref::bigint
      and ((v_admin is not null) or (v_player.id is not null and j.created_by_player_id = v_player.id));
    select (v_admin is not null) or (v_player.id is not null and j.created_by_player_id = v_player.id and now() <= j.created_at + interval '5 minutes') into v_can_edit from public.jas_games j where j.id = match_ref::bigint;
  else
    raise exception 'Onbekend speltype';
  end if;
  return jsonb_build_object('ok', true, 'match', out_payload, 'can_edit', coalesce(v_can_edit,false));
end;
$fn$;

create or replace function public.player_update_match_action(
  game_type_input text,
  session_token text,
  match_ref text,
  match_payload jsonb default '{}'::jsonb,
  delete_match boolean default false,
  reason_input text default null
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_game text := lower(trim(coalesce(game_type_input,'')));
  v_player public.players%rowtype;
  before_payload jsonb;
  v_name text;
  participant jsonb;
  resolved_player_id bigint;
  v_allowed boolean := false;
begin
  select * into v_player from public._gejast_player_from_session(session_token);
  v_name := v_player.display_name;

  if v_game = 'beerpong' then
    select (created_by_player_id = v_player.id and now() <= created_at + interval '5 minutes') into v_allowed from public.beerpong_matches where client_match_id = match_ref;
    if not coalesce(v_allowed,false) then raise exception 'Bewerkenstijd verlopen.'; end if;
    select payload into before_payload from public.beerpong_matches where client_match_id = match_ref;
    if delete_match then
      update public.beerpong_matches set deleted_at = now(), updated_at = now() where client_match_id = match_ref;
    else
      update public.beerpong_matches
         set winner_team = coalesce(nullif(match_payload->>'winner_team',''), winner_team),
             team_a_player_names = coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'team_a_player_names', to_jsonb(team_a_player_names)))), team_a_player_names),
             team_b_player_names = coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'team_b_player_names', to_jsonb(team_b_player_names)))), team_b_player_names),
             team_a_cups_left = coalesce(nullif(match_payload->>'team_a_cups_left','')::integer, team_a_cups_left),
             team_b_cups_left = coalesce(nullif(match_payload->>'team_b_cups_left','')::integer, team_b_cups_left),
             finished_at = coalesce(nullif(match_payload->>'finished_at','')::timestamptz, finished_at),
             payload = match_payload,
             deleted_at = null,
             updated_at = now()
       where client_match_id = match_ref;
    end if;
  elsif v_game = 'boerenbridge' then
    select (created_by_player_id = v_player.id and now() <= created_at + interval '5 minutes') into v_allowed from public.boerenbridge_matches where client_match_id = match_ref;
    if not coalesce(v_allowed,false) then raise exception 'Bewerkenstijd verlopen.'; end if;
    select payload into before_payload from public.boerenbridge_matches where client_match_id = match_ref;
    if delete_match then
      update public.boerenbridge_matches set deleted_at = now(), updated_at = now() where client_match_id = match_ref;
    else
      update public.boerenbridge_matches
         set payload = match_payload,
             finished_at = coalesce(nullif(match_payload->>'finished_at','')::timestamptz, finished_at),
             match_status = case when nullif(match_payload->>'finished_at','') is not null then 'finished' else coalesce(match_status,'draft') end,
             deleted_at = null,
             updated_at = now()
       where client_match_id = match_ref;
    end if;
  elsif v_game = 'klaverjas' then
    select (created_by_player_id = v_player.id and now() <= created_at + interval '5 minutes') into v_allowed from public.jas_games where id = match_ref::bigint;
    if not coalesce(v_allowed,false) then raise exception 'Bewerkenstijd verlopen.'; end if;
    select payload into before_payload from public.jas_games where id = match_ref::bigint;
    if delete_match then
      update public.jas_games set deleted_at = now(), updated_at = now() where id = match_ref::bigint;
    else
      update public.jas_games
         set title = coalesce(nullif(trim(coalesce(match_payload->>'title','')), ''), title),
             played_at = coalesce(nullif(match_payload->>'played_at','')::date, played_at),
             payload = match_payload,
             deleted_at = null,
             updated_at = now()
       where id = match_ref::bigint;
      delete from public.jas_game_entries where game_id = match_ref::bigint;
      for participant in select * from jsonb_array_elements(coalesce(match_payload->'participants','[]'::jsonb)) loop
        select p.id into resolved_player_id from public.players p where lower(p.display_name) = lower(trim(participant ->> 'name')) limit 1;
        insert into public.jas_game_entries(game_id, player_id, display_name, seat_no, team_no, total_points, is_winner)
        values (match_ref::bigint, resolved_player_id, participant->>'name', (participant->>'seat_no')::integer, (participant->>'team_no')::integer, coalesce((participant->>'total_points')::integer,0), coalesce((participant->>'is_winner')::boolean,false));
      end loop;
    end if;
  else
    raise exception 'Onbekend speltype';
  end if;

  insert into public.match_change_log(game_type, match_ref, change_type, changed_by_role, changed_by_name, reason, before_payload, after_payload)
  values (v_game, match_ref, case when delete_match then 'delete' else 'update' end, 'player', v_name, reason_input, before_payload, match_payload);
  perform public._enqueue_rating_rebuild(v_game, case when delete_match then 'player_delete' else 'player_update' end, match_ref, 'player', v_name);
  perform public.process_game_rating_rebuild_queue(10);
  return jsonb_build_object('ok', true);
end;
$fn$;

create or replace function public.admin_update_match_action(
  game_type_input text,
  admin_session_token text,
  match_ref text,
  match_payload jsonb default '{}'::jsonb,
  delete_match boolean default false,
  reason_input text default null
) returns jsonb language plpgsql security definer set search_path to 'public' as $fn$
declare
  v_game text := lower(trim(coalesce(game_type_input,'')));
  v_admin jsonb;
  v_name text;
  before_payload jsonb;
  participant jsonb;
  resolved_player_id bigint;
begin
  v_admin := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_admin->>'ok')::boolean, false) is not true then raise exception 'Log opnieuw in als admin.'; end if;
  v_name := coalesce(nullif(trim(v_admin->>'admin_username'),''), nullif(trim(v_admin->>'username'),''), 'admin');

  if v_game = 'beerpong' then
    select payload into before_payload from public.beerpong_matches where client_match_id = match_ref;
    if delete_match then
      update public.beerpong_matches set deleted_at = now(), updated_at = now() where client_match_id = match_ref;
    else
      update public.beerpong_matches set
        winner_team = coalesce(nullif(match_payload->>'winner_team',''), winner_team),
        team_a_player_names = coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'team_a_player_names', to_jsonb(team_a_player_names)))), team_a_player_names),
        team_b_player_names = coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'team_b_player_names', to_jsonb(team_b_player_names)))), team_b_player_names),
        team_a_cups_left = coalesce(nullif(match_payload->>'team_a_cups_left','')::integer, team_a_cups_left),
        team_b_cups_left = coalesce(nullif(match_payload->>'team_b_cups_left','')::integer, team_b_cups_left),
        finished_at = coalesce(nullif(match_payload->>'finished_at','')::timestamptz, finished_at),
        payload = match_payload,
        deleted_at = null,
        updated_at = now()
      where client_match_id = match_ref;
    end if;
  elsif v_game = 'boerenbridge' then
    select payload into before_payload from public.boerenbridge_matches where client_match_id = match_ref;
    if delete_match then
      update public.boerenbridge_matches set deleted_at = now(), updated_at = now() where client_match_id = match_ref;
    else
      update public.boerenbridge_matches set payload = match_payload, finished_at = coalesce(nullif(match_payload->>'finished_at','')::timestamptz, finished_at), match_status = case when nullif(match_payload->>'finished_at','') is not null then 'finished' else coalesce(match_status,'draft') end, deleted_at = null, updated_at = now() where client_match_id = match_ref;
    end if;
  elsif v_game = 'klaverjas' then
    select payload into before_payload from public.jas_games where id = match_ref::bigint;
    if delete_match then
      update public.jas_games set deleted_at = now(), updated_at = now() where id = match_ref::bigint;
    else
      update public.jas_games set title = coalesce(nullif(trim(coalesce(match_payload->>'title','')), ''), title), played_at = coalesce(nullif(match_payload->>'played_at','')::date, played_at), payload = match_payload, deleted_at = null, updated_at = now() where id = match_ref::bigint;
      delete from public.jas_game_entries where game_id = match_ref::bigint;
      for participant in select * from jsonb_array_elements(coalesce(match_payload->'participants','[]'::jsonb)) loop
        select p.id into resolved_player_id from public.players p where lower(p.display_name) = lower(trim(participant ->> 'name')) limit 1;
        insert into public.jas_game_entries(game_id, player_id, display_name, seat_no, team_no, total_points, is_winner)
        values (match_ref::bigint, resolved_player_id, participant->>'name', (participant->>'seat_no')::integer, (participant->>'team_no')::integer, coalesce((participant->>'total_points')::integer,0), coalesce((participant->>'is_winner')::boolean,false));
      end loop;
    end if;
  else
    raise exception 'Onbekend speltype';
  end if;

  insert into public.match_change_log(game_type, match_ref, change_type, changed_by_role, changed_by_name, reason, before_payload, after_payload)
  values (v_game, match_ref, case when delete_match then 'delete' else 'update' end, 'admin', v_name, reason_input, before_payload, match_payload);
  perform public._enqueue_rating_rebuild(v_game, case when delete_match then 'admin_delete' else 'admin_update' end, match_ref, 'admin', v_name);
  perform public.process_game_rating_rebuild_queue(10);
  return jsonb_build_object('ok', true);
end;
$fn$;

grant execute on function public.get_match_control_list_action(text, text, text, integer) to anon, authenticated;
grant execute on function public.get_match_control_detail_action(text, text, text, text) to anon, authenticated;
grant execute on function public.player_update_match_action(text, text, text, jsonb, boolean, text) to anon, authenticated;
grant execute on function public.admin_update_match_action(text, text, text, jsonb, boolean, text) to anon, authenticated;
grant execute on function public.process_game_rating_rebuild_queue(integer) to anon, authenticated;

commit;
