-- GEJAST v755: separate Toepen persistence and analytics lane.
-- Additive only: no Klaverjas, Boerenbridge, drinks or account objects are changed.

begin;

create table if not exists public.toepen_games (
  id bigint generated by default as identity primary key,
  client_match_id text not null unique,
  site_scope text not null default 'friends' check (site_scope in ('friends','family')),
  created_by_player_id bigint null,
  created_by_player_name text not null,
  played_at timestamptz not null default now(),
  target_points integer not null default 10 check (target_points between 1 and 100),
  ruleset jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null,
  winner_names text[] not null default '{}'::text[],
  status text not null default 'finished' check (status in ('draft','finished','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists toepen_games_scope_played_idx on public.toepen_games(site_scope, played_at desc);
create index if not exists toepen_games_creator_idx on public.toepen_games(created_by_player_id, played_at desc);

create table if not exists public.toepen_game_participants (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.toepen_games(id) on delete cascade,
  seat_no integer not null check (seat_no between 1 and 8),
  player_name text not null,
  start_points integer not null default 0,
  end_points integer not null default 0,
  eliminated boolean not null default false,
  eliminated_round_no integer null,
  finish_rank integer null,
  created_at timestamptz not null default now(),
  unique(game_id, seat_no)
);

create index if not exists toepen_participants_name_idx on public.toepen_game_participants(lower(player_name), game_id);
create unique index if not exists toepen_participants_game_name_uidx
  on public.toepen_game_participants(game_id, lower(player_name));

create table if not exists public.toepen_rounds (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.toepen_games(id) on delete cascade,
  round_no integer not null check (round_no > 0),
  dealer_seat integer not null check (dealer_seat between 1 and 8),
  winner_seat integer not null check (winner_seat between 1 and 8),
  winner_name text not null,
  stake_final integer not null check (stake_final > 0),
  knock_count integer not null default 0,
  special_tags text[] not null default '{}'::text[],
  note text not null default '',
  raw_round jsonb not null,
  created_at timestamptz not null default now(),
  unique(game_id, round_no)
);

create table if not exists public.toepen_round_results (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.toepen_rounds(id) on delete cascade,
  game_id bigint not null references public.toepen_games(id) on delete cascade,
  round_no integer not null,
  seat_no integer not null check (seat_no between 1 and 8),
  player_name text not null,
  action text not null check (action in ('win','stay','fold')),
  penalty_points integer not null check (penalty_points >= 0),
  folded_at_stake integer null,
  created_at timestamptz not null default now(),
  unique(round_id, seat_no)
);

create index if not exists toepen_round_results_player_idx on public.toepen_round_results(lower(player_name), game_id, round_no);

alter table public.toepen_games enable row level security;
alter table public.toepen_game_participants enable row level security;
alter table public.toepen_rounds enable row level security;
alter table public.toepen_round_results enable row level security;

-- Direct table access remains closed; all reads/writes use SECURITY DEFINER RPCs.
revoke all on public.toepen_games from anon, authenticated;
revoke all on public.toepen_game_participants from anon, authenticated;
revoke all on public.toepen_rounds from anon, authenticated;
revoke all on public.toepen_round_results from anon, authenticated;

create or replace function public.create_toepen_game(
  session_token text,
  game_payload jsonb,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  viewer public.players%rowtype;
  game_id_out bigint;
  existing_id bigint;
  participant jsonb;
  round_row jsonb;
  result_row jsonb;
  round_id_out bigint;
  participant_count integer;
  round_count integer;
  winner_names_out text[];
  client_id text;
  seen_names text[] := '{}'::text[];
  lower_name text;
  creator_name text;
  creator_slug text;
  creator_seen boolean := false;
  active_seats integer[];
  winner_seat_value integer;
  stake_value integer;
  seat_value integer;
  action_value text;
  folded_value integer;
  round_result_count integer;
  use_scope text := case when lower(coalesce(site_scope_input,''))='family' then 'family' else 'friends' end;
begin
  if game_payload is null or jsonb_typeof(game_payload) <> 'object' then
    raise exception 'Ongeldig Toepen-payload.';
  end if;

  viewer := public._tier3_player_from_any_session_v740(session_token);
  if viewer.id is null then
    raise exception 'Niet ingelogd.';
  end if;
  if lower(coalesce(viewer.site_scope,'friends')) <> use_scope then
    raise exception 'Verkeerde Toepen-scope voor deze speler.';
  end if;
  creator_name := lower(trim(coalesce(viewer.display_name,'')));
  creator_slug := lower(trim(coalesce(viewer.slug,'')));

  client_id := nullif(trim(game_payload->>'client_match_id'),'');
  if client_id is null then
    raise exception 'client_match_id ontbreekt.';
  end if;
  if coalesce(game_payload->>'game_type','toepen') <> 'toepen' then
    raise exception 'Verkeerd speltype.';
  end if;

  participant_count := jsonb_array_length(coalesce(game_payload->'participants','[]'::jsonb));
  round_count := jsonb_array_length(coalesce(game_payload->'rounds','[]'::jsonb));
  if participant_count < 2 or participant_count > 8 then
    raise exception 'Toepen vereist 2 tot 8 spelers.';
  end if;
  if round_count < 1 then
    raise exception 'Een opgeslagen Toepen-potje vereist minimaal één ronde.';
  end if;

  select id into existing_id from public.toepen_games where client_match_id=client_id limit 1;
  if existing_id is not null then
    return jsonb_build_object('ok',true,'game_id',existing_id,'already_saved',true);
  end if;

  select coalesce(array_agg(p->>'name' order by nullif(p->>'finish_rank','')::integer) filter (where nullif(p->>'finish_rank','')::integer=1),'{}'::text[])
    into winner_names_out
    from jsonb_array_elements(game_payload->'participants') p;

  insert into public.toepen_games(
    client_match_id,site_scope,created_by_player_id,created_by_player_name,played_at,
    target_points,ruleset,raw_payload,winner_names,status
  ) values (
    client_id,use_scope,viewer.id,
    coalesce(nullif(trim(viewer.display_name),''),nullif(trim(viewer.slug),''),'Onbekende speler'),
    coalesce(nullif(game_payload->>'played_at','')::timestamptz,now()),
    greatest(1,least(100,coalesce(nullif(game_payload->>'target_points','')::integer,10))),
    coalesce(game_payload->'ruleset','{}'::jsonb),game_payload,coalesce(winner_names_out,'{}'::text[]),'finished'
  ) returning id into game_id_out;

  for participant in select value from jsonb_array_elements(game_payload->'participants')
  loop
    if nullif(trim(participant->>'name'),'') is null then
      raise exception 'Een deelnemer heeft geen naam.';
    end if;
    if nullif(participant->>'seat_no','')::integer is null
       or nullif(participant->>'seat_no','')::integer < 1
       or nullif(participant->>'seat_no','')::integer > participant_count then
      raise exception 'Ongeldig Toepen-stoelnummer.';
    end if;
    lower_name := lower(trim(participant->>'name'));
    if lower_name = any(seen_names) then
      raise exception 'Een Toepen-deelnemer komt dubbel voor.';
    end if;
    seen_names := array_append(seen_names, lower_name);
    if lower_name = creator_name or (creator_slug <> '' and lower_name = creator_slug) then
      creator_seen := true;
    end if;
    insert into public.toepen_game_participants(
      game_id,seat_no,player_name,start_points,end_points,eliminated,eliminated_round_no,finish_rank
    ) values (
      game_id_out,
      nullif(participant->>'seat_no','')::integer,
      trim(participant->>'name'),
      coalesce(nullif(participant->>'start_points','')::integer,0),
      coalesce(nullif(participant->>'end_points','')::integer,0),
      coalesce(nullif(participant->>'eliminated','')::boolean,false),
      nullif(participant->>'eliminated_round_no','')::integer,
      nullif(participant->>'finish_rank','')::integer
    );
  end loop;

  if not creator_seen then
    raise exception 'Alleen een deelnemer mag dit Toepen-potje opslaan.';
  end if;

  for round_row in select value from jsonb_array_elements(game_payload->'rounds')
  loop
    active_seats := array(
      select (p->>'seat_no')::integer
        from jsonb_array_elements(game_payload->'participants') p
       where coalesce(nullif(p->>'eliminated','')::boolean,false) is false
          or coalesce(nullif(p->>'eliminated_round_no','')::integer, 2147483647) >= nullif(round_row->>'round_no','')::integer
    );
    winner_seat_value := nullif(round_row->>'winner_seat','')::integer;
    stake_value := greatest(1,coalesce(nullif(round_row->>'stake_final','')::integer,1));
    if stake_value > 10 then
      raise exception 'Toepen-inzet is hoger dan toegestaan.';
    end if;
    if winner_seat_value is null or not (winner_seat_value = any(active_seats)) then
      raise exception 'Rondewinnaar is geen actieve Toepen-speler.';
    end if;
    round_result_count := jsonb_array_length(coalesce(round_row->'results','[]'::jsonb));
    if round_result_count <> array_length(active_seats, 1) then
      raise exception 'Toepen-ronde bevat niet exact alle actieve spelers.';
    end if;

    insert into public.toepen_rounds(
      game_id,round_no,dealer_seat,winner_seat,winner_name,stake_final,knock_count,special_tags,note,raw_round,created_at
    ) values (
      game_id_out,
      nullif(round_row->>'round_no','')::integer,
      nullif(round_row->>'dealer_seat','')::integer,
      nullif(round_row->>'winner_seat','')::integer,
      coalesce(nullif(trim(round_row->>'winner_name'),''),'Onbekend'),
      stake_value,
      greatest(0,coalesce(nullif(round_row->>'knock_count','')::integer,0)),
      coalesce(array(select jsonb_array_elements_text(coalesce(round_row->'special_tags','[]'::jsonb))),'{}'::text[]),
      coalesce(round_row->>'note',''),round_row,
      coalesce(nullif(round_row->>'created_at','')::timestamptz,now())
    ) returning id into round_id_out;

    for result_row in select value from jsonb_array_elements(coalesce(round_row->'results','[]'::jsonb))
    loop
      seat_value := nullif(result_row->>'seat_no','')::integer;
      action_value := case when result_row->>'action' in ('win','stay','fold') then result_row->>'action' else 'stay' end;
      folded_value := nullif(result_row->>'folded_at_stake','')::integer;
      if seat_value is null or not (seat_value = any(active_seats)) then
        raise exception 'Toepen-resultaat verwijst naar een niet-actieve speler.';
      end if;
      if (seat_value = winner_seat_value and action_value <> 'win')
         or (seat_value <> winner_seat_value and action_value = 'win') then
        raise exception 'Alleen de rondewinnaar mag als winnaar worden opgeslagen.';
      end if;
      if action_value = 'fold'
         and (stake_value <= 1 or folded_value is null or folded_value < 1 or folded_value >= stake_value) then
        raise exception 'Ongeldige Toepen-foldwaarde.';
      end if;
      if action_value <> 'fold' and folded_value is not null then
        raise exception 'Alleen een fold mag een foldwaarde hebben.';
      end if;
      if action_value = 'win' and greatest(0,coalesce(nullif(result_row->>'penalty_points','')::integer,0)) <> 0 then
        raise exception 'Een Toepen-rondewinnaar krijgt geen strafpunten.';
      end if;
      if action_value = 'stay' and greatest(0,coalesce(nullif(result_row->>'penalty_points','')::integer,0)) <> stake_value then
        raise exception 'Blijven moet exact de eindinzet als strafpunten krijgen.';
      end if;
      if action_value = 'fold' and greatest(0,coalesce(nullif(result_row->>'penalty_points','')::integer,0)) <> folded_value then
        raise exception 'Folden moet exact de foldwaarde als strafpunten krijgen.';
      end if;
      insert into public.toepen_round_results(
        round_id,game_id,round_no,seat_no,player_name,action,penalty_points,folded_at_stake
      ) values (
        round_id_out,game_id_out,nullif(round_row->>'round_no','')::integer,
        seat_value,
        coalesce(nullif(trim(result_row->>'name'),''),'Onbekend'),
        action_value,
        greatest(0,coalesce(nullif(result_row->>'penalty_points','')::integer,0)),
        folded_value
      );
    end loop;
  end loop;

  return jsonb_build_object('ok',true,'game_id',game_id_out,'already_saved',false);
exception when others then
  if game_id_out is not null then delete from public.toepen_games where id=game_id_out; end if;
  raise;
end;
$fn$;

revoke all on function public.create_toepen_game(text,jsonb,text) from public;
grant execute on function public.create_toepen_game(text,jsonb,text) to anon, authenticated;

create or replace function public.get_toepen_app_state(
  session_token text default null,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  viewer public.players%rowtype;
  viewer_name text := null;
  use_scope text := case when lower(coalesce(site_scope_input,''))='family' then 'family' else 'friends' end;
  recent jsonb;
begin
  if nullif(trim(session_token),'') is not null then
    begin
      viewer := public._tier3_player_from_any_session_v740(session_token);
      viewer_name := coalesce(nullif(trim(viewer.display_name),''),nullif(trim(viewer.slug),''));
    exception when others then
      viewer_name := null;
    end;
  end if;

  select coalesce(jsonb_agg(row_to_json(x) order by x.played_at desc),'[]'::jsonb)
    into recent
    from (
      select g.id,g.client_match_id,g.played_at,g.target_points,g.winner_names,
             array_agg(p.player_name order by p.seat_no) as participant_names,
             (select count(*) from public.toepen_rounds r where r.game_id=g.id) as round_count
        from public.toepen_games g
        join public.toepen_game_participants p on p.game_id=g.id
       where g.site_scope=use_scope and g.status='finished'
         and (viewer_name is null or exists (
           select 1 from public.toepen_game_participants mine
            where mine.game_id=g.id and lower(mine.player_name)=lower(viewer_name)
         ))
       group by g.id
       order by g.played_at desc
       limit 20
    ) x;

  return jsonb_build_object('ok',true,'my_name',viewer_name,'recent_games',recent,'all_names','[]'::jsonb);
end;
$fn$;

revoke all on function public.get_toepen_app_state(text,text) from public;
grant execute on function public.get_toepen_app_state(text,text) to anon, authenticated;

create or replace function public._v755_admin_session_ok(admin_session_token text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  state jsonb;
  token_column text;
  ok boolean := false;
begin
  if nullif(trim(admin_session_token),'') is null then return false; end if;

  if to_regprocedure('public.admin_check_session(text)') is not null then
    begin
      execute 'select to_jsonb(public.admin_check_session($1))' into state using admin_session_token;
      if coalesce((state->>'ok')::boolean, false) is true then
        return true;
      end if;
      return false;
    exception when others then
      return false;
    end;
  end if;

  if to_regclass('public.admin_sessions') is not null then
    select column_name into token_column
      from information_schema.columns
     where table_schema='public' and table_name='admin_sessions'
       and column_name in ('admin_session_token','session_token','token')
     order by case column_name when 'admin_session_token' then 1 when 'session_token' then 2 else 3 end
     limit 1;
    if token_column is not null then
      execute format('select exists(select 1 from public.admin_sessions where %I=$1)',token_column)
        into ok using admin_session_token;
      return coalesce(ok,false);
    end if;
  end if;
  return false;
end;
$fn$;

revoke all on function public._v755_admin_session_ok(text) from public;
revoke all on function public._v755_admin_session_ok(text) from anon, authenticated;

create or replace function public.get_toepen_vault_summary(
  admin_session_token text,
  limit_count integer default 100,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  use_scope text := case when lower(coalesce(site_scope_input,''))='family' then 'family' else 'friends' end;
  recent jsonb;
  players jsonb;
begin
  if not public._v755_admin_session_ok(admin_session_token) then
    raise exception 'Geen geldige adminsessie.';
  end if;

  select coalesce(jsonb_agg(row_to_json(x) order by x.played_at desc),'[]'::jsonb)
    into recent
    from (
      select g.id,g.client_match_id,g.played_at,g.target_points,g.created_by_player_name,g.winner_names,g.ruleset,
             array_agg(p.player_name order by p.seat_no) as participant_names,
             (select count(*) from public.toepen_rounds r where r.game_id=g.id) as round_count
        from public.toepen_games g
        join public.toepen_game_participants p on p.game_id=g.id
       where g.site_scope=use_scope and g.status='finished'
       group by g.id
       order by g.played_at desc
       limit greatest(1,least(coalesce(limit_count,100),500))
    ) x;

  select coalesce(jsonb_agg(row_to_json(x) order by x.games_won desc,x.games_played desc,x.player_name),'[]'::jsonb)
    into players
    from (
      select p.player_name,
             count(distinct p.game_id) as games_played,
             count(distinct p.game_id) filter (where p.finish_rank=1) as games_won,
             round(avg(p.finish_rank)::numeric,2) as average_finish,
             count(*) filter (where p.eliminated) as eliminations,
             round(avg(p.end_points)::numeric,2) as average_end_points,
             count(rr.id) filter (where rr.action='fold') as folds,
             count(rr.id) filter (where rr.action='stay') as stay_losses,
             count(rr.id) filter (where rr.action='win') as rounds_won
        from public.toepen_game_participants p
        join public.toepen_games g on g.id=p.game_id and g.site_scope=use_scope and g.status='finished'
        left join public.toepen_round_results rr on rr.game_id=p.game_id and lower(rr.player_name)=lower(p.player_name)
       group by p.player_name
    ) x;

  return jsonb_build_object('ok',true,'site_scope',use_scope,'recent_games',recent,'player_stats',players);
end;
$fn$;

revoke all on function public.get_toepen_vault_summary(text,integer,text) from public;
grant execute on function public.get_toepen_vault_summary(text,integer,text) to anon, authenticated;

notify pgrst, 'reload schema';
notify pgrst, 'reload config';

commit;
