const GEJAST_VAPID_KEY = 'BPqY04jDOB_8RlhNxURgWFl6cMge64Mr7DkrWtgMfG4ARWLJ6S-r6c6JeQJ6o4kysWT0WeR9oVpahP85L8GLl_4';
const GEJAST_SUPABASE_URL = 'https://uiqntazgnrxwliaidkmy.supabase.co';
const GEJAST_SUPABASE_KEY = 'sb_publishable_rBDv3k3BWdnQZMDi2hjfuA_76FVf_wA';
function coalesce(){ for (const v of arguments) if (v !== undefined && v !== null && v !== '') return v; return null; }
function pick(data){ const tokens=data.actionTokens||data.action_tokens||data.tokens||{}; return { title:coalesce(data.title,data.notification_title,'Gejast'), body:coalesce(data.body,data.message,'Er staat iets voor je klaar.'), url:coalesce(data.url,data.targetUrl,data.target_url,data.click_url,(data.requestKind||data.request_kind)==='speed'?'./drinks_speed.html':'./drinks_pending.html'), tag:coalesce(data.tag,data.notification_tag,`gejast-${coalesce(data.kind,data.trigger_kind,'push')}`), jobId:coalesce(data.jobId,data.job_id), traceId:coalesce(data.traceId,data.trace_id), kind:coalesce(data.kind,data.trigger_kind), requestKind:coalesce(data.requestKind,data.request_kind), requestId:coalesce(data.requestId,data.request_id), verifyActionToken:coalesce(data.verifyActionToken,data.verify_action_token,tokens.verify,tokens.verifyActionToken,tokens.verify_action_token), rejectActionToken:coalesce(data.rejectActionToken,data.reject_action_token,tokens.reject,tokens.rejectActionToken,tokens.reject_action_token), expiresAt:coalesce(data.expiresAt,data.expires_at), requireInteraction:!!coalesce(data.requireInteraction,data.require_interaction,false), vibrate:Array.isArray(data.vibratePattern)?data.vibratePattern:(Array.isArray(data.vibrate)?data.vibrate:[180,80,180]) }; }
async function consumeActionToken(actionToken){ if(!actionToken) return {ok:false,reason:'missing-token'}; try{ const res=await fetch(`${GEJAST_SUPABASE_URL}/rest/v1/rpc/consume_web_push_action_v3`,{method:'POST',headers:{'Content-Type':'application/json',apikey:GEJAST_SUPABASE_KEY,Authorization:`Bearer ${GEJAST_SUPABASE_KEY}`,Accept:'application/json'},body:JSON.stringify({action_token_input:actionToken})}); const txt=await res.text(); let data=null; try{data=txt?JSON.parse(txt):null;}catch(_){data={raw:txt};} if(!res.ok) return {ok:false,reason:data?.message||data?.error||txt||`HTTP ${res.status}`}; return Object.assign({ok:true},data||{}); }catch(err){ return {ok:false,reason:err&&err.message||'consume-failed'}; } }
function withStatusUrl(target,params={}){ const url=new URL(target||'./drinks_pending.html',self.location.origin); Object.entries(params||{}).forEach(([k,v])=>{ if(v!==undefined&&v!==null&&v!=='') url.searchParams.set(k,String(v)); }); return url.href; }
async function focusOrOpen(target){ const want=new URL(target||'./index.html',self.location.origin); const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true}); for(const client of clients){ try{ const url=new URL(client.url); if(url.pathname===want.pathname){ await client.focus(); if('navigate' in client && client.url!==want.href) await client.navigate(want.href); return; } }catch(_){} } if(self.clients.openWindow) await self.clients.openWindow(want.href); }
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',(event)=>event.waitUntil(self.clients.claim()));
self.addEventListener('push',(event)=>{ let raw={}; try{raw=event.data?event.data.json():{};}catch(_){} const data=pick(raw||{}); const wantsActions=!!(data.verifyActionToken||data.rejectActionToken); const payloadActions=Array.isArray(raw.actions)?raw.actions:[]; const actions=payloadActions.length?payloadActions:(wantsActions?[{action:'open',title:'Openen'},{action:'verify',title:'Bevestigen'},{action:'reject',title:'Afkeuren'}]:[{action:'open',title:'Openen'}]); event.waitUntil(self.registration.showNotification(data.title,{body:data.body,tag:data.tag,icon:'./logo.png',badge:'./logo.png',renotify:true,requireInteraction:data.requireInteraction||wantsActions,silent:false,timestamp:Date.now(),vibrate:data.vibrate,actions,data})); });
self.addEventListener('notificationclick',(event)=>{ const data=(event.notification&&event.notification.data)||{}; const action=event.action||'open'; const fallbackTarget=data.url||(data.requestKind==='speed'?'./drinks_speed.html':'./drinks_pending.html'); if(event.notification) event.notification.close(); event.waitUntil((async()=>{ if(action==='verify'||action==='reject'){ const result=await consumeActionToken(action==='verify'?data.verifyActionToken:data.rejectActionToken); const status=result&&result.ok?(action==='verify'?'verified':'rejected'):'failed'; await focusOrOpen(withStatusUrl(fallbackTarget,{request_kind:data.requestKind||'',request_id:data.requestId||'',action_status:status,trace_id:data.traceId||'',job_id:data.jobId||'',action_reason:result&&result.reason||''})); return; } await focusOrOpen(withStatusUrl(fallbackTarget,{request_kind:data.requestKind||'',request_id:data.requestId||'',action_status:'opened',trace_id:data.traceId||'',job_id:data.jobId||''})); })()); });
self.addEventListener('pushsubscriptionchange',(event)=>{ event.waitUntil((async()=>{ try{ if(!self.registration.pushManager) return; const padding='='.repeat((4-(GEJAST_VAPID_KEY.length%4))%4); const base64=(GEJAST_VAPID_KEY+padding).replace(/-/g,'+').replace(/_/g,'/'); const raw=atob(base64); const key=new Uint8Array(raw.length); for(let i=0;i<raw.length;i++) key[i]=raw.charCodeAt(i); await self.registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key}); const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true}); clients.forEach((client)=>{ try{client.postMessage({type:'gejast-pushsubscriptionchange'});}catch(_){} }); }catch(_){} })()); });
