(function(){
  const cfg = window.GEJAST_CONFIG || {};
  const scopeUtils = window.GEJAST_SCOPE_UTILS || {};
  const PARTICIPANT_KEY = 'gejast_pikken_participant_v501';
  const DICE_LOCK_KEY = 'gejast_pikken_dice_lock_v501';
  const HISTORY_KEY = 'gejast_pikken_bid_history_v501';

  function getScope(){ try { return (scopeUtils.getScope && scopeUtils.getScope()) || (new URLSearchParams(location.search).get('scope') === 'family' ? 'family' : 'friends'); } catch(_){ return 'friends'; } }
  function sessionToken(){ try { return (cfg.getPlayerSessionToken && cfg.getPlayerSessionToken()) || ''; } catch(_){ return ''; } }
  function headers(){ return { apikey: cfg.SUPABASE_PUBLISHABLE_KEY || '', Authorization: `Bearer ${cfg.SUPABASE_PUBLISHABLE_KEY || ''}`, 'Content-Type':'application/json', Accept:'application/json' }; }
  async function parse(res){ const text = await res.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { throw new Error(text || `HTTP ${res.status}`); } if(!res.ok) throw new Error(data?.message || data?.error || data?.hint || text || `HTTP ${res.status}`); return data; }
  async function rpc(name, payload){ const res = await fetch(`${cfg.SUPABASE_URL}/rest/v1/rpc/${name}`, { method:'POST', headers:headers(), body: JSON.stringify(payload || {}), cache:'no-store', mode:'cors' }); return parse(res); }
  async function rpcFirst(names, payload){ let last = null; for (const name of names){ try { return await rpc(name, payload); } catch (err) { last = err; } } throw last || new Error('RPC mislukt.'); }

  function qs(sel, root){ return (root||document).querySelector(sel); }
  function esc(s){ const map = {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}; return String(s??'').replace(/[&<>"']/g,m=>map[m]); }
  function normalizeError(err){ const msg = String(err && err.message || err || 'Onbekende fout'); if(/function|schema cache|missing|does not exist/i.test(msg)) return `Backend-seam ontbreekt nog: ${msg}`; return msg; }
  function setParticipantToken(gameId, active){ try{ if(active && gameId){ localStorage.setItem(PARTICIPANT_KEY, JSON.stringify({game_id:String(gameId), at:Date.now()})); } else { localStorage.removeItem(PARTICIPANT_KEY); } }catch(_){ } }
  function liveHref(gameId){ return `./pikken_live.html?client_match_id=${encodeURIComponent(String(gameId||''))}`; }
  function spectatorHref(gameId){ return `./pikken_spectator.html?client_match_id=${encodeURIComponent(String(gameId||''))}`; }
  function setStatus(text, isError){ const el = qs('#pkStatus'); if(!el) return; el.textContent = text || ''; el.style.color = isError ? '#7f2f1d' : '#6b6257'; }
  function setChip(text){ const el = qs('#pkStatusChip'); if(el) el.textContent = text || 'Pikken'; }
  function dieImg(face, cls){ const n = Number(face||0); const img = document.createElement('img'); img.className = cls || ''; img.alt = n ? `die ${n}` : 'die'; img.src = n ? `./assets/pikken/dice-${n}.svg` : './assets/pikken/dice-hidden.svg'; return img; }
  function sortDice(arr){ const order = {2:0,3:1,4:2,5:3,6:4,1:5}; return (Array.isArray(arr)?arr:[]).slice().sort((a,b)=> (order[Number(a)] ?? 99) - (order[Number(b)] ?? 99)); }
  function bidText(bid){ const count = Number(bid?.count || bid?.bid_count || 0); const face = Number(bid?.face || bid?.bid_face || 0); if (!count || !face) return '—'; return face === 1 ? `${count} × pik` : `${count} × ${face}`; }
  function readJson(key, fallback){ try{ const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; }catch(_){ return fallback; } }
  function writeJson(key, value){ try{ localStorage.setItem(key, JSON.stringify(value)); }catch(_){ } }
  function lockState(gameId){ const all = readJson(DICE_LOCK_KEY, {}); return all[String(gameId||'')] || []; }
  function setLockState(gameId, locks){ const all = readJson(DICE_LOCK_KEY, {}); all[String(gameId||'')] = Array.isArray(locks) ? locks : []; writeJson(DICE_LOCK_KEY, all); }
  function historyState(gameId){ const all = readJson(HISTORY_KEY, {}); return Array.isArray(all[String(gameId||'')]) ? all[String(gameId||'')] : []; }
  function setHistoryState(gameId, items){ const all = readJson(HISTORY_KEY, {}); all[String(gameId||'')] = Array.isArray(items) ? items.slice(-40) : []; writeJson(HISTORY_KEY, all); }
  function pushHistory(gameId, item){ const rows = historyState(gameId); const key = `${item.kind||'x'}|${item.round_no||0}|${item.count||0}|${item.face||0}|${item.by||''}|${item.vote||''}`; if (!rows.some((r)=>`${r.kind||'x'}|${r.round_no||0}|${r.count||0}|${r.face||0}|${r.by||''}|${r.vote||''}` === key)) rows.push(item); setHistoryState(gameId, rows); }
  function nextBidOptions(currentBid, maxCount){ const faceOrder = [2,3,4,5,6,1]; const currentCount = Number(currentBid?.count || currentBid?.bid_count || 0); const currentFace = Number(currentBid?.face || currentBid?.bid_face || 0); const currentIndex = faceOrder.indexOf(currentFace); const options = []; const upper = Math.max(1, Number(maxCount || 0)); for (let count = 1; count <= upper; count += 1){ for (let i = 0; i < faceOrder.length; i += 1){ const face = faceOrder[i]; const above = !currentCount || count > currentCount || (count === currentCount && i > currentIndex); if (!above) continue; options.push({ count, face, label: face === 1 ? `${count} × pik` : `${count} × ${face}` }); } } return options; }

  const UI = { gameId:'', lastStateVersion:-1, pollTimer:null, lastRoundMarker:'', localHand:[], localLocks:[] };

  function renderHistory(state){
    const game = state?.game || {}; const currentBid = game?.state?.bid || null; const roundNo = Number(game?.state?.round_no || 0); const history = historyState(UI.gameId);
    if (currentBid) pushHistory(UI.gameId, { kind:'bid', round_no:roundNo, count:Number(currentBid.count||currentBid.bid_count||0), face:Number(currentBid.face||currentBid.bid_face||0), by:String(currentBid.bidder_name || '') });
    const lastReveal = game?.state?.last_reveal || null;
    if (lastReveal) pushHistory(UI.gameId, { kind:'reveal', round_no:Number(lastReveal.round_no||0), count:Number(lastReveal.bid?.count||0), face:Number(lastReveal.bid?.face||0), by:String(lastReveal.bid?.bidder_name || ''), vote:lastReveal.bid_true ? 'gehaald' : 'niet gehaald' });
    const rows = historyState(UI.gameId).slice().reverse();
    const wrap = qs('#pkBidHistory'); if (!wrap) return;
    if (!rows.length){ wrap.textContent = 'Nog geen biedingen.'; return; }
    wrap.innerHTML = rows.map((row)=>`<article class="history-card"><div><strong>${esc(row.kind === 'reveal' ? 'Reveal' : 'Bod')}</strong> · ronde ${Number(row.round_no||0)}</div><div style="margin-top:6px">${esc((row.face===1?`${row.count} × pik`:`${row.count} × ${row.face}`) || '—')}</div><div class="muted tiny" style="margin-top:6px">${esc(row.by || 'onbekend')}${row.vote ? ` · ${esc(row.vote)}` : ''}</div></article>`).join('');
  }

  function render(state){
    const game = state?.game || {}; const viewer = state?.viewer || {}; const players = Array.isArray(state?.players) ? state.players : []; const votes = Array.isArray(state?.votes) ? state.votes : [];
    const serverHand = Array.isArray(state?.my_hand) ? state.my_hand.map(Number) : []; const phase = String(game?.state?.phase || 'lobby'); const bid = game?.state?.bid && game.state.bid !== null ? game.state.bid : null;
    const turnSeat = Number(game?.state?.current_turn_seat || 0); const voteTurnSeat = Number(game?.state?.vote_turn_seat || 0); const lastReveal = game?.state?.last_reveal || null; const totals = state?.dice_totals || {};
    setParticipantToken(game?.id || UI.gameId, phase && phase !== 'finished'); setChip(phase);
    qs('#pkLobbyCode').textContent = game?.lobby_code || '—'; qs('#pkPhase').textContent = phase; qs('#pkRoundNo').textContent = String(Number(game?.state?.round_no || 0) || 0);
    qs('#pkBidText').textContent = bidText(bid); qs('#pkBidBy').textContent = bid ? `door ${bid.bidder_name || '—'}` : '';
    qs('#pkDiceFraction').innerHTML = `${Number(totals.current_total||0)}<span style="opacity:.6">/</span>${Number(totals.start_total||0)} <small>dobbelstenen over</small>`;
    const liveLink = qs('#pkLiveLink'); const spectatorLink = qs('#pkSpectatorLink'); if(liveLink){ liveLink.href = liveHref(game?.id || UI.gameId); liveLink.style.display = (game?.id || UI.gameId) ? '' : 'none'; } if(spectatorLink){ spectatorLink.href = spectatorHref(game?.id || UI.gameId); }

    const list = qs('#pkPlayers');
    list.innerHTML = players.map((p)=>{ const seat = Number(p.seat||0); const alive = !!p.alive; const isTurn = phase === 'bidding' && seat === turnSeat; const isVoteTurn = phase === 'voting' && seat === voteTurnSeat; const vote = votes.find(v=>Number(v.seat||0)===seat); const voteStatus = vote ? String(vote.status||'waiting') : 'waiting'; const pillText = voteStatus === 'approved' ? '👍 ja' : voteStatus === 'rejected' ? '👎 nee' : '… wacht'; const pillClass = voteStatus === 'approved' ? 'pill ok' : voteStatus === 'rejected' ? 'pill bad' : 'pill wait'; const kick = viewer?.is_host && !p.is_self ? `<button class="btn alt tiny" data-kick-seat="${seat}">Kick</button>` : ''; return `<div class="player-row ${alive?'':'dead'} ${isTurn||isVoteTurn?'turn':''}"><div><div class="name"><strong>${esc(p.name||'Speler')}</strong> <span class="muted">#${seat}</span></div><div class="meta muted">${alive?'Levend':'Dood'} · ${Number(p.dice_count||0)} dobbelstenen</div></div><div>${phase==='voting'?`<span class="${pillClass}">${pillText}</span>`:''}</div><div>${kick}</div></div>`; }).join('');

    if (serverHand.length){ UI.localHand = sortDice(serverHand); }
    const savedLocks = lockState(UI.gameId); if (!UI.localLocks.length || UI.localLocks.length !== UI.localHand.length) UI.localLocks = UI.localHand.map((_, idx)=> !!savedLocks[idx]);
    const myDiceWrap = qs('#pkMyDice'); myDiceWrap.innerHTML = ''; UI.localHand.forEach((face, idx)=>{ const holder = document.createElement('div'); holder.className = `die-wrap ${UI.localLocks[idx] ? 'locked' : ''}`; const btn = document.createElement('button'); btn.className = 'die-btn'; btn.type = 'button'; btn.dataset.lockIndex = String(idx); btn.appendChild(dieImg(face, `die ${Number(face)===1?'pik':''}`.trim())); holder.appendChild(btn); myDiceWrap.appendChild(holder); });

    const myTurn = phase === 'bidding' && Number(viewer.seat||0) === turnSeat && !!viewer.alive; const myVoteTurn = phase === 'voting' && Number(viewer.seat||0) === voteTurnSeat && !!viewer.alive;
    qs('#pkBidPanel').style.display = myTurn ? 'block' : 'none'; qs('#pkVotePanel').style.display = myVoteTurn ? 'block' : 'none'; qs('#pkRejectBtn').disabled = !myTurn || !bid;
    const bidSelect = qs('#pkBidSelect'); const options = nextBidOptions(bid, Number(totals.current_total || 0)); bidSelect.innerHTML = options.map((opt)=>`<option value="${opt.count}|${opt.face}">${esc(opt.label)}</option>`).join('');
    if (!options.length) bidSelect.innerHTML = '<option value="">Geen legal next bid</option>';

    const revealWrap = qs('#pkReveal'); if(!lastReveal){ revealWrap.style.display='none'; revealWrap.innerHTML=''; } else { revealWrap.style.display='block'; const lrBid = lastReveal.bid || {}; const lrBidTxt = (Number(lrBid.face)===1) ? `${lrBid.count} × pik` : `${lrBid.count} × ${lrBid.face}`; revealWrap.innerHTML = `<details class="accordion" open><summary><span>Laatste ronde (R${Number(lastReveal.round_no||0)}): bod ${esc(lrBidTxt)}</span><span class="muted">${lastReveal.bid_true ? 'gehaald' : 'niet gehaald'} · geteld ${Number(lastReveal.counted_total||0)}</span></summary><div class="detail"><div class="muted">Verliezers: ${esc(String(lastReveal.losing_kind||''))} · Starter: stoel ${Number(lastReveal.next_starter_seat||0)}</div><div class="reveal-grid">${(Array.isArray(lastReveal.hands)?lastReveal.hands:[]).map((h)=>{ const dice = Array.isArray(h.dice) ? h.dice : []; return `<div class="reveal-card"><div class="reveal-name"><strong>${esc(h.name||'Speler')}</strong> <span class="muted">#${Number(h.seat||0)}</span></div><div class="dice-row">${sortDice(dice).map((d)=>`<img class="die ${Number(d)===1?'pik':''}" src="./assets/pikken/dice-${Number(d)}.svg" alt="die ${Number(d)}">`).join('')}</div></div>`; }).join('')}</div></div></details>`; }
    renderHistory(state); setLockState(UI.gameId, UI.localLocks);
  }

  async function loadAndRender(){ if(!UI.gameId) return; try{ const state = await rpc('pikken_get_state_scoped', { session_token: sessionToken() || null, game_id_input: UI.gameId }); const version = Number(state?.game?.state_version || -1); if(version !== UI.lastStateVersion){ UI.lastStateVersion = version; render(state); } else { render(state); } setStatus('', false); }catch(err){ setStatus(normalizeError(err) || 'Laden mislukt.', true); } }
  function startPolling(){ stopPolling(); UI.pollTimer = setInterval(()=>{ if(!document.hidden) loadAndRender(); }, 1100); loadAndRender(); }
  function stopPolling(){ if(UI.pollTimer){ clearInterval(UI.pollTimer); UI.pollTimer=null; } }

  async function createLobby(){ setStatus('Lobby maken…', false); const mode = qs('#pkPenaltyMode').value || 'wrong_loses'; const startDice = Number(qs('#pkStartDice').value || 6); const out = await rpc('pikken_create_lobby_scoped', { session_token: sessionToken() || null, site_scope_input: getScope(), config_input: { penalty_mode: mode, start_dice: startDice } }); UI.gameId = out.game_id; setParticipantToken(UI.gameId, true); history.replaceState(null,'',`pikken.html?game_id=${encodeURIComponent(UI.gameId)}&scope=${encodeURIComponent(getScope())}`); startPolling(); }
  async function joinLobby(){ const code = String(qs('#pkJoinCode').value||'').trim().toUpperCase(); if(!code) return setStatus('Vul een lobby code in.', true); setStatus('Lobby joinen…', false); const out = await rpc('pikken_join_lobby_scoped', { session_token: sessionToken() || null, site_scope_input: getScope(), lobby_code_input: code }); UI.gameId = out.game_id; setParticipantToken(UI.gameId, true); history.replaceState(null,'',`pikken.html?game_id=${encodeURIComponent(UI.gameId)}&scope=${encodeURIComponent(getScope())}`); startPolling(); }
  async function setReady(ready){ setStatus(ready?'Ready…':'Unready…', false); await rpc('pikken_set_ready_scoped', { session_token: sessionToken()||null, game_id_input: UI.gameId, ready_input: !!ready }); await loadAndRender(); }
  async function startGame(){ setStatus('Starten…', false); await rpc('pikken_start_game_scoped', { session_token: sessionToken()||null, game_id_input: UI.gameId }); await loadAndRender(); window.location.href = spectatorHref(UI.gameId); }
  async function placeBid(){ const raw = String(qs('#pkBidSelect').value || ''); if (!raw) throw new Error('Kies eerst een geldig bod.'); const [count, face] = raw.split('|').map(Number); setStatus('Bieden…', false); const state = await rpc('pikken_place_bid_scoped', { session_token: sessionToken()||null, game_id_input: UI.gameId, bid_count_input: count, bid_face_input: face }); render(state); }
  async function rejectBid(){ setStatus('Afkeuren…', false); const state = await rpc('pikken_reject_bid_scoped', { session_token: sessionToken()||null, game_id_input: UI.gameId }); render(state); }
  async function vote(v){ setStatus('Stemmen…', false); const state = await rpc('pikken_cast_vote_scoped', { session_token: sessionToken()||null, game_id_input: UI.gameId, vote_input: !!v }); render(state); }
  async function leaveMatch(){ setStatus('Match verlaten…', false); await rpcFirst(['pikken_leave_game_scoped','pikken_leave_lobby_scoped'], { session_token: sessionToken()||null, game_id_input: UI.gameId }); setParticipantToken(UI.gameId, false); UI.gameId=''; stopPolling(); history.replaceState(null,'','pikken.html'); setStatus('Match verlaten.', false); }
  async function destroyMatch(){ setStatus('Match slopen…', false); await rpcFirst(['pikken_destroy_game_scoped','pikken_destroy_lobby_scoped'], { session_token: sessionToken()||null, game_id_input: UI.gameId }); setParticipantToken(UI.gameId, false); UI.gameId=''; stopPolling(); history.replaceState(null,'','pikken.html'); setStatus('Match verwijderd.', false); }
  async function kickSeat(seat){ setStatus(`Speler #${seat} kicken…`, false); await rpcFirst(['pikken_kick_player_scoped'], { session_token: sessionToken()||null, game_id_input: UI.gameId, seat_input: Number(seat), target_seat_input: Number(seat) }); await loadAndRender(); }

  function localSortDice(){ UI.localHand = sortDice(UI.localHand); render({ game:{ state:{}, id:UI.gameId }, my_hand:UI.localHand, players:[], votes:[], dice_totals:{} }); loadAndRender(); }
  function localThrowUnlocked(){ UI.localHand = UI.localHand.map((face, idx)=> UI.localLocks[idx] ? face : ([1,2,3,4,5,6][Math.floor(Math.random()*6)])); UI.localHand = sortDice(UI.localHand); setStatus('Lokale throw gedaan voor ongesloten dobbelstenen.', false); render({ game:{ state:{}, id:UI.gameId }, my_hand:UI.localHand, players:[], votes:[], dice_totals:{} }); loadAndRender(); }
  function unlockAll(){ UI.localLocks = UI.localLocks.map(()=>false); setLockState(UI.gameId, UI.localLocks); loadAndRender(); }

  function boot(){ const params = new URLSearchParams(location.search); UI.gameId = params.get('game_id') || ''; qs('#pkCreateLobbyBtn').addEventListener('click', ()=>createLobby().catch(e=>setStatus(normalizeError(e)||'Maken mislukt.',true))); qs('#pkJoinLobbyBtn').addEventListener('click', ()=>joinLobby().catch(e=>setStatus(normalizeError(e)||'Join mislukt.',true))); qs('#pkReadyBtn').addEventListener('click', ()=>setReady(true).catch(e=>setStatus(normalizeError(e)||'Ready mislukt.',true))); qs('#pkUnreadyBtn').addEventListener('click', ()=>setReady(false).catch(e=>setStatus(normalizeError(e)||'Unready mislukt.',true))); qs('#pkStartBtn').addEventListener('click', ()=>startGame().catch(e=>setStatus(normalizeError(e)||'Start mislukt.',true))); qs('#pkPlaceBidBtn').addEventListener('click', ()=>placeBid().catch(e=>setStatus(normalizeError(e)||'Bieden mislukt.',true))); qs('#pkRejectBtn').addEventListener('click', ()=>rejectBid().catch(e=>setStatus(normalizeError(e)||'Afkeuren mislukt.',true))); qs('#pkVoteApproveBtn').addEventListener('click', ()=>vote(true).catch(e=>setStatus(normalizeError(e)||'Stem mislukt.',true))); qs('#pkVoteRejectBtn').addEventListener('click', ()=>vote(false).catch(e=>setStatus(normalizeError(e)||'Stem mislukt.',true))); qs('#pkLeaveBtn').addEventListener('click', ()=>leaveMatch().catch(e=>setStatus(normalizeError(e)||'Verlaten mislukt.',true))); qs('#pkDestroyBtn').addEventListener('click', ()=>destroyMatch().catch(e=>setStatus(normalizeError(e)||'Destroy mislukt.',true))); qs('#pkSortDiceBtn').addEventListener('click', localSortDice); qs('#pkThrowUnlockedBtn').addEventListener('click', localThrowUnlocked); qs('#pkUnlockDiceBtn').addEventListener('click', unlockAll); document.addEventListener('click', (ev)=>{ const btn = ev.target.closest('[data-kick-seat]'); if (btn) kickSeat(btn.getAttribute('data-kick-seat')).catch(e=>setStatus(normalizeError(e)||'Kick mislukt.',true)); const lock = ev.target.closest('[data-lock-index]'); if (lock){ const idx = Number(lock.getAttribute('data-lock-index')); UI.localLocks[idx] = !UI.localLocks[idx]; setLockState(UI.gameId, UI.localLocks); loadAndRender(); } }); if(UI.gameId){ setParticipantToken(UI.gameId, true); startPolling(); } }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded', boot, { once:true }); else boot();
})();
