begin;

create or replace function public._gejast_norm_name(name_input text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(trim(coalesce(name_input,'')), '\s+', ' ', 'g'))
$$;

create or replace function public._gejast_round_count(payload jsonb)
returns integer
language sql
immutable
as $$
  select case
    when jsonb_typeof(coalesce(payload,'{}'::jsonb)->'rounds') = 'array' then jsonb_array_length(coalesce(payload,'{}'::jsonb)->'rounds')
    else 0
  end
$$;

create or replace function public._gejast_summary_participants(payload jsonb, fallback text[] default null)
returns text[]
language sql
immutable
as $$
  with src as (
    select case
      when jsonb_typeof(coalesce(payload,'{}'::jsonb)->'participants') = 'array' then coalesce(payload,'{}'::jsonb)->'participants'
      when jsonb_typeof(coalesce(payload,'{}'::jsonb)->'players') = 'array' then coalesce(payload,'{}'::jsonb)->'players'
      else '[]'::jsonb
    end as j
  )
  select coalesce(
    array_agg(trim(v.value::text)) filter (where nullif(trim(v.value::text),'') is not null),
    coalesce(fallback, '{}'::text[])
  )
  from src
  left join lateral jsonb_array_elements_text(src.j) as v(value) on true
$$;

create or replace function public._gejast_summary_winners(payload jsonb, fallback text[] default null)
returns text[]
language sql
immutable
as $$
  with src as (
    select case
      when jsonb_typeof(coalesce(payload,'{}'::jsonb)->'winner_names') = 'array' then coalesce(payload,'{}'::jsonb)->'winner_names'
      else '[]'::jsonb
    end as j
  )
  select coalesce(
    array_agg(trim(v.value::text)) filter (where nullif(trim(v.value::text),'') is not null),
    coalesce(fallback, '{}'::text[])
  )
  from src
  left join lateral jsonb_array_elements_text(src.j) as v(value) on true
$$;

create or replace function public._gejast_player_id_from_session(session_token text)
returns bigint
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_player public.players%rowtype;
begin
  if nullif(trim(coalesce(session_token,'')), '') is null then
    return null;
  end if;
  begin
    select * into v_player from public._gejast_player_from_session(session_token);
  exception when others then
    return null;
  end;
  return v_player.id;
end;
$fn$;

create or replace function public._gejast_player_name_from_session(session_token text)
returns text
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_player public.players%rowtype;
begin
  if nullif(trim(coalesce(session_token,'')), '') is null then
    return null;
  end if;
  begin
    select * into v_player from public._gejast_player_from_session(session_token);
  exception when others then
    return null;
  end;
  return nullif(trim(coalesce(v_player.display_name,'')), '');
end;
$fn$;

create or replace function public._gejast_resolve_player_name(player_name_input text)
returns text
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_name text := nullif(trim(coalesce(player_name_input,'')), '');
  v_player public.players%rowtype;
begin
  if v_name is null then return null; end if;
  select * into v_player
  from public.players p
  where public._gejast_norm_name(p.display_name) = public._gejast_norm_name(v_name)
  order by p.id
  limit 1;
  if found then
    return v_player.display_name;
  end if;
  return v_name;
end;
$fn$;

create or replace function public._gejast_public_badge(total_matches integer, win_pct numeric)
returns text
language plpgsql
immutable
as $fn$
begin
  if coalesce(total_matches,0) >= 60 and coalesce(win_pct,0) >= 60 then return 'Legend'; end if;
  if coalesce(total_matches,0) >= 30 and coalesce(win_pct,0) >= 55 then return 'Gold'; end if;
  if coalesce(total_matches,0) >= 15 then return 'Actief'; end if;
  if coalesce(total_matches,0) >= 5 then return 'Groeier'; end if;
  return 'Starter';
end;
$fn$;

create table if not exists public.site_poll_votes (
  id bigint generated by default as identity primary key,
  poll_key text not null,
  player_id bigint references public.players(id) on delete set null,
  display_name text not null,
  desired_status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_poll_votes add column if not exists player_id bigint references public.players(id) on delete set null;
alter table public.site_poll_votes add column if not exists poll_key text;
alter table public.site_poll_votes add column if not exists desired_status text;
alter table public.site_poll_votes add column if not exists created_at timestamptz not null default now();
alter table public.site_poll_votes add column if not exists updated_at timestamptz not null default now();

update public.site_poll_votes
   set poll_key = coalesce(nullif(trim(coalesce(poll_key,'')), ''), 'gezopen_vanavond')
 where poll_key is null or nullif(trim(coalesce(poll_key,'')), '') is null;

create unique index if not exists site_poll_votes_poll_name_uidx on public.site_poll_votes (poll_key, lower(display_name));
create index if not exists site_poll_votes_poll_idx on public.site_poll_votes (poll_key, desired_status);

create or replace function public.get_site_poll_state(
  poll_key_input text,
  session_token text default null
) returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_poll text := coalesce(nullif(trim(coalesce(poll_key_input,'')), ''), 'gezopen_vanavond');
  v_my_name text := public._gejast_player_name_from_session(session_token);
  v_yes jsonb := '[]'::jsonb;
  v_no jsonb := '[]'::jsonb;
  v_my_status text;
begin
  select coalesce(jsonb_agg(spv.display_name order by lower(spv.display_name)), '[]'::jsonb)
    into v_yes
  from public.site_poll_votes spv
  where spv.poll_key = v_poll and lower(coalesce(spv.desired_status,'')) = 'ja';

  select coalesce(jsonb_agg(spv.display_name order by lower(spv.display_name)), '[]'::jsonb)
    into v_no
  from public.site_poll_votes spv
  where spv.poll_key = v_poll and lower(coalesce(spv.desired_status,'')) = 'nee';

  if v_my_name is not null then
    select spv.desired_status into v_my_status
    from public.site_poll_votes spv
    where spv.poll_key = v_poll
      and public._gejast_norm_name(spv.display_name) = public._gejast_norm_name(v_my_name)
    order by spv.updated_at desc, spv.id desc
    limit 1;
  end if;

  return jsonb_build_object(
    'poll_key', v_poll,
    'yes_names', v_yes,
    'no_names', v_no,
    'legends', v_yes,
    'losers', v_no,
    'yes_count', jsonb_array_length(v_yes),
    'no_count', jsonb_array_length(v_no),
    'can_count', jsonb_array_length(v_yes),
    'my_name', v_my_name,
    'my_status', v_my_status
  );
end;
$fn$;

create or replace function public.cast_site_poll_vote(
  poll_key_input text,
  session_token text,
  desired_status text
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_poll text := coalesce(nullif(trim(coalesce(poll_key_input,'')), ''), 'gezopen_vanavond');
  v_status text := lower(trim(coalesce(desired_status,'')));
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
begin
  if v_status not in ('ja','nee') then
    raise exception 'desired_status ongeldig';
  end if;
  if v_name is null then
    raise exception 'Log opnieuw in om te stemmen.';
  end if;

  delete from public.site_poll_votes
   where poll_key = v_poll
     and (
       public._gejast_norm_name(display_name) = public._gejast_norm_name(v_name)
       or (v_player_id is not null and player_id = v_player_id)
     );

  insert into public.site_poll_votes(poll_key, player_id, display_name, desired_status, created_at, updated_at)
  values (v_poll, v_player_id, v_name, v_status, now(), now());

  return public.get_site_poll_state(v_poll, session_token);
end;
$fn$;

create or replace function public.remove_my_site_poll_vote(
  poll_key_input text,
  session_token text
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_poll text := coalesce(nullif(trim(coalesce(poll_key_input,'')), ''), 'gezopen_vanavond');
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
begin
  if v_name is null and v_player_id is null then
    raise exception 'Log opnieuw in om je stem te verwijderen.';
  end if;

  delete from public.site_poll_votes
   where poll_key = v_poll
     and (
       (v_name is not null and public._gejast_norm_name(display_name) = public._gejast_norm_name(v_name))
       or (v_player_id is not null and player_id = v_player_id)
     );

  return public.get_site_poll_state(v_poll, session_token);
end;
$fn$;

create or replace function public.admin_remove_site_poll_vote(
  admin_session_token text,
  poll_key_input text,
  display_name_input text
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_poll text := coalesce(nullif(trim(coalesce(poll_key_input,'')), ''), 'gezopen_vanavond');
  v_name text := nullif(trim(coalesce(display_name_input,'')), '');
begin
  perform public.admin_check_session(admin_session_token);
  if v_name is null then
    raise exception 'display_name ontbreekt';
  end if;

  delete from public.site_poll_votes
   where poll_key = v_poll
     and public._gejast_norm_name(display_name) = public._gejast_norm_name(v_name);

  return public.get_site_poll_state(v_poll, null);
end;
$fn$;

create table if not exists public.web_push_subscriptions (
  id bigint generated by default as identity primary key,
  player_id bigint references public.players(id) on delete cascade,
  display_name text,
  endpoint text not null unique,
  p256dh_key text not null,
  auth_key text not null,
  user_agent text,
  permission_state text,
  platform text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  disabled_at timestamptz,
  last_error text
);

create index if not exists web_push_subscriptions_player_idx on public.web_push_subscriptions (player_id, last_seen_at desc);

create table if not exists public.web_push_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'pending',
  target_player_id bigint references public.players(id) on delete set null,
  target_subscription_id bigint references public.web_push_subscriptions(id) on delete cascade,
  title text not null,
  body text not null,
  target_url text,
  payload jsonb not null default '{}'::jsonb,
  claimed_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  error_text text
);

create index if not exists web_push_jobs_status_idx on public.web_push_jobs (status, created_at);

create table if not exists public.web_push_active_presence (
  id bigint generated by default as identity primary key,
  player_id bigint references public.players(id) on delete cascade,
  display_name text not null,
  endpoint text,
  platform text,
  permission_state text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (player_id, endpoint)
);

create index if not exists web_push_active_presence_seen_idx on public.web_push_active_presence (last_seen_at desc);

create or replace function public.register_web_push_subscription(
  session_token text,
  endpoint_input text,
  p256dh_input text,
  auth_input text,
  user_agent_input text default null,
  permission_input text default null,
  platform_input text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_endpoint text := nullif(trim(coalesce(endpoint_input,'')), '');
  v_row public.web_push_subscriptions%rowtype;
begin
  if v_player_id is null or v_name is null then
    raise exception 'Log opnieuw in voor meldingen.';
  end if;
  if v_endpoint is null then
    raise exception 'Push endpoint ontbreekt';
  end if;
  if nullif(trim(coalesce(p256dh_input,'')), '') is null or nullif(trim(coalesce(auth_input,'')), '') is null then
    raise exception 'Push sleutelgegevens ontbreken';
  end if;

  insert into public.web_push_subscriptions(player_id, display_name, endpoint, p256dh_key, auth_key, user_agent, permission_state, platform, created_at, updated_at, last_seen_at, disabled_at, last_error)
  values (v_player_id, v_name, v_endpoint, p256dh_input, auth_input, nullif(trim(coalesce(user_agent_input,'')), ''), nullif(trim(coalesce(permission_input,'')), ''), nullif(trim(coalesce(platform_input,'')), ''), now(), now(), now(), null, null)
  on conflict (endpoint)
  do update set
    player_id = excluded.player_id,
    display_name = excluded.display_name,
    p256dh_key = excluded.p256dh_key,
    auth_key = excluded.auth_key,
    user_agent = excluded.user_agent,
    permission_state = excluded.permission_state,
    platform = excluded.platform,
    updated_at = now(),
    last_seen_at = now(),
    disabled_at = null,
    last_error = null
  returning * into v_row;

  return jsonb_build_object('ok', true, 'subscription_id', v_row.id, 'display_name', v_name);
end;
$fn$;

create or replace function public.touch_active_web_push_presence(
  session_token text,
  endpoint_input text default null,
  permission_input text default null,
  user_agent_input text default null,
  platform_input text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_endpoint text := nullif(trim(coalesce(endpoint_input,'')), '');
begin
  if v_player_id is null or v_name is null then
    raise exception 'Log opnieuw in voor actieve meldingen.';
  end if;

  if v_endpoint is null then
    select s.endpoint into v_endpoint
    from public.web_push_subscriptions s
    where s.player_id = v_player_id and s.disabled_at is null
    order by s.last_seen_at desc, s.id desc
    limit 1;
  end if;

  if v_endpoint is not null then
    update public.web_push_subscriptions
       set last_seen_at = now(),
           updated_at = now(),
           permission_state = coalesce(nullif(trim(coalesce(permission_input,'')), ''), permission_state),
           user_agent = coalesce(nullif(trim(coalesce(user_agent_input,'')), ''), user_agent),
           platform = coalesce(nullif(trim(coalesce(platform_input,'')), ''), platform),
           disabled_at = null
     where endpoint = v_endpoint;
  end if;

  delete from public.web_push_active_presence
   where player_id = v_player_id
     and ((endpoint is null and v_endpoint is null) or endpoint = v_endpoint);

  insert into public.web_push_active_presence(player_id, display_name, endpoint, platform, permission_state, user_agent, created_at, updated_at, last_seen_at)
  values (v_player_id, v_name, v_endpoint, nullif(trim(coalesce(platform_input,'')), ''), nullif(trim(coalesce(permission_input,'')), ''), nullif(trim(coalesce(user_agent_input,'')), ''), now(), now(), now());

  return jsonb_build_object('ok', true, 'display_name', v_name, 'endpoint', v_endpoint);
end;
$fn$;

create or replace function public.admin_get_active_web_push_presence(
  admin_session_token text,
  seen_within_minutes integer default 5
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb := '[]'::jsonb;
  v_cutoff timestamptz := now() - make_interval(mins => greatest(coalesce(seen_within_minutes,5), 1));
begin
  perform public.admin_check_session(admin_session_token);

  select coalesce(jsonb_agg(row_json order by last_seen_at desc, display_name asc), '[]'::jsonb)
    into v_items
  from (
    select
      p.display_name,
      p.player_id,
      max(p.last_seen_at) as last_seen_at,
      count(*)::int as device_count,
      jsonb_agg(distinct jsonb_build_object('endpoint', p.endpoint, 'platform', p.platform, 'permission_state', p.permission_state)) as devices,
      jsonb_build_object(
        'display_name', p.display_name,
        'player_id', p.player_id,
        'last_seen_at', max(p.last_seen_at),
        'device_count', count(*)::int,
        'devices', jsonb_agg(distinct jsonb_build_object('endpoint', p.endpoint, 'platform', p.platform, 'permission_state', p.permission_state))
      ) as row_json
    from public.web_push_active_presence p
    where p.last_seen_at >= v_cutoff
    group by p.display_name, p.player_id
  ) grouped;

  return jsonb_build_object('ok', true, 'count', jsonb_array_length(v_items), 'targets', v_items, 'items', v_items);
end;
$fn$;

create or replace function public.queue_test_web_push(session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_count integer := 0;
begin
  if v_player_id is null or v_name is null then
    raise exception 'Log opnieuw in voor testmeldingen.';
  end if;

  insert into public.web_push_jobs(target_player_id, target_subscription_id, title, body, target_url, payload, created_at, updated_at, status)
  select
    v_player_id,
    s.id,
    'GEJAST testmelding',
    'Je toestel is gekoppeld en klaar voor web-push.',
    './index.html',
    jsonb_build_object('kind','test','display_name',v_name),
    now(),
    now(),
    'pending'
  from public.web_push_subscriptions s
  where s.player_id = v_player_id
    and s.disabled_at is null;

  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count, 'display_name', v_name);
end;
$fn$;

create or replace function public.admin_queue_active_web_push(
  admin_session_token text,
  title_input text,
  body_input text,
  target_url_input text default './index.html',
  seen_within_minutes integer default 5
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_title text := nullif(trim(coalesce(title_input,'')), '');
  v_body text := nullif(trim(coalesce(body_input,'')), '');
  v_count integer := 0;
  v_cutoff timestamptz := now() - make_interval(mins => greatest(coalesce(seen_within_minutes,5), 1));
begin
  perform public.admin_check_session(admin_session_token);
  if v_title is null or v_body is null then
    raise exception 'Geef titel en tekst mee voor de pushmelding.';
  end if;

  insert into public.web_push_jobs(target_player_id, target_subscription_id, title, body, target_url, payload, created_at, updated_at, status)
  select distinct
    s.player_id,
    s.id,
    v_title,
    v_body,
    nullif(trim(coalesce(target_url_input,'')), ''),
    jsonb_build_object('kind','admin_active_broadcast'),
    now(),
    now(),
    'pending'
  from public.web_push_subscriptions s
  join public.web_push_active_presence p
    on p.player_id = s.player_id
   and (p.endpoint is null or p.endpoint = s.endpoint)
  where s.disabled_at is null
    and p.last_seen_at >= v_cutoff;

  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count);
end;
$fn$;

create or replace function public.claim_web_push_jobs(max_jobs integer default 25)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_items jsonb := '[]'::jsonb;
begin
  with picked as (
    select j.id
    from public.web_push_jobs j
    join public.web_push_subscriptions s on s.id = j.target_subscription_id
    where j.status = 'pending'
      and s.disabled_at is null
    order by j.created_at asc, j.id asc
    limit greatest(coalesce(max_jobs,25),1)
    for update of j skip locked
  ), claimed as (
    update public.web_push_jobs j
       set status = 'claimed',
           claimed_at = now(),
           updated_at = now()
     where j.id in (select id from picked)
     returning j.*
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'job_id', c.id,
    'title', c.title,
    'body', c.body,
    'target_url', c.target_url,
    'endpoint', s.endpoint,
    'p256dh_key', s.p256dh_key,
    'auth_key', s.auth_key,
    'display_name', s.display_name
  ) order by c.created_at asc, c.id asc), '[]'::jsonb)
    into v_items
  from claimed c
  join public.web_push_subscriptions s on s.id = c.target_subscription_id;

  return jsonb_build_object('items', v_items);
end;
$fn$;

create or replace function public.mark_web_push_job_sent(job_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  update public.web_push_jobs
     set status = 'sent',
         sent_at = now(),
         updated_at = now(),
         error_text = null
   where id = job_id_input;
  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$fn$;

create or replace function public.mark_web_push_job_failed(job_id_input bigint, error_input text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_sub_id bigint;
  v_err text := left(coalesce(error_input,''), 1200);
begin
  update public.web_push_jobs
     set status = 'failed',
         failed_at = now(),
         updated_at = now(),
         error_text = v_err
   where id = job_id_input
   returning target_subscription_id into v_sub_id;

  if v_sub_id is not null and (v_err ilike '%410%' or v_err ilike '%404%' or v_err ilike '%unsub%' or v_err ilike '%gone%') then
    update public.web_push_subscriptions
       set disabled_at = now(),
           last_error = v_err,
           updated_at = now()
     where id = v_sub_id;
  elsif v_sub_id is not null then
    update public.web_push_subscriptions
       set last_error = v_err,
           updated_at = now()
     where id = v_sub_id;
  end if;

  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$fn$;

create or replace function public._gejast_summary_rows(include_live boolean default true)
returns table(
  game_key text,
  match_ref text,
  created_at timestamptz,
  finished_at timestamptz,
  participants text[],
  winner_names text[],
  recap_text text,
  summary_payload jsonb,
  is_live boolean
)
language sql
stable
as $$
  with rows as (
    select
      lower(s.game_type) as game_key,
      s.client_match_id as match_ref,
      s.created_at,
      s.finished_at,
      public._gejast_summary_participants(s.summary_payload, s.participant_names) as participants,
      public._gejast_summary_winners(s.summary_payload, s.winner_names) as winner_names,
      coalesce(nullif(trim(coalesce(s.summary_payload->>'recap_text','')), ''), s.recap_text) as recap_text,
      coalesce(s.summary_payload, '{}'::jsonb) as summary_payload,
      (s.finished_at is null) as is_live
    from public.game_match_summaries s
    where lower(coalesce(s.game_type,'')) in ('klaverjas','boerenbridge')
  )
  select *
  from rows r
  where (
    r.game_key = 'klaverjas'
    and coalesce(array_length(r.participants,1),0) = 4
    and (include_live or r.finished_at is not null)
    and (r.is_live or public._gejast_round_count(r.summary_payload) > 0)
  )
  or (
    r.game_key = 'boerenbridge'
    and coalesce(array_length(r.participants,1),0) >= 3
    and (include_live or r.finished_at is not null)
    and (r.is_live or public._gejast_round_count(r.summary_payload) > 0)
  )
$$;

create or replace function public._gejast_summary_player_rows(include_live boolean default false)
returns table(
  game_key text,
  match_ref text,
  created_at timestamptz,
  finished_at timestamptz,
  player_name text,
  is_win boolean,
  recap_text text,
  participants text[],
  winner_names text[],
  summary_payload jsonb,
  is_live boolean
)
language sql
stable
as $$
  select
    r.game_key,
    r.match_ref,
    r.created_at,
    r.finished_at,
    p.player_name,
    exists(select 1 from unnest(r.winner_names) w where public._gejast_norm_name(w) = public._gejast_norm_name(p.player_name)) as is_win,
    r.recap_text,
    r.participants,
    r.winner_names,
    r.summary_payload,
    r.is_live
  from public._gejast_summary_rows(include_live) r
  cross join lateral unnest(r.participants) as p(player_name)
$$;

create or replace function public._gejast_beerpong_player_rows()
returns table(
  match_ref text,
  finished_at timestamptz,
  player_name text,
  is_win boolean,
  participants text[],
  winner_names text[],
  summary_payload jsonb
)
language sql
stable
as $$
  select
    m.client_match_id as match_ref,
    coalesce(m.finished_at, m.created_at) as finished_at,
    p.display_name as player_name,
    case
      when lower(coalesce(m.winner_team,'')) = 'team_a' and p.id = any(m.team_a_player_ids) then true
      when lower(coalesce(m.winner_team,'')) = 'team_b' and p.id = any(m.team_b_player_ids) then true
      else false
    end as is_win,
    array(
      select p2.display_name
      from public.players p2
      where p2.id = any(m.team_a_player_ids) or p2.id = any(m.team_b_player_ids)
      order by case when p2.id = any(m.team_a_player_ids) then array_position(m.team_a_player_ids, p2.id) else 100 + array_position(m.team_b_player_ids, p2.id) end
    ) as participants,
    case
      when lower(coalesce(m.winner_team,'')) = 'team_a' then array(
        select p2.display_name from public.players p2 where p2.id = any(m.team_a_player_ids) order by array_position(m.team_a_player_ids, p2.id)
      )
      when lower(coalesce(m.winner_team,'')) = 'team_b' then array(
        select p2.display_name from public.players p2 where p2.id = any(m.team_b_player_ids) order by array_position(m.team_b_player_ids, p2.id)
      )
      else '{}'::text[]
    end as winner_names,
    jsonb_build_object(
      'match_format', m.match_format,
      'cups_left_team_a', m.cups_left_team_a,
      'cups_left_team_b', m.cups_left_team_b,
      'payload', coalesce(m.payload, '{}'::jsonb)
    ) as summary_payload
  from public.beerpong_matches m
  join public.players p
    on p.id = any(m.team_a_player_ids)
    or p.id = any(m.team_b_player_ids)
  where lower(coalesce(m.match_status,'finished')) = 'finished'
$$;

create or replace function public.get_live_match_summary_public(
  game_type_input text,
  match_ref_input text default null,
  session_token text default null
) returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_game text := lower(trim(coalesce(game_type_input,'')));
  v_match_ref text := nullif(trim(coalesce(match_ref_input,'')), '');
  v_name text := public._gejast_player_name_from_session(session_token);
  v_item jsonb;
begin
  if v_game not in ('klaverjas','boerenbridge') then
    raise exception 'game_type ongeldig';
  end if;

  if v_match_ref is null and v_name is not null then
    select r.match_ref into v_match_ref
    from public._gejast_summary_rows(true) r
    where r.game_key = v_game
      and r.is_live = true
      and exists (select 1 from unnest(r.participants) p where public._gejast_norm_name(p) = public._gejast_norm_name(v_name))
    order by r.created_at desc
    limit 1;
  end if;

  if v_match_ref is null then
    raise exception 'match_ref ontbreekt';
  end if;

  select jsonb_build_object(
    'ok', true,
    'game_type', r.game_key,
    'match_ref', r.match_ref,
    'created_at', r.created_at,
    'updated_at', coalesce(nullif(r.summary_payload->'live_state'->>'updated_at','')::timestamptz, r.finished_at, r.created_at),
    'finished_at', r.finished_at,
    'is_live', r.is_live,
    'participants', to_jsonb(r.participants),
    'winner_names', to_jsonb(r.winner_names),
    'recap_text', r.recap_text,
    'summary', r.summary_payload,
    'item', jsonb_build_object(
      'game_type', r.game_key,
      'match_ref', r.match_ref,
      'created_at', r.created_at,
      'updated_at', coalesce(nullif(r.summary_payload->'live_state'->>'updated_at','')::timestamptz, r.finished_at, r.created_at),
      'finished_at', r.finished_at,
      'is_live', r.is_live,
      'participants', to_jsonb(r.participants),
      'winner_names', to_jsonb(r.winner_names),
      'recap_text', r.recap_text,
      'summary', r.summary_payload,
      'summary_payload', r.summary_payload
    )
  ) into v_item
  from public._gejast_summary_rows(true) r
  where r.game_key = v_game
    and r.match_ref = v_match_ref
  order by r.created_at desc
  limit 1;

  if v_item is null then
    raise exception 'Live samenvatting niet gevonden.';
  end if;

  return v_item;
end;
$fn$;

create or replace function public.get_homepage_live_state_public(session_token text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_name text := public._gejast_player_name_from_session(session_token);
  v_kl jsonb;
  v_bb jsonb;
begin
  if v_name is not null then
    select jsonb_build_object(
      'is_live', true,
      'match_ref', r.match_ref,
      'href', './klaverjas_live.html?match_ref=' || r.match_ref,
      'label', 'Klaverjas Live',
      'copy', 'Bekijk live scoreblad van jouw huidige potje.',
      'participants', to_jsonb(r.participants)
    ) into v_kl
    from public._gejast_summary_rows(true) r
    where r.game_key = 'klaverjas'
      and r.is_live = true
      and exists (select 1 from unnest(r.participants) p where public._gejast_norm_name(p) = public._gejast_norm_name(v_name))
    order by r.created_at desc
    limit 1;

    select jsonb_build_object(
      'is_live', true,
      'match_ref', r.match_ref,
      'href', './boerenbridge_live.html?match_ref=' || r.match_ref,
      'label', 'Boerenbridge Live',
      'copy', 'Bekijk live scoreblad van jouw huidige potje.',
      'participants', to_jsonb(r.participants)
    ) into v_bb
    from public._gejast_summary_rows(true) r
    where r.game_key = 'boerenbridge'
      and r.is_live = true
      and exists (select 1 from unnest(r.participants) p where public._gejast_norm_name(p) = public._gejast_norm_name(v_name))
    order by r.created_at desc
    limit 1;
  end if;

  return jsonb_build_object(
    'entries', jsonb_build_object(
      'klaverjas', coalesce(v_kl, jsonb_build_object('is_live', false)),
      'boerenbridge', coalesce(v_bb, jsonb_build_object('is_live', false))
    ),
    'by_game', jsonb_build_object(
      'klaverjas', coalesce(v_kl, jsonb_build_object('is_live', false)),
      'boerenbridge', coalesce(v_bb, jsonb_build_object('is_live', false))
    )
  );
end;
$fn$;

create or replace function public._gejast_public_game_bundle(game_key_input text, player_name_input text)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_game text := lower(trim(coalesce(game_key_input,'')));
  v_name text := public._gejast_resolve_player_name(player_name_input);
  v_summary jsonb := '{}'::jsonb;
  v_matches jsonb := '[]'::jsonb;
  v_rating numeric := 1000;
  v_badge text := 'Starter';
  v_games integer := 0;
  v_wins integer := 0;
  v_losses integer := 0;
  v_win_pct numeric := 0;
begin
  if v_name is null then
    return jsonb_build_object('player_name', null, 'badge', 'Starter', 'summary', jsonb_build_object('games_played',0,'matches_played',0,'wins',0,'losses',0,'win_pct',0,'elo_rating',1000), 'matches', '[]'::jsonb);
  end if;

  if v_game in ('klaverjas','boerenbridge') then
    with rows as (
      select *
      from public._gejast_summary_player_rows(false)
      where game_key = v_game
        and public._gejast_norm_name(player_name) = public._gejast_norm_name(v_name)
    ), agg as (
      select
        count(*)::int as games_played,
        count(*) filter (where is_win)::int as wins,
        count(*) filter (where not is_win)::int as losses
      from rows
    )
    select
      coalesce(a.games_played,0),
      coalesce(a.wins,0),
      coalesce(a.losses,0),
      coalesce(jsonb_agg(jsonb_build_object(
        'finished_at', r.finished_at,
        'winner_names', to_jsonb(r.winner_names),
        'participants', to_jsonb(r.participants),
        'player_result', case when r.is_win then 'win' when coalesce(array_length(r.winner_names,1),0) = 0 or coalesce(array_length(r.winner_names,1),0) = coalesce(array_length(r.participants,1),0) then 'draw' else 'loss' end,
        'elo_delta', 0,
        'scoreline', case
          when v_game = 'klaverjas' then coalesce(r.summary_payload->'totals'->>'wij','0') || ' - ' || coalesce(r.summary_payload->'totals'->>'zij','0')
          else coalesce(r.summary_payload->'match_summary'->>'top_score', r.summary_payload->>'top_score', '')
        end,
        'recap_text', r.recap_text,
        'details', '[]'::jsonb
      ) order by r.finished_at desc, r.match_ref desc), '[]'::jsonb)
    into v_games, v_wins, v_losses, v_matches
    from agg a
    left join rows r on true
    group by a.games_played, a.wins, a.losses;

    v_win_pct := case when v_games > 0 then round((100.0 * v_wins) / v_games, 1) else 0 end;
    v_rating := 1000;
  elsif v_game = 'beerpong' then
    with rows as (
      select *
      from public._gejast_beerpong_player_rows()
      where public._gejast_norm_name(player_name) = public._gejast_norm_name(v_name)
    ), agg as (
      select
        count(*)::int as games_played,
        count(*) filter (where is_win)::int as wins,
        count(*) filter (where not is_win)::int as losses
      from rows
    )
    select
      coalesce(a.games_played,0),
      coalesce(a.wins,0),
      coalesce(a.losses,0),
      coalesce(jsonb_agg(jsonb_build_object(
        'finished_at', r.finished_at,
        'winner_names', to_jsonb(r.winner_names),
        'participants', to_jsonb(r.participants),
        'player_result', case when r.is_win then 'win' else 'loss' end,
        'elo_delta', 0,
        'scoreline', case when lower(coalesce(r.summary_payload->>'match_format','2v2')) = '1v1' then '1v1' else '2v2' end,
        'recap_text', case when r.is_win then 'Beerpong winst.' else 'Beerpong verlies.' end,
        'details', '[]'::jsonb
      ) order by r.finished_at desc, r.match_ref desc), '[]'::jsonb)
    into v_games, v_wins, v_losses, v_matches
    from agg a
    left join rows r on true
    group by a.games_played, a.wins, a.losses;

    select coalesce(rating,1000) into v_rating
    from public.beerpong_player_ratings bpr
    join public.players p on p.id = bpr.player_id
    where public._gejast_norm_name(p.display_name) = public._gejast_norm_name(v_name)
    order by bpr.updated_at desc nulls last
    limit 1;
    v_win_pct := case when v_games > 0 then round((100.0 * v_wins) / v_games, 1) else 0 end;
  else
    return jsonb_build_object('player_name', v_name, 'badge', 'Starter', 'summary', jsonb_build_object('games_played',0,'matches_played',0,'wins',0,'losses',0,'win_pct',0,'elo_rating',1000), 'matches', '[]'::jsonb);
  end if;

  v_badge := public._gejast_public_badge(v_games, v_win_pct);
  v_summary := jsonb_build_object(
    'games_played', v_games,
    'matches_played', v_games,
    'wins', v_wins,
    'losses', v_losses,
    'win_pct', v_win_pct,
    'elo_rating', round(coalesce(v_rating,1000))
  );

  return jsonb_build_object(
    'player_name', v_name,
    'badge', v_badge,
    'summary', v_summary,
    'matches', coalesce(v_matches, '[]'::jsonb)
  );
end;
$fn$;

create or replace function public.get_public_shared_player_stats(game_key text, player_name text)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_bundle jsonb := public._gejast_public_game_bundle(game_key, player_name);
  v_recent_form text := '—';
  v_activity_30d integer := 0;
  v_results text[] := '{}'::text[];
begin
  select coalesce(array_agg(case
    when coalesce(m->>'player_result','') = 'win' then 'W'
    when coalesce(m->>'player_result','') = 'draw' then 'G'
    when coalesce(m->>'player_result','') = 'loss' then 'L'
    else '—'
  end), '{}'::text[])
    into v_results
  from jsonb_array_elements(coalesce(v_bundle->'matches', '[]'::jsonb)) with ordinality as rows(m, ord)
  where ord <= 5;

  select count(*)::int into v_activity_30d
  from jsonb_array_elements(coalesce(v_bundle->'matches', '[]'::jsonb)) as rows(m)
  where nullif(rows.m->>'finished_at','')::timestamptz >= now() - interval '30 days';

  if coalesce(array_length(v_results,1),0) > 0 then
    v_recent_form := array_to_string(v_results, '');
  end if;

  return jsonb_build_object(
    'recent_form', v_recent_form,
    'activity_30d', coalesce(v_activity_30d,0),
    'biggest_gain', 0,
    'biggest_drop', 0,
    'volatility', 0
  );
end;
$fn$;

create or replace function public.get_public_player_game_insights(game_key text, player_name text)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_bundle jsonb := public._gejast_public_game_bundle(game_key, player_name);
  v_cards jsonb := '[]'::jsonb;
  v_last jsonb;
  v_best_score text := '—';
  v_total_wins integer := coalesce((v_bundle->'summary'->>'wins')::integer, 0);
  v_total_games integer := coalesce((v_bundle->'summary'->>'games_played')::integer, 0);
begin
  select m into v_last
  from jsonb_array_elements(coalesce(v_bundle->'matches', '[]'::jsonb)) as rows(m)
  limit 1;

  if lower(coalesce(game_key,'')) = 'boerenbridge' then
    select coalesce(max(nullif(m->>'scoreline','')), '—') into v_best_score
    from jsonb_array_elements(coalesce(v_bundle->'matches', '[]'::jsonb)) as rows(m);
  elsif lower(coalesce(game_key,'')) = 'klaverjas' then
    select coalesce(max(nullif(m->>'scoreline','')), '—') into v_best_score
    from jsonb_array_elements(coalesce(v_bundle->'matches', '[]'::jsonb)) as rows(m);
  elsif lower(coalesce(game_key,'')) = 'beerpong' then
    v_best_score := coalesce(v_bundle->'summary'->>'elo_rating', '1000');
  end if;

  v_cards := jsonb_build_array(
    jsonb_build_object('label','Laatste pot','value',coalesce(to_char(nullif(v_last->>'finished_at','')::timestamptz at time zone 'Europe/Amsterdam','DD-MM HH24:MI'),'Nog geen data'), 'sub', coalesce(v_last->>'player_result','')),
    jsonb_build_object('label','Gewonnen potjes','value', v_total_wins, 'sub', format('%s totaal gespeeld', v_total_games)),
    jsonb_build_object('label', case when lower(coalesce(game_key,'')) = 'beerpong' then 'Huidige rating' else 'Beste scorelijn' end, 'value', v_best_score)
  );

  return jsonb_build_object('cards', v_cards);
end;
$fn$;

create or replace function public.get_public_player_unified(player_name text)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_name text := public._gejast_resolve_player_name(player_name);
  v_player public.players%rowtype;
  v_profile public.player_profiles%rowtype;
  v_kl jsonb;
  v_bb jsonb;
  v_bp jsonb;
  v_total_matches integer;
  v_best_badge text;
begin
  if v_name is null then
    raise exception 'player_name ontbreekt';
  end if;

  select * into v_player
  from public.players p
  where public._gejast_norm_name(p.display_name) = public._gejast_norm_name(v_name)
  order by p.id
  limit 1;

  if found then
    select * into v_profile from public.player_profiles pp where pp.player_id = v_player.id;
    v_name := v_player.display_name;
  end if;

  v_kl := public._gejast_public_game_bundle('klaverjas', v_name);
  v_bb := public._gejast_public_game_bundle('boerenbridge', v_name);
  v_bp := public._gejast_public_game_bundle('beerpong', v_name);

  v_total_matches := coalesce((v_kl->'summary'->>'games_played')::integer,0) + coalesce((v_bb->'summary'->>'games_played')::integer,0) + coalesce((v_bp->'summary'->>'games_played')::integer,0);
  v_best_badge := public._gejast_public_badge(v_total_matches, greatest(coalesce((v_kl->'summary'->>'win_pct')::numeric,0), coalesce((v_bb->'summary'->>'win_pct')::numeric,0), coalesce((v_bp->'summary'->>'win_pct')::numeric,0)));

  return jsonb_build_object(
    'player_name', v_name,
    'overview', jsonb_build_object(
      'total_matches', v_total_matches,
      'best_badge', v_best_badge,
      'profile_picture_url', v_profile.profile_picture_url,
      'favorite_game', v_profile.favorite_game,
      'bio', v_profile.bio
    ),
    'games', jsonb_build_object(
      'klaverjas', jsonb_build_object('player_name', v_name, 'badge', coalesce(v_kl->>'badge','Starter'), 'summary', coalesce(v_kl->'summary','{}'::jsonb), 'matches', coalesce(v_kl->'matches','[]'::jsonb)),
      'boerenbridge', jsonb_build_object('player_name', v_name, 'badge', coalesce(v_bb->>'badge','Starter'), 'summary', coalesce(v_bb->'summary','{}'::jsonb), 'matches', coalesce(v_bb->'matches','[]'::jsonb)),
      'beerpong', jsonb_build_object('player_name', v_name, 'badge', coalesce(v_bp->>'badge','Starter'), 'summary', coalesce(v_bp->'summary','{}'::jsonb), 'matches', coalesce(v_bp->'matches','[]'::jsonb))
    )
  );
end;
$fn$;

create or replace function public.get_all_site_players_public()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v_players jsonb := '[]'::jsonb;
begin
  with summary_counts as (
    select
      spr.player_name,
      count(*)::int as total_summary_matches,
      count(*) filter (where spr.is_win)::int as total_summary_wins,
      count(*) filter (where spr.game_key = 'klaverjas')::int as klaverjas_matches,
      count(*) filter (where spr.game_key = 'boerenbridge')::int as boerenbridge_matches
    from public._gejast_summary_player_rows(false) spr
    group by spr.player_name
  ), beerpong_counts as (
    select
      bpr.player_name,
      count(*)::int as beerpong_matches,
      count(*) filter (where bpr.is_win)::int as beerpong_wins
    from public._gejast_beerpong_player_rows() bpr
    group by bpr.player_name
  ), merged as (
    select
      p.id,
      p.display_name,
      pp.profile_picture_url,
      pp.favorite_game,
      coalesce(sc.total_summary_matches,0) + coalesce(bp.beerpong_matches,0) as total_matches,
      coalesce(sc.total_summary_wins,0) + coalesce(bp.beerpong_wins,0) as total_wins,
      coalesce(sc.klaverjas_matches,0) as klaverjas_matches,
      coalesce(sc.boerenbridge_matches,0) as boerenbridge_matches,
      coalesce(bp.beerpong_matches,0) as beerpong_matches,
      coalesce(round((select rating from public.beerpong_player_ratings r where r.player_id = p.id),0),1000) as best_rating,
      public._gejast_public_badge(
        coalesce(sc.total_summary_matches,0) + coalesce(bp.beerpong_matches,0),
        case when (coalesce(sc.total_summary_matches,0) + coalesce(bp.beerpong_matches,0)) > 0 then
          (100.0 * (coalesce(sc.total_summary_wins,0) + coalesce(bp.beerpong_wins,0))) / (coalesce(sc.total_summary_matches,0) + coalesce(bp.beerpong_matches,0))
        else 0 end
      ) as best_badge
    from public.players p
    left join public.player_profiles pp on pp.player_id = p.id
    left join summary_counts sc on public._gejast_norm_name(sc.player_name) = public._gejast_norm_name(p.display_name)
    left join beerpong_counts bp on public._gejast_norm_name(bp.player_name) = public._gejast_norm_name(p.display_name)
    where nullif(trim(coalesce(p.display_name,'')), '') is not null
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'player_name', m.display_name,
    'display_name', m.display_name,
    'public_display_name', m.display_name,
    'profile_picture_url', m.profile_picture_url,
    'favorite_game', coalesce(m.favorite_game, case when m.beerpong_matches > greatest(m.klaverjas_matches, m.boerenbridge_matches) then 'Beerpong' when m.boerenbridge_matches > m.klaverjas_matches then 'Boerenbridge' when m.klaverjas_matches > 0 then 'Klaverjas' else null end),
    'total_matches', m.total_matches,
    'total_wins', m.total_wins,
    'best_rating', m.best_rating,
    'best_badge', m.best_badge,
    'klaverjas_matches', m.klaverjas_matches,
    'boerenbridge_matches', m.boerenbridge_matches,
    'beerpong_matches', m.beerpong_matches
  ) order by m.total_matches desc, lower(m.display_name) asc), '[]'::jsonb)
    into v_players
  from merged m;

  return jsonb_build_object('players', v_players);
end;
$fn$;

commit;
