begin;

-- Live summaries remain the canonical live-state source for homepage LIVE buttons and spectator pages.
create or replace function public.get_live_match_summaries_scoped(session_token text default null, game_type_input text default null, site_scope_input text default 'friends', client_match_id_input text default null)
returns jsonb
language plpgsql
security definer
as $$
declare viewer_name text; scope_norm text := public._gejast_live_scope_norm(site_scope_input); out_matches jsonb;
begin
  viewer_name := public._gejast_name_for_session(session_token);
  if viewer_name is null then raise exception 'Je moet ingelogd zijn om live scoreformulieren te bekijken.'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'game_type', g.game_type,
    'client_match_id', g.client_match_id,
    'site_scope', coalesce(g.site_scope, 'friends'),
    'participants', to_jsonb(coalesce(nullif(g.participant_names, '{}'::text[]), coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(g.summary_payload->'participants','[]'::jsonb))), '{}'::text[]), coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(g.summary_payload->'players','[]'::jsonb))), '{}'::text[]))),
    'winner_names', to_jsonb(coalesce(g.winner_names, '{}'::text[])),
    'submitter_name', coalesce(g.summary_payload->'submitter_meta'->>'submitted_by_name', null),
    'summary_payload', g.summary_payload,
    'created_at', g.created_at,
    'updated_at', coalesce(g.finished_at, g.created_at)
  ) order by coalesce(g.finished_at, g.created_at) desc), '[]'::jsonb)
  into out_matches
  from public.game_match_summaries g
  where (nullif(trim(coalesce(game_type_input,'')), '') is null or lower(g.game_type)=lower(trim(game_type_input)))
    and coalesce(lower(g.site_scope), 'friends') = scope_norm
    and (nullif(trim(coalesce(client_match_id_input,'')), '') is null or g.client_match_id = trim(client_match_id_input))
    and coalesce(g.finished_at, nullif(g.summary_payload->>'finished_at','')::timestamptz) is null;
  return jsonb_build_object('viewer_name', viewer_name, 'site_scope', scope_norm, 'matches', coalesce(out_matches, '[]'::jsonb));
end; $$;
grant execute on function public.get_live_match_summaries_scoped(text,text,text,text) to anon, authenticated;

-- Safe ballroom write path with explicit row targeting.
create table if not exists public.ballroom_safe_state (id integer primary key default 1 check (id = 1), king_name text, king_avatar_url text, claimed_at timestamptz, updated_at timestamptz not null default now());
create table if not exists public.ballroom_safe_members (player_name text primary key, avatar_url text, approved_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ballroom_safe_requests (id bigint generated by default as identity primary key, player_name text not null, avatar_url text, requested_at timestamptz not null default now(), status text not null default 'pending', resolved_at timestamptz);
create unique index if not exists ballroom_safe_requests_pending_name_idx on public.ballroom_safe_requests (lower(player_name), status);
create or replace function public._ballroom_safe_token(session_token text default null, session_token_input text default null) returns text language sql immutable as $$ select nullif(trim(coalesce(session_token, session_token_input, '')), '') $$;
create or replace function public._ballroom_safe_require_name(session_token text default null, session_token_input text default null) returns text language plpgsql security definer as $$ declare viewer text := public._gejast_name_for_session(public._ballroom_safe_token(session_token, session_token_input)); begin if viewer is null then raise exception 'Log eerst in als speler.'; end if; return viewer; end; $$;
create or replace function public.get_ballroom_public_state_safe(session_token text default null, session_token_input text default null) returns jsonb language plpgsql security definer as $$ declare viewer_name text := public._gejast_name_for_session(public._ballroom_safe_token(session_token, session_token_input)); king_name text; king_avatar text; approved_members jsonb; pending_requests jsonb; succession_line jsonb; begin select s.king_name, s.king_avatar_url into king_name, king_avatar from public.ballroom_safe_state s where s.id = 1; select coalesce(jsonb_agg(jsonb_build_object('display_name', m.player_name, 'avatar_url', m.avatar_url) order by m.approved_at), '[]'::jsonb) into approved_members from public.ballroom_safe_members m; select coalesce(jsonb_agg(x.obj order by x.approved_at), '[]'::jsonb) into succession_line from (select jsonb_build_object('display_name', m.player_name, 'avatar_url', m.avatar_url) as obj, m.approved_at from public.ballroom_safe_members m where coalesce(lower(m.player_name),'') <> coalesce(lower(king_name),'') order by m.approved_at limit 3) x; select coalesce(jsonb_agg(jsonb_build_object('id', r.id, 'display_name', r.player_name, 'avatar_url', r.avatar_url, 'requested_at', r.requested_at) order by r.requested_at), '[]'::jsonb) into pending_requests from public.ballroom_safe_requests r where r.status='pending'; return jsonb_build_object('has_king', nullif(trim(coalesce(king_name,'')), '') is not null, 'king', case when nullif(trim(coalesce(king_name,'')), '') is not null then jsonb_build_object('display_name', king_name, 'avatar_url', king_avatar) else null end, 'approved_members', approved_members, 'succession_line', succession_line, 'pending_requests', pending_requests, 'viewer', jsonb_build_object('display_name', viewer_name, 'is_king', viewer_name is not null and lower(viewer_name)=lower(coalesce(king_name,'')), 'is_member', viewer_name is not null and exists(select 1 from public.ballroom_safe_members m where lower(m.player_name)=lower(viewer_name)), 'pending', viewer_name is not null and exists(select 1 from public.ballroom_safe_requests r where lower(r.player_name)=lower(viewer_name) and r.status='pending'))); end; $$;
create or replace function public.get_ballroom_state_safe(session_token text default null, session_token_input text default null) returns jsonb language sql security definer as $$ select public.get_ballroom_public_state_safe(session_token, session_token_input) $$;
create or replace function public.ballroom_claim_king_safe(session_token text default null, session_token_input text default null) returns jsonb language plpgsql security definer as $$ declare viewer_name text := public._ballroom_safe_require_name(session_token, session_token_input); current_king text; begin select king_name into current_king from public.ballroom_safe_state where id = 1; if nullif(trim(coalesce(current_king,'')), '') is not null and lower(current_king) <> lower(viewer_name) then raise exception 'Er is al een koning in de balzaal.'; end if; insert into public.ballroom_safe_state(id, king_name, claimed_at, updated_at) values (1, viewer_name, now(), now()) on conflict (id) do update set king_name = excluded.king_name, claimed_at = coalesce(public.ballroom_safe_state.claimed_at, now()), updated_at = now(); insert into public.ballroom_safe_members(player_name, approved_at, updated_at) values (viewer_name, now(), now()) on conflict (player_name) do update set updated_at = now(); return public.get_ballroom_public_state_safe(session_token, session_token_input); end; $$;
create or replace function public.ballroom_request_entry_safe(session_token text default null, session_token_input text default null) returns jsonb language plpgsql security definer as $$ declare viewer_name text := public._ballroom_safe_require_name(session_token, session_token_input); begin if not exists(select 1 from public.ballroom_safe_state where id = 1 and nullif(trim(coalesce(king_name,'')), '') is not null) then raise exception 'Er is nog geen koning in de balzaal.'; end if; if exists(select 1 from public.ballroom_safe_members m where lower(m.player_name)=lower(viewer_name)) then raise exception 'Je staat al in de balzaal.'; end if; if exists(select 1 from public.ballroom_safe_requests r where lower(r.player_name)=lower(viewer_name) and r.status='pending') then raise exception 'Jouw entreeverzoek staat al open.'; end if; insert into public.ballroom_safe_requests(player_name, requested_at, status) values (viewer_name, now(), 'pending'); return public.get_ballroom_public_state_safe(session_token, session_token_input); end; $$;
create or replace function public.ballroom_resolve_request_safe(session_token text default null, session_token_input text default null, request_id_input bigint default null, approve_input boolean default false) returns jsonb language plpgsql security definer as $$ declare viewer_name text := public._ballroom_safe_require_name(session_token, session_token_input); king_name text; req_name text; begin select s.king_name into king_name from public.ballroom_safe_state s where s.id = 1; if lower(coalesce(king_name,'')) <> lower(coalesce(viewer_name,'')) then raise exception 'Alleen de koning mag verzoeken beoordelen.'; end if; if request_id_input is null then raise exception 'Er ontbreekt een verzoek-id.'; end if; select r.player_name into req_name from public.ballroom_safe_requests r where r.id = request_id_input and r.status='pending'; if req_name is null then raise exception 'Dit entreeverzoek is niet meer actief.'; end if; update public.ballroom_safe_requests set status = case when approve_input then 'approved' else 'rejected' end, resolved_at = now() where id = request_id_input and status='pending'; if approve_input then insert into public.ballroom_safe_members(player_name, approved_at, updated_at) values (req_name, now(), now()) on conflict (player_name) do update set updated_at = now(); end if; return public.get_ballroom_public_state_safe(session_token, session_token_input); end; $$;
create or replace function public.ballroom_abdicate_safe(session_token text default null, session_token_input text default null) returns jsonb language plpgsql security definer as $$ declare viewer_name text := public._ballroom_safe_require_name(session_token, session_token_input); current_king text; successor text; begin select king_name into current_king from public.ballroom_safe_state where id = 1; if lower(coalesce(current_king,'')) <> lower(coalesce(viewer_name,'')) then raise exception 'Alleen de koning kan afstand doen van de kroon.'; end if; select m.player_name into successor from public.ballroom_safe_members m where lower(m.player_name) <> lower(viewer_name) order by m.approved_at limit 1; update public.ballroom_safe_state set king_name = successor, claimed_at = case when successor is null then null else now() end, updated_at = now() where id = 1; return public.get_ballroom_public_state_safe(session_token, session_token_input); end; $$;
grant execute on function public.get_ballroom_public_state_safe(text,text) to anon, authenticated;
grant execute on function public.get_ballroom_state_safe(text,text) to anon, authenticated;
grant execute on function public.ballroom_claim_king_safe(text,text) to anon, authenticated;
grant execute on function public.ballroom_request_entry_safe(text,text) to anon, authenticated;
grant execute on function public.ballroom_resolve_request_safe(text,text,bigint,boolean) to anon, authenticated;
grant execute on function public.ballroom_abdicate_safe(text,text) to anon, authenticated;

-- Beerpong pussycup stats and public ranking.
create or replace function public.get_beerpong_player_pussycup_public(player_name text)
returns jsonb
language sql
security definer
set search_path to 'public'
as $fn$
with target as (
  select id, display_name
  from public.players
  where lower(display_name) = lower(trim(player_name))
  limit 1
), finished_matches as (
  select m.*,
         coalesce((m.payload->>'team_a_pussycup')::boolean, false) as team_a_pussycup,
         coalesce((m.payload->>'team_b_pussycup')::boolean, false) as team_b_pussycup,
         case
           when exists (select 1 from target t where t.id = any(coalesce(m.team_a_player_ids, '{}'::bigint[]))) then 'a'
           when exists (select 1 from target t where t.id = any(coalesce(m.team_b_player_ids, '{}'::bigint[]))) then 'b'
           else null
         end as side
  from public.beerpong_matches m
  where coalesce(m.deleted_at is null, true)
    and coalesce(m.match_status, 'finished') = 'finished'
), relevant as (
  select *
  from finished_matches
  where side is not null
), summary as (
  select
    count(*)::int as matches,
    count(*) filter (where (side = 'a' and team_a_pussycup) or (side = 'b' and team_b_pussycup))::int as pussycup_hits,
    count(*) filter (where winner_team = side)::int as wins,
    round(
      case when count(*) = 0 then 0
      else 100.0 * count(*) filter (where (side = 'a' and team_a_pussycup) or (side = 'b' and team_b_pussycup)) / count(*)
      end
    , 1) as pussycup_pct
  from relevant
), recent as (
  select jsonb_agg(
    jsonb_build_object(
      'finished_at', coalesce(finished_at, created_at),
      'side', side,
      'pussycup', case when side = 'a' then team_a_pussycup else team_b_pussycup end,
      'won', winner_team = side,
      'teammates', case when side = 'a' then coalesce(payload->'team_a_player_names', '[]'::jsonb) else coalesce(payload->'team_b_player_names', '[]'::jsonb) end,
      'opponents', case when side = 'a' then coalesce(payload->'team_b_player_names', '[]'::jsonb) else coalesce(payload->'team_a_player_names', '[]'::jsonb) end
    )
    order by coalesce(finished_at, created_at) desc
  ) as items
  from (select * from relevant order by coalesce(finished_at, created_at) desc limit 8) r
)
select jsonb_build_object(
  'player_name', coalesce((select display_name from target), trim(player_name)),
  'summary', jsonb_build_object(
    'matches', coalesce((select matches from summary), 0),
    'wins', coalesce((select wins from summary), 0),
    'pussycup_hits', coalesce((select pussycup_hits from summary), 0),
    'pussycup_pct', coalesce((select pussycup_pct from summary), 0)
  ),
  'recent', coalesce((select items from recent), '[]'::jsonb)
);
$fn$;
grant execute on function public.get_beerpong_player_pussycup_public(text) to anon, authenticated;

drop function if exists public.get_beerpong_pussycup_ranking_public();
create or replace function public.get_beerpong_pussycup_ranking_public()
returns jsonb
language sql
security definer
set search_path to 'public'
as $fn$
with matches_base as (
  select
    m.*,
    coalesce((m.payload->>'team_a_pussycup')::boolean, false) as team_a_pussycup,
    coalesce((m.payload->>'team_b_pussycup')::boolean, false) as team_b_pussycup,
    coalesce(m.payload->'team_a_player_names', m.payload->'team_a_names', '[]'::jsonb) as team_a_names_json,
    coalesce(m.payload->'team_b_player_names', m.payload->'team_b_names', '[]'::jsonb) as team_b_names_json,
    lower(coalesce(m.payload->>'winner_team','')) as winner_team_payload
  from public.beerpong_matches m
  where coalesce(m.match_status, 'finished') = 'finished'
    and coalesce(nullif(to_jsonb(m)->>'deleted_at','')::timestamptz is null, true)
), exploded as (
  select lower(trim(n.value)) as player_key, trim(n.value) as player_name, team_a_pussycup as pussycup, winner_team_payload in ('a','team_a') as won
  from matches_base mb, lateral jsonb_array_elements_text(mb.team_a_names_json) as n(value)
  union all
  select lower(trim(n.value)) as player_key, trim(n.value) as player_name, team_b_pussycup as pussycup, winner_team_payload in ('b','team_b') as won
  from matches_base mb, lateral jsonb_array_elements_text(mb.team_b_names_json) as n(value)
), grouped as (
  select player_key, min(player_name) as player_name, count(*)::int as matches, count(*) filter (where pussycup)::int as pussycup_hits, count(*) filter (where won)::int as wins, round(case when count(*)=0 then 0 else 100.0*count(*) filter (where pussycup)/count(*) end, 1) as pussycup_pct
  from exploded
  where player_key <> ''
  group by player_key
), ranking as (
  select * from grouped where matches > 0 order by pussycup_pct desc, pussycup_hits desc, matches desc, lower(player_name) asc
), summary as (
  select count(*)::int as players, coalesce(sum(matches),0)::int as matches, round(coalesce(avg(pussycup_pct),0),1) as avg_pct, coalesce(max(pussycup_pct),0)::numeric as best_pct from ranking
)
select jsonb_build_object(
  'summary', jsonb_build_object('players', coalesce((select players from summary),0), 'matches', coalesce((select matches from summary),0), 'avg_pct', coalesce((select avg_pct from summary),0), 'best_pct', coalesce((select best_pct from summary),0)),
  'ranking', coalesce((select jsonb_agg(jsonb_build_object('player_name', player_name, 'matches', matches, 'pussycup_hits', pussycup_hits, 'wins', wins, 'pussycup_pct', pussycup_pct)) from ranking), '[]'::jsonb)
);
$fn$;
grant execute on function public.get_beerpong_pussycup_ranking_public() to anon, authenticated;

-- Public badge registry so profile pages can describe all attainable badges.
create or replace function public.get_badge_registry_public()
returns jsonb
language sql
security definer
set search_path to 'public'
as $$
select jsonb_build_object('badges', jsonb_build_array(
  jsonb_build_object('key','starter','name','Starter','rarity',1,'nickname','Nieuweling','description','Je hebt je eerste stappen op de site gezet.','image','./badges/starter.png'),
  jsonb_build_object('key','debutant','name','Debutant','rarity',2,'nickname','Debutant','description','Speel minstens 1 geregistreerde wedstrijd.','image','./badges/debutant.png'),
  jsonb_build_object('key','stamgast','name','Stamgast','rarity',3,'nickname','Stamgast','description','Speel minstens 10 wedstrijden op de site.','image','./badges/stamgast.png'),
  jsonb_build_object('key','serieuze_speler','name','Serieuze speler','rarity',4,'nickname','Volhouder','description','Speel minstens 25 wedstrijden.','image','./badges/serieuze_speler.png'),
  jsonb_build_object('key','klaverkoning','name','Klaverkoning','rarity',5,'nickname','Klaverkoning','description','Speel minstens 15 potjes klaverjas.','image','./badges/klaverkoning.png'),
  jsonb_build_object('key','bridgebrein','name','Bridgebrein','rarity',5,'nickname','Bridgebrein','description','Speel minstens 15 potjes Boerenbridge.','image','./badges/bridgebrein.png'),
  jsonb_build_object('key','pongbeul','name','Pongbeul','rarity',5,'nickname','Pongbeul','description','Speel minstens 10 potjes Beerpong.','image','./badges/pongbeul.png'),
  jsonb_build_object('key','winnaar','name','Winnaar','rarity',6,'nickname','Winnaar','description','Win minstens 10 wedstrijden.','image','./badges/winnaar.png'),
  jsonb_build_object('key','gouden_hand','name','Gouden hand','rarity',7,'nickname','Gouden hand','description','Bereik een beste ELO van minstens 1200.','image','./badges/gouden_hand.png'),
  jsonb_build_object('key','nachtburgemeester','name','Nachtburgemeester','rarity',7,'nickname','Nachtburgemeester','description','Drink minstens 25 units in totaal.','image','./badges/nachtburgemeester.png'),
  jsonb_build_object('key','snelheidsduivel','name','Snelheidsduivel','rarity',8,'nickname','Snelheidsduivel','description','Zet een bevestigd snelheidsrecord neer.','image','./badges/snelheidsduivel.png'),
  jsonb_build_object('key','pussykoning','name','Pussykoning','rarity',9,'nickname','Pussykoning','description','Haal een pussycup-percentage van minstens 50% in Beerpong.','image','./badges/pussykoning.png'),
  jsonb_build_object('key','living_legend','name','Living Legend','rarity',10,'nickname','Living Legend','description','Speel minstens 50 wedstrijden op de site.','image','./badges/living_legend.png')
));
$$;
grant execute on function public.get_badge_registry_public() to anon, authenticated;


-- Web-push queue state transitions and test queue visibility.
create or replace function public.queue_test_web_push(session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_count integer := 0;
begin
  if v_player_id is null or v_name is null then
    raise exception 'Log opnieuw in voor testmeldingen.';
  end if;
  insert into public.web_push_jobs(target_player_id, target_subscription_id, title, body, target_url, payload, created_at, updated_at, status)
  select v_player_id, s.id, 'GEJAST testmelding', 'Je toestel is gekoppeld en klaar voor web-push.', './index.html', jsonb_build_object('kind','test','display_name',v_name), now(), now(), 'pending'
  from public.web_push_subscriptions s
  where s.player_id = v_player_id and coalesce(s.disabled_at is null, true);
  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count, 'display_name', v_name);
end;
$fn$;

drop function if exists public.claim_web_push_jobs(integer);
create or replace function public.claim_web_push_jobs(max_jobs integer default 25)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare v_items jsonb := '[]'::jsonb;
begin
  with picked as (
    select j.id
    from public.web_push_jobs j
    join public.web_push_subscriptions s on s.id = j.target_subscription_id
    where j.status = 'pending' and coalesce(s.disabled_at is null, true)
    order by j.created_at asc, j.id asc
    limit greatest(coalesce(max_jobs,25),1)
    for update of j skip locked
  ), claimed as (
    update public.web_push_jobs j
       set status = 'claimed', claimed_at = now(), updated_at = now()
     where j.id in (select id from picked)
     returning j.*
  )
  select coalesce(jsonb_agg(jsonb_build_object('job_id', c.id, 'title', c.title, 'body', c.body, 'target_url', c.target_url, 'endpoint', s.endpoint, 'p256dh_key', s.p256dh_key, 'auth_key', s.auth_key, 'display_name', s.display_name) order by c.created_at asc, c.id asc), '[]'::jsonb)
  into v_items
  from claimed c join public.web_push_subscriptions s on s.id = c.target_subscription_id;
  return jsonb_build_object('items', v_items);
end;
$fn$;

create or replace function public.mark_web_push_job_sent(job_id_input bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
begin
  update public.web_push_jobs set status = 'sent', sent_at = now(), updated_at = now(), error_text = null where id = job_id_input;
  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$fn$;

create or replace function public.mark_web_push_job_failed(job_id_input bigint, error_input text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare v_sub_id bigint; v_err text := left(coalesce(error_input,''), 1200);
begin
  update public.web_push_jobs set status = 'failed', failed_at = now(), updated_at = now(), error_text = v_err where id = job_id_input returning target_subscription_id into v_sub_id;
  if v_sub_id is not null and (v_err ilike '%410%' or v_err ilike '%404%' or v_err ilike '%unsub%' or v_err ilike '%gone%') then
    update public.web_push_subscriptions set disabled_at = now(), last_error = v_err, updated_at = now() where id = v_sub_id;
  elsif v_sub_id is not null then
    update public.web_push_subscriptions set last_error = v_err, updated_at = now() where id = v_sub_id;
  end if;
  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$fn$;
grant execute on function public.queue_test_web_push(text) to anon, authenticated;
grant execute on function public.claim_web_push_jobs(integer) to anon, authenticated;
grant execute on function public.mark_web_push_job_sent(bigint) to anon, authenticated;
grant execute on function public.mark_web_push_job_failed(bigint, text) to anon, authenticated;

commit;
