-- gejast v32 secure activation links
-- Run this in Supabase SQL Editor after reviewing in a staging project first.
-- This patch does NOT send email by itself. It creates the secure token flow that
-- your mail sender / edge function should use.

create extension if not exists pgcrypto;

create table if not exists public.player_activation_links (
  id bigint generated by default as identity primary key,
  claim_request_id bigint not null unique references public.claim_requests(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  display_name text not null,
  requester_email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz null,
  created_at timestamptz not null default now(),
  last_sent_at timestamptz null
);

create index if not exists player_activation_links_player_idx on public.player_activation_links(player_id);
create index if not exists player_activation_links_email_idx on public.player_activation_links(lower(requester_email));

create or replace function public._hash_activation_token(raw_token text)
returns text
language sql
immutable
as $$
  select encode(digest(raw_token, 'sha256'), 'hex');
$$;

create or replace function public.create_player_activation_link(
  admin_session_token text,
  request_id_input bigint,
  base_url text default 'https://YOUR-SITE/activate.html'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  sess record;
  req public.claim_requests%rowtype;
  player_row public.players%rowtype;
  raw_token text;
  hashed_token text;
  clean_base_url text;
begin
  select * into sess
  from public._require_valid_admin_session(admin_session_token);

  if coalesce(sess.ok, false) is not true then
    raise exception 'Ongeldige admin-sessie';
  end if;

  select *
    into req
    from public.claim_requests
   where id = request_id_input;

  if not found then
    raise exception 'Aanvraag niet gevonden';
  end if;

  if lower(coalesce(req.status, '')) <> 'approved' then
    raise exception 'Activatielink kan alleen voor goedgekeurde aanvragen worden gemaakt';
  end if;

  if req.requester_email is null or trim(req.requester_email) = '' then
    raise exception 'Deze aanvraag heeft geen e-mailadres';
  end if;

  select *
    into player_row
    from public.players
   where id = req.player_id
      or lower(display_name) = lower(coalesce(public._claim_request_display_name(req.id), ''))
   order by case when id = req.player_id then 0 else 1 end
   limit 1;

  if not found then
    raise exception 'Geen speler gevonden voor deze goedgekeurde aanvraag';
  end if;

  raw_token := encode(gen_random_bytes(24), 'hex');
  hashed_token := public._hash_activation_token(raw_token);
  clean_base_url := regexp_replace(trim(base_url), '/+$', '');

  insert into public.player_activation_links (
    claim_request_id,
    player_id,
    display_name,
    requester_email,
    token_hash,
    expires_at,
    last_sent_at
  )
  values (
    req.id,
    player_row.id,
    player_row.display_name,
    lower(trim(req.requester_email)),
    hashed_token,
    now() + interval '7 days',
    now()
  )
  on conflict (claim_request_id)
  do update set
    player_id = excluded.player_id,
    display_name = excluded.display_name,
    requester_email = excluded.requester_email,
    token_hash = excluded.token_hash,
    expires_at = excluded.expires_at,
    used_at = null,
    last_sent_at = now();

  return jsonb_build_object(
    'request_id', req.id,
    'display_name', player_row.display_name,
    'requester_email', lower(trim(req.requester_email)),
    'activation_url', clean_base_url || '?token=' || raw_token,
    'expires_at', (now() + interval '7 days')
  );
end;
$function$;

create or replace function public.get_activation_link_context(
  activation_token text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  link_row public.player_activation_links%rowtype;
begin
  if activation_token is null or trim(activation_token) = '' then
    raise exception 'Activatietoken ontbreekt';
  end if;

  select *
    into link_row
    from public.player_activation_links
   where token_hash = public._hash_activation_token(trim(activation_token))
   limit 1;

  if not found then
    raise exception 'Activatielink ongeldig';
  end if;

  if link_row.used_at is not null then
    raise exception 'Deze activatielink is al gebruikt';
  end if;

  if link_row.expires_at < now() then
    raise exception 'Deze activatielink is verlopen';
  end if;

  return jsonb_build_object(
    'display_name', link_row.display_name,
    'requester_email', link_row.requester_email,
    'expires_at', link_row.expires_at
  );
end;
$function$;

create or replace function public.activate_player_from_email_link(
  activation_token text,
  new_pin text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  link_row public.player_activation_links%rowtype;
  player_row public.players%rowtype;
begin
  if activation_token is null or trim(activation_token) = '' then
    raise exception 'Activatietoken ontbreekt';
  end if;

  if new_pin is null or new_pin !~ '^[0-9]{4}$' then
    raise exception 'Pincode moet precies 4 cijfers zijn';
  end if;

  select *
    into link_row
    from public.player_activation_links
   where token_hash = public._hash_activation_token(trim(activation_token))
   limit 1;

  if not found then
    raise exception 'Activatielink ongeldig';
  end if;

  if link_row.used_at is not null then
    raise exception 'Deze activatielink is al gebruikt';
  end if;

  if link_row.expires_at < now() then
    raise exception 'Deze activatielink is verlopen';
  end if;

  select *
    into player_row
    from public.players
   where id = link_row.player_id
   limit 1;

  if not found then
    raise exception 'Speler niet gevonden';
  end if;

  if lower(player_row.display_name) <> lower(link_row.display_name) then
    raise exception 'Naam komt niet overeen met deze activatielink';
  end if;

  update public.players
     set pin_hash = crypt(new_pin, gen_salt('bf')),
         approved = true,
         active = true,
         approved_email = link_row.requester_email
   where id = player_row.id;

  update public.player_activation_links
     set used_at = now()
   where id = link_row.id;

  return public.login_player(player_row.display_name, new_pin);
end;
$function$;

comment on function public.create_player_activation_link(text,bigint,text)
is 'Generates a one-time activation URL for an approved claim request. Send the returned activation_url to requester_email via your own mail system or Supabase Edge Function.';

comment on function public.get_activation_link_context(text)
is 'Returns safe, non-secret context for a valid unused activation token so activate.html can show the bound name and email.';

comment on function public.activate_player_from_email_link(text,text)
is 'Consumes a one-time activation token, stores a 4-digit PIN for the linked player, and returns the normal login payload.';
