begin;

create table if not exists public.boerenbridge_matches (
  id bigint generated by default as identity primary key,
  client_match_id text not null unique,
  match_name text,
  match_status text not null default 'draft',
  rules_version text,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  created_by_player_id bigint references public.players(id) on delete set null,
  payload jsonb not null default '{}'::jsonb
);

alter table public.boerenbridge_matches add column if not exists match_name text;
alter table public.boerenbridge_matches add column if not exists match_status text not null default 'draft';
alter table public.boerenbridge_matches add column if not exists rules_version text;
alter table public.boerenbridge_matches add column if not exists app_version text;
alter table public.boerenbridge_matches add column if not exists created_at timestamptz not null default now();
alter table public.boerenbridge_matches add column if not exists updated_at timestamptz not null default now();
alter table public.boerenbridge_matches add column if not exists started_at timestamptz;
alter table public.boerenbridge_matches add column if not exists finished_at timestamptz;
alter table public.boerenbridge_matches add column if not exists created_by_player_id bigint references public.players(id) on delete set null;
alter table public.boerenbridge_matches add column if not exists payload jsonb not null default '{}'::jsonb;

create unique index if not exists boerenbridge_matches_client_match_id_idx on public.boerenbridge_matches(client_match_id);
create index if not exists boerenbridge_matches_status_idx on public.boerenbridge_matches(match_status, updated_at desc);

create table if not exists public.boerenbridge_player_stats (
  player_name text primary key,
  games_played integer not null default 0,
  wins integer not null default 0,
  total_points integer not null default 0,
  updated_at timestamptz not null default now()
);

create or replace function public.get_requestable_names()
returns table(display_name text, slug text)
language sql
security definer
set search_path to 'public'
as $fn$
  select distinct
    au.display_name::text as display_name,
    au.slug::text as slug
  from public.allowed_usernames au
  where coalesce(lower(au.status), '') = 'available'
    and nullif(trim(coalesce(au.display_name, '')), '') is not null
  order by lower(au.display_name), au.display_name
$fn$;

drop function if exists public.save_boerenbridge_match(text, text, text, text, jsonb);

create function public.save_boerenbridge_match(
  session_token text,
  client_match_id text,
  rules_version text default null,
  app_version text default null,
  match_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_player public.players%rowtype;
  v_match_id bigint;
  v_status text := lower(trim(coalesce(match_payload->>'match_status', 'draft')));
  v_started_at timestamptz := coalesce(nullif(match_payload->>'started_at','')::timestamptz, now());
  v_finished_at timestamptz := nullif(match_payload->>'finished_at','')::timestamptz;
  v_players text[] := coalesce(
    (select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'players','[]'::jsonb))),
    '{}'::text[]
  );
  v_winners text[] := coalesce(
    (select array_agg(value::text) from jsonb_array_elements_text(coalesce(match_payload->'winner_names','[]'::jsonb))),
    '{}'::text[]
  );
  v_stats_applied_at timestamptz;
  v_is_finished boolean;
  v_name text;
  v_points integer;
  v_is_winner boolean;
begin
  if nullif(trim(coalesce(client_match_id, '')), '') is null then
    raise exception 'client_match_id ontbreekt';
  end if;

  begin
    if nullif(trim(coalesce(session_token, '')), '') is not null then
      select * into v_player from public._gejast_player_from_session(session_token);
    end if;
  exception when others then
    null;
  end;

  if v_status not in ('draft','finished') then
    v_status := case when v_finished_at is not null then 'finished' else 'draft' end;
  end if;
  v_is_finished := v_status = 'finished';
  if v_is_finished and v_finished_at is null then
    v_finished_at := now();
  end if;

  insert into public.boerenbridge_matches (
    client_match_id, match_name, match_status, rules_version, app_version,
    created_by_player_id, started_at, finished_at, payload, updated_at
  )
  values (
    client_match_id,
    nullif(trim(coalesce(match_payload->>'match_name','')), ''),
    v_status,
    rules_version,
    app_version,
    v_player.id,
    v_started_at,
    v_finished_at,
    coalesce(match_payload, '{}'::jsonb),
    now()
  )
  on conflict (client_match_id)
  do update set
    match_name = coalesce(excluded.match_name, public.boerenbridge_matches.match_name),
    match_status = excluded.match_status,
    rules_version = coalesce(excluded.rules_version, public.boerenbridge_matches.rules_version),
    app_version = coalesce(excluded.app_version, public.boerenbridge_matches.app_version),
    created_by_player_id = coalesce(public.boerenbridge_matches.created_by_player_id, excluded.created_by_player_id),
    started_at = coalesce(public.boerenbridge_matches.started_at, excluded.started_at),
    finished_at = case
      when excluded.match_status = 'finished' then coalesce(public.boerenbridge_matches.finished_at, excluded.finished_at)
      else public.boerenbridge_matches.finished_at
    end,
    payload = excluded.payload,
    updated_at = now()
  returning id, nullif(payload->>'stats_applied_at','')::timestamptz into v_match_id, v_stats_applied_at;

  if v_is_finished and v_stats_applied_at is null then
    for v_name, v_points in
      select
        coalesce(x->>'name','') as player_name,
        coalesce((x->>'final_total_points')::integer,0) as final_total_points
      from jsonb_array_elements(coalesce(match_payload->'totals','[]'::jsonb)) x
    loop
      if nullif(trim(v_name), '') is null then
        continue;
      end if;
      v_is_winner := v_points = (
        select max(coalesce((y->>'final_total_points')::integer,0))
        from jsonb_array_elements(coalesce(match_payload->'totals','[]'::jsonb)) y
      );
      insert into public.boerenbridge_player_stats(player_name, games_played, wins, total_points, updated_at)
      values (v_name, 1, case when v_is_winner then 1 else 0 end, v_points, now())
      on conflict (player_name)
      do update set
        games_played = public.boerenbridge_player_stats.games_played + 1,
        wins = public.boerenbridge_player_stats.wins + case when v_is_winner then 1 else 0 end,
        total_points = public.boerenbridge_player_stats.total_points + v_points,
        updated_at = now();
    end loop;

    update public.boerenbridge_matches
       set payload = jsonb_set(coalesce(payload,'{}'::jsonb), '{stats_applied_at}', to_jsonb(now()::text), true),
           updated_at = now()
     where id = v_match_id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'match_id', v_match_id,
    'client_match_id', client_match_id,
    'match_status', v_status,
    'stats_applied', (v_is_finished and v_stats_applied_at is null)
  );
end;
$function$;

grant execute on function public.get_requestable_names() to anon, authenticated;
grant execute on function public.save_boerenbridge_match(text, text, text, text, jsonb) to anon, authenticated;

commit;
