-- gejast_v423.sql
-- Patch goals:
-- 1) restore missing homepage RPCs / analytics / push-test compatibility on live Supabase
-- 2) keep old frontend callers working while newer v2/v3 push functions exist
-- 3) homepage frontend patch is paired with this SQL


-- ===== existing analytics patch body (v108) =====
begin;

create table if not exists public.site_visitor_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null default 'page_view',
  page_path text not null,
  page_title text null,
  referrer_url text null,
  visitor_id text not null,
  session_id text not null,
  device_type text null,
  browser_name text null,
  os_name text null,
  viewport_width integer null,
  viewport_height integer null,
  language_code text null,
  time_zone text null,
  user_agent text null,
  extra jsonb not null default '{}'::jsonb
);

create index if not exists site_visitor_events_created_at_idx on public.site_visitor_events (created_at desc);
create index if not exists site_visitor_events_page_path_idx on public.site_visitor_events (page_path);
create index if not exists site_visitor_events_visitor_id_idx on public.site_visitor_events (visitor_id);
create index if not exists site_visitor_events_session_id_idx on public.site_visitor_events (session_id);
create index if not exists site_visitor_events_event_name_idx on public.site_visitor_events (event_name);

create or replace function public.track_site_event(
  event_name text default 'page_view',
  page_path text default null,
  page_title text default null,
  referrer_url text default null,
  visitor_id text default null,
  session_id text default null,
  device_type text default null,
  browser_name text default null,
  os_name text default null,
  viewport_width integer default null,
  viewport_height integer default null,
  language_code text default null,
  time_zone text default null,
  user_agent text default null,
  extra jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_page_path text := nullif(trim(coalesce(track_site_event.page_path, '')), '');
  v_visitor_id text := nullif(trim(coalesce(track_site_event.visitor_id, '')), '');
  v_session_id text := nullif(trim(coalesce(track_site_event.session_id, '')), '');
  v_event_name text := nullif(trim(coalesce(track_site_event.event_name, '')), '');
begin
  if v_page_path is null then
    raise exception 'page_path ontbreekt';
  end if;
  if v_visitor_id is null then
    raise exception 'visitor_id ontbreekt';
  end if;
  if v_session_id is null then
    raise exception 'session_id ontbreekt';
  end if;
  if v_event_name is null then
    v_event_name := 'page_view';
  end if;

  insert into public.site_visitor_events (
    event_name,
    page_path,
    page_title,
    referrer_url,
    visitor_id,
    session_id,
    device_type,
    browser_name,
    os_name,
    viewport_width,
    viewport_height,
    language_code,
    time_zone,
    user_agent,
    extra
  )
  values (
    v_event_name,
    v_page_path,
    nullif(trim(coalesce(track_site_event.page_title, '')), ''),
    nullif(trim(coalesce(track_site_event.referrer_url, '')), ''),
    v_visitor_id,
    v_session_id,
    nullif(trim(coalesce(track_site_event.device_type, '')), ''),
    nullif(trim(coalesce(track_site_event.browser_name, '')), ''),
    nullif(trim(coalesce(track_site_event.os_name, '')), ''),
    track_site_event.viewport_width,
    track_site_event.viewport_height,
    nullif(trim(coalesce(track_site_event.language_code, '')), ''),
    nullif(trim(coalesce(track_site_event.time_zone, '')), ''),
    nullif(trim(coalesce(track_site_event.user_agent, '')), ''),
    coalesce(track_site_event.extra, '{}'::jsonb)
  );

  return jsonb_build_object('ok', true);
end;
$function$;

create or replace function public.admin_get_site_analytics_action(
  admin_session_token text,
  range_days integer default 7,
  recent_limit integer default 80
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_session jsonb;
  v_days integer := greatest(1, least(coalesce(range_days, 7), 365));
  v_recent_limit integer := greatest(1, least(coalesce(recent_limit, 80), 250));
  v_since timestamptz := now() - make_interval(days => v_days);
begin
  v_session := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_session->>'ok')::boolean, false) is not true then
    raise exception 'Log opnieuw in als admin.';
  end if;

  return jsonb_build_object(
    'ok', true,
    'admin_session_token', coalesce(v_session->>'admin_session_token', admin_session_token),
    'summary', (
      select jsonb_build_object(
        'total_views', count(*)::int,
        'unique_visitors', count(distinct e.visitor_id)::int,
        'unique_sessions', count(distinct e.session_id)::int,
        'range_days', v_days
      )
      from public.site_visitor_events e
      where e.created_at >= v_since
    ),
    'top_pages', coalesce((
      select jsonb_agg(jsonb_build_object('page_path', x.page_path, 'views', x.views) order by x.views desc, x.page_path)
      from (
        select e.page_path, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by e.page_path
        order by views desc, e.page_path
        limit 12
      ) x
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object('device_type', x.device_type, 'views', x.views) order by x.views desc, x.device_type)
      from (
        select coalesce(nullif(e.device_type,''), 'Onbekend') as device_type, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 8
      ) x
    ), '[]'::jsonb),
    'browsers', coalesce((
      select jsonb_agg(jsonb_build_object('browser_name', x.browser_name, 'views', x.views) order by x.views desc, x.browser_name)
      from (
        select coalesce(nullif(e.browser_name,''), 'Onbekend') as browser_name, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 8
      ) x
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(jsonb_build_object('referrer_url', x.referrer_url, 'views', x.views) order by x.views desc)
      from (
        select coalesce(nullif(e.referrer_url,''), 'Direct') as referrer_url, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 10
      ) x
    ), '[]'::jsonb),
    'recent_events', coalesce((
      select jsonb_agg(jsonb_build_object(
        'created_at', x.created_at,
        'page_path', x.page_path,
        'device_type', x.device_type,
        'browser_name', x.browser_name,
        'referrer_url', x.referrer_url
      ) order by x.created_at desc)
      from (
        select e.created_at, e.page_path,
               coalesce(nullif(e.device_type,''), 'Onbekend') as device_type,
               coalesce(nullif(e.browser_name,''), 'Onbekend') as browser_name,
               coalesce(nullif(e.referrer_url,''), 'Direct') as referrer_url
        from public.site_visitor_events e
        where e.created_at >= v_since
        order by e.created_at desc
        limit v_recent_limit
      ) x
    ), '[]'::jsonb)
  );
end;
$function$;

grant execute on function public.track_site_event(text, text, text, text, text, text, text, text, text, integer, integer, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_get_site_analytics_action(text, integer, integer) to anon, authenticated;

commit;

-- ===== existing homepage/frontend alignment body (v47) =====
-- gejast v47 frontend alignment + queue patch
create extension if not exists pgcrypto;

create table if not exists public.outbound_email_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  job_status text not null default 'queued',
  recipient_email text not null,
  recipient_name text null,
  subject text not null,
  payload jsonb not null default '{}'::jsonb,
  requested_by_admin_id bigint null,
  related_claim_request_id bigint null references public.claim_requests(id) on delete set null,
  related_player_id bigint null references public.players(id) on delete set null,
  last_error text null,
  provider_message_id text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outbound_email_jobs_status_idx on public.outbound_email_jobs(job_status, created_at desc);
create index if not exists outbound_email_jobs_claim_idx on public.outbound_email_jobs(related_claim_request_id);
create index if not exists outbound_email_jobs_email_idx on public.outbound_email_jobs(lower(recipient_email));

create or replace function public._touch_outbound_email_job_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_outbound_email_jobs_updated_at on public.outbound_email_jobs;
create trigger trg_outbound_email_jobs_updated_at
before update on public.outbound_email_jobs
for each row
execute function public._touch_outbound_email_job_updated_at();

create or replace function public.get_gejast_homepage_state(
  session_token text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  base_state jsonb;
  can_count integer;
begin
  base_state := public.get_public_state(session_token);
  can_count := coalesce((base_state ->> 'can_count')::integer, (base_state ->> 'yes_count')::integer, 0);

  if coalesce(base_state ->> 'status_key', '') <> '' and coalesce(base_state ->> 'status_label', '') <> '' then
    return base_state;
  end if;

  return coalesce(base_state, '{}'::jsonb)
    || jsonb_build_object(
      'status_key',
      case when can_count >= 4 then 'yes' when can_count = 3 then 'maybe' else 'no' end,
      'status_label',
      case when can_count >= 4 then 'Ja' when can_count = 3 then 'Bijna' else 'Nee' end
    );
end;
$$;

comment on function public.get_gejast_homepage_state(text)
is 'Homepage wrapper around get_public_state that guarantees status_key and status_label.';

create or replace function public.admin_queue_activation_email(
  admin_session_token text,
  request_id_input bigint,
  base_url text,
  recipient_email_input text default null,
  recipient_name_input text default null,
  activation_link_input text default null,
  player_id_input bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  admin_row record;
  req public.claim_requests%rowtype;
  activation_payload jsonb;
  activation_url text;
  recipient_email_clean text;
  recipient_name_clean text;
  job_id_out bigint;
begin
  select * into admin_row from public._require_valid_admin_session(admin_session_token);

  select * into req
  from public.claim_requests
  where id = request_id_input
  limit 1;

  if not found then
    raise exception 'Aanvraag niet gevonden';
  end if;

  if lower(coalesce(req.status, '')) <> 'approved' then
    raise exception 'Alleen goedgekeurde aanvragen kunnen in de mailqueue';
  end if;

  activation_url := nullif(trim(coalesce(activation_link_input, '')), '');

  if activation_url is null then
    activation_payload := public.create_player_activation_link(admin_session_token, request_id_input, base_url);
    activation_url := activation_payload ->> 'activation_url';
  else
    activation_payload := jsonb_build_object(
      'request_id', req.id,
      'display_name', coalesce(public._claim_request_display_name(req.id), null),
      'requester_email', coalesce(nullif(trim(recipient_email_input), ''), lower(trim(req.requester_email))),
      'activation_url', activation_url
    );
  end if;

  recipient_email_clean := lower(trim(coalesce(nullif(recipient_email_input, ''), req.requester_email)));
  recipient_name_clean := nullif(trim(coalesce(recipient_name_input, activation_payload ->> 'display_name', public._claim_request_display_name(req.id))), '');

  if recipient_email_clean is null or recipient_email_clean = '' then
    raise exception 'Ontvanger-e-mail ontbreekt';
  end if;

  insert into public.outbound_email_jobs (
    job_type, job_status, recipient_email, recipient_name, subject, payload,
    requested_by_admin_id, related_claim_request_id, related_player_id
  )
  values (
    'activation_email',
    'queued',
    recipient_email_clean,
    recipient_name_clean,
    'Activeer je account',
    jsonb_build_object(
      'request_id', req.id,
      'activation_url', activation_url,
      'display_name', coalesce(recipient_name_clean, activation_payload ->> 'display_name'),
      'requester_email', recipient_email_clean,
      'base_url', regexp_replace(trim(base_url), '/+$', ''),
      'template', 'activation_email_v1'
    ),
    admin_row.id,
    req.id,
    coalesce(player_id_input, req.player_id)
  )
  returning id into job_id_out;

  return jsonb_build_object(
    'queued', true,
    'job_id', job_id_out,
    'request_id', req.id,
    'recipient_email', recipient_email_clean,
    'recipient_name', recipient_name_clean,
    'activation_url', activation_url,
    'delivery_mode', 'outbound_email_jobs'
  );
end;
$$;

comment on function public.admin_queue_activation_email(text,bigint,text,text,text,text,bigint)
is 'Queues an activation email job in outbound_email_jobs and returns the activation_url used by admin.html.';

create or replace view public.outbound_email_jobs_pending as
select *
from public.outbound_email_jobs
where job_status = 'queued'
order by created_at asc;

-- ===== existing jas app state body (v48 extract) =====
create or replace function public.get_jas_app_state(session_token text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  base_state jsonb;
  recent_games jsonb;
  registered_names jsonb;
begin
  base_state := public.get_public_state(session_token);

  select coalesce(jsonb_agg(p.display_name order by lower(p.display_name)), '[]'::jsonb)
    into registered_names
    from public.players p;

  select coalesce(jsonb_agg(game_row order by played_at desc, created_at desc), '[]'::jsonb)
    into recent_games
    from (
      select
        g.id,
        g.title,
        g.played_at,
        g.variant,
        g.scoreboard_mode,
        g.created_at,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id
        ), '[]'::jsonb) as players,
        coalesce((
          select jsonb_agg(e.display_name order by e.seat_no, e.id)
          from public.jas_game_entries e
          where e.game_id = g.id and e.is_winner = true
        ), '[]'::jsonb) as winners
      from public.jas_games g
      order by g.played_at desc, g.created_at desc
      limit 12
    ) game_row;

  return jsonb_build_object(
    'all_names', registered_names,
    'my_name', base_state ->> 'my_name',
    'recent_games', recent_games
  );
end;
$$;


-- ===== existing push pipeline repair body (v355) =====
begin;

alter table if exists public.web_push_subscriptions
  add column if not exists site_scope text,
  add column if not exists standalone boolean,
  add column if not exists installation_mode text,
  add column if not exists page_path text,
  add column if not exists last_sync_at timestamptz,
  add column if not exists last_success_at timestamptz,
  add column if not exists failure_count integer not null default 0;

alter table if exists public.web_push_active_presence
  add column if not exists subscription_id bigint references public.web_push_subscriptions(id) on delete set null,
  add column if not exists site_scope text,
  add column if not exists page_path text,
  add column if not exists standalone boolean,
  add column if not exists installation_mode text,
  add column if not exists lat double precision,
  add column if not exists lng double precision,
  add column if not exists accuracy double precision;

alter table if exists public.web_push_jobs
  add column if not exists site_scope text,
  add column if not exists trigger_kind text,
  add column if not exists request_kind text,
  add column if not exists request_id bigint,
  add column if not exists created_by_player_id bigint references public.players(id) on delete set null,
  add column if not exists target_player_name text,
  add column if not exists dedupe_key text,
  add column if not exists notification_tag text,
  add column if not exists require_interaction boolean not null default false,
  add column if not exists vibrate_pattern jsonb not null default '[180,80,180]'::jsonb,
  add column if not exists trace_id uuid not null default gen_random_uuid(),
  add column if not exists claim_token uuid,
  add column if not exists claimed_by text,
  add column if not exists claim_expires_at timestamptz,
  add column if not exists marked_at timestamptz,
  add column if not exists error_stage text,
  add column if not exists error_code text,
  add column if not exists provider_message_id text,
  add column if not exists attempt_count integer not null default 0;

create table if not exists public.web_push_job_attempts (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.web_push_jobs(id) on delete cascade,
  worker_id text,
  claim_token uuid,
  stage text not null,
  status text not null,
  error_code text,
  error_text text,
  created_at timestamptz not null default now()
);

create index if not exists web_push_presence_scope_seen_idx
  on public.web_push_active_presence(site_scope, last_seen_at desc);

create index if not exists web_push_jobs_runtime_idx
  on public.web_push_jobs(status, site_scope, created_at asc);

create unique index if not exists web_push_jobs_dedupe_uidx
  on public.web_push_jobs(dedupe_key)
  where dedupe_key is not null;

create index if not exists web_push_job_attempts_job_idx
  on public.web_push_job_attempts(job_id, created_at desc);

create or replace function public._web_push_player_name(player_id_input bigint)
returns text
language sql
stable
as $$
  select coalesce(nullif(p.display_name,''), nullif(p.nickname,''), p.name, 'Onbekend')
  from public.players p
  where p.id = player_id_input
  limit 1;
$$;

create or replace function public._web_push_scope_for_player(player_id_input bigint)
returns text
language sql
stable
as $$
  select coalesce(nullif(to_jsonb(p)->>'site_scope',''), 'friends')
  from public.players p
  where p.id = player_id_input
  limit 1;
$$;

create or replace function public._web_push_distance_meters(lat1 double precision, lng1 double precision, lat2 double precision, lng2 double precision)
returns double precision
language sql
immutable
as $$
  select case
    when lat1 is null or lng1 is null or lat2 is null or lng2 is null then null
    else 6371000 * 2 * asin(
      sqrt(
        power(sin(radians(lat2 - lat1) / 2), 2) +
        cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lng2 - lng1) / 2), 2)
      )
    )
  end
$$;

create or replace function public.register_web_push_subscription_v2(
  session_token text,
  endpoint_input text,
  p256dh_input text,
  auth_input text,
  page_path_input text default null,
  permission_input text default null,
  standalone_input boolean default null,
  site_scope_input text default 'friends',
  platform_input text default null,
  installation_mode_input text default null,
  user_agent_input text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), public._web_push_scope_for_player(v_player_id), 'friends');
  v_endpoint text := nullif(trim(coalesce(endpoint_input,'')), '');
  v_row public.web_push_subscriptions%rowtype;
begin
  if v_player_id is null or v_name is null then raise exception 'MISSING_SESSION'; end if;
  if v_endpoint is null then raise exception 'MISSING_ENDPOINT'; end if;
  if nullif(trim(coalesce(p256dh_input,'')), '') is null or nullif(trim(coalesce(auth_input,'')), '') is null then raise exception 'MISSING_KEYS'; end if;

  insert into public.web_push_subscriptions(
    player_id, display_name, endpoint, p256dh_key, auth_key, user_agent, permission_state, platform,
    site_scope, standalone, installation_mode, page_path, created_at, updated_at, last_seen_at,
    last_sync_at, last_success_at, disabled_at, last_error, failure_count
  ) values (
    v_player_id, v_name, v_endpoint, p256dh_input, auth_input,
    nullif(trim(coalesce(user_agent_input,'')), ''),
    nullif(trim(coalesce(permission_input,'')), ''),
    nullif(trim(coalesce(platform_input,'')), ''),
    v_scope, standalone_input, nullif(trim(coalesce(installation_mode_input,'')), ''),
    nullif(trim(coalesce(page_path_input,'')), ''),
    now(), now(), now(), now(), now(), null, null, 0
  )
  on conflict (endpoint) do update set
    player_id = excluded.player_id,
    display_name = excluded.display_name,
    p256dh_key = excluded.p256dh_key,
    auth_key = excluded.auth_key,
    user_agent = excluded.user_agent,
    permission_state = excluded.permission_state,
    platform = excluded.platform,
    site_scope = excluded.site_scope,
    standalone = excluded.standalone,
    installation_mode = excluded.installation_mode,
    page_path = excluded.page_path,
    updated_at = now(),
    last_seen_at = now(),
    last_sync_at = now(),
    last_success_at = now(),
    disabled_at = null,
    last_error = null,
    failure_count = 0
  returning * into v_row;

  return jsonb_build_object('ok', true, 'subscription_id', v_row.id, 'player_name', v_name, 'site_scope', v_scope);
end;
$$;

create or replace function public.touch_active_web_push_presence_v2(
  session_token text,
  endpoint_input text default null,
  p256dh_input text default null,
  auth_input text default null,
  page_path_input text default null,
  permission_input text default null,
  standalone_input boolean default null,
  site_scope_input text default 'friends',
  platform_input text default null,
  installation_mode_input text default null,
  lat_input double precision default null,
  lng_input double precision default null,
  accuracy_input double precision default null,
  user_agent_input text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), public._web_push_scope_for_player(v_player_id), 'friends');
  v_endpoint text := nullif(trim(coalesce(endpoint_input,'')), '');
  v_subscription_id bigint := null;
begin
  if v_player_id is null or v_name is null then raise exception 'MISSING_SESSION'; end if;

  if v_endpoint is not null then
    select id into v_subscription_id
    from public.web_push_subscriptions
    where endpoint = v_endpoint
    limit 1;
  end if;

  if v_subscription_id is null and v_endpoint is not null and nullif(trim(coalesce(p256dh_input,'')), '') is not null and nullif(trim(coalesce(auth_input,'')), '') is not null then
    perform public.register_web_push_subscription_v2(
      session_token, v_endpoint, p256dh_input, auth_input, page_path_input, permission_input, standalone_input,
      v_scope, platform_input, installation_mode_input, user_agent_input
    );
    select id into v_subscription_id from public.web_push_subscriptions where endpoint = v_endpoint limit 1;
  end if;

  insert into public.web_push_active_presence(
    player_id, display_name, endpoint, platform, permission_state, user_agent, created_at, updated_at, last_seen_at,
    subscription_id, site_scope, page_path, standalone, installation_mode, lat, lng, accuracy
  ) values (
    v_player_id, v_name, v_endpoint, nullif(trim(coalesce(platform_input,'')), ''), nullif(trim(coalesce(permission_input,'')), ''),
    nullif(trim(coalesce(user_agent_input,'')), ''), now(), now(), now(),
    v_subscription_id, v_scope, nullif(trim(coalesce(page_path_input,'')), ''), standalone_input,
    nullif(trim(coalesce(installation_mode_input,'')), ''), lat_input, lng_input, accuracy_input
  )
  on conflict (player_id, endpoint) do update set
    display_name = excluded.display_name,
    platform = excluded.platform,
    permission_state = excluded.permission_state,
    user_agent = excluded.user_agent,
    updated_at = now(),
    last_seen_at = now(),
    subscription_id = excluded.subscription_id,
    site_scope = excluded.site_scope,
    page_path = excluded.page_path,
    standalone = excluded.standalone,
    installation_mode = excluded.installation_mode,
    lat = excluded.lat,
    lng = excluded.lng,
    accuracy = excluded.accuracy;

  return jsonb_build_object('ok', true, 'player_name', v_name, 'subscription_id', v_subscription_id, 'site_scope', v_scope);
end;
$$;

create or replace function public.queue_test_web_push_v2(session_token text, site_scope_input text default 'friends')
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_name text := public._gejast_player_name_from_session(session_token);
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), public._web_push_scope_for_player(v_player_id), 'friends');
  v_count integer := 0;
begin
  if v_player_id is null or v_name is null then raise exception 'MISSING_SESSION'; end if;

  insert into public.web_push_jobs(
    status, target_player_id, target_subscription_id, title, body, target_url, payload, site_scope, trigger_kind,
    created_by_player_id, target_player_name, dedupe_key, notification_tag, require_interaction
  )
  select
    'queued', s.player_id, s.id,
    'GEJAST testmelding',
    'Je toestel is gekoppeld en klaar voor web-push.',
    './index.html',
    jsonb_build_object('kind','test','display_name',v_name),
    v_scope, 'self_test',
    v_player_id, v_name,
    'self-test:' || s.id || ':' || to_char(current_timestamp, 'YYYYMMDDHH24MI'),
    'self-test',
    false
  from public.web_push_subscriptions s
  where s.player_id = v_player_id
    and s.disabled_at is null
    and coalesce(s.site_scope, v_scope) = v_scope;

  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count, 'player_name', v_name, 'site_scope', v_scope);
end;
$$;

create or replace function public.queue_nearby_verification_pushes_v2(
  request_kind_input text,
  request_id_input bigint,
  cooldown_seconds integer default 600
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_kind text := lower(trim(coalesce(request_kind_input,'')));
  v_creator_id bigint;
  v_scope text := 'friends';
  v_lat double precision;
  v_lng double precision;
  v_accuracy double precision;
  v_target_url text;
  v_count integer := 0;
begin
  if v_kind = 'drink' then
    select de.player_id, public._web_push_scope_for_player(de.player_id), de.lat, de.lng, de.accuracy, './drinks_pending.html'
      into v_creator_id, v_scope, v_lat, v_lng, v_accuracy, v_target_url
    from public.drink_events de
    where de.id = request_id_input
      and coalesce(de.status,'pending') = 'pending';
  elsif v_kind = 'speed' then
    select ds.player_id, public._web_push_scope_for_player(ds.player_id), ds.lat, ds.lng, ds.accuracy, './drinks_speed.html'
      into v_creator_id, v_scope, v_lat, v_lng, v_accuracy, v_target_url
    from public.drink_speed_attempts ds
    where ds.id = request_id_input
      and coalesce(ds.status,'pending') = 'pending';
  else
    raise exception 'INVALID_KIND';
  end if;

  if v_creator_id is null then
    return jsonb_build_object('ok', false, 'reason', 'request_not_pending');
  end if;

  insert into public.web_push_jobs(
    status, target_player_id, target_subscription_id, title, body, target_url, payload, site_scope,
    trigger_kind, request_kind, request_id, created_by_player_id, target_player_name, dedupe_key, notification_tag
  )
  select
    'queued',
    s.player_id,
    s.id,
    case when v_kind = 'speed' then 'Nieuwe snelheidspoging in de buurt' else 'Nieuw drankje verifiëren' end,
    case when v_kind = 'speed' then 'Er staat een snelheidspoging in jouw buurt klaar voor verificatie.' else 'Er staat een drankverificatie in jouw buurt klaar.' end,
    v_target_url,
    jsonb_build_object('kind','nearby_verification','request_kind',v_kind,'request_id',request_id_input),
    v_scope,
    'nearby_verification',
    v_kind,
    request_id_input,
    v_creator_id,
    public._web_push_player_name(s.player_id),
    'nearby:' || v_kind || ':' || request_id_input || ':' || s.id,
    'nearby-' || v_kind || '-' || request_id_input
  from public.web_push_subscriptions s
  join public.web_push_active_presence p
    on p.subscription_id = s.id
  where s.disabled_at is null
    and coalesce(s.permission_state,'') = 'granted'
    and p.last_seen_at >= now() - interval '10 minutes'
    and coalesce(p.site_scope, s.site_scope, v_scope) = v_scope
    and s.player_id <> v_creator_id
    and p.lat is not null and p.lng is not null
    and public._web_push_distance_meters(v_lat, v_lng, p.lat, p.lng) <= greatest(coalesce(v_accuracy, 150), coalesce(p.accuracy, 150)) + 350
  on conflict (dedupe_key) do nothing;

  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count, 'request_kind', v_kind, 'request_id', request_id_input, 'site_scope', v_scope);
end;
$$;

create or replace function public.admin_queue_active_web_push_v2(
  admin_session_token text,
  title_input text,
  body_input text,
  target_url_input text default './index.html',
  active_minutes integer default 5,
  site_scope_input text default 'friends'
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_title text := nullif(trim(coalesce(title_input,'')), '');
  v_body text := nullif(trim(coalesce(body_input,'')), '');
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), 'friends');
  v_cutoff timestamptz := now() - make_interval(mins => greatest(coalesce(active_minutes,5),1));
  v_count integer := 0;
begin
  perform public.admin_check_session(admin_session_token);
  if v_title is null or v_body is null then raise exception 'EMPTY_MESSAGE'; end if;

  insert into public.web_push_jobs(
    status, target_player_id, target_subscription_id, title, body, target_url, payload, site_scope,
    trigger_kind, target_player_name, dedupe_key, notification_tag, require_interaction
  )
  select
    'queued', s.player_id, s.id, v_title, v_body, nullif(trim(coalesce(target_url_input,'')), ''), jsonb_build_object('kind','admin_active_broadcast'),
    v_scope, 'admin_broadcast', public._web_push_player_name(s.player_id),
    'admin:' || v_scope || ':' || s.id || ':' || to_char(current_timestamp, 'YYYYMMDDHH24MI'),
    'admin-broadcast',
    false
  from public.web_push_subscriptions s
  join public.web_push_active_presence p on p.subscription_id = s.id
  where s.disabled_at is null
    and p.last_seen_at >= v_cutoff
    and coalesce(p.permission_state, s.permission_state, '') = 'granted'
    and coalesce(p.site_scope, s.site_scope, v_scope) = v_scope;

  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'queued_count', v_count, 'site_scope', v_scope);
end;
$$;

create or replace function public.requeue_stale_web_push_claims_v2(stale_minutes integer default 15)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_count integer := 0;
begin
  update public.web_push_jobs
     set status = 'queued',
         updated_at = now(),
         claim_token = null,
         claimed_by = null,
         claim_expires_at = null,
         error_stage = coalesce(error_stage, 'claim'),
         error_code = coalesce(error_code, 'CLAIM_EXPIRED')
   where status = 'claimed'
     and claim_expires_at < now();
  get diagnostics v_count = row_count;
  return jsonb_build_object('ok', true, 'requeued_count', v_count);
end;
$$;

create or replace function public.claim_web_push_jobs_v2(
  max_jobs integer default 25,
  worker_id_input text default 'dispatcher',
  claim_token_input uuid default gen_random_uuid()
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_items jsonb := '[]'::jsonb;
begin
  with picked as (
    select j.id
    from public.web_push_jobs j
    join public.web_push_subscriptions s on s.id = j.target_subscription_id
    where j.status = 'queued'
      and s.disabled_at is null
    order by j.created_at asc, j.id asc
    limit greatest(coalesce(max_jobs,25),1)
    for update of j skip locked
  ), claimed as (
    update public.web_push_jobs j
       set status = 'claimed',
           claimed_at = now(),
           updated_at = now(),
           claim_token = claim_token_input,
           claimed_by = worker_id_input,
           claim_expires_at = now() + interval '15 minutes',
           attempt_count = coalesce(j.attempt_count,0) + 1
     where j.id in (select id from picked)
     returning j.*
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'job_id', c.id,
    'title', c.title,
    'body', c.body,
    'target_url', c.target_url,
    'endpoint', s.endpoint,
    'p256dh_key', s.p256dh_key,
    'auth_key', s.auth_key,
    'target_scope', c.site_scope,
    'trigger_kind', c.trigger_kind,
    'notification_tag', c.notification_tag,
    'require_interaction', c.require_interaction,
    'vibrate_pattern', c.vibrate_pattern,
    'trace_id', c.trace_id
  ) order by c.created_at asc, c.id asc), '[]'::jsonb)
    into v_items
  from claimed c
  join public.web_push_subscriptions s on s.id = c.target_subscription_id;

  insert into public.web_push_job_attempts(job_id, worker_id, claim_token, stage, status)
  select c.id, worker_id_input, claim_token_input, 'claim', 'ok'
  from public.web_push_jobs c
  where c.claim_token = claim_token_input;

  return jsonb_build_object('ok', true, 'claim_token', claim_token_input, 'items', v_items);
end;
$$;

create or replace function public.mark_web_push_job_sent_v2(
  job_id_input bigint,
  claim_token_input uuid,
  worker_id_input text,
  provider_message_id_input text default null
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.web_push_jobs
     set status = 'sent',
         sent_at = now(),
         marked_at = now(),
         updated_at = now(),
         error_stage = null,
         error_code = null,
         error_text = null,
         provider_message_id = provider_message_id_input
   where id = job_id_input
     and claim_token = claim_token_input
     and claimed_by = worker_id_input;

  insert into public.web_push_job_attempts(job_id, worker_id, claim_token, stage, status)
  values (job_id_input, worker_id_input, claim_token_input, 'mark_sent', 'ok');

  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$$;

create or replace function public.mark_web_push_job_failed_v2(
  job_id_input bigint,
  claim_token_input uuid,
  worker_id_input text,
  error_stage_input text,
  error_code_input text,
  error_text_input text,
  disable_subscription_input boolean default false
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_sub_id bigint;
begin
  update public.web_push_jobs
     set status = 'failed',
         failed_at = now(),
         marked_at = now(),
         updated_at = now(),
         error_stage = left(coalesce(error_stage_input,''), 80),
         error_code = left(coalesce(error_code_input,''), 80),
         error_text = left(coalesce(error_text_input,''), 2000)
   where id = job_id_input
     and claim_token = claim_token_input
     and claimed_by = worker_id_input
   returning target_subscription_id into v_sub_id;

  insert into public.web_push_job_attempts(job_id, worker_id, claim_token, stage, status, error_code, error_text)
  values (job_id_input, worker_id_input, claim_token_input, coalesce(error_stage_input,'send'), 'failed', left(coalesce(error_code_input,''),80), left(coalesce(error_text_input,''),2000));

  if v_sub_id is not null then
    update public.web_push_subscriptions
       set updated_at = now(),
           last_error = left(coalesce(error_text_input,''), 1000),
           failure_count = coalesce(failure_count,0) + 1,
           disabled_at = case when disable_subscription_input then now() else disabled_at end
     where id = v_sub_id;
  end if;

  return jsonb_build_object('ok', true, 'job_id', job_id_input);
end;
$$;

create or replace function public.get_web_push_self_diagnostics_v2(
  session_token text,
  page_path_input text default null,
  site_scope_input text default 'friends'
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_player_id bigint := public._gejast_player_id_from_session(session_token);
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), public._web_push_scope_for_player(v_player_id), 'friends');
begin
  if v_player_id is null then raise exception 'MISSING_SESSION'; end if;

  return jsonb_build_object(
    'ok', true,
    'subscription', (
      select jsonb_build_object(
        'ok', s.id is not null,
        'subscription_id', s.id,
        'endpoint', s.endpoint,
        'permission_state', s.permission_state,
        'last_sync_at', s.last_sync_at,
        'last_error', s.last_error,
        'disabled_at', s.disabled_at
      )
      from public.web_push_subscriptions s
      where s.player_id = v_player_id
        and coalesce(s.site_scope, v_scope) = v_scope
      order by s.last_seen_at desc nulls last, s.id desc
      limit 1
    ),
    'presence', (
      select jsonb_build_object(
        'ok', p.id is not null,
        'presence_id', p.id,
        'last_seen_at', p.last_seen_at,
        'page_path', p.page_path,
        'installation_mode', p.installation_mode,
        'subscription_id', p.subscription_id
      )
      from public.web_push_active_presence p
      where p.player_id = v_player_id
        and coalesce(p.site_scope, v_scope) = v_scope
      order by p.last_seen_at desc nulls last, p.id desc
      limit 1
    ),
    'recent_job', (
      select jsonb_build_object(
        'job_id', j.id,
        'status', j.status,
        'trigger_kind', j.trigger_kind,
        'created_at', j.created_at,
        'claimed_at', j.claimed_at,
        'sent_at', j.sent_at,
        'failed_at', j.failed_at,
        'error_stage', j.error_stage,
        'error_code', j.error_code,
        'error_text', j.error_text
      )
      from public.web_push_jobs j
      where j.target_player_id = v_player_id
        and coalesce(j.site_scope, v_scope) = v_scope
      order by j.created_at desc, j.id desc
      limit 1
    )
  );
end;
$$;

create or replace function public.admin_get_web_push_diagnostics_v2(
  admin_session_token text,
  active_minutes integer default 5,
  site_scope_input text default 'friends'
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_scope text := coalesce(nullif(trim(coalesce(site_scope_input,'')), ''), 'friends');
  v_cutoff timestamptz := now() - make_interval(mins => greatest(coalesce(active_minutes,5),1));
  v_rows jsonb := '[]'::jsonb;
begin
  perform public.admin_check_session(admin_session_token);

  select coalesce(jsonb_agg(to_jsonb(x) order by x.last_seen_at desc nulls last, lower(x.player_name)), '[]'::jsonb)
    into v_rows
  from (
    select
      coalesce(s.display_name, p.display_name, public._web_push_player_name(coalesce(s.player_id, p.player_id))) as player_name,
      coalesce(s.site_scope, p.site_scope, v_scope) as site_scope,
      s.endpoint,
      s.permission_state,
      s.platform,
      s.installation_mode,
      s.disabled_at,
      s.last_sync_at,
      s.last_success_at,
      s.last_error as subscription_error,
      p.last_seen_at,
      p.page_path,
      p.subscription_id,
      case when s.id is null then 'missing_subscription' when s.disabled_at is not null then 'disabled_subscription' else 'subscription_ok' end as subscription_state,
      case when p.id is null then 'missing_presence' when p.last_seen_at < v_cutoff then 'stale_presence' else 'presence_ok' end as presence_state,
      j.status as job_status,
      j.claimed_at,
      j.sent_at,
      j.failed_at,
      j.error_stage,
      j.error_code,
      j.error_text,
      j.trigger_kind
    from public.web_push_subscriptions s
    full outer join public.web_push_active_presence p
      on p.subscription_id = s.id
    left join lateral (
      select *
      from public.web_push_jobs j
      where j.target_subscription_id = s.id
      order by j.created_at desc, j.id desc
      limit 1
    ) j on true
    where coalesce(s.site_scope, p.site_scope, v_scope) = v_scope
  ) x;

  return jsonb_build_object('ok', true, 'site_scope', v_scope, 'rows', v_rows, 'count', jsonb_array_length(v_rows));
end;
$$;

create or replace function public._queue_nearby_push_after_drink_event()
returns trigger
language plpgsql
as $$
begin
  if coalesce(new.status, 'pending') = 'pending' and new.lat is not null and new.lng is not null then
    perform public.queue_nearby_verification_pushes_v2('drink', new.id, 600);
  end if;
  return new;
end;
$$;

create or replace function public._queue_nearby_push_after_speed_attempt()
returns trigger
language plpgsql
as $$
begin
  if coalesce(new.status, 'pending') = 'pending' and new.lat is not null and new.lng is not null then
    perform public.queue_nearby_verification_pushes_v2('speed', new.id, 600);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_queue_nearby_push_after_drink_event on public.drink_events;
create trigger trg_queue_nearby_push_after_drink_event
after insert on public.drink_events
for each row execute function public._queue_nearby_push_after_drink_event();

drop trigger if exists trg_queue_nearby_push_after_speed_attempt on public.drink_speed_attempts;
create trigger trg_queue_nearby_push_after_speed_attempt
after insert on public.drink_speed_attempts
for each row execute function public._queue_nearby_push_after_speed_attempt();

grant execute on function public.register_web_push_subscription_v2(text, text, text, text, text, text, boolean, text, text, text, text) to anon, authenticated;
grant execute on function public.touch_active_web_push_presence_v2(text, text, text, text, text, text, boolean, text, text, text, double precision, double precision, double precision, text) to anon, authenticated;
grant execute on function public.queue_test_web_push_v2(text, text) to anon, authenticated;
grant execute on function public.queue_nearby_verification_pushes_v2(text, bigint, integer) to anon, authenticated;
grant execute on function public.admin_queue_active_web_push_v2(text, text, text, text, integer, text) to anon, authenticated;
grant execute on function public.requeue_stale_web_push_claims_v2(integer) to anon, authenticated;
grant execute on function public.claim_web_push_jobs_v2(integer, text, uuid) to anon, authenticated;
grant execute on function public.mark_web_push_job_sent_v2(bigint, uuid, text, text) to anon, authenticated;
grant execute on function public.mark_web_push_job_failed_v2(bigint, uuid, text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.get_web_push_self_diagnostics_v2(text, text, text) to anon, authenticated;
grant execute on function public.admin_get_web_push_diagnostics_v2(text, integer, text) to anon, authenticated;

commit;

-- ===== existing structured performance helpers (v358) =====
begin;

create or replace function public.get_homepage_boot_bundle_scoped(
  session_token text default null,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_scope text := public._scope_norm(site_scope_input);
  v_homepage_state jsonb := '{}'::jsonb;
  v_extra_poll jsonb := '{}'::jsonb;
  v_ladders jsonb := '{}'::jsonb;
  v_drinks_home jsonb := '{}'::jsonb;
  v_drinks_top5 jsonb := '{}'::jsonb;
  v_live_entries jsonb := '{}'::jsonb;
begin
  begin
    v_homepage_state := public.get_gejast_homepage_state(session_token);
  exception when undefined_function or others then
    begin
      v_homepage_state := public.get_public_state(session_token);
    exception when others then
      v_homepage_state := '{}'::jsonb;
    end;
  end;

  begin
    v_extra_poll := public.get_site_poll_state('gejast_drinks_donderdag', session_token);
  exception when undefined_function or others then
    v_extra_poll := '{}'::jsonb;
  end;

  begin
    v_ladders := public.get_homepage_ladders_public_scoped(v_scope);
  exception when undefined_function then
    v_ladders := public.get_homepage_ladders_public();
  when others then
    v_ladders := '{}'::jsonb;
  end;

  begin
    v_drinks_home := public.get_drinks_homepage_public_scoped(v_scope);
  exception when undefined_function then
    v_drinks_home := public.get_drinks_homepage_public();
  when others then
    v_drinks_home := '{}'::jsonb;
  end;

  begin
    v_drinks_top5 := public.get_drinks_homepage_top5_public_scoped(v_scope);
  exception when undefined_function then
    v_drinks_top5 := public.get_drinks_homepage_top5_public();
  when others then
    v_drinks_top5 := '{}'::jsonb;
  end;

  begin
    v_live_entries := public.get_homepage_live_state_public(session_token);
  exception when others then
    v_live_entries := '{}'::jsonb;
  end;

  return jsonb_build_object(
    'site_scope', v_scope,
    'homepage_state', coalesce(v_homepage_state, '{}'::jsonb),
    'extra_poll_state', coalesce(v_extra_poll, '{}'::jsonb),
    'ladders', coalesce(v_ladders, '{}'::jsonb),
    'drinks_home', coalesce(v_drinks_home, '{}'::jsonb),
    'drinks_top5', coalesce(v_drinks_top5, '{}'::jsonb),
    'live_entries', coalesce(v_live_entries, '{}'::jsonb),
    'perf_hints', jsonb_build_object(
      'defer_drinks_top5_rotation', true,
      'defer_homepage_ladders_until_visible', v_scope = 'friends',
      'render_mobile_lite', true
    )
  );
end;
$fn$;

create or replace function public.get_player_page_bundle_scoped(
  player_name text,
  game_key text default 'klaverjas',
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_scope text := public._scope_norm(site_scope_input);
  v_unified jsonb := '{}'::jsonb;
  v_shared jsonb := '{}'::jsonb;
  v_insights jsonb := '{}'::jsonb;
  v_drinks jsonb := '{}'::jsonb;
  v_badges jsonb := '{}'::jsonb;
begin
  v_unified := public.get_public_player_unified_scoped(player_name, v_scope);
  v_shared := public.get_public_shared_player_stats_scoped(game_key, player_name, v_scope);
  v_insights := public.get_public_player_game_insights_scoped(game_key, player_name, v_scope);

  begin
    v_drinks := public.get_drink_player_public_scoped(player_name, v_scope);
  exception when undefined_function then
    v_drinks := public.get_drink_player_public(player_name);
  when others then
    v_drinks := '{}'::jsonb;
  end;

  begin
    v_badges := public.get_player_badge_bundle_scoped(player_name, v_scope);
  exception when undefined_function or others then
    v_badges := '{}'::jsonb;
  end;

  return jsonb_build_object(
    'player_name', player_name,
    'game_key', lower(trim(coalesce(game_key, 'klaverjas'))),
    'site_scope', v_scope,
    'unified', coalesce(v_unified, '{}'::jsonb),
    'shared_stats', coalesce(v_shared, '{}'::jsonb),
    'game_insights', coalesce(v_insights, '{}'::jsonb),
    'drinks', coalesce(v_drinks, '{}'::jsonb),
    'badges', coalesce(v_badges, '{}'::jsonb),
    'perf_hints', jsonb_build_object(
      'defer_matches_render', true,
      'defer_drinks_panel', true,
      'chunk_match_render', true
    )
  );
end;
$fn$;

create or replace function public.get_profiles_page_bundle_scoped(
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_scope text := public._scope_norm(site_scope_input);
  v_players jsonb := '[]'::jsonb;
  v_badges jsonb := '[]'::jsonb;
begin
  v_players := coalesce(public.get_all_site_players_public_scoped(v_scope)->'players', '[]'::jsonb);

  begin
    v_badges := coalesce(public.get_site_player_badge_cards_scoped(v_scope)->'players', '[]'::jsonb);
  exception when undefined_function or others then
    v_badges := '[]'::jsonb;
  end;

  return jsonb_build_object(
    'site_scope', v_scope,
    'players', coalesce(v_players, '[]'::jsonb),
    'badge_cards', coalesce(v_badges, '[]'::jsonb),
    'perf_hints', jsonb_build_object(
      'chunk_cards', true,
      'lazy_avatars', true,
      'mobile_initial_batch', 18
    )
  );
end;
$fn$;

create or replace function public.get_drinks_page_bundle_public_scoped(
  session_token text default null,
  viewer_lat numeric default null,
  viewer_lng numeric default null,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_scope text := public._scope_norm(site_scope_input);
  v_page jsonb := '{}'::jsonb;
  v_dashboard jsonb := '{}'::jsonb;
  v_history jsonb := '[]'::jsonb;
  v_speed jsonb := '{}'::jsonb;
begin
  begin
    v_page := public.get_drinks_page_public(session_token, viewer_lat, viewer_lng);
  exception when others then
    v_page := '{}'::jsonb;
  end;

  begin
    v_dashboard := public.get_drinks_dashboard_fallback_public();
  exception when others then
    v_dashboard := '{}'::jsonb;
  end;

  begin
    v_history := public.get_verified_drinks_history_public_scoped(25, v_scope);
  exception when undefined_function then
    v_history := public.get_verified_drinks_history_public(25);
  when others then
    v_history := '[]'::jsonb;
  end;

  begin
    v_speed := public.get_drink_speed_page_public(session_token);
  exception when others then
    v_speed := '{}'::jsonb;
  end;

  return jsonb_build_object(
    'site_scope', v_scope,
    'page', coalesce(v_page, '{}'::jsonb),
    'dashboard', coalesce(v_dashboard, '{}'::jsonb),
    'history', coalesce(v_history, '[]'::jsonb),
    'speed', coalesce(v_speed, '{}'::jsonb),
    'perf_hints', jsonb_build_object(
      'defer_location_breakdown', true,
      'defer_speed_highlights', true,
      'geo_refresh_cooldown_ms', 15000
    )
  );
end;
$fn$;

grant execute on function public.get_homepage_boot_bundle_scoped(text, text) to anon, authenticated;
grant execute on function public.get_player_page_bundle_scoped(text, text, text) to anon, authenticated;
grant execute on function public.get_profiles_page_bundle_scoped(text) to anon, authenticated;
grant execute on function public.get_drinks_page_bundle_public_scoped(text, numeric, numeric, text) to anon, authenticated;

commit;

begin;

-- Compatibility wrapper for callers that still hit queue_test_web_push directly.
create or replace function public.queue_test_web_push(
  session_token_input text default null,
  session_token text default null,
  site_scope_input text default 'friends'
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_token text := coalesce(nullif(trim(coalesce(session_token_input,'')), ''), nullif(trim(coalesce(session_token,'')), ''));
begin
  if to_regprocedure('public.queue_test_web_push_v2(text,text)') is not null then
    return public.queue_test_web_push_v2(v_token, site_scope_input);
  end if;

  if to_regprocedure('public.queue_test_web_push(text)') is not null then
    return public.queue_test_web_push(v_token);
  end if;

  return jsonb_build_object('ok', false, 'reason', 'queue_test_web_push_missing');
end;
$$;

grant execute on function public.queue_test_web_push(text, text, text) to anon, authenticated;

-- Compatibility wrapper for newer frontend push runtime expecting *_v3.
create or replace function public.touch_active_web_push_presence_v3(
  session_token_input text default null,
  endpoint_input text default null,
  p256dh_input text default null,
  auth_input text default null,
  page_path_input text default null,
  permission_input text default null,
  standalone_input boolean default null,
  site_scope_input text default 'friends',
  platform_input text default null,
  installation_mode_input text default null,
  user_agent_input text default null,
  lat_input double precision default null,
  lng_input double precision default null,
  accuracy_input double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_token text := nullif(trim(coalesce(session_token_input,'')), '');
begin
  if to_regprocedure('public.touch_active_web_push_presence_v2(text,text,text,text,text,text,boolean,text,text,text,text,double precision,double precision,double precision)') is not null then
    return public.touch_active_web_push_presence_v2(
      v_token, endpoint_input, p256dh_input, auth_input, page_path_input, permission_input, standalone_input,
      site_scope_input, platform_input, installation_mode_input, user_agent_input, lat_input, lng_input, accuracy_input
    );
  end if;

  if to_regprocedure('public.touch_active_web_push_presence(text,text,text,text,text,text,boolean)') is not null then
    return public.touch_active_web_push_presence(
      v_token, endpoint_input, p256dh_input, auth_input, page_path_input, permission_input, standalone_input
    );
  end if;

  return jsonb_build_object('ok', false, 'reason', 'touch_active_web_push_presence_missing');
end;
$$;

grant execute on function public.touch_active_web_push_presence_v3(text, text, text, text, text, text, boolean, text, text, text, text, double precision, double precision, double precision) to anon, authenticated;

commit;
