
-- gejast v125 stats hub + unified ladders
begin;

create table if not exists public.game_elo_ratings (
  game_key text not null,
  player_name text not null,
  elo_rating numeric(10,2) not null default 1000,
  games_played integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  last_match_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (game_key, player_name)
);

create table if not exists public.game_elo_history (
  id bigint generated by default as identity primary key,
  game_key text not null,
  match_ref text not null,
  player_name text not null,
  rating_before numeric(10,2) not null,
  rating_after numeric(10,2) not null,
  delta numeric(10,2) not null,
  finish_position numeric(10,2),
  actual_score numeric(10,4),
  event_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create unique index if not exists game_elo_history_unique_match_player_idx
  on public.game_elo_history (game_key, match_ref, lower(player_name));
create index if not exists game_elo_history_lookup_idx
  on public.game_elo_history (game_key, event_at desc);
create index if not exists game_elo_ratings_lookup_idx
  on public.game_elo_ratings (game_key, elo_rating desc, lower(player_name));

create or replace function public._game_expected_score(player_rating numeric, opponent_rating numeric)
returns numeric
language sql
immutable
as $$
  select 1.0 / (1.0 + power(10.0, (($2 - $1) / 400.0)));
$$;

create or replace function public._ensure_game_elo_row(p_game_key text, p_player_name text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if nullif(trim(coalesce(p_player_name,'')), '') is null then
    return;
  end if;

  insert into public.game_elo_ratings(game_key, player_name)
  values (lower(trim(p_game_key)), trim(p_player_name))
  on conflict (game_key, player_name) do nothing;
end;
$$;

create or replace function public._apply_klaverjas_match_elo(p_game_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_match_ref text := concat('jas:', p_game_id);
  v_finished_at timestamptz;
  v_team_1 text[];
  v_team_2 text[];
  v_team_1_avg numeric;
  v_team_2_avg numeric;
  v_expected_1 numeric;
  v_expected_2 numeric;
  v_actual_1 numeric;
  v_actual_2 numeric;
  v_delta_1 numeric;
  v_delta_2 numeric;
  v_name text;
  v_before numeric;
  v_after numeric;
  v_entry record;
  v_k numeric := 28.0;
begin
  if exists (select 1 from public.game_elo_history where game_key='klaverjas' and match_ref=v_match_ref limit 1) then
    return;
  end if;

  if (select count(*) from public.jas_game_entries where game_id = p_game_id) <> 4 then
    return;
  end if;

  select coalesce(g.created_at, now()) into v_finished_at
  from public.jas_games g where g.id = p_game_id;

  select array_agg(display_name order by seat_no) filter (where team_no = 1),
         array_agg(display_name order by seat_no) filter (where team_no = 2)
    into v_team_1, v_team_2
  from public.jas_game_entries
  where game_id = p_game_id;

  if coalesce(array_length(v_team_1,1),0) <> 2 or coalesce(array_length(v_team_2,1),0) <> 2 then
    return;
  end if;

  foreach v_name in array v_team_1 loop perform public._ensure_game_elo_row('klaverjas', v_name); end loop;
  foreach v_name in array v_team_2 loop perform public._ensure_game_elo_row('klaverjas', v_name); end loop;

  select avg(elo_rating) into v_team_1_avg from public.game_elo_ratings where game_key='klaverjas' and player_name = any(v_team_1);
  select avg(elo_rating) into v_team_2_avg from public.game_elo_ratings where game_key='klaverjas' and player_name = any(v_team_2);

  v_expected_1 := public._game_expected_score(v_team_1_avg, v_team_2_avg);
  v_expected_2 := public._game_expected_score(v_team_2_avg, v_team_1_avg);
  v_actual_1 := case when exists (select 1 from public.jas_game_entries where game_id=p_game_id and team_no=1 and is_winner is true) then 1 else 0 end;
  v_actual_2 := 1 - v_actual_1;
  v_delta_1 := v_k * (v_actual_1 - v_expected_1);
  v_delta_2 := v_k * (v_actual_2 - v_expected_2);

  for v_entry in
    select display_name, team_no, is_winner, total_points,
           case when is_winner then 1.5 else 3.5 end as finish_position
    from public.jas_game_entries
    where game_id = p_game_id
  loop
    select elo_rating into v_before
    from public.game_elo_ratings
    where game_key='klaverjas' and player_name=v_entry.display_name;

    update public.game_elo_ratings r
       set elo_rating = r.elo_rating + (case when v_entry.team_no=1 then v_delta_1 else v_delta_2 end) / 2.0,
           games_played = r.games_played + 1,
           wins = r.wins + case when v_entry.is_winner then 1 else 0 end,
           losses = r.losses + case when v_entry.is_winner then 0 else 1 end,
           last_match_at = v_finished_at,
           updated_at = now()
     where r.game_key='klaverjas' and r.player_name=v_entry.display_name;

    select elo_rating into v_after
    from public.game_elo_ratings
    where game_key='klaverjas' and player_name=v_entry.display_name;

    insert into public.game_elo_history(
      game_key, match_ref, player_name, rating_before, rating_after, delta, finish_position, actual_score, event_at, payload
    ) values (
      'klaverjas', v_match_ref, v_entry.display_name, coalesce(v_before,1000), coalesce(v_after,1000),
      round(coalesce(v_after,1000) - coalesce(v_before,1000), 2), v_entry.finish_position,
      case when v_entry.is_winner then 1 else 0 end, v_finished_at,
      jsonb_build_object('game_id', p_game_id, 'team_no', v_entry.team_no, 'total_points', v_entry.total_points)
    )
    on conflict (game_key, match_ref, lower(player_name)) do nothing;
  end loop;
end;
$$;

create or replace function public._apply_boerenbridge_match_elo(p_match_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_match record;
  v_match_ref text;
  v_finished_at timestamptz;
  v_k numeric := 24.0;
  v_row record;
  v_other record;
  v_expected numeric;
  v_actual numeric;
  v_before numeric;
  v_after numeric;
  v_delta numeric;
  v_player_count integer;
begin
  select m.* into v_match
  from public.boerenbridge_matches m
  where m.id = p_match_id;

  if not found then return; end if;
  if coalesce(lower(v_match.match_status), '') <> 'finished' then return; end if;

  v_match_ref := concat('boerenbridge:', coalesce(v_match.client_match_id, p_match_id::text));
  if exists (select 1 from public.game_elo_history where game_key='boerenbridge' and match_ref=v_match_ref limit 1) then
    return;
  end if;

  v_finished_at := coalesce(v_match.finished_at, v_match.updated_at, now());

  create temporary table if not exists tmp_bb_rank (
    player_name text,
    final_points integer,
    is_winner boolean,
    finish_position numeric,
    actual_score numeric
  ) on commit drop;
  truncate tmp_bb_rank;

  insert into tmp_bb_rank(player_name, final_points, is_winner)
  select
    trim(coalesce(x->>'name','')) as player_name,
    coalesce((x->>'final_total_points')::integer, 0) as final_points,
    trim(coalesce(x->>'name','')) = any(
      coalesce((select array_agg(value::text) from jsonb_array_elements_text(coalesce(v_match.payload->'match_summary'->'winner_names','[]'::jsonb))), '{}'::text[])
    ) as is_winner
  from jsonb_array_elements(coalesce(v_match.payload->'totals','[]'::jsonb)) x
  where nullif(trim(coalesce(x->>'name','')), '') is not null;

  select count(*) into v_player_count from tmp_bb_rank;
  if v_player_count < 2 then return; end if;

  with ranked as (
    select player_name, rank() over (order by final_points desc, lower(player_name)) as pos
    from tmp_bb_rank
  )
  update tmp_bb_rank t
     set finish_position = ranked.pos,
         actual_score = case when v_player_count <= 1 then 1 else greatest(0, (v_player_count - ranked.pos)::numeric / (v_player_count - 1)::numeric) end
  from ranked where ranked.player_name = t.player_name;

  for v_row in select * from tmp_bb_rank loop
    perform public._ensure_game_elo_row('boerenbridge', v_row.player_name);
  end loop;

  for v_row in select * from tmp_bb_rank loop
    v_expected := 0;
    for v_other in select * from tmp_bb_rank where lower(player_name) <> lower(v_row.player_name) loop
      v_expected := v_expected + public._game_expected_score(
        coalesce((select elo_rating from public.game_elo_ratings where game_key='boerenbridge' and player_name=v_row.player_name), 1000),
        coalesce((select elo_rating from public.game_elo_ratings where game_key='boerenbridge' and player_name=v_other.player_name), 1000)
      );
    end loop;
    v_expected := v_expected / greatest(v_player_count - 1, 1);
    v_actual := coalesce(v_row.actual_score, 0);
    v_delta := round(v_k * (v_actual - v_expected), 2);

    select elo_rating into v_before
    from public.game_elo_ratings where game_key='boerenbridge' and player_name=v_row.player_name;

    update public.game_elo_ratings r
       set elo_rating = r.elo_rating + v_delta,
           games_played = r.games_played + 1,
           wins = r.wins + case when v_row.is_winner then 1 else 0 end,
           losses = r.losses + case when v_row.is_winner then 0 else 1 end,
           last_match_at = v_finished_at,
           updated_at = now()
     where r.game_key='boerenbridge' and r.player_name=v_row.player_name;

    select elo_rating into v_after
    from public.game_elo_ratings where game_key='boerenbridge' and player_name=v_row.player_name;

    insert into public.game_elo_history(
      game_key, match_ref, player_name, rating_before, rating_after, delta, finish_position, actual_score, event_at, payload
    ) values (
      'boerenbridge', v_match_ref, v_row.player_name, coalesce(v_before,1000), coalesce(v_after,1000),
      round(coalesce(v_after,1000) - coalesce(v_before,1000),2), v_row.finish_position, v_actual, v_finished_at,
      jsonb_build_object('match_id', p_match_id, 'final_points', v_row.final_points, 'player_count', v_player_count)
    )
    on conflict (game_key, match_ref, lower(player_name)) do nothing;
  end loop;
end;
$$;

create or replace function public._trg_apply_klaverjas_elo()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  perform public._apply_klaverjas_match_elo(coalesce(new.game_id, old.game_id));
  return coalesce(new, old);
end;
$$;

create or replace function public._trg_apply_boerenbridge_elo()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  perform public._apply_boerenbridge_match_elo(coalesce(new.id, old.id));
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_apply_klaverjas_elo on public.jas_game_entries;
create trigger trg_apply_klaverjas_elo
after insert or update on public.jas_game_entries
for each row execute function public._trg_apply_klaverjas_elo();

drop trigger if exists trg_apply_boerenbridge_elo on public.boerenbridge_matches;
create trigger trg_apply_boerenbridge_elo
after insert or update on public.boerenbridge_matches
for each row execute function public._trg_apply_boerenbridge_elo();

create or replace function public.rebuild_stats_hub_elo(p_game_key text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_game text := lower(trim(coalesce(p_game_key, '')));
  v_row record;
begin
  if v_game in ('', 'klaverjas') then
    delete from public.game_elo_history where game_key='klaverjas';
    delete from public.game_elo_ratings where game_key='klaverjas';
    for v_row in select id from public.jas_games order by played_at, created_at, id loop
      perform public._apply_klaverjas_match_elo(v_row.id);
    end loop;
  end if;

  if v_game in ('', 'boerenbridge') then
    delete from public.game_elo_history where game_key='boerenbridge';
    delete from public.game_elo_ratings where game_key='boerenbridge';
    for v_row in select id from public.boerenbridge_matches where coalesce(lower(match_status),'')='finished' order by coalesce(finished_at, updated_at, created_at), id loop
      perform public._apply_boerenbridge_match_elo(v_row.id);
    end loop;
  end if;

  return jsonb_build_object(
    'ok', true,
    'rebuilt', case when v_game='' then jsonb_build_array('klaverjas','boerenbridge') else jsonb_build_array(v_game) end
  );
end;
$$;

create or replace function public.get_stats_hub_homepage()
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_cards jsonb;
  v_totals jsonb;
begin
  with unified as (
    select 'klaverjas'::text as game_key, player_name, elo_rating as rating, games_played, wins, losses, last_match_at
    from public.game_elo_ratings where game_key='klaverjas'
    union all
    select 'boerenbridge'::text as game_key, player_name, elo_rating as rating, games_played, wins, losses, last_match_at
    from public.game_elo_ratings where game_key='boerenbridge'
    union all
    select 'beerpong'::text as game_key, player_name, elo_rating as rating, games_played, wins, losses, last_match_at
    from public.beerpong_player_ratings
  ), ranked as (
    select *, row_number() over (partition by game_key order by rating desc, wins desc, lower(player_name)) as rn
    from unified
  )
  select jsonb_build_object(
    'klaverjas', coalesce((select jsonb_agg(jsonb_build_object('player_name', player_name, 'rating', round(rating,2), 'games_played', games_played, 'wins', wins, 'losses', losses) order by rn) from ranked where game_key='klaverjas' and rn <= 5), '[]'::jsonb),
    'boerenbridge', coalesce((select jsonb_agg(jsonb_build_object('player_name', player_name, 'rating', round(rating,2), 'games_played', games_played, 'wins', wins, 'losses', losses) order by rn) from ranked where game_key='boerenbridge' and rn <= 5), '[]'::jsonb),
    'beerpong', coalesce((select jsonb_agg(jsonb_build_object('player_name', player_name, 'rating', round(rating,2), 'games_played', games_played, 'wins', wins, 'losses', losses) order by rn) from ranked where game_key='beerpong' and rn <= 5), '[]'::jsonb)
  ) into v_cards;

  with unified as (
    select 'klaverjas'::text as game_key, count(*)::int as players, round(avg(elo_rating),1) as avg_rating from public.game_elo_ratings where game_key='klaverjas'
    union all
    select 'boerenbridge'::text as game_key, count(*)::int as players, round(avg(elo_rating),1) as avg_rating from public.game_elo_ratings where game_key='boerenbridge'
    union all
    select 'beerpong'::text as game_key, count(*)::int as players, round(avg(elo_rating),1) as avg_rating from public.beerpong_player_ratings
  )
  select jsonb_object_agg(game_key, jsonb_build_object('players', players, 'avg_rating', avg_rating)) into v_totals from unified;

  return jsonb_build_object('top_five', coalesce(v_cards, '{}'::jsonb), 'totals', coalesce(v_totals, '{}'::jsonb));
end;
$$;

create or replace function public.get_game_ladder_page(p_game_key text, limit_count integer default 250)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_game text := lower(trim(coalesce(p_game_key,'')));
  v_limit integer := greatest(coalesce(limit_count,250), 1);
  v_board jsonb;
  v_histories jsonb;
  v_recent jsonb;
  v_summary jsonb;
begin
  if v_game = 'beerpong' then
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_name', player_name,
      'rating', round(elo_rating,2),
      'games_played', games_played,
      'wins', wins,
      'losses', losses,
      'winrate', case when games_played>0 then round((100.0*wins::numeric)/games_played::numeric,1) else 0 end,
      'last_match_at', last_match_at
    ) order by elo_rating desc, wins desc, lower(player_name)), '[]'::jsonb)
    into v_board
    from (select * from public.beerpong_player_ratings order by elo_rating desc, wins desc, lower(player_name) limit v_limit) x;

    with top10 as (
      select player_name from public.beerpong_player_ratings order by elo_rating desc, wins desc, lower(player_name) limit 10
    )
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_name', t.player_name,
      'series', (
        select coalesce(jsonb_agg(jsonb_build_object('label', to_char(h.created_at,'DD Mon'),'rating', round(h.rating_after,2)) order by h.created_at), '[]'::jsonb)
        from public.beerpong_player_rating_history h
        where lower(h.player_name)=lower(t.player_name)
      )
    ) order by lower(t.player_name)), '[]'::jsonb)
    into v_histories
    from top10 t;

    select coalesce(jsonb_agg(jsonb_build_object(
      'title', concat_ws(' vs ', array_to_string(team_a_player_names,' + '), array_to_string(team_b_player_names,' + ')),
      'played_at', coalesce(finished_at, created_at),
      'winner_names', case when winner_team='a' then team_a_player_names else team_b_player_names end,
      'margin', abs(coalesce(team_a_cups_left,0)-coalesce(team_b_cups_left,0))
    ) order by coalesce(finished_at, created_at) desc), '[]'::jsonb)
    into v_recent
    from (select * from public.beerpong_matches order by coalesce(finished_at, created_at) desc limit 25) m;

    select jsonb_build_object(
      'game_key', 'beerpong',
      'players', coalesce((select count(*) from public.beerpong_player_ratings),0),
      'matches', coalesce((select count(*) from public.beerpong_matches),0),
      'leader', coalesce((select player_name from public.beerpong_player_ratings order by elo_rating desc, wins desc, lower(player_name) limit 1), '-'),
      'avg_rating', coalesce((select round(avg(elo_rating),1) from public.beerpong_player_ratings),0)
    ) into v_summary;
  else
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_name', player_name,
      'rating', round(elo_rating,2),
      'games_played', games_played,
      'wins', wins,
      'losses', losses,
      'winrate', case when games_played>0 then round((100.0*wins::numeric)/games_played::numeric,1) else 0 end,
      'last_match_at', last_match_at
    ) order by elo_rating desc, wins desc, lower(player_name)), '[]'::jsonb)
    into v_board
    from (select * from public.game_elo_ratings where game_key=v_game order by elo_rating desc, wins desc, lower(player_name) limit v_limit) x;

    with top10 as (
      select player_name from public.game_elo_ratings where game_key=v_game order by elo_rating desc, wins desc, lower(player_name) limit 10
    )
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_name', t.player_name,
      'series', (
        select coalesce(jsonb_agg(jsonb_build_object('label', to_char(h.event_at,'DD Mon'),'rating', round(h.rating_after,2)) order by h.event_at), '[]'::jsonb)
        from public.game_elo_history h
        where h.game_key=v_game and lower(h.player_name)=lower(t.player_name)
      )
    ) order by lower(t.player_name)), '[]'::jsonb)
    into v_histories
    from top10 t;

    if v_game='klaverjas' then
      select coalesce(jsonb_agg(jsonb_build_object(
        'title', coalesce(g.title,'Klaverjas potje'),
        'played_at', coalesce(g.played_at::timestamptz, g.created_at),
        'winner_names', (select coalesce(jsonb_agg(e.display_name order by e.seat_no), '[]'::jsonb) from public.jas_game_entries e where e.game_id=g.id and e.is_winner is true),
        'entries', (select coalesce(jsonb_agg(jsonb_build_object('player_name', e.display_name, 'points', e.total_points, 'is_winner', e.is_winner) order by e.seat_no), '[]'::jsonb) from public.jas_game_entries e where e.game_id=g.id)
      ) order by g.played_at desc, g.created_at desc), '[]'::jsonb)
      into v_recent
      from (select * from public.jas_games order by played_at desc, created_at desc limit 25) g;

      select jsonb_build_object(
        'game_key', 'klaverjas',
        'players', coalesce((select count(*) from public.game_elo_ratings where game_key='klaverjas'),0),
        'matches', coalesce((select count(*) from public.jas_games),0),
        'leader', coalesce((select player_name from public.game_elo_ratings where game_key='klaverjas' order by elo_rating desc, wins desc, lower(player_name) limit 1), '-'),
        'avg_rating', coalesce((select round(avg(elo_rating),1) from public.game_elo_ratings where game_key='klaverjas'),0)
      ) into v_summary;
    else
      select coalesce(jsonb_agg(jsonb_build_object(
        'title', coalesce(match_name,'Boerenbridge'),
        'played_at', coalesce(finished_at, updated_at, created_at),
        'winner_names', coalesce(payload->'match_summary'->'winner_names', '[]'::jsonb),
        'entries', coalesce(payload->'totals', '[]'::jsonb)
      ) order by coalesce(finished_at, updated_at, created_at) desc), '[]'::jsonb)
      into v_recent
      from (select * from public.boerenbridge_matches where coalesce(lower(match_status),'')='finished' order by coalesce(finished_at, updated_at, created_at) desc limit 25) m;

      select jsonb_build_object(
        'game_key', 'boerenbridge',
        'players', coalesce((select count(*) from public.game_elo_ratings where game_key='boerenbridge'),0),
        'matches', coalesce((select count(*) from public.boerenbridge_matches where coalesce(lower(match_status),'')='finished'),0),
        'leader', coalesce((select player_name from public.game_elo_ratings where game_key='boerenbridge' order by elo_rating desc, wins desc, lower(player_name) limit 1), '-'),
        'avg_rating', coalesce((select round(avg(elo_rating),1) from public.game_elo_ratings where game_key='boerenbridge'),0)
      ) into v_summary;
    end if;
  end if;

  return jsonb_build_object('summary', v_summary, 'leaderboard', coalesce(v_board,'[]'::jsonb), 'histories', coalesce(v_histories,'[]'::jsonb), 'recent_matches', coalesce(v_recent,'[]'::jsonb));
end;
$$;

create or replace function public.get_game_player_profile(p_game_key text, p_player_name text, limit_matches integer default 100)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_game text := lower(trim(coalesce(p_game_key,'')));
  v_name text := trim(coalesce(p_player_name,''));
  v_summary jsonb;
  v_matches jsonb;
  v_history jsonb;
begin
  if v_game='beerpong' then
    select jsonb_build_object(
      'player_name', v_name,
      'rating', coalesce((select round(elo_rating,2) from public.beerpong_player_ratings where lower(player_name)=lower(v_name)), 1000),
      'games_played', coalesce((select games_played from public.beerpong_player_ratings where lower(player_name)=lower(v_name)), 0),
      'wins', coalesce((select wins from public.beerpong_player_ratings where lower(player_name)=lower(v_name)), 0),
      'losses', coalesce((select losses from public.beerpong_player_ratings where lower(player_name)=lower(v_name)), 0),
      'winrate', coalesce((select case when games_played>0 then round((100.0*wins::numeric)/games_played::numeric,1) else 0 end from public.beerpong_player_ratings where lower(player_name)=lower(v_name)), 0)
    ) into v_summary;

    select coalesce(jsonb_agg(jsonb_build_object(
      'played_at', coalesce(m.finished_at, m.created_at),
      'title', concat_ws(' vs ', array_to_string(m.team_a_player_names,' + '), array_to_string(m.team_b_player_names,' + ')),
      'result', case when (m.winner_team='a' and lower(v_name)=any(select lower(x) from unnest(m.team_a_player_names) x)) or (m.winner_team='b' and lower(v_name)=any(select lower(x) from unnest(m.team_b_player_names) x)) then 'W' else 'L' end,
      'details', jsonb_build_object('winner_team', m.winner_team, 'team_a', m.team_a_player_names, 'team_b', m.team_b_player_names, 'margin', abs(coalesce(m.team_a_cups_left,0)-coalesce(m.team_b_cups_left,0)))
    ) order by coalesce(m.finished_at,m.created_at) desc), '[]'::jsonb)
    into v_matches
    from (
      select * from public.beerpong_matches m
      where exists (select 1 from unnest(coalesce(m.team_a_player_names,'{}'::text[])) x where lower(x)=lower(v_name))
         or exists (select 1 from unnest(coalesce(m.team_b_player_names,'{}'::text[])) x where lower(x)=lower(v_name))
      order by coalesce(m.finished_at,m.created_at) desc limit greatest(limit_matches,1)
    ) m;

    select coalesce(jsonb_agg(jsonb_build_object('label', to_char(created_at,'DD Mon'),'rating', round(rating_after,2)) order by created_at), '[]'::jsonb)
      into v_history
    from public.beerpong_player_rating_history where lower(player_name)=lower(v_name);
  elsif v_game='klaverjas' then
    select jsonb_build_object(
      'player_name', v_name,
      'rating', coalesce((select round(elo_rating,2) from public.game_elo_ratings where game_key='klaverjas' and lower(player_name)=lower(v_name)), 1000),
      'games_played', coalesce((select games_played from public.game_elo_ratings where game_key='klaverjas' and lower(player_name)=lower(v_name)), 0),
      'wins', coalesce((select wins from public.game_elo_ratings where game_key='klaverjas' and lower(player_name)=lower(v_name)), 0),
      'losses', coalesce((select losses from public.game_elo_ratings where game_key='klaverjas' and lower(player_name)=lower(v_name)), 0),
      'winrate', coalesce((select case when games_played>0 then round((100.0*wins::numeric)/games_played::numeric,1) else 0 end from public.game_elo_ratings where game_key='klaverjas' and lower(player_name)=lower(v_name)), 0),
      'avg_points', coalesce((select round(avg(total_points),1) from public.jas_game_entries where lower(display_name)=lower(v_name)), 0),
      'best_game', coalesce((select max(total_points) from public.jas_game_entries where lower(display_name)=lower(v_name)), 0)
    ) into v_summary;

    select coalesce(jsonb_agg(jsonb_build_object(
      'played_at', coalesce(g.played_at::timestamptz, g.created_at),
      'title', coalesce(g.title,'Klaverjas potje'),
      'result', case when e.is_winner then 'W' else 'L' end,
      'details', jsonb_build_object('points', e.total_points, 'seat_no', e.seat_no, 'team_no', e.team_no)
    ) order by g.played_at desc, g.created_at desc), '[]'::jsonb)
    into v_matches
    from (
      select g.*, e.total_points, e.is_winner, e.seat_no, e.team_no
      from public.jas_game_entries e
      join public.jas_games g on g.id=e.game_id
      where lower(e.display_name)=lower(v_name)
      order by g.played_at desc, g.created_at desc
      limit greatest(limit_matches,1)
    ) g;

    select coalesce(jsonb_agg(jsonb_build_object('label', to_char(event_at,'DD Mon'),'rating', round(rating_after,2)) order by event_at), '[]'::jsonb)
      into v_history
    from public.game_elo_history where game_key='klaverjas' and lower(player_name)=lower(v_name);
  else
    select jsonb_build_object(
      'player_name', v_name,
      'rating', coalesce((select round(elo_rating,2) from public.game_elo_ratings where game_key='boerenbridge' and lower(player_name)=lower(v_name)), 1000),
      'games_played', coalesce((select games_played from public.game_elo_ratings where game_key='boerenbridge' and lower(player_name)=lower(v_name)), 0),
      'wins', coalesce((select wins from public.game_elo_ratings where game_key='boerenbridge' and lower(player_name)=lower(v_name)), 0),
      'losses', coalesce((select losses from public.game_elo_ratings where game_key='boerenbridge' and lower(player_name)=lower(v_name)), 0),
      'winrate', coalesce((select case when games_played>0 then round((100.0*wins::numeric)/games_played::numeric,1) else 0 end from public.game_elo_ratings where game_key='boerenbridge' and lower(player_name)=lower(v_name)), 0),
      'avg_points', coalesce((select round(avg((x->>'final_total_points')::numeric),1) from public.boerenbridge_matches m, jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x where coalesce(lower(m.match_status),'')='finished' and lower(x->>'name')=lower(v_name)), 0),
      'best_game', coalesce((select max((x->>'final_total_points')::integer) from public.boerenbridge_matches m, jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x where coalesce(lower(m.match_status),'')='finished' and lower(x->>'name')=lower(v_name)), 0),
      'avg_finish', coalesce((select round(avg(h.finish_position),2) from public.game_elo_history h where h.game_key='boerenbridge' and lower(h.player_name)=lower(v_name)), 0),
      'field_score', coalesce((select round(avg(h.actual_score)*100,1) from public.game_elo_history h where h.game_key='boerenbridge' and lower(h.player_name)=lower(v_name)), 0),
      'exact_bid_rate', coalesce((select round(avg(case when total_rounds > 0 then exacts::numeric / total_rounds::numeric else 0 end) * 100, 1) from (
        select coalesce((x->>'exact_bid_count')::integer,0) as exacts,
               greatest(jsonb_array_length(coalesce(m.payload->'rounds','[]'::jsonb)),0) as total_rounds
        from public.boerenbridge_matches m, jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x
        where coalesce(lower(m.match_status),'')='finished' and lower(x->>'name')=lower(v_name)
      ) s), 0)
    ) into v_summary;

    select coalesce(jsonb_agg(jsonb_build_object(
      'played_at', coalesce(m.finished_at, m.updated_at, m.created_at),
      'title', coalesce(m.match_name,'Boerenbridge'),
      'result', case when exists (select 1 from jsonb_array_elements_text(coalesce(m.payload->'match_summary'->'winner_names','[]'::jsonb)) w where lower(w)=lower(v_name)) then 'W' else 'P' end,
      'details', (
        select jsonb_build_object(
          'final_points', coalesce((x->>'final_total_points')::integer,0),
          'exact_bid_count', coalesce((x->>'exact_bid_count')::integer,0),
          'total_slagen', coalesce((x->>'total_slagen')::integer,0)
        )
        from jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x
        where lower(x->>'name')=lower(v_name) limit 1
      )
    ) order by coalesce(m.finished_at,m.updated_at,m.created_at) desc), '[]'::jsonb)
    into v_matches
    from (
      select * from public.boerenbridge_matches m
      where coalesce(lower(m.match_status),'')='finished'
        and exists (select 1 from jsonb_array_elements(coalesce(m.payload->'totals','[]'::jsonb)) x where lower(x->>'name')=lower(v_name))
      order by coalesce(m.finished_at,m.updated_at,m.created_at) desc
      limit greatest(limit_matches,1)
    ) m;

    select coalesce(jsonb_agg(jsonb_build_object('label', to_char(event_at,'DD Mon'),'rating', round(rating_after,2)) order by event_at), '[]'::jsonb)
      into v_history
    from public.game_elo_history where game_key='boerenbridge' and lower(player_name)=lower(v_name);
  end if;

  return jsonb_build_object('summary', coalesce(v_summary,'{}'::jsonb), 'matches', coalesce(v_matches,'[]'::jsonb), 'history', coalesce(v_history,'[]'::jsonb));
end;
$$;

grant execute on function public.rebuild_stats_hub_elo(text) to anon, authenticated;
grant execute on function public.get_stats_hub_homepage() to anon, authenticated;
grant execute on function public.get_game_ladder_page(text, integer) to anon, authenticated;
grant execute on function public.get_game_player_profile(text, text, integer) to anon, authenticated;

commit;
