
begin;

create table if not exists public.site_visitor_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null default 'page_view',
  page_path text not null,
  page_title text,
  referrer_url text,
  visitor_id text not null,
  session_id text not null,
  device_type text,
  browser_name text,
  os_name text,
  viewport_width integer,
  viewport_height integer,
  language_code text,
  time_zone text,
  user_agent text,
  extra jsonb not null default '{}'::jsonb
);

create index if not exists site_visitor_events_created_at_idx on public.site_visitor_events (created_at desc);
create index if not exists site_visitor_events_page_path_idx on public.site_visitor_events (page_path);
create index if not exists site_visitor_events_visitor_id_idx on public.site_visitor_events (visitor_id);
create index if not exists site_visitor_events_session_id_idx on public.site_visitor_events (session_id);
create index if not exists site_visitor_events_event_name_idx on public.site_visitor_events (event_name);

create or replace function public.track_site_event(
  event_name text default 'page_view',
  page_path text default null,
  page_title text default null,
  referrer_url text default null,
  visitor_id text default null,
  session_id text default null,
  device_type text default null,
  browser_name text default null,
  os_name text default null,
  viewport_width integer default null,
  viewport_height integer default null,
  language_code text default null,
  time_zone text default null,
  user_agent text default null,
  extra jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $track$
declare
  v_page_path text := nullif(trim(coalesce(track_site_event.page_path, '')), '');
  v_visitor_id text := nullif(trim(coalesce(track_site_event.visitor_id, '')), '');
  v_session_id text := nullif(trim(coalesce(track_site_event.session_id, '')), '');
  v_event_name text := nullif(trim(coalesce(track_site_event.event_name, '')), '');
begin
  if v_page_path is null then raise exception 'page_path ontbreekt'; end if;
  if v_visitor_id is null then raise exception 'visitor_id ontbreekt'; end if;
  if v_session_id is null then raise exception 'session_id ontbreekt'; end if;
  if v_event_name is null then v_event_name := 'page_view'; end if;

  insert into public.site_visitor_events (
    event_name, page_path, page_title, referrer_url, visitor_id, session_id,
    device_type, browser_name, os_name, viewport_width, viewport_height,
    language_code, time_zone, user_agent, extra
  )
  values (
    v_event_name,
    v_page_path,
    nullif(trim(coalesce(track_site_event.page_title, '')), ''),
    nullif(trim(coalesce(track_site_event.referrer_url, '')), ''),
    v_visitor_id,
    v_session_id,
    nullif(trim(coalesce(track_site_event.device_type, '')), ''),
    nullif(trim(coalesce(track_site_event.browser_name, '')), ''),
    nullif(trim(coalesce(track_site_event.os_name, '')), ''),
    track_site_event.viewport_width,
    track_site_event.viewport_height,
    nullif(trim(coalesce(track_site_event.language_code, '')), ''),
    nullif(trim(coalesce(track_site_event.time_zone, '')), ''),
    nullif(trim(coalesce(track_site_event.user_agent, '')), ''),
    coalesce(track_site_event.extra, '{}'::jsonb)
  );

  return jsonb_build_object('ok', true);
end;
$track$;

create or replace function public.admin_get_site_analytics_action(
  admin_session_token text,
  range_days integer default 7,
  recent_limit integer default 80
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $analytics$
declare
  v_session jsonb;
  v_days integer := greatest(1, least(coalesce(range_days, 7), 365));
  v_recent_limit integer := greatest(1, least(coalesce(recent_limit, 80), 250));
  v_since timestamptz := date_trunc('day', now()) - make_interval(days => v_days - 1);
begin
  v_session := to_jsonb(public.admin_check_session(admin_session_token));
  if coalesce((v_session->>'ok')::boolean, false) is not true then
    raise exception 'Log opnieuw in als admin.';
  end if;

  return jsonb_build_object(
    'ok', true,
    'admin_session_token', coalesce(v_session->>'admin_session_token', admin_session_token),
    'summary', (
      select jsonb_build_object(
        'total_views', count(*)::int,
        'unique_visitors', count(distinct e.visitor_id)::int,
        'unique_sessions', count(distinct e.session_id)::int,
        'range_days', v_days
      )
      from public.site_visitor_events e
      where e.created_at >= v_since
    ),
    'daily_views', coalesce((
      with days as (
        select generate_series(
          date_trunc('day', now()) - make_interval(days => v_days - 1),
          date_trunc('day', now()),
          interval '1 day'
        ) as day_start
      ), counts as (
        select date_trunc('day', e.created_at) as day_start, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
      )
      select jsonb_agg(jsonb_build_object(
        'day', to_char(d.day_start, 'YYYY-MM-DD'),
        'day_label', to_char(d.day_start, 'DD Mon'),
        'views', coalesce(c.views, 0)
      ) order by d.day_start)
      from days d
      left join counts c on c.day_start = d.day_start
    ), '[]'::jsonb),
    'top_pages', coalesce((
      select jsonb_agg(jsonb_build_object('page_path', x.page_path, 'views', x.views) order by x.views desc, x.page_path)
      from (
        select e.page_path, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by e.page_path
        order by views desc, e.page_path
        limit 12
      ) x
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object('device_type', x.device_type, 'views', x.views) order by x.views desc, x.device_type)
      from (
        select coalesce(nullif(e.device_type,''), 'Onbekend') as device_type, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 8
      ) x
    ), '[]'::jsonb),
    'browsers', coalesce((
      select jsonb_agg(jsonb_build_object('browser_name', x.browser_name, 'views', x.views) order by x.views desc, x.browser_name)
      from (
        select coalesce(nullif(e.browser_name,''), 'Onbekend') as browser_name, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 8
      ) x
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(jsonb_build_object('referrer_url', x.referrer_url, 'views', x.views) order by x.views desc)
      from (
        select coalesce(nullif(e.referrer_url,''), 'Direct') as referrer_url, count(*)::int as views
        from public.site_visitor_events e
        where e.created_at >= v_since
        group by 1
        order by views desc, 1
        limit 10
      ) x
    ), '[]'::jsonb),
    'recent_events', coalesce((
      select jsonb_agg(jsonb_build_object(
        'created_at', x.created_at,
        'page_path', x.page_path,
        'device_type', x.device_type,
        'browser_name', x.browser_name,
        'referrer_url', x.referrer_url
      ) order by x.created_at desc)
      from (
        select e.created_at, e.page_path,
               coalesce(nullif(e.device_type,''), 'Onbekend') as device_type,
               coalesce(nullif(e.browser_name,''), 'Onbekend') as browser_name,
               coalesce(nullif(e.referrer_url,''), 'Direct') as referrer_url
        from public.site_visitor_events e
        where e.created_at >= v_since
        order by e.created_at desc
        limit v_recent_limit
      ) x
    ), '[]'::jsonb)
  );
end;
$analytics$;

grant execute on function public.track_site_event(text, text, text, text, text, text, text, text, text, integer, integer, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.admin_get_site_analytics_action(text, integer, integer) to anon, authenticated;

commit;
