
(function(global){
  function cfg(){ return global.GEJAST_CONFIG || {}; }
  function scope(){ try{ return global.GEJAST_ADMIN_RPC && global.GEJAST_ADMIN_RPC.getScope ? global.GEJAST_ADMIN_RPC.getScope() : (global.GEJAST_SCOPE_UTILS && global.GEJAST_SCOPE_UTILS.getScope ? global.GEJAST_SCOPE_UTILS.getScope() : 'friends'); }catch(_){ return 'friends'; } }
  function esc(v){ return String(v ?? '').replace(/[&<>"']/g, (m)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[m])); }
  function rpcHeaders(){ const c=cfg(); return { apikey:c.SUPABASE_PUBLISHABLE_KEY||'', Authorization:`Bearer ${c.SUPABASE_PUBLISHABLE_KEY||''}`, 'Content-Type':'application/json', Accept:'application/json' }; }
  async function parse(res){ const t=await res.text(); let d=null; try{ d=t?JSON.parse(t):null; }catch(_){ throw new Error(t||`HTTP ${res.status}`); } if(!res.ok) throw new Error(d?.message||d?.error||d?.details||d?.hint||t||`HTTP ${res.status}`); return d; }
  async function publicRpc(name, payload){ if(global.GEJAST_SCOPED_RPC && typeof global.GEJAST_SCOPED_RPC.callRpc==='function') return global.GEJAST_SCOPED_RPC.callRpc(name, payload||{}); const c=cfg(); const res=await fetch(`${c.SUPABASE_URL}/rest/v1/rpc/${name}`, { method:'POST', mode:'cors', cache:'no-store', headers:rpcHeaders(), body:JSON.stringify(payload||{})}); const raw=await parse(res); return raw && raw[name]!==undefined ? raw[name] : raw; }
  async function adminRpc(name, payload){ if(global.GEJAST_ADMIN_RPC && typeof global.GEJAST_ADMIN_RPC.rpc==='function'){ const raw=await global.GEJAST_ADMIN_RPC.rpc(name, payload||{}); return raw && raw[name]!==undefined ? raw[name] : raw; } const c=cfg(); const res=await fetch(`${c.SUPABASE_URL}/rest/v1/rpc/${name}`, { method:'POST', mode:'cors', cache:'no-store', headers:rpcHeaders(), body:JSON.stringify(payload||{})}); const raw=await parse(res); return raw && raw[name]!==undefined ? raw[name] : raw; }
  function setStatus(id,msg,kind){ const el=global.document.getElementById(id||'pageStatus'); if(!el) return; el.textContent=msg||''; el.className=`status${kind?` ${kind}`:''}`; }
  function num(v){ const n=Number(v); return Number.isFinite(n)?n:0; }
  function renderCards(targetId, cards, story){ const el=global.document.getElementById(targetId); if(!el) return; const rows=Array.isArray(cards)?cards:[]; el.className=`grid ${story?'story':'overview'}`; el.innerHTML=rows.length?rows.map((c)=>`<article class="card${story?' story-card':''}"><div class="k">${esc(c.label||c.k||'')}</div><div class="v">${esc(c.value||c.v||'')}</div><div class="sub">${esc(c.sub||'')}</div></article>`).join(''):`<div class="note">Nog geen data.</div>`; }
  function renderLeaderboards(targetId, sections){ const el=global.document.getElementById(targetId); if(!el) return; const list=Array.isArray(sections)?sections:[]; el.className='section-list'; el.innerHTML=list.length?list.map((sec)=>{ const rows=Array.isArray(sec.rows)?sec.rows:[]; const max=Math.max(1,...rows.map((r)=>num(r.value))); return `<article class="section-card"><div><h3>${esc(sec.title||'')}</h3><p>${esc(sec.subtitle||'')}</p></div><div class="bar-list">${rows.length?rows.map((r)=>{ const pct=Math.max(6,Math.round((num(r.value)/max)*100)); return `<div class="bar-row"><div class="bar-head"><strong>${esc(r.label||'')}</strong><span>${esc(r.value||'')}</span></div><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div><div class="bar-sub">${esc(r.sub||'')}</div></div>`; }).join(''):`<div class="note">Nog geen data.</div>`}</div></article>`; }).join(''):`<div class="note">Nog geen leaderboards.</div>`; }
  function renderRecent(targetId, rows){ const el=global.document.getElementById(targetId); if(!el) return; const list=Array.isArray(rows)?rows:[]; el.className='feed'; el.innerHTML=list.length?list.map((r)=>`<article class="feed-row"><div class="main"><strong>${esc(r.title||'')}</strong><div class="meta">${esc(r.sub||'')}</div><div class="meta">${esc(r.meta||'')}</div></div><div class="pill">${esc(r.value||'')}</div></article>`).join(''):`<div class="note">Nog geen recente regels.</div>`; }
  function renderTables(targetId, sections){ const el=global.document.getElementById(targetId); if(!el) return; const list=Array.isArray(sections)?sections:[]; el.innerHTML=list.length?list.map((sec)=>{ const columns=Array.isArray(sec.columns)?sec.columns:[]; const rows=Array.isArray(sec.rows)?sec.rows:[]; return `<section class="panel"><h2>${esc(sec.title||'')}</h2><p>${esc(sec.subtitle||'')}</p><div class="table-wrap" style="margin-top:12px"><table class="table"><thead><tr>${columns.map((c)=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map((row)=>`<tr>${(Array.isArray(row)?row:[]).map((cell)=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${Math.max(columns.length,1)}">Nog geen data.</td></tr>`}</tbody></table></div></section>`; }).join(''):`<div class="note">Nog geen tabellen.</div>`; }
  const publicMap={ despimarkt:'despimarkt_get_stats_scoped', pikken:'get_pikken_stats_scoped', paardenrace:'get_paardenrace_stats_scoped', rad:'get_rad_stats_scoped' };
  const adminMap={ despimarkt:'admin_get_despimarkt_insights_action', pikken:'admin_get_pikken_dashboard_action', paardenrace:'admin_get_paardenrace_dashboard_action', rad:'admin_get_rad_dashboard_action' };
  async function loadPublicPage(kind){ setStatus('pageStatus','Stats laden…'); try{ const data=await publicRpc(publicMap[kind], { site_scope_input: scope(), limit_count: 40 }); renderCards('overviewGrid', data?.overview_cards, false); renderCards('storyGrid', data?.story_cards, true); renderLeaderboards('leaderboardsMount', data?.leaderboard_sections); renderRecent('recentMount', data?.recent_rows); renderTables('tablesMount', data?.table_sections); setStatus('pageStatus','Stats geladen.','ok'); }catch(err){ setStatus('pageStatus', err.message||String(err), 'error'); } }
  async function loadAdminPage(kind){ if(global.GEJAST_ADMIN_RPC && typeof global.GEJAST_ADMIN_RPC.requirePage==='function'){ const ok=await global.GEJAST_ADMIN_RPC.requirePage(`admin_${kind}.html`); if(!ok) return; } setStatus('pageStatus','Adminstats laden…'); try{ const data=await adminRpc(adminMap[kind], { admin_session_token: global.GEJAST_ADMIN_RPC && global.GEJAST_ADMIN_RPC.getSessionToken ? global.GEJAST_ADMIN_RPC.getSessionToken() : '', site_scope_input: scope(), limit_count: 60 }); renderCards('opsGrid', data?.ops_cards, false); renderCards('overviewGrid', data?.overview_cards, false); renderCards('storyGrid', data?.story_cards, true); renderLeaderboards('leaderboardsMount', data?.leaderboard_sections); renderRecent('recentMount', data?.recent_rows); renderTables('tablesMount', data?.table_sections); setStatus('pageStatus','Adminstats geladen.','ok'); }catch(err){ setStatus('pageStatus', err.message||String(err), 'error'); } }
  global.GEJAST_GAME_HQ={ loadPublicPage, loadAdminPage, publicRpc, adminRpc, setStatus };
})(window);
