import postgres from "npm:postgres@3.4.7";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const DB_URL = Deno.env.get("SUPABASE_DB_URL");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
if (!DB_URL || !SUPABASE_URL || !SERVICE_ROLE) throw new Error("required Supabase environment missing");
const sql = postgres(DB_URL,{max:2,prepare:false,idle_timeout:20});
const storage=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const BUCKET="c720p-security-private";
const BRIDGE_TOKEN_SHA256="f76c2ca6526b7d48c6f864e374898ebafca35720d0ffebe898d326f8741798ab";
const ALLOWED_ORIGINS=new Set(["https://kalenel.nl","https://www.kalenel.nl","https://admin.kalenel.nl"]);
const enc=new TextEncoder();

function cors(origin:string|null){const h:Record<string,string>={"cache-control":"no-store","access-control-allow-methods":"GET,POST,HEAD,OPTIONS","access-control-allow-headers":"authorization,content-type,x-c720p-token,range,if-range,if-none-match,if-modified-since","vary":"Origin"};if(origin&&ALLOWED_ORIGINS.has(origin))h["access-control-allow-origin"]=origin;return h}
function json(data:unknown,status=200,origin:string|null=null){return new Response(JSON.stringify(data),{status,headers:{...cors(origin),"content-type":"application/json; charset=utf-8"}})}
async function sha256Hex(value:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(value));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function constEq(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function bridgeOK(req:Request){const t=req.headers.get("x-c720p-token")||"";return t.length>=32&&constEq(await sha256Hex(t),BRIDGE_TOKEN_SHA256)}
async function mediaSession(req:Request){const raw=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(raw.length<32||raw.length>256)return null;const hash=await sha256Hex(raw);const rows=await sql`select token_hash,admin_username,expires_at from c720p_security.sessions where token_hash=${hash} and expires_at>now() limit 1`;if(!rows.length)return null;await sql`update c720p_security.sessions set last_seen_at=now() where token_hash=${hash}`;return rows[0]}
function cleanName(v:unknown,ext?:string){const s=String(v||"").split(/[\\/]/).pop()||"";if(!/^[A-Za-z0-9._-]{1,180}$/.test(s)||s.includes(".."))return null;if(ext&&!s.toLowerCase().endsWith(ext))return null;return s}
async function signed(path:string,seconds=300){const{data,error}=await storage.storage.from(BUCKET).createSignedUrl(path,seconds);if(error||!data?.signedUrl)return null;return data.signedUrl}
async function requireAdminSession(req:Request,origin:string|null){if(!origin||!ALLOWED_ORIGINS.has(origin))return{error:json({ok:false,error:"origin_denied"},403,origin)};const body=await req.json().catch(()=>null) as Record<string,unknown>|null;const token=String(body?.admin_session_token||"").trim();if(token.length<20||token.length>500)return{error:json({ok:false,error:"admin_session_required"},401,origin)};const rows=await sql`select public.admin_check_session(${token}) as data`;const checked=rows?.[0]?.data as Record<string,unknown>|undefined;if(!checked||checked.ok!==true)return{error:json({ok:false,error:"admin_session_invalid"},401,origin)};return{checked}}
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function hexBytes(hex:string){if(!/^[0-9a-f]{64}$/i.test(hex))throw new Error("bad_secret");const out=new Uint8Array(hex.length/2);for(let i=0;i<out.length;i++)out[i]=parseInt(hex.slice(i*2,i*2+2),16);return out}
async function tunnelToken(secretHex:string,seconds=900){const now=Math.floor(Date.now()/1000),exp=now+seconds;const payloadPart=b64url(enc.encode(JSON.stringify({iat:now-120,exp,scope:"c720p-security-media-v1"})));const key=await crypto.subtle.importKey("raw",hexBytes(secretHex),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(payloadPart)));return `${payloadPart}.${b64url(sig)}`}
function proxyPath(u:URL){const cam=u.searchParams.get("camera");const kind=u.searchParams.get("kind");if(cam!=="new")return"";if(kind==="status")return `/${cam}/api/status`;if(kind==="events")return `/${cam}/api/events`;if(kind==="live")return `/${cam}/live.mjpg`;if(kind==="snap"){const n=cleanName(u.searchParams.get("name"));return n?`/${cam}/snap/${encodeURIComponent(n)}`:""}if(kind==="clip"){const n=cleanName(u.searchParams.get("name"),".mp4");return n?`/${cam}/clip/${encodeURIComponent(n)}`:""}return""}
async function proxyLive(req:Request,u:URL,origin:string|null){const session=await mediaSession(req);if(!session)return json({ok:false,error:"media_session_required"},401,origin);const path=proxyPath(u);if(!path)return json({ok:false,error:"bad_media_path"},400,origin);const rows=await sql`select tunnel_url,hmac_secret from c720p_security.control where singleton=true`;const control=rows?.[0];const tunnel=String(control?.tunnel_url||"").replace(/\/+$/,"");const secret=String(control?.hmac_secret||"");if(!/^https:\/\/[a-z0-9-]+\.trycloudflare\.com$/i.test(tunnel)||!/^[0-9a-f]{64}$/i.test(secret))return json({ok:false,error:"camera_origin_offline"},503,origin);const token=await tunnelToken(secret,180);const target=new URL(tunnel+path);const h=new Headers();h.set("X-C720P-Media-Token",token);for(const n of ["Range","If-Range","If-None-Match","If-Modified-Since"]){const v=req.headers.get(n);if(v)h.set(n,v)}let r:Response;try{r=await fetch(target.toString(),{method:req.method,headers:h,redirect:"error"})}catch(e){console.error("camera proxy fetch",e);return json({ok:false,error:"camera_origin_unavailable"},502,origin)}if(r.status===401||r.status===403)return json({ok:false,error:"camera_origin_rejected"},502,origin);const out=new Headers(cors(origin));for(const n of ["Content-Type","Content-Length","Content-Range","Accept-Ranges","ETag","Last-Modified","Content-Disposition"]){const v=r.headers.get(n);if(v)out.set(n,v)}out.set("cache-control","private, no-store, max-age=0");out.set("x-content-type-options","nosniff");return new Response(req.method==="HEAD"?null:r.body,{status:r.status,statusText:r.statusText,headers:out})}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});const u=new URL(req.url),action=u.searchParams.get("action")||"status";try{
if(action==="session"&&req.method==="POST"){const r=await requireAdminSession(req,origin);if(r.error)return r.error;const cr=(await sql`select tunnel_url,hmac_secret from c720p_security.control where singleton=true`)[0]||{};const cameraOrigin=String(cr.tunnel_url||"").replace(/\/+$/,"");const cameraSecret=String(cr.hmac_secret||"");if(!/^https:\/\/[a-z0-9-]+\.trycloudflare\.com$/i.test(cameraOrigin)||!/^[0-9a-f]{64}$/i.test(cameraSecret))return json({ok:false,error:"camera_origin_offline"},503,origin);await sql`delete from c720p_security.sessions where expires_at<=now()`;const token=randomToken(32),hash=await sha256Hex(token),exp=new Date(Date.now()+15*60*1000),username=String(r.checked?.username||"admin").slice(0,120);await sql`insert into c720p_security.sessions(token_hash,expires_at,admin_username) values(${hash},${exp.toISOString()},${username})`;const cameraToken=await tunnelToken(cameraSecret,15*60);return json({ok:true,media_token:token,expires_at:exp.toISOString(),admin_session_token:r.checked?.admin_session_token||null,admin_username:username,camera_origin:cameraOrigin,camera_token:cameraToken,camera_token_expires_at:exp.toISOString()},200,origin)}
if(action==="proxy"&&(req.method==="GET"||req.method==="HEAD"))return await proxyLive(req,u,origin);
if(["sync_events","poll","upload_frame","upload_snapshot","upload_clip"].includes(action)){if(!(await bridgeOK(req)))return json({ok:false,error:"unauthorized"},401,origin);
if(action==="sync_events"&&req.method==="POST"){const body=await req.json().catch(()=>null) as {events?:unknown}|null;const events=Array.isArray(body?.events)?body!.events.slice(0,1000):[],seen:number[]=[];for(const raw of events as Record<string,unknown>[]){const no=Number(raw.clip_no);if(!Number.isInteger(no)||no<1||no>100000000)continue;const clipName=cleanName(raw.clip,".mp4"),snapName=cleanName(raw.snapshot);seen.push(no);await sql`insert into c720p_security.events(clip_no,event_timestamp,event_date,reason,saved,method,duration_target_seconds,clip_name,snapshot_name,local_present,synced_at) values(${no},${String(raw.timestamp||"").slice(0,80)},${String(raw.date||"").slice(0,32)},${String(raw.reason||"").slice(0,1000)},${!!raw.saved},${String(raw.method||"").slice(0,120)},${Number.isInteger(Number(raw.duration_target_seconds))?Number(raw.duration_target_seconds):null},${clipName},${snapName},true,now()) on conflict(clip_no) do update set event_timestamp=excluded.event_timestamp,event_date=excluded.event_date,reason=excluded.reason,saved=excluded.saved,method=excluded.method,duration_target_seconds=excluded.duration_target_seconds,clip_name=excluded.clip_name,snapshot_name=excluded.snapshot_name,local_present=true,synced_at=now()`}if(seen.length)await sql`update c720p_security.events set local_present=false where not (clip_no=any(${seen}))`;else await sql`update c720p_security.events set local_present=false`;await sql`update c720p_security.control set last_sync_at=now(),updated_at=now() where singleton=true`;const missing=await sql`select clip_no from c720p_security.events where local_present=true and snapshot_name is not null and snapshot_uploaded=false order by clip_no desc limit 100`;return json({ok:true,count:seen.length,need_snapshots:missing.map(x=>x.clip_no)},200,origin)}
if(action==="poll"&&req.method==="GET"){const rows=await sql`select viewer_until,last_sync_at,last_frame_at from c720p_security.control where singleton=true`;const pending=await sql`select clip_no from c720p_security.clip_requests where state in ('pending','error') order by requested_at limit 10`;const c=rows[0]||{};return json({ok:true,viewer_active:!!c.viewer_until&&new Date(c.viewer_until).getTime()>Date.now(),viewer_until:c.viewer_until||null,pending_clips:pending.map(x=>x.clip_no),last_sync_at:c.last_sync_at||null,last_frame_at:c.last_frame_at||null},200,origin)}
if(action==="upload_frame"&&req.method==="POST"){const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length<1000||bytes.length>2_000_000)return json({ok:false,error:"invalid_frame"},400,origin);const{error}=await storage.storage.from(BUCKET).upload("live/latest.jpg",bytes,{contentType:"image/jpeg",upsert:true,cacheControl:"0"});if(error)throw error;await sql`update c720p_security.control set last_frame_at=now(),last_frame_bytes=${bytes.length},updated_at=now() where singleton=true`;return json({ok:true,bytes:bytes.length},200,origin)}
if(action==="upload_snapshot"&&req.method==="POST"){const no=Number(u.searchParams.get("clip_no"));if(!Number.isInteger(no)||no<1)return json({ok:false,error:"bad_clip"},400,origin);const exists=await sql`select clip_no from c720p_security.events where clip_no=${no} and local_present=true`;if(!exists.length)return json({ok:false,error:"event_missing"},404,origin);const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length<1000||bytes.length>5_000_000)return json({ok:false,error:"invalid_snapshot"},400,origin);const{error}=await storage.storage.from(BUCKET).upload(`snaps/${no}.jpg`,bytes,{contentType:"image/jpeg",upsert:true,cacheControl:"300"});if(error)throw error;await sql`update c720p_security.events set snapshot_uploaded=true where clip_no=${no}`;return json({ok:true,bytes:bytes.length},200,origin)}
if(action==="upload_clip"&&req.method==="POST"){const no=Number(u.searchParams.get("clip_no"));if(!Number.isInteger(no)||no<1)return json({ok:false,error:"bad_clip"},400,origin);const exists=await sql`select clip_no from c720p_security.events where clip_no=${no} and local_present=true and clip_name is not null`;if(!exists.length)return json({ok:false,error:"event_missing"},404,origin);await sql`insert into c720p_security.clip_requests(clip_no,state,updated_at) values(${no},'uploading',now()) on conflict(clip_no) do update set state='uploading',error=null,updated_at=now()`;const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length<10000||bytes.length>100_000_000){await sql`update c720p_security.clip_requests set state='error',error='invalid clip size',updated_at=now() where clip_no=${no}`;return json({ok:false,error:"invalid_clip"},400,origin)}const{error}=await storage.storage.from(BUCKET).upload(`clips/${no}.mp4`,bytes,{contentType:"video/mp4",upsert:true,cacheControl:"300"});if(error){await sql`update c720p_security.clip_requests set state='error',error=${String(error.message||error).slice(0,500)},updated_at=now() where clip_no=${no}`;throw error}await sql`update c720p_security.events set clip_uploaded=true where clip_no=${no}`;await sql`update c720p_security.clip_requests set state='ready',error=null,updated_at=now() where clip_no=${no}`;return json({ok:true,bytes:bytes.length},200,origin)}return json({ok:false,error:"method_not_allowed"},405,origin)}
const session=await mediaSession(req);if(!session)return json({ok:false,error:"media_session_required"},401,origin);
if(action==="events"&&req.method==="GET"){const rows=await sql`select clip_no,event_timestamp,event_date,reason,saved,method,duration_target_seconds,clip_uploaded,snapshot_uploaded from c720p_security.events where local_present=true order by clip_no desc limit 500`;const snapPaths=rows.filter(x=>x.snapshot_uploaded).map(x=>`snaps/${x.clip_no}.jpg`),map=new Map<string,string>();if(snapPaths.length){const{data}=await storage.storage.from(BUCKET).createSignedUrls(snapPaths,300);for(const x of data||[])if(x.path&&x.signedUrl)map.set(x.path,x.signedUrl)}return json({ok:true,events:rows.map(x=>({...x,snapshot_url:map.get(`snaps/${x.clip_no}.jpg`)||null}))},200,origin)}
if(action==="live_heartbeat"&&req.method==="POST"){await sql`update c720p_security.control set viewer_until=now()+interval '35 seconds',updated_at=now() where singleton=true`;return json({ok:true,viewer_seconds:35},200,origin)}
if(action==="frame"&&req.method==="GET"){const{data,error}=await storage.storage.from(BUCKET).download("live/latest.jpg");if(error||!data)return json({ok:false,error:"frame_unavailable"},503,origin);return new Response(data.stream(),{status:200,headers:{...cors(origin),"content-type":"image/jpeg","cache-control":"private, no-store, max-age=0"}})}
if(action==="clip_url"&&req.method==="GET"){const no=Number(u.searchParams.get("clip_no"));if(!Number.isInteger(no)||no<1)return json({ok:false,error:"bad_clip"},400,origin);const rows=await sql`select clip_uploaded,local_present from c720p_security.events where clip_no=${no}`;if(!rows.length||!rows[0].local_present)return json({ok:false,error:"not_found"},404,origin);if(rows[0].clip_uploaded){const url=await signed(`clips/${no}.mp4`,300);if(url)return json({ok:true,ready:true,url,expires_in:300},200,origin)}await sql`insert into c720p_security.clip_requests(clip_no,state,requested_at,updated_at) values(${no},'pending',now(),now()) on conflict(clip_no) do update set state=case when c720p_security.clip_requests.state='ready' then 'pending' else c720p_security.clip_requests.state end,requested_at=now(),updated_at=now()`;return json({ok:true,ready:false,state:"pending"},202,origin)}
if(action==="status"&&req.method==="GET"){const c=(await sql`select viewer_until,last_sync_at,last_frame_at,last_frame_bytes from c720p_security.control where singleton=true`)[0]||{};const count=Number((await sql`select count(*)::int as n from c720p_security.events where local_present=true`)[0]?.n||0);return json({ok:true,event_count:count,last_sync_at:c.last_sync_at||null,last_frame_at:c.last_frame_at||null,last_frame_bytes:c.last_frame_bytes||null},200,origin)}
return json({ok:false,error:"not_found"},404,origin)}catch(e){console.error(e);return json({ok:false,error:"internal"},500,origin)}});
