from pathlib import Path
p=Path('cloudflare/workers/admin-gate/src/worker.js')
s=p.read_text()

def once(old,new,label):
 global s
 if old not in s: raise SystemExit(label+' anchor missing')
 s=s.replace(old,new,1)

once("const ADMIN_BUILD = 'v775-security-resilient-on-demand';","const ADMIN_BUILD = 'v776-security-direct-relay-fallback';",'build')
once("  const cameraToken = String(mediaData?.camera_token || '').trim();\n  const expiryMs = Date.parse(String(mediaData?.expires_at || ''));","  const cameraToken = String(mediaData?.camera_token || '').trim();\n  const mediaToken = String(mediaData?.media_token || '').trim();\n  const expiryMs = Date.parse(String(mediaData?.expires_at || ''));",'media token parse')
once("      !/^[A-Za-z0-9_-]{16,1024}\\.[A-Za-z0-9_-]{32,256}$/.test(cameraToken) ||\n      !Number.isFinite(expiryMs)","      !/^[A-Za-z0-9_-]{16,1024}\\.[A-Za-z0-9_-]{32,256}$/.test(cameraToken) ||\n      mediaToken.length < 32 || mediaToken.length > 256 ||\n      !Number.isFinite(expiryMs)",'media token validation')
once("    cameraOrigin, cameraToken, iat: now(), exp","    cameraOrigin, cameraToken, mediaToken, iat: now(), exp",'session media token')
once("  const token = String(media.cameraToken || '');\n  return /^https:\\/\\/[a-z0-9-]+\\.trycloudflare\\.com$/i.test(origin) &&\n    /^[A-Za-z0-9_-]{16,1024}\\.[A-Za-z0-9_-]{32,256}$/.test(token);","  const token = String(media.cameraToken || '');\n  const relayToken = String(media.mediaToken || '');\n  return /^https:\\/\\/[a-z0-9-]+\\.trycloudflare\\.com$/i.test(origin) &&\n    /^[A-Za-z0-9_-]{16,1024}\\.[A-Za-z0-9_-]{32,256}$/.test(token) &&\n    relayToken.length >= 32 && relayToken.length <= 256;",'valid session')

anchor="""async function proxySecurityOrigin(request, media, upstreamPath) {\n  const target = securityProxyTarget(media, upstreamPath);\n"""
helper="""function securityRelayTarget(upstreamPath) {\n  const s = String(upstreamPath || '');\n  let camera = '', kind = '', name = '';\n  let m = s.match(/^\\/(new|s3)\\/api\\/(status|events|controls|control)$/);\n  if (m) { camera=m[1]; kind=m[2]; }\n  if (!m && (m=s.match(/^\\/(new|s3)\\/live\\.mjpg$/))) { camera=m[1]; kind='live'; }\n  if (!m && (m=s.match(/^\\/(new|s3)\\/snap\\/([A-Za-z0-9._%-]+)$/))) { camera=m[1]; kind='snap'; try{name=decodeURIComponent(m[2])}catch{return '';} }\n  if (!m && (m=s.match(/^\\/(new|s3)\\/clip\\/([A-Za-z0-9._%-]+)$/))) { camera=m[1]; kind='clip'; try{name=decodeURIComponent(m[2])}catch{return '';} }\n  if (!camera || !kind) return '';\n  const u = new URL(SECURITY_MEDIA_PROXY_URL);\n  u.searchParams.set('camera', camera);\n  u.searchParams.set('kind', kind);\n  if (name) u.searchParams.set('name', name);\n  return u.toString();\n}\nfunction securityProxyResponse(response, requestMethod, mediaPath) {\n  const headers = securityResponseHeaders();\n  for (const name of ['Content-Type','Content-Length','Content-Range','Accept-Ranges','ETag','Last-Modified','Content-Disposition']) {\n    const value = response.headers.get(name);\n    if (value) headers.set(name, value);\n  }\n  headers.set('X-Kalenel-Security-Media-Path', mediaPath);\n  return new Response(requestMethod === 'HEAD' ? null : response.body, { status: response.status, statusText: response.statusText, headers });\n}\nasync function proxySecurityOrigin(request, media, upstreamPath) {\n  const target = securityProxyTarget(media, upstreamPath);\n"""
once(anchor,helper,'proxy helper')
old="""  let response;\n  try {\n    // The origin is a strict trycloudflare hostname minted into an encrypted\n    // session. Refuse redirects so the HMAC query token can never leak onward.\n    response = await fetch(target, { method: request.method, headers: upstreamHeaders, body, redirect: 'error' });\n  } catch {\n    return securityJson({ ok:false, error:'camera_origin_unavailable' }, 502);\n  }\n  if (response.status === 401 || response.status === 403) {\n    return securityJson({ ok:false, error:'security_unlock_required' }, 401, true);\n  }\n  const headers = securityResponseHeaders();\n  for (const name of ['Content-Type','Content-Length','Content-Range','Accept-Ranges','ETag','Last-Modified','Content-Disposition']) {\n    const value = response.headers.get(name);\n    if (value) headers.set(name, value);\n  }\n  return new Response(request.method === 'HEAD' ? null : response.body, { status: response.status, statusText: response.statusText, headers });\n}\n"""
new="""  let response = null;\n  let directFailed = false;\n  try {\n    // Prefer the direct tunnel so successful traffic does not consume Supabase\n    // egress. Refuse redirects so the HMAC query token cannot leak onward.\n    response = await fetch(target, { method: request.method, headers: upstreamHeaders, body, redirect: 'error' });\n  } catch { directFailed = true; }\n  if (!directFailed && response && response.status !== 401 && response.status !== 403 && response.status < 500) {\n    return securityProxyResponse(response, request.method, 'direct');\n  }\n  if (!directFailed && response && (response.status === 401 || response.status === 403)) {\n    return securityJson({ ok:false, error:'security_unlock_required' }, 401, true);\n  }\n\n  // Cloudflare Quick Tunnels can occasionally be unreachable specifically from\n  // another Cloudflare Worker while remaining healthy from normal internet\n  // clients. Fall back to the authenticated Supabase relay for that transport\n  // failure only. Browser URLs remain same-origin and no tunnel credential is\n  // exposed to JavaScript.\n  const relayTarget = securityRelayTarget(upstreamPath);\n  const relayToken = String(media?.mediaToken || '');\n  if (!relayTarget || relayToken.length < 32 || relayToken.length > 256) {\n    return securityJson({ ok:false, error:'camera_origin_unavailable' }, 502);\n  }\n  const relayHeaders = new Headers({ 'X-Kalenel-Media-Token': relayToken });\n  for (const name of ['Range','If-Range','If-None-Match','If-Modified-Since']) {\n    const value = request.headers.get(name);\n    if (value) relayHeaders.set(name, value);\n  }\n  if (body !== undefined) relayHeaders.set('Content-Type','application/json');\n  let relayResponse;\n  try { relayResponse = await fetch(relayTarget, { method: request.method, headers: relayHeaders, body, redirect:'follow' }); }\n  catch { return securityJson({ ok:false, error:'camera_origin_unavailable' }, 502); }\n  if (relayResponse.status === 401 || relayResponse.status === 403) {\n    return securityJson({ ok:false, error:'security_unlock_required' }, 401, true);\n  }\n  return securityProxyResponse(relayResponse, request.method, 'supabase-fallback');\n}\n"""
once(old,new,'proxy body')
p.write_text(s)
print('V776_PATCH=PASS')
