-- v843 comprehensive shop admin growth intelligence.
-- Production-applied 2026-09-20.

create table if not exists public.shop_price_cost_history_v843 (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  product_id text not null,
  variant_id text not null,
  product_name text not null,
  collection text not null default 'unknown',
  size text null,
  retail_cents integer not null check (retail_cents >= 0),
  production_cost_cents integer null check (production_cost_cents is null or production_cost_cents >= 0),
  gross_margin_cents integer null,
  source_cost_usd_cents integer null check (source_cost_usd_cents is null or source_cost_usd_cents >= 0),
  fx_usd_eur numeric(18,8) null check (fx_usd_eur is null or fx_usd_eur > 0),
  changed_fields text[] not null default '{}'::text[]
);
alter table public.shop_price_cost_history_v843 enable row level security;
revoke all on table public.shop_price_cost_history_v843 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_price_cost_history_v843 to service_role;
grant usage, select on sequence public.shop_price_cost_history_v843_id_seq to service_role;
create index if not exists shop_price_cost_history_v843_variant_idx on public.shop_price_cost_history_v843(product_id,variant_id,captured_at desc);
create index if not exists shop_price_cost_history_v843_time_idx on public.shop_price_cost_history_v843(captured_at desc);

create table if not exists public.shop_campaign_spend_v843 (
  id bigint generated by default as identity primary key,
  occurred_on date not null,
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  amount_cents integer not null check (amount_cents > 0 and amount_cents <= 100000000),
  note text null,
  created_by_admin_id bigint null references public.admin_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.shop_campaign_spend_v843 enable row level security;
revoke all on table public.shop_campaign_spend_v843 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_campaign_spend_v843 to service_role;
grant usage, select on sequence public.shop_campaign_spend_v843_id_seq to service_role;
create index if not exists shop_campaign_spend_v843_date_idx on public.shop_campaign_spend_v843(occurred_on desc);
create index if not exists shop_campaign_spend_v843_campaign_idx on public.shop_campaign_spend_v843(utm_source,utm_medium,utm_campaign,occurred_on desc);

create table if not exists public.shop_goals_v843 (
  id bigint generated by default as identity primary key,
  period_month date not null,
  metric text not null check (metric in ('recognized_sales_cents','known_contribution_cents','paid_orders','conversion_rate','repeat_customer_rate')),
  target_value numeric(18,4) not null check (target_value >= 0),
  note text null,
  created_by_admin_id bigint null references public.admin_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(period_month,metric)
);
alter table public.shop_goals_v843 enable row level security;
revoke all on table public.shop_goals_v843 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_goals_v843 to service_role;
grant usage, select on sequence public.shop_goals_v843_id_seq to service_role;

create table if not exists public.shop_annotations_v843 (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null,
  category text not null default 'note' check (category in ('note','campaign','price_change','product_change','operations','other')),
  title text not null check (char_length(title) between 1 and 160),
  note text null check (note is null or char_length(note) <= 2000),
  created_by_admin_id bigint null references public.admin_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.shop_annotations_v843 enable row level security;
revoke all on table public.shop_annotations_v843 from public, anon, authenticated;
grant select, insert, update, delete on table public.shop_annotations_v843 to service_role;
grant usage, select on sequence public.shop_annotations_v843_id_seq to service_role;
create index if not exists shop_annotations_v843_time_idx on public.shop_annotations_v843(occurred_at desc);
